### PR TITLE
[Fix] Stabilize the login/logout e2e spec

### LINKED ISSUE #11261: 🧪 Second tab logout test flaky
## 🧪 Tests

Our test to ensure that all tabs are logged out when one logs out is flaky and we need to stabilize it.

## 🕵️ Details

Seems like it is a bit of a race condition where the second tab does not have time to load the tokens and know it is logged in before they are removed and the logout message is sent to it? :thinking: 

## 🙋‍♀️ Proposed Solution

Adding an expectation that the second tab is logged in before deleting tokens in first tab.

## ✅ Acceptance Criteria

- [ ] `login-logout.spec.ts` consistently passes

### PR DESCRIPTION
**Pull request by esizer**
🤖 Resolves #11261 

## 👋 Introduction

Hopefully will stabilize the `login-logout.spec.ts`.

## 🕵️ Details

Before the changes I was getting about 25% failure rate, after I could not get it to fail after 5-6 runs so :crossed_fingers: 

## 🧪 Testing

1. Run the spec in webkit multiple times 10+ should be fine?
2. Ensure it does not fail and is stable

### CODE REVIEW

**Review by mnigh — COMMENTED** [review]
Ran `pnpm run e2e:playwright:webkit login-logout` 10 times, passed 7/10:

- ✅ pass
- ✅ pass
- ✅ pass
- ❌ fail
- ❌ fail
- ✅ pass
- ❌ fail
- ✅ pass
- ✅ pass
- ✅ pass

---

Ran `pnpm run e2e:playwright:webkit --repeat-each=10 login-logout` with timeout set to 30 seconds:

```
 5 failed
    [webkit] › login-logout.spec.ts:133:7 › Login and logout › share the refresh ───────────────────
    [webkit] › login-logout.spec.ts:133:7 › Login and logout › share the refresh ───────────────────
    [webkit] › login-logout.spec.ts:133:7 › Login and logout › share the refresh ───────────────────
    [webkit] › login-logout.spec.ts:133:7 › Login and logout › share the refresh ───────────────────
    [webkit] › login-logout.spec.ts:133:7 › Login and logout › share the refresh ───────────────────
  79 passed (12.1m)
```

```
[webkit] › login-logout.spec.ts:133:7 › Login and logout › share the refresh ──────────────────

    Test timeout of 30000ms exceeded.

    Error: page.waitForRequest: Test timeout of 30000ms exceeded.

      145 |     // get ready to catch the next graphql request
      146 |     await page
    > 147 |       .waitForRequest(async (req) => {
          |        ^
      148 |         if (req.url()?.includes("/graphql")) {
      149 |           const reqJson = await req.postDataJSON();
      150 |           return typeof reqJson.operationName !== "undefined";
```

Unfortunately, still seems pretty flaky 😢.

**Comment by esizer** [comment]
> Ran `pnpm run e2e:playwright:webkit --repeat-each=10 login-logout` with timeout set to 30 seconds:

Was it timing out because the test was taking longer than 30 seconds or because it was waiting for something to appear?

**Comment by mnigh** [comment]
> > Ran `pnpm run e2e:playwright:webkit --repeat-each=10 login-logout` with timeout set to 30 seconds:
> 
> Was it timing out because the test was taking longer than 30 seconds or because it was waiting for something to appear?

😅 I think the problem might be that `/en/applicant/profile` doesn't exist anymore and it should be `/applicant/profile-and-applications`:

https://github.com/GCTC-NTGC/gc-digital-talent/blob/e44dc6b7108b64d0a08711d0fc65e2372627b1b1/apps/playwright/tests/login-logout.spec.ts#L142-L143

**Comment by esizer** [comment]
> 😅 I think the problem might be that `/en/applicant/profile` doesn't exist anymore and it should be `/en/applicant/profile-and-applications`:

Good eye, updated that as well in [update to use real route path](https://github.com/GCTC-NTGC/gc-digital-talent/pull/11262/commits/7c9b50222d37e150e22af19500ada07a3aa54eca)

**Review by mnigh — COMMENTED** [review]
Still failed or `pnpm run e2e:playwright:webkit --repeat-each=10 login-logout`, though a bit different.

## Screenshot

Screen Shot 2024-08-15 at 13 24 19

**Review by mnigh — APPROVED** [review]
Ran it 5 times with high timeout values to account for a slower machine than what CI is. No failures. 🤞 :shipit: 

## Screenshot

Screen Shot 2024-08-15 at 16 03 38

**Pull request merged**
