### PR TITLE
Monitor front-end bundlesize changes

### PR DESCRIPTION
**Pull request by patcon**
Hey all!

As a way of orienting, I was doing some poking around related to performance and bundle size. I see some ways to reduce bundle size, but I thought it might be helpful to first have bundle size changes appear prominently in PRs. This way, there are no surprises when bundle size grows, and it can be self-explanatory when it shrinks :)

I initially thought this would be a lighter touch PR, but I ended up touching 3 unexpected things I should explain:
1. `maintenance/scripts/setup.sh` needed to be modified to be able to build JS sub-projects with `npm run production` instead of `npm run dev`, since `npm run production` is the true bundle size we want to track.
2. this runs docker-compose commands in the github action environment to run `setup.sh` in the maintenance container. the tactic of using `nvm` to run node-related binaries (e.g., `node`, `npx`, `mix`, etc) stopped working, specifically erroring with a mention of `#!/usr/bin/env node`. I suspect this different behavior from local development has to do with Github Actions running containers inside containers, which docker is [surprisingly] supposed to support (aka "docker in docker"). Using the official `node:14.18.1-bullseye-slim` image for the maintenance container (comparable to the previous `ubuntu:latest`) resulted in the scripts working again.
    - See: https://stackoverflow.com/a/43395332
        > if you have your Node installed from the binary packages and not from sources then your shebang line in the npm binary will likely be `#!/usr/bin/env node` which **will not work** when the correct version of Node in the PATH
3. added some bash script modes to improve debugging and error-detection

EDIT: This is how the checks will look when running on PRs within this upstream repo: https://github.com/patcon/gc-digital-talent/pull/1

EDIT2: challenge (2) might have to do with nvm being run as root, which can have some issues with PATH. I can also investigate that if changing the docker base image is a problem.

### CODE REVIEW

**Comment by patcon** [comment]
Going to see if I can mess with the PATH in the script and get nvm working on GitHub Actions without changing the base image.

(Getting a full docker-compose build working on GitHub Actions will have benefits. Specificially, easy e2e testing on CI [with Cypress](https://www.cypress.io/). So I'd really love for the full docker-compose setup to be working there.)

**Comment by petertgiles** [comment]
HI @patcon, this looks very cool!  We went with an Ubuntu image since that's what we've got on our production server.  If you can make it work properly on that distro it would probably be best. 🍀  The docker file for the maintenance image is [here](https://github.com/GCTC-NTGC/gc-digital-talent/blob/main/infrastructure/maintenance-container/Dockerfile) in case you find there's something we can tweak in the setup of nvm or node to make it work better. 🚀

**Comment by petertgiles** [comment]
> might have to do with nvm being run as root

Interesting.  I was working on an updated container for PHP 8.0 and the folks using Apple workstations seemed to be seeing a similar problem.  I use a Windows workstation and it was OK but maybe this is the same thing causing issues for you on Github.

**Comment by patcon** [comment]
I was a little confounded by it (only failing when running docker in GitHub actions env, but not with local docker), and so I made a minimal reproduction, so that I could file it upstream somewhere :)

https://github.com/patcon/nvm-ubuntu-docker-test

The workaround right now is to avoid using `--latest-npm` with `nvm install`, and keeping npm at v6.x

`npm run foo` is mangling the PATH when executed from a folder on a shared volume, but it only happens on newer npm versions.

There might also be a work-around where we can use npm 7.x+ and somehow override the permissions on the random PATH dirs it appends to the front of PATH

No rush tho. I'll try to find who'll take responsibility for it upstream :)

**Comment by patcon** [comment]
Going to close this until I can debug the underlying issue or find a way to use a more docker-friendly way of running node :)

**Pull request closed without merging**
