### PR TITLE
Remove requirement for x5c key in jwks

### PR DESCRIPTION
**Pull request by patcon**
Closes https://github.com/GCTC-NTGC/gc-digital-talent/issues/2716

## To Do
- [x] Added `web-token/jwt-core` and updated lockfile
- [x] Added note about php ext required
- [x] Remove requirement for using `x5c` prop in JWKS endpoint data, in favour of generating its public key from the props `n` (modulus) and `e` (exponent).
- [x] update test data so jwks resources have "e" and "n", but lack "x5c"

Result: Can now use an off-the-shelf mock oauth2 server (which don't support the niche x5c prop)

## Alternatives
1. using a pure-php crypto library like `phpseclib` directly (without new system reqs like `bcmath` or `gmp`)
2. using another JWT library that uses `phpseclib`: https://phpseclib.com/docs/rsa#raw-rsa-public-keys
3. maybe doing it without a library: https://www.identityblog.com/?p=389

## Open Question

1. Is `bcmath` PHP extension available to enable/install on the UAT server? If not, what about `gmp`? (both are required for the currently implemented JWT library that handles working with JWKS endpoint data.) Are we open to using one of them?
2. would we rather use one of the alternatives?
    1. are these alternatives slower? and does speed even matter?

### CODE REVIEW

**Comment by petertgiles** [comment]
Don't forget to inform people that they'll need to rebuild the image for *php* and then instantiate a new container.

**Comment by patcon** [comment]
> It pegs my CPU at 100% for several minutes - I haven't let it finish yet. In the logs for Actions it looks like it completes normally. Is this happening for you?

Are you running phpunit in docker, or locally? If locally, you'll need to install bcmath pho ext (which I added to the workflow)

There's a command to run phpunit inside the php container of docker via `docker-compose run` but I recall our docs only mention running it locally?

**Comment by patcon** [comment]
I feel funny installing a whole other jwt management lib for just these two jkws functions, though its true that our current lib doesn't have any supports for managing jwks. In theory, we could choose a new lib that handles jwks better, with an eye to perhaps fully migrating to it at some point (if it serves us better than lcobucci/jwt).

Options:
1. keep this PR. Aka install a second jwt management package, and install bcmath/gmp on docker+UAT (running phpunit locally also will not work without those)
2. Use alternative (3) above, and copy in our own minimal pure PHP public key derivation code.
3. Keep this basic PR, but use the [firebase-jwt lib](https://github.com/firebase/php-jwt) instead. Perks: built on a pure-php polyfill, that optimistically uses an audited, non-php crypto library (libsodium) if available on the OS. Most widely-used PHP jwt lib. Risks: many open GitHub issues, so that's a slight smell.

I'd recommend the third option, of using firebase-jwt instead of the jwt-core for jwks processing (again, for ONLY the jwks code in this PR, not swapping out [our whole lcobucci/jwt lib](https://github.com/lcobucci/jwt))

**Comment by petertgiles** [comment]
Oh, of course, yeah it runs fine in the container with the new dep.  :blush:   That's weird behaviour - it doesn't display an error message but just locks up.  So, do we have this dep in production or is it going to lock up there, too?

For the decision - I guess the best dep is the one we have access to in production. It sounds like we can't just install whatever we want. :grin: I don't have a strong opinion beyond that.  @tristan-orourke?

**Comment by patcon** [comment]
Closing this in favour of a new PR

**Pull request closed without merging**
