### PR TITLE
Dark mode - Admin misc edition

### PR DESCRIPTION
**Pull request by substrae**
## ✨ Summary

Contact @substrae with design questions

Similarly to #8819, this PR aims to catch small dark mode things in the admin UIs.

```[tasklist]
### ✅ Requirements
- [ ] All remaining admin dark mode UI passes AA contrast checks
- [ ] All remaining admin dark mode UI has dark mode styles
```

### CODE REVIEW

**Comment by vd1992** [comment]
Process status on process information

Both the "open" and the date

image

And closed

image

**Comment by vd1992** [comment]
Individual roles table, edit user account page

image

Team information

image

View team members

image

**Review by vd1992 — CHANGES_REQUESTED** [review]
Zipping around, looks good to me, just a few contrast things I found above

**Comment by substrae** [comment]
@vd1992 Okay I think I got everything you flagged. I do have concerns around those "read only" styled inputs, because they are individually styled `<p>` tags in the code rather than a centralized component. This likely means there are other places where we've styled fake "read only" things that might also be failing. Any ideas?

**Comment by vd1992** [comment]
> @vd1992 Okay I think I got everything you flagged. I do have concerns around those "read only" styled inputs, because they are individually styled `<p>` tags in the code rather than a centralized component. This likely means there are other places where we've styled fake "read only" things that might also be failing. Any ideas?

I'm not sure, but I have combed through quite a bit of the app now so I caught all the ones I happened upon. Hopefully we are good 😬

**Review by vd1992 — APPROVED** [review]
All looks good to me, amazing!

**Pull request merged**
