### PR TITLE
Factor out callbacks in memoized data

### PR DESCRIPTION
**Pull request by petertgiles**
It seems that the new eslint warnings are due to having callbacks instead of memoized data.  New instances of the callback cause the memoized component to rerender every time.  [This reference](https://dmitripavlutin.com/use-react-memo-wisely/#4-reactmemo-and-callback-functions) helped me understand the issue.

This branch factors out the callbacks to declared functions to solve the issue.

Solves #1190

### CODE REVIEW

**Review by yonikid15 — COMMENTED** [review]
Nice work Peter! That link really helps break it down.
I was wondering if we can make this more "DRY", so I tested it out and pulled the edit button into the common folder in a new file (`/helpers/table.tsx`). Looks like its working. Do you want me to push my changes up, or did you want to handle it yourself?

**Comment by petertgiles** [comment]
> Do you want me to push my changes up, or did you want to handle it yourself?

Great idea!   A shared component is a better implementation.  Go ahead and push your changes up.

**Comment by yonikid15** [comment]
> > Do you want me to push my changes up, or did you want to handle it yourself?
> 
> Great idea! A shared component is a better implementation. Go ahead and push your changes up.

Sounds good! Also, there's some react-intl formatted messages that have the same error so I'll make a fix for those as well.

**Comment by petertgiles** [comment]
Great change, Yoni!  I like the DRY reuse of the accessor and good catch on the one I missed.  I (unofficially) approve. 👍

**Review by yonikid15 — APPROVED** [review]

**Pull request merged**
