### PR TITLE
[Fix] Missing favicons paths

### LINKED ISSUE #8781: ✨ Add missing/misrouted site icons
## ✨ Feature

Our HTTP 4xx logs show that our clients are requesting many icon files and not finding them.  Are the icons missing?  Are the icons misrouted?  Maybe some of these aren't even legitimate - and part of a security scan?

## 🕵️ Details

/apple-touch-icon-120x120-precomposed.png
/apple-touch-icon-120x120.png
/apple-touch-icon-152x152-precomposed.png
/apple-touch-icon-152x152.png
/apple-touch-icon-precomposed.png
/apple-touch-icon.png
/talent/images/android-chrome-192x192.png
/talent/images/android-chrome-512x512.png
/talent/images/apple-touch-icon.png
/talent/images/favicon-16x16.png
/talent/images/favicon-32x32.png
/talent/images/mstile-144x144.png
/talent/images/mstile-150x150.png
/talent/images/mstile-310x150.png
/talent/images/mstile-310x310.png
/talent/images/mstile-70x70.png

## ✅ Acceptance Criteria

- [ ] Find out why these icon files are not found
- [ ] Use Figma plugin to make all the images from the original image
- [ ] Add as many as possible to the site

### PR DESCRIPTION
**Pull request by esizer**
🤖 Resolves #8781 

## 👋 Introduction

Add missing favicon paths in `index.html`

> [!NOTE]
> This sets the default to the digital talent favicon. Since we have an SPA with all the projects we need to use javascript with a fallback.

## 🕵️ Details

Looks like we had all the files, we just weren;t telling the browsers where to find them so they went looking and that is why we saw some 4XX's related to them.

## 🧪 Testing

> [!NOTE]
> We will need testing done on various devices 😓 

1. Build `npm run dev`
2. Navigate to `/`
3. Disable javascript and reload
4. Confirm there are no 404's related to favicons

### CODE REVIEW

**Review by mnigh — COMMENTED** [review]
Any reason not all the sizes and types were added in this PR?

It looks like this was originally done with all the sizes in https://github.com/GCTC-NTGC/gc-digital-talent/pull/4277 but maybe got overlooked in one of the PRs that moved files around?

**Comment by esizer** [comment]
> Any reason not all the sizes and types were added in this PR?

So, not all sizes are required if you are explicit about paths. The reason we were getting 404's is a mix between the two following:

- We used to provide them, the path was cached and browsers/search engines were looking for outdated paths
- We never supplied one so browsers/search engines were looking for common paths/file names

Now that we are being explicit, it should resolve itself in time. Though, because of the cache, we may want to revisit this in the future to be certain.

REF: https://evilmartians.com/chronicles/how-to-favicon-in-2021-six-files-that-fit-most-needs

**Comment by tristan-orourke** [comment]
I'm not sure how to test this. I don't see any icon 404s even on the main branch, or on production.

**Comment by esizer** [comment]
> I'm not sure how to test this. I don't see any icon 404s even on the main branch, or on production.

Oh, you will need to disable JavaScript (I should have mentioned that 😅 ). You likely don't see any 404 because we added the correct paths with javascript and the 404s were coming from web crawlers not executing it (similar issue to the link preview image issue we fixed).

**Comment by tristan-orourke** [comment]
Maybe we should try to put this through some kind of SEO analysis?

**Review by tristan-orourke — APPROVED** [review]
We'll try just launching this and seeing if it reduces 404s in our prod logs.

**Pull request merged**
