### PR TITLE
1790 - personal experiences form

### PR DESCRIPTION
**Pull request by vd1992**
for #1790 
it was pretty quick, pretty much recycled from the last few forms, might as well check it off

wireframe here
https://www.figma.com/proto/PrvXEDac0HVp7dF7SLWVFm/Candidate-profile-interfaces---V5.0.0?node-id=2340%3A4352&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=1%3A2

### CODE REVIEW

**Comment by vd1992** [comment]
any styling concerns? I can't seem to make the form blurb split lines, new line and line breaks seem to do nothing

**Review by petertgiles — CHANGES_REQUESTED** [review]
Nice, cranked it out quick!  The validation and functionality is great.  I think the only suggestion I have is adding a margin between the two dates and having them collapse on a small viewport.
image
Regarding the *I Agree* blurb, yeah it's pretty ugly.  I think the text should flow like it does without a preset line break but I don't like how the checkbox floats above the text and validation warning.  That's not a problem for this PR.  I'll probably open a separate issue to look at the Checkbox component on its own.

**Comment by vd1992** [comment]
> Could you take a look at the Fieldset component, too? I think that would add the nice frame around the checkboxes like in the wireframe.

Aye aye

**Comment by vd1992** [comment]
@petertgiles 
- Space added
- Date inputs swap positioning with viewport change
- Fieldset added in, it was straightforward to work in and seems to have done the job. Setting legend to empty string felt odd though

**Comment by petertgiles** [comment]
The collapse looks great now!

Regarding the fieldset, I was playing around with it a bit.  If you check the wireframe you'll see that there's actually two frames, one on each box.  If you do it this way you do need the legend.
```
        <Fieldset legend="Disclaimer" required>
          <Checkbox
            id="disclaimer"
            label={label here}
            name="disclaimer"
            rules={{ required: intl.formatMessage(errorMessages.required) }}
          />
        </Fieldset>
        <Fieldset legend="Current Experience">
          <Checkbox
            id="current-role"
            label={label here}
            name="current-role"
          />
        </Fieldset>
```
The trouble with this is that we have a `hideoptional` for checkboxes but not a `hiderequired`.
image
I suggest either rolling back this change to remove the frames or put it in like this but open a new issue to add the ability to hide the required field.  Whichever way you got, let me know when it's changed and I'll approve.

**Comment by vd1992** [comment]
Yeah, splitting into 2 fieldsets, good idea. 
I like the look of it, will open an issue after
@petertgiles

**Comment by vd1992** [comment]
@petertgiles 
aaah, I forgot the Intls, there is definitely some time involved before it becomes a muscle memory thing
thanks for doing it

**Comment by petertgiles** [comment]
> aaah, I forgot the Intls,

No, worries, I forget this all the time too. 😄 Please link back to this PR when you open the checkbox issue so we can come back to update this later.

**Pull request merged**
