### PR TITLE
Import talentsearch french strings into merged Storybook (hosted on Chromatic)

### PR DESCRIPTION
**Pull request by patcon**
talentsearch french string weren't being merged into the omni-storybook during build, and so storybook wasn't properly reflecting live app translations.

## Before

Screen Shot 2022-09-07 at 10 40 15 AM

https://main--61e099a1bb1465003a73d3ce.chromatic.com/?path=/story/workpreferencesform--individual-work-preferences

## After

Screen Shot 2022-09-07 at 10 39 39 AM

### CODE REVIEW

**Comment by patcon** [comment]
> Oh! Is this what is causing issues in https://github.com/GCTC-NTGC/gc-digital-talent/issues/2895 ?

Looks like it! Submitted a fix, and ready for review after Chromatic builds.

**Review by esizer — APPROVED** [review]
Yay! Working as expected 😄  Also, thank-you for reverting the French page hack 🙇‍♀️ 

## Talent Search

Screen Shot 2022-09-07 at 1 27 57 PM

## IAP

Screen Shot 2022-09-07 at 1 27 08 PM

**Comment by patcon** [comment]
thanks for review @esizer 🙌

**Comment by patcon** [comment]
Ugh, note that there are some irritating edge-cases if the same string+description exists in both common and talentsearch/admin, as keys will override.

Current load order in admin storybook is admin > common > talent > indigenous (with later ones overriding). We could adjust the order, but still possible to get caught

I just spent a bunch of time changing it in common's fr.json, and banging my head trying to figure out why it wasn't reflected in storybook. Turns out it's that talentsearch's fr.json was overriding my change :/

I suppose this is a subtle consequence of maintaining separate apps, which would be resolved by https://github.com/GCTC-NTGC/gc-digital-talent/issues/2917

**Pull request merged**
