### PR TITLE
Bug - 5465 - Updates faker data to be consistent

### LINKED ISSUE #5465: 🧪 Tests - Storybook: some stories regenerate text every Chromatic UI review
## 🧪 Tests

Some stories keep regenerating text each time the Chromatic deployment and UI review runs. 
This is creating noise as these diffs aren't really meaningful. 

## 🕵️ Details

These stories in particular

image

Example of the noise from text regenerating 

image

## 🙋‍♀️ Proposed Solution

Likely some random generation needs to be adjusted to always seed the same value?

## ✅ Acceptance Criteria

- [ ] Storybook UI review no longer generates noise each run

### PR DESCRIPTION
**Pull request by mnigh**
🤖 Resolves #5465.

## 👋 Introduction

This PR updates faker data to be consistent in order to avoid creating unexpected changes for Chromatic.

## 🧪 Testing

1. `npm run storybook`
2. Observe any instances in storybook stories where `faker` is referenced to render text
3. Ensure on page refresh, text output is the same

### CODE REVIEW

**Comment by vd1992** [comment]
we won't know for sure if it works until after it is merged in, generating a new collection of baseline snapshots, and someone runs a fresh diff on a branch

**Comment by vd1992** [comment]
Testing and refreshing pages in storybook locally...
```
Application Page Wrapper
Profile Form Wrapper
Request Confirmation Page
User General Information Tab
```
appear to be resolved
```
User Profile
```
has an issue for it specifically

**Review by vd1992 — CHANGES_REQUESTED** [review]
one story is not quite there yet
```
Team Table
```
changes on reload

gif

**Comment by mnigh** [comment]
> one story is not quite there yet
> 
> ```
> Team Table
> ```
> 
> changes on reload

Good catch @vd1992. I've had to add a `initialSortBy` (I chose the **Team** column since that seemed the most logical choice from what columns are currently rendered) to the `TeamTable` for consistent sorting before moving on to refactoring `fakeTeams` to generate consistent data:

- [Add initialSortBy teamName](https://github.com/GCTC-NTGC/gc-digital-talent/pull/5687/commits/456039cb529ab1f8ea7aa0d9291dee15fc690cde)
- [Refactor fakeTeams to generate consistent data](https://github.com/GCTC-NTGC/gc-digital-talent/pull/5687/commits/c626f6b6d6fecefee87c4844a82dcdef647ce3d6)

**Review by vd1992 — APPROVED** [review]
Nice!

**Pull request merged**
