### PR TITLE
Bug - 2804 - Talent profile bugs

### PR DESCRIPTION
**Pull request by esizer**
## Summary

This fixes a few minor bugs on the talent profile page.

- [x] Vertically centre page heading
- [x] Update breadcrumbs on Experience & Skills form
- [x] Fix offset of anchor links
- [x] Add missing `<ul>` for `<li>` element
- [x] Add missing `role=tablist` to `<TabSet>`

### CODE REVIEW

**Review by vd1992 — APPROVED** [review]
- hero had text centred 
- clicking nav menu now behaves as expect WRT to section positioning 
- breadcrumbs updated 

Nice!
Everything shifted up a bit on the profile, not drastically so, but enough to be noticeable. Might want to let someone else weigh in on whether that is a problem.

**Comment by vd1992** [comment]
Not in the issue, but tangential to the page being worked on. I was playing around with the Dev Tools of Edge, specifically Lighthouse tool. It made the following recommendations for the Profile Page in accessibility improvements. Your discretion what to make of it. 

image

And

image

It also remarked about contrast ratio but I think we've got enough people keeping an eye on that stuff already.

**Comment by esizer** [comment]
Thanks, I'll take a look at these and they should be easy enough I can fix them in this PR since it is kind of a general "bug fixes" anyway.

**Comment by esizer** [comment]
> Not in the issue, but tangential to the page being worked on. I was playing around with the Dev Tools of Edge, specifically Lighthouse tool. It made the following recommendations for the Profile Page in accessibility improvements. Your discretion what to make of it.

Was able to get these in. Can you take a second look before I merge, please? 😃

**Pull request merged**
