### PR TITLE
Bug - NavMenu ListItem alignment

### LINKED ISSUE #3283: Bug - Navigation links not center aligned
### Description
`ListItem` component items used in `NavMenu` component not center aligned with `Header` component items on smaller screen widths.

### Acceptance Criteria
- [ ] Navigation links are center aligned

### PR DESCRIPTION
**Pull request by mnigh**
Resolves #3283.

### Steps to Test
1. Visit `/en/login-info` in local environment
2. View **NavMenu** component alignment on both small and large screen widths (with one item on right for large screen)
3. Login at `/en/login-info` in local environment
4. View **NavMenu** component alignment on both small and large screen widths (with two items on right for large screen)

### CODE REVIEW

**Review by vd1992 — DISMISSED** [review]
looks resolved to me, nice!

image

**Review by JamesHuf — CHANGES_REQUESTED** [review]
I don't think this looks right to me. I'm not getting any space between the menu items.
image
image

**Comment by vd1992** [comment]
> I don't think this looks right to me. I'm not getting any space between the menu items.

weird, I checked out and built, I had the normal menu items and fixed small-view, but then upon refreshing twice I got your results

**Comment by mnigh** [comment]
Closing PR, see: https://github.com/GCTC-NTGC/gc-digital-talent/issues/3283#issuecomment-1179353577

**Pull request closed without merging**
