### PR TITLE
Bug - 3422 - Fix link default behaviour

### LINKED ISSUE #3422: Allow opening new tabs with cmd+click (native browser behaviour)
<sup>ℹ️ [Figma (root)][figma] | [Sitemap][sitemap]</sup>
<sup>_This initial comment is collaborative and open to modification by all._</sup>

## Description

In native browser behavior, cmd or ctrl clicking a link will open it in a new window. React onClick handlers (with `e.preventDefault()`) which don't offer an escape hatch for these special clicks, prevent this behaviour.

We should figure out how to allow normal browser behavior when these hotkeys are selected.

### Normal desired behaviour

Cmd+click opens any link in new tab: https://recordit.co/Sp5czQcItC

## Current behaviour

Cmd+click ignores new tab, and opens in current one: https://recordit.co/dkA66xv4H9

## Potential solution

https://stackoverflow.com/a/10808972/504018

Likely site of intervention:
https://github.com/GCTC-NTGC/gc-digital-talent/blob/5a82ac417eead526f20ac062082d62bbf87143ef/frontend/common/src/components/Link/Link.tsx#L53-L61

## Acceptance Criteria
- [ ] Cmd/Ctrl+clicking an _internal_ app link opens it in a new tab
- [ ] Regular clicking an _internal_ app link doesn't open a new tab

   [image]: https://user-images.githubusercontent.com/305339/166570935-6425a615-82c7-4b2f-9840-5c7d698fa2ab.png
   [image-link]: https://example.com
   [figma]: https://go.talent.c4nada.ca/figma
   [sitemap]: https://go.talent.c4nada.ca/sitemap

### PR DESCRIPTION
**Pull request by esizer**
Resolves #3422 

## Summary

Removes the `<Link>` click handler and relies on default `href` attribute.

### CODE REVIEW

**Comment by esizer** [comment]
If we would like to improve our link component we could get some influence from `react-router`.

https://github.com/remix-run/react-router/blob/f2178b9d093eb43f958815137067649c0335f1bd/packages/react-router-dom/index.tsx#L393-L435

**Review by tristan-orourke — DISMISSED** [review]
The primary purpose of the Link component is to trigger client-side navigation instead of normal browser navigation, which speeds things up by 1) avoiding re-running the whole react framework each time, and 2) keeping a cache of API queries in memory. This quick fix does fix the original bug, but loses all that functionality.

On the one hand, this seems like another good reason for us to migrate to a library like react-router. On the other hand, seems like we could reproduce the useLinkClickHandler you linked pretty easily, so lets do that for now!

**Comment by esizer** [comment]
> On the other hand, seems like we could reproduce the useLinkClickHandler you linked pretty easily, so lets do that for now!

So, this doesn't even come close to the full functionality provided in `react-router`. But, it will properly navigate to a URL without overriding some link functionality such as opening in a new tab and holding modifier keys.

**Review by mnigh — CHANGES_REQUESTED** [review]
The components that have been updated seem to function as listed in the acceptance criteria in the linked issue, but there are a few other components that need to be updated as well, see screenshot:

Screen Shot 2022-07-27 at 09 28 49

**Comment by esizer** [comment]
> The components that have been updated seem to function as listed in the acceptance criteria in the linked issue, but there are a few other components that need to be updated as well, see screenshot:

Fixed with:

- [replace tabel edit button with link](https://github.com/GCTC-NTGC/gc-digital-talent/pull/3423/commits/423c1d2bb267842909d037278b57307a3726aa79)
- [replace other link click handlers](https://github.com/GCTC-NTGC/gc-digital-talent/pull/3423/commits/db440037d385ebaa2405052e400218f967c0b679)
- [update router link click handler](https://github.com/GCTC-NTGC/gc-digital-talent/pull/3423/commits/6dd259973c77ae069e668fbb409f1fe1dd1c65d5)

**Review by mnigh — APPROVED** [review]
Nice work, looks good to me!

**Pull request merged**
