### PR TITLE
Feature - 3169 - Edit Pool Mutations

### LINKED ISSUE #3169: Edit Pool page - Mutations and Testing
<sup>ℹ️ [Figma (root)][figma] | [Sitemap][sitemap]</sup>
<sup>_This initial comment is collaborative and open to modification by all._</sup>

## Description

*This second issue is to implement all the actions and add testing.*

This page contains an editable form for the information in the pool model.
This page also contains buttons that open modals to change the "Status" of this pool. Which in turn changes the behavior of the Pool Advertisement page.

If the pool status is in DRAFT, you can SAVE, PUBLISH, or DELETE.
If the pool status is PUBLISHED (Active before "Closing Date") you can CLOSE or EXTEND THE DATE.
If the pool status is PUBLISHED (Expired after "Closing Date") you can EXTEND THE DATE or ARCHIVE.

NOTE 01: GENERIC CLASSIFICATION: Leave out this dropdown selector from this issue, it will be addressed at a later point.

NOTE 02: DATE PICKER (yyyy/mm/dd): Date will always be set in Pacific Time at 11:59:59 p.m. (probably handled in the backend mutation) 

NOTE 03: We are not gonna implement "ARCHIVE" yet, just leave the button in but it won't do anything yet.

NOTE 04: CLASSIFICATION PICKER (e.g. IT-01): Front-end will be a 1 selection only (dropdown), but back end will allow multiple selections (just in case we need to allow this down the line). 

## Screenshot: Prototype
image

## Acceptance Criteria
- [x] Implement all actions in the buttons with API mutations
- [x] Page needs to behave in different way depending on status (Draft, Published (Active), Closed (Published and Expired)
- [ ] Appropriate automated testing (Jest?  Cypress?)

[Link to Edit Pool Advertisement wireframe](https://www.figma.com/proto/b6lDM86QCJQ6iaAh7qrTYH/Admin-v4-(Direct-Intake)?page-id=0%3A1&node-id=1618%3A6064&viewport=-3442%2C1747%2C0.59&scaling=min-zoom&starting-point-node-id=1618%3A6064)

### PR DESCRIPTION
**Pull request by esizer**
Resolves #3169 

## Summary

This adds the necessary mutations to the `EditPool` page and fires them on the associated form events.

## Mutations added

- `updatePoolAdvertisement`
- `publishPoolAdvertisement`
- `closePoolAdvertisement`
- `deletePoolAdvertisement`

## TO DO

- [x] Write cypress tests

## Notes on Updating

While updating a pool, it is done by sections so it is entirely possible someone would like to edit multiple sections in a single workflow. So, instead of navigating away from the page, we forego this in the `updatePoolAdvertisement` mutation. However, this causes an issue when using the **Extend the Date** button near then end of the page. The mutation runs, but the current pool query's cache is not invalidated and refetched so the field for the date stays the same.

### Possible Solution

I have been considering different solutions and think the best way is to allow an argument to the `useMutations` `update` method to specify if the user should be navigated away from the page or not. We could then set this to `true` only for when the **Extend the Date** button is pressed and leave it as false for every other `update`.

## Testing

> Note: It is best to start with a draft pool that has yet to expire and another that has been published and expired.
> To do this, just login to adminer and manually set these.

### Updating

1. Navigate to `/admin/pools`
2. Click edit on the pool that is a draft
3. Attempt to modify all different sections
4. Confirm each operation is successful

## Publishing

> On the same edit page as the `Updating` step

1. Scroll to the bottom
2. Click on the Publish button near the end of the page
3. Confirm the operation was successful

## Extending

1. Navigate to `/admin/pools`
2. Edit one of the pools which have expired
3. Scroll to the **Extend the date** button and click on it
4. Select a date in the future
5. Click **Extend closing date** button
6. Confirm the operation was successful

## Closing

1. Navigate to `/admin/pools`
2. Click edit on the pool that is published but not expired
3. Scroll to the **Close** button and click on it
4. Click the **Close pool now** button in the modal
5. Confirm the operation was successful

### CODE REVIEW

**Comment by tristan-orourke** [comment]
There seems to be a slight discrepancy in different views of the closing date - a timezone issue?
Closing date is Sept 28
Closing date field shows Sept 28
Publish modal shows closing Sept 27
Publish modal shows closing date of Sept 27

**Comment by esizer** [comment]
> There seems to be a slight discrepancy in different views of the closing date - a timezone issue?

😬 That is most definitely a timezone issue. I'll take a look into it.

**Comment by tristan-orourke** [comment]
I can't publish without setting specific locations.

https://recordit.co/qEfDT4YLnv

Seems like a problem with the validator though, so I'll make a separate bug ticket.
```
{
  "errors": [
    {
      "message": "validation.string",
      "extensions": {
        "validation": {
          "advertisement_location.en": [
            "validation.string"
          ],
          "advertisement_location.fr": [
            "validation.string"
          ]
        },
        "category": "validation"
      },
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "publishPoolAdvertisement"
      ],
      "trace": [
        {
          "file": "\/var\/www\/html\/api\/vendor\/nuwave\/lighthouse\/src\/Auth\/CanDirective.php",
          "line": 151,
          "call": "App\\GraphQL\\Mutations\\PublishPoolAdvertisement::__invoke(null, array(1), instance of Nuwave\\Lighthouse\\Schema\\Context, instance of GraphQL\\Type\\Definition\\ResolveInfo)"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/nuwave\/lighthouse\/src\/Auth\/GuardDirective.php",
          "line": 69,
          "call": "Nuwave\\Lighthouse\\Auth\\CanDirective::Nuwave\\Lighthouse\\Auth\\{closure}(null, array(1), instance of Nuwave\\Lighthouse\\Schema\\Context, instance of GraphQL\\Type\\Definition\\ResolveInfo)"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/nuwave\/lighthouse\/src\/Schema\/Directives\/RenameArgsDirective.php",
          "line": 35,
          "call": "Nuwave\\Lighthouse\\Auth\\GuardDirective::Nuwave\\Lighthouse\\Auth\\{closure}(null, array(1), instance of Nuwave\\Lighthouse\\Schema\\Context, instance of GraphQL\\Type\\Definition\\ResolveInfo)"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/nuwave\/lighthouse\/src\/Schema\/Directives\/SpreadDirective.php",
          "line": 34,
          "call": "Nuwave\\Lighthouse\\Schema\\Directives\\RenameArgsDirective::Nuwave\\Lighthouse\\Schema\\Directives\\{closure}(null, array(1), instance of Nuwave\\Lighthouse\\Schema\\Context, instance of GraphQL\\Type\\Definition\\ResolveInfo)"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/nuwave\/lighthouse\/src\/Schema\/Directives\/ArgTraversalDirective.php",
          "line": 27,
          "call": "Nuwave\\Lighthouse\\Schema\\Directives\\SpreadDirective::Nuwave\\Lighthouse\\Schema\\Directives\\{closure}(null, array(1), instance of Nuwave\\Lighthouse\\Schema\\Context, instance of GraphQL\\Type\\Definition\\ResolveInfo)"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/nuwave\/lighthouse\/src\/Validation\/ValidateDirective.php",
          "line": 50,
          "call": "Nuwave\\Lighthouse\\Schema\\Directives\\ArgTraversalDirective::Nuwave\\Lighthouse\\Schema\\Directives\\{closure}(null, array(1), instance of Nuwave\\Lighthouse\\Schema\\Context, instance of GraphQL\\Type\\Definition\\ResolveInfo)"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/nuwave\/lighthouse\/src\/Schema\/Directives\/ArgTraversalDirective.php",
          "line": 27,
          "call": "Nuwave\\Lighthouse\\Validation\\ValidateDirective::Nuwave\\Lighthouse\\Validation\\{closure}(null, array(1), instance of Nuwave\\Lighthouse\\Schema\\Context, instance of GraphQL\\Type\\Definition\\ResolveInfo)"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/nuwave\/lighthouse\/src\/Schema\/Directives\/TrimDirective.php",
          "line": 54,
          "call": "Nuwave\\Lighthouse\\Schema\\Directives\\ArgTraversalDirective::Nuwave\\Lighthouse\\Schema\\Directives\\{closure}(null, array(1), instance of Nuwave\\Lighthouse\\Schema\\Context, instance of GraphQL\\Type\\Definition\\ResolveInfo)"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/nuwave\/lighthouse\/src\/Schema\/Factories\/FieldFactory.php",
          "line": 97,
          "call": "Nuwave\\Lighthouse\\Schema\\Directives\\TrimDirective::Nuwave\\Lighthouse\\Schema\\Directives\\{closure}(null, array(1), instance of Nuwave\\Lighthouse\\Schema\\Context, instance of GraphQL\\Type\\Definition\\ResolveInfo)"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/webonyx\/graphql-php\/src\/Executor\/ReferenceExecutor.php",
          "line": 623,
          "call": "Nuwave\\Lighthouse\\Schema\\Factories\\FieldFactory::Nuwave\\Lighthouse\\Schema\\Factories\\{closure}(null, array(1), instance of Nuwave\\Lighthouse\\Schema\\Context, instance of GraphQL\\Type\\Definition\\ResolveInfo)"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/webonyx\/graphql-php\/src\/Executor\/ReferenceExecutor.php",
          "line": 550,
          "call": "GraphQL\\Executor\\ReferenceExecutor::resolveFieldValueOrError(instance of GraphQL\\Type\\Definition\\FieldDefinition, instance of GraphQL\\Language\\AST\\FieldNode, instance of Closure, null, instance of GraphQL\\Type\\Definition\\ResolveInfo)"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/webonyx\/graphql-php\/src\/Executor\/ReferenceExecutor.php",
          "line": 474,
          "call": "GraphQL\\Executor\\ReferenceExecutor::resolveField(GraphQLType: Mutation, null, instance of ArrayObject(1), array(1))"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/webonyx\/graphql-php\/src\/Executor\/ReferenceExecutor.php",
          "line": 857,
          "call": "GraphQL\\Executor\\ReferenceExecutor::GraphQL\\Executor\\{closure}(array(0), 'publishPoolAdvertisement')"
        },
        {
          "call": "GraphQL\\Executor\\ReferenceExecutor::GraphQL\\Executor\\{closure}(array(0), 'publishPoolAdvertisement')"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/webonyx\/graphql-php\/src\/Executor\/ReferenceExecutor.php",
          "line": 859,
          "function": "array_reduce(array(1), instance of Closure, array(0))"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/webonyx\/graphql-php\/src\/Executor\/ReferenceExecutor.php",
          "line": 490,
          "call": "GraphQL\\Executor\\ReferenceExecutor::promiseReduce(array(1), instance of Closure, array(0))"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/webonyx\/graphql-php\/src\/Executor\/ReferenceExecutor.php",
          "line": 263,
          "call": "GraphQL\\Executor\\ReferenceExecutor::executeFieldsSerially(GraphQLType: Mutation, null, array(0), instance of ArrayObject(1))"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/webonyx\/graphql-php\/src\/Executor\/ReferenceExecutor.php",
          "line": 215,
          "call": "GraphQL\\Executor\\ReferenceExecutor::executeOperation(instance of GraphQL\\Language\\AST\\OperationDefinitionNode, null)"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/webonyx\/graphql-php\/src\/Executor\/Executor.php",
          "line": 156,
          "call": "GraphQL\\Executor\\ReferenceExecutor::doExecute()"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/webonyx\/graphql-php\/src\/GraphQL.php",
          "line": 162,
          "call": "GraphQL\\Executor\\Executor::promiseToExecute(instance of GraphQL\\Executor\\Promise\\Adapter\\SyncPromiseAdapter, instance of GraphQL\\Type\\Schema, instance of GraphQL\\Language\\AST\\DocumentNode, null, instance of Nuwave\\Lighthouse\\Schema\\Context, array(1), 'publishPoolAdvertisement', null)"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/webonyx\/graphql-php\/src\/GraphQL.php",
          "line": 94,
          "call": "GraphQL\\GraphQL::promiseToExecute(instance of GraphQL\\Executor\\Promise\\Adapter\\SyncPromiseAdapter, instance of GraphQL\\Type\\Schema, instance of GraphQL\\Language\\AST\\DocumentNode, null, instance of Nuwave\\Lighthouse\\Schema\\Context, array(1), 'publishPoolAdvertisement', null, array(29))"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/nuwave\/lighthouse\/src\/GraphQL.php",
          "line": 268,
          "call": "GraphQL\\GraphQL::executeQuery(instance of GraphQL\\Type\\Schema, instance of GraphQL\\Language\\AST\\DocumentNode, null, instance of Nuwave\\Lighthouse\\Schema\\Context, array(1), 'publishPoolAdvertisement', null, array(29))"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/nuwave\/lighthouse\/src\/GraphQL.php",
          "line": 203,
          "call": "Nuwave\\Lighthouse\\GraphQL::executeParsedQuery(instance of GraphQL\\Language\\AST\\DocumentNode, instance of Nuwave\\Lighthouse\\Schema\\Context, array(1), null, 'publishPoolAdvertisement')"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/nuwave\/lighthouse\/src\/GraphQL.php",
          "line": 162,
          "call": "Nuwave\\Lighthouse\\GraphQL::parseAndExecuteQuery('mutation publishPoolAdvertisement($id: ID!) {\n  publishPoolAdvertisement(id: $id) {\n    isPublished\n    __typename\n  }\n}', instance of Nuwave\\Lighthouse\\Schema\\Context, array(1), null, 'publishPoolAdvertisement')"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/nuwave\/lighthouse\/src\/GraphQL.php",
          "line": 121,
          "call": "Nuwave\\Lighthouse\\GraphQL::executeOperation(instance of GraphQL\\Server\\OperationParams, instance of Nuwave\\Lighthouse\\Schema\\Context)"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/nuwave\/lighthouse\/src\/Support\/Utils.php",
          "line": 99,
          "call": "Nuwave\\Lighthouse\\GraphQL::Nuwave\\Lighthouse\\{closure}(instance of GraphQL\\Server\\OperationParams)"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/nuwave\/lighthouse\/src\/GraphQL.php",
          "line": 120,
          "call": "Nuwave\\Lighthouse\\Support\\Utils::mapEach(instance of Closure, instance of GraphQL\\Server\\OperationParams)"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/nuwave\/lighthouse\/src\/Support\/Http\/Controllers\/GraphQLController.php",
          "line": 32,
          "call": "Nuwave\\Lighthouse\\GraphQL::executeOperationOrOperations(instance of GraphQL\\Server\\OperationParams, instance of Nuwave\\Lighthouse\\Schema\\Context)"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/ControllerDispatcher.php",
          "line": 48,
          "call": "Nuwave\\Lighthouse\\Support\\Http\\Controllers\\GraphQLController::__invoke(instance of Illuminate\\Http\\Request, instance of Nuwave\\Lighthouse\\GraphQL, instance of Illuminate\\Events\\Dispatcher, instance of Laragraph\\Utils\\RequestParser, instance of Nuwave\\Lighthouse\\Execution\\SingleResponse, instance of Nuwave\\Lighthouse\\Execution\\ContextFactory)"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Route.php",
          "line": 262,
          "call": "Illuminate\\Routing\\ControllerDispatcher::dispatch(instance of Illuminate\\Routing\\Route, instance of Nuwave\\Lighthouse\\Support\\Http\\Controllers\\GraphQLController, '__invoke')"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Route.php",
          "line": 205,
          "call": "Illuminate\\Routing\\Route::runController()"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php",
          "line": 721,
          "call": "Illuminate\\Routing\\Route::run()"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php",
          "line": 128,
          "call": "Illuminate\\Routing\\Router::Illuminate\\Routing\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "\/var\/www\/html\/api\/app\/Http\/Middleware\/AuditQueryMiddleware.php",
          "line": 42,
          "call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php",
          "line": 167,
          "call": "App\\Http\\Middleware\\AuditQueryMiddleware::handle(instance of Illuminate\\Http\\Request, instance of Closure)"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/nuwave\/lighthouse\/src\/Support\/Http\/Middleware\/AttemptAuthentication.php",
          "line": 34,
          "call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php",
          "line": 167,
          "call": "Nuwave\\Lighthouse\\Support\\Http\\Middleware\\AttemptAuthentication::handle(instance of Illuminate\\Http\\Request, instance of Closure)"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/nuwave\/lighthouse\/src\/Support\/Http\/Middleware\/AcceptJson.php",
          "line": 27,
          "call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php",
          "line": 167,
          "call": "Nuwave\\Lighthouse\\Support\\Http\\Middleware\\AcceptJson::handle(instance of Illuminate\\Http\\Request, instance of Closure)"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php",
          "line": 103,
          "call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php",
          "line": 723,
          "call": "Illuminate\\Pipeline\\Pipeline::then(instance of Closure)"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php",
          "line": 698,
          "call": "Illuminate\\Routing\\Router::runRouteWithinStack(instance of Illuminate\\Routing\\Route, instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php",
          "line": 662,
          "call": "Illuminate\\Routing\\Router::runRoute(instance of Illuminate\\Http\\Request, instance of Illuminate\\Routing\\Route)"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php",
          "line": 651,
          "call": "Illuminate\\Routing\\Router::dispatchToRoute(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Kernel.php",
          "line": 167,
          "call": "Illuminate\\Routing\\Router::dispatch(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php",
          "line": 128,
          "call": "Illuminate\\Foundation\\Http\\Kernel::Illuminate\\Foundation\\Http\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Middleware\/TransformsRequest.php",
          "line": 21,
          "call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Middleware\/ConvertEmptyStringsToNull.php",
          "line": 31,
          "call": "Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest::handle(instance of Illuminate\\Http\\Request, instance of Closure)"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php",
          "line": 167,
          "call": "Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull::handle(instance of Illuminate\\Http\\Request, instance of Closure)"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Middleware\/TransformsRequest.php",
          "line": 21,
          "call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Middleware\/TrimStrings.php",
          "line": 40,
          "call": "Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest::handle(instance of Illuminate\\Http\\Request, instance of Closure)"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php",
          "line": 167,
          "call": "Illuminate\\Foundation\\Http\\Middleware\\TrimStrings::handle(instance of Illuminate\\Http\\Request, instance of Closure)"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Middleware\/ValidatePostSize.php",
          "line": 27,
          "call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php",
          "line": 167,
          "call": "Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize::handle(instance of Illuminate\\Http\\Request, instance of Closure)"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Middleware\/PreventRequestsDuringMaintenance.php",
          "line": 86,
          "call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php",
          "line": 167,
          "call": "Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance::handle(instance of Illuminate\\Http\\Request, instance of Closure)"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/fruitcake\/laravel-cors\/src\/HandleCors.php",
          "line": 38,
          "call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php",
          "line": 167,
          "call": "Fruitcake\\Cors\\HandleCors::handle(instance of Illuminate\\Http\\Request, instance of Closure)"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/laravel\/framework\/src\/Illuminate\/Http\/Middleware\/TrustProxies.php",
          "line": 39,
          "call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php",
          "line": 167,
          "call": "Illuminate\\Http\\Middleware\\TrustProxies::handle(instance of Illuminate\\Http\\Request, instance of Closure)"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php",
          "line": 103,
          "call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Kernel.php",
          "line": 142,
          "call": "Illuminate\\Pipeline\\Pipeline::then(instance of Closure)"
        },
        {
          "file": "\/var\/www\/html\/api\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Kernel.php",
          "line": 111,
          "call": "Illuminate\\Foundation\\Http\\Kernel::sendRequestThroughRouter(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "\/var\/www\/html\/api\/public\/index.php",
          "line": 52,
          "call": "Illuminate\\Foundation\\Http\\Kernel::handle(instance of Illuminate\\Http\\Request)"
        }
      ]
    }
  ],
  "data": {
    "publishPoolAdvertisement": null
  }
}
```

**Comment by esizer** [comment]
> Seems like a problem with the validator though, so I'll make a separate bug ticket.

Sorry, that was my fault, I should have mentioned this in the description but forgot. 

We have the validation set but I think we are waiting the issue related to displaying graphql errors to the user. https://github.com/gctc-ntgc/gc-digital-talent/issues/3322

**Review by tristan-orourke — COMMENTED** [review]
I've been thinking about the problem of the Closing Date field not updating when doing the Extend Date mutation. Instead of refreshing the page, we can make use of the react-hook-form [reset api](https://react-hook-form.com/api/useform/reset).

Here's my solution:
```
export const ClosingDateSection = ({
  poolAdvertisement,
  sectionMetadata,
  onSave,
}: ClosingDateSectionProps): JSX.Element => {
  const intl = useIntl();
  const { isSubmitting } = useEditPoolContext();

  const suppliedFormValues = dataToFormValues(poolAdvertisement);
  const methods = useForm<FormValues>({
    defaultValues: suppliedFormValues,
  });
  const { handleSubmit, reset } = methods;

  // If poolAdvertisement.expiryDate changes due to outside interference, reset this form
  useDeepCompareEffect(() => {
    reset(suppliedFormValues);
  }, [reset, suppliedFormValues]);
  ```

If we want to force this kind of reset elsewhere, we could write a custom hook for it. Maybe something that wraps useForm, and encapsulates the functionality to reset when defaultValues changes.

**Comment by tristan-orourke** [comment]
I'm not sure why the e2e-tests are failing. Everything seems to work when I test it manually. Is it just a timeout issue?

**Comment by esizer** [comment]
> I'm not sure why the e2e-tests are failing. Everything seems to work when I test it manually. Is it just a timeout issue?

Yeah, I think this is related to #3311 . For some reason, the `cy.wait('@gql{alias}Mutation');` intermittently times out.

**Comment by vd1992** [comment]
a quality of life improvement thing might be to mention that there are fields required before you can Publish
as is, everything is marked optional and the Publish modal doesn't mentioned there are required fields

sure you can output error messages, but it seems handy to be upfront about what you will need to have before the publish will work
this could merit its own issue though, since where and how to explain this is up for debate

**Comment by esizer** [comment]
> this could merit its own issue though, since where and how to explain this is up for debate

I agree, do we want to pass this over to design and see what they think the best solution is for making it clear what fields need to be filled out before you can publish? Also, likely be a good idea to, at the same time, disable the publish button until those fields are filled out.

**Comment by esizer** [comment]
> I've been thinking about the problem of the Closing Date field not updating when doing the Extend Date mutation. Instead of refreshing the page, we can make use of the react-hook-form [reset api](https://react-hook-form.com/api/useform/reset).

Nice! This worked wonderfully, thanks!

[update closing date on extend](https://github.com/GCTC-NTGC/gc-digital-talent/pull/3568/commits/70a24a3eef200bbeb0b0bca750d4e4dc8d24851e)

**Comment by tristan-orourke** [comment]
> do we want to pass this over to design and see what they think the best solution is for making it clear what fields need to be filled out before you can publish?

We should flag that to design, but it doesn't need to block this PR.

**Review by tristan-orourke — APPROVED** [review]
I'm happy with this, besides the failing test. Any remaining issues are being split into their own tickets.
#3586 
#3580 
#3585

**Pull request merged**
