### PR TITLE
Create a prod robots file which disallows admin and personal urls

### LINKED ISSUE #4395: Improve prod.robots.txt
Here's the current situation:
- talentsearch has robots.txt file that makes everything searchable.
- tc-report has a robots.txt file of its own, which disallows everything.
- its currently the tc-report version which is served at the root /robots.txt url.

TODO:
- ~on UAT (and any non-prod environment), serve an alternate robots.txt file which disallows everything.~ #4618 
- on prod, serve a robots.txt that we've thought more carefully about.

## Acceptance Criteria
- [ ] Modify (or create) `infrastructure/conf/prod.robots.txt` file that allows/disallows the following pages/sections:
    - [ ] disallow admin
    - [ ] disallow profile
    - [ ] disallow logged-out
    - [ ] disallow talent search? (@gobyrne ?)
    - [ ] disallow applications or /create-application
    - [ ] allow homepage
    - [ ] allow browse jobs
    - [ ] allow individual job posters
    - [ ] allow tc-report (all of it)
    - [ ] allow iap homepage
    - [ ] allow support page and footer links
    - [ ] allow login info
    - [ ] provide testing plan for reviewers
- Note that all rules should work with or without language codes
- Note that language codes can be arbitrary, because we plan to add more indigenous languages as we go.

### PR DESCRIPTION
**Pull request by tristan-orourke**
Resolves #4395

Ready to be tested on UAT.

Deployment instructions: IaC must be updated to add the "s" to the robots filename:
    - `ROBOTS_FILENAME=dev.robot.txt` becomes `ROBOTS_FILENAME=dev.robots.txt`
    - `ROBOTS_FILENAME=prod.robot.txt` becomes `ROBOTS_FILENAME=prod.robots.txt`

### CODE REVIEW

**Comment by brindasasi** [comment]
I believe UAT is in use rt now.. should I test this in dev instead? @tristan-orourke

**Comment by brindasasi** [comment]
> I believe UAT is in use rt now.. should I test this in dev instead? @tristan-orourke

I deployed prod file into dev server and try to validate via https://technicalseo.com/tools/robots-txt/ . It didn't work out as its closed for internet. 

I will check it out on UAT once I get the green signal to deploy it there.

**Comment by tristan-orourke** [comment]
Thanks @brindasasi. We'll probably have to avoid testing on UAT this week. I'll mark this PR as blocked for now.

**Comment by patcon** [comment]
Availa rest of today, but back in use on Monday

**Review by brindasasi — APPROVED** [review]
LGTM

**Pull request merged**
