### PR TITLE
deleteDepartment api call must return correct type

### LINKED ISSUE #1844: Bug - deleteDepartment api call must return department
# Description
Should return department instead, not user.

### PR DESCRIPTION
**Pull request by tristan-orourke**
Resolves #1844

### CODE REVIEW

**Review by petertgiles — APPROVED** [review]
Works for me

**Comment by petertgiles** [comment]
@tristan-orourke doh, I just realized that we now have to commit changes to the graphql schema.  Could you put that in please?

**Comment by patcon** [comment]
> doh, I just realized that we now have to commit changes to the graphql schema.

I mean, I guess we could just have the workflow make it's own commit to the PR if it finds it's needed, instead of justing failing the check...? Though this may be a bit confusing for a dev when they push again, and it's rejected due to the extra remote commit on GitHub, at least until they `git pull --rebase`

Lemme know if this auto-updating of the out-of-aync schema file in PRs would be helpful :)

**Comment by petertgiles** [comment]
> we could just have the workflow make it's own commit to the PR

I'm not sure how everyone else feels but I don't think that's necessary.  Having a github action tell me I missed something makes sense to me.

**Pull request merged**
