### PR TITLE
[Copy] Removes pleonasm create new

### LINKED ISSUE #12019: 🔤 Replacing "create new X" with "create X"
## 🔤 Copy

1. Please update buttons saying "Create new X" across the admin side to remove the word "new".
2. Please also update page titles and headings saying "Create a new X"

## 🕵️ Details

As adding "new" after "create" doesn't add meaning, we can remove it.

**Buttons**
Please update the buttons to say "Create {item}".

In French, please update them from "Créez un nouveau {item}" to "Créez un {item}" and "Créez une nouvelle {item}" to "Créez une {item}".

It might be that there are still some French **buttons** that use infinitive (Créer), these should be updated as above (so using imperative (Créez).

**Page titles and headings**
Please replace headings saying "Create a new {item}" with "Create a {item}" or "Create an {item}".
In French, please update them from "Créer un nouveau {item}" and "Créer une nouvelle {item}" to "Créer un {item}" and "Créer une {item}" 

@mnigh kindly dug up where they're used:
image

image

## ✅ Acceptance Criteria

- [ ] No occurrence of "create (a) + new" and "créer/créez (un/une) + nouveau/nouvelle" on the platform.

### PR DESCRIPTION
**Pull request by mnigh**
🤖 Resolves #12019.

## 👋 Introduction

This PR removes pleonasms **create new** and **create a new** where it has been deemed redundant, updates some verb tenses in French, and fixes a typo in documentation.

## 🎩 Acknowledgements
@NienkeBr for **creating a new** entry in my lexicon, pleonasm.

## 🧪 Testing

1. `pnpm build`
2. Verify pleonasms **create new** and **create a new** do not exist in English
3. Verify pleonasms **créez/creer un/une nouveau/nouvelle** do not exist in French

## 📸 Screenshots

<details>
  <summary>French and English</summary>
Screen Shot 2024-11-26 at 11 44 55
Screen Shot 2024-11-26 at 11 45 04
Screen Shot 2024-11-26 at 11 45 36
Screen Shot 2024-11-26 at 11 45 45
Screen Shot 2024-11-26 at 11 46 41
Screen Shot 2024-11-26 at 11 46 51
Screen Shot 2024-11-26 at 11 48 38
Screen Shot 2024-11-26 at 11 48 51
Screen Shot 2024-11-26 at 11 50 24
Screen Shot 2024-11-26 at 11 50 46
Screen Shot 2024-11-26 at 11 56 17
Screen Shot 2024-11-26 at 11 56 34
Screen Shot 2024-11-26 at 12 00 53
Screen Shot 2024-11-26 at 12 01 02
Screen Shot 2024-11-26 at 12 01 38
Screen Shot 2024-11-26 at 12 01 49
Screen Shot 2024-11-26 at 12 02 33
Screen Shot 2024-11-26 at 12 02 42
</details>

### CODE REVIEW

**Comment by vd1992** [comment]
Unrelated, but found a favourite of yours

image

**Review by vd1992 — APPROVED** [review]

**Comment by NienkeBr** [comment]
1. Could you please change this button to say to "Créez"?
image
2. This link is there to let the user create another request after they've submitted the previous one, right? Could we change this link to "Create another talent request" (French: "Créez une autre demande de talents"?
image
3. Could you please change this to say "Créez l'équipe"?
image

**Comment by mnigh** [comment]
@NienkeBr Thanks for your review. If there is nothing else to change, could you approve this PR?

> 1. Could you please change this button to say to "Créez"?

Screen Shot 2024-11-27 at 09 43 07

---

> 2. This link is there to let the user create another request after they've submitted the previous one, right? Could we change this link to "Create another talent request" (French: "Créez une autre demande de talents"?

### English
Screen Shot 2024-11-27 at 09 48 12

### French
Screen Shot 2024-11-27 at 09 48 28

---

> 3. Could you please change this to say "Créez l'équipe"?

Screen Shot 2024-11-27 at 09 51 57

**Review by NienkeBr — APPROVED** [review]
Looks good to me, thanks!

**Pull request merged**
