### PR TITLE
Feature - Add support API endpoint

### LINKED ISSUE #4187: API endpoint which forwards Create Ticket request to Freshdesk
Create an api endpoint in our laravel server which forwards a payload to the [Freshdesk api](https://developers.freshdesk.com/api/#create_ticket). It doesn't need to do any validation, just send on the same payload it receives, and return the response it gets from Freshdesk.

The one thing this endpoint has to do, and the reason we won't just send a request directly from the client-side to Freshdesk, is that the server must add a Freshdesk API Key (stored in a new env variable) to the request.

This involves:
    - adding a route to `api/routes/api.php` (while you're add it, you can remove the default unused route)
    - adding a Controller class in `api/app/Http/Controllers`, where the logic is
    - adding a new (empty) key to `api/.env.example`
    - probably an additional line to .htaccess and deploy.htaccess

## Acceptance Criteria

- [ ] Our server accepts a POST request to the route `/api/support-tickets`, forwards the payload to freshdesk (using an env var api key) and returns whatever response it gets.

### PR DESCRIPTION
**Pull request by mnigh**
Resolves #4187.

h/t @esizer for co-piloting.

### Steps to test

1. Create a test [Freshdesk account](https://freshdesk.com/signup-free)
2. Add environment variables to api/.env based on api/.env.example from test Freshdesk account
3. Clear config cache `php artisan config:cache` (inside shell)
4. Clear route cache `php artisan route:cache` (inside shell)
5. Build talent search `npm run production --workspace=talentsearch`
6. Run talent search storybook `npm run storybook --workspace=talentsearch`
7. Verify successful ticket creation
8. Verify unsuccessful ticket creation (by not sending in one of the [required parameters](https://developers.freshdesk.com/api/#create_ticket) to Freshdesk)

### CODE REVIEW

**Review by tristan-orourke — COMMENTED** [review]
Code looks good! Still have to sign into Freshdesk to test this.

**Review by tristan-orourke — CHANGES_REQUESTED** [review]
I got an error when I finally tried it for real - missing a required product_id field! :(

**Comment by mnigh** [comment]
> I got an error when I finally tried it for real - missing a required product_id field! :(

That is very strange considering `product_id` is not a required field in [Freshdesk's API](https://developers.freshdesk.com/api/#create_ticket) nor [our controller](https://github.com/GCTC-NTGC/gc-digital-talent/pull/4355/files#diff-8130b3059bf86a24d7ed17faaac96ebf590f438321f7622a164cfb39b0595466) (not [yet](https://github.com/GCTC-NTGC/gc-digital-talent/issues/4294)) 🤔.

**Review by tristan-orourke — APPROVED** [review]

**Comment by tristan-orourke** [comment]
Using Matt's freshdesk api key solved the problem! The PR itself is fine.

**Pull request merged**
