### PR TITLE
a11y - 3832 - Fix Heading Levels

### LINKED ISSUE #3832: Heading levels should only increase by one
## Summary

Ensures the order of headings is semantically correct.

## Locations

https://github.com/GCTC-NTGC/gc-digital-talent/blob/759d780c3dbde4012aac0b96515f1b5dacb0334d/frontend/admin/src/js/components/poolCandidate/CreatePoolCandidate.tsx#L355-L360

https://github.com/GCTC-NTGC/gc-digital-talent/blob/759d780c3dbde4012aac0b96515f1b5dacb0334d/frontend/admin/src/js/components/poolCandidate/UpdatePoolCandidate.tsx#L180-L185

https://github.com/GCTC-NTGC/gc-digital-talent/blob/759d780c3dbde4012aac0b96515f1b5dacb0334d/frontend/admin/src/js/components/poolCandidate/UpdatePoolCandidate.tsx#L249-L254

https://github.com/GCTC-NTGC/gc-digital-talent/blob/c8ff1a196d4275a58269f4273774e165366ee676/frontend/common/src/components/UserProfile/UserProfile.tsx#L176-L181

### PR DESCRIPTION
**Pull request by esizer**
Resolves #3832 

## Summary

This increases the heading levels for a few components by 1 to meet [WCAG 2.4.10.](https://www.w3.org/WAI/WCAG21/quickref/?showtechniques=246#section-headings)

### CODE REVIEW

**Comment by petertgiles** [comment]
Hi @Jerryescandon or @JoshBeveridge .  Could one of you review the Chromatic diff on this one?  https://www.chromatic.com/pullrequest?appId=61e099a1bb1465003a73d3ce&number=4043

**Comment by JoshBeveridge** [comment]
@esizer Do you mind tacking on the appropriate `data-h2-font-size` values to bring them back down to their original appearance? Definitely makes sense to fix the semantic hierarchy, but I think they're feeling a little visually heavy in this case for their intended purpose.

**Comment by JoshBeveridge** [comment]
🙈 @esizer please don't hate me but can I nitpick two things:
- Let's dump the font weight back down too
- Can you figure out why the alignment of the sibling link isn't centered with the heading text?

**Comment by JoshBeveridge** [comment]
Thanks @esizer!

**Review by JoshBeveridge — APPROVED** [review]

**Pull request merged**
