### PR TITLE
[Fix] Add more missing icons

### LINKED ISSUE #9129: ✨ More Missing Icons
## ✨ Feature

As a followup to #8781, we still have some missing icons showing up in the logs.   Over the last 3 days:

| Path                                               | Count |
|----------------------------------------------------|-------|
| /images/android-chrome-192x192.png                 | 302   |
| /images/android-chrome-512x512.png                 | 294   |
| /talent/images/mstile-310x310.png                  | 82    |
| /talent/images/apple-touch-icon.png                | 82    |
| /talent/images/android-chrome-512x512.png          | 81    |
| /talent/images/android-chrome-192x192.png          | 78    |
| /talent/images/mstile-144x144.png                  | 77    |
| /talent/images/mstile-310x150.png                  | 76    |
| /talent/images/mstile-150x150.png                  | 76    |
| /talent/images/favicon-32x32.png                   | 74    |
| /talent/images/mstile-70x70.png                    | 73    |
| /talent/images/favicon-16x16.png                   | 72    |
| /apple-touch-icon.png                              | 62    |
| /apple-touch-icon-precomposed.png                  | 56    |
| /apple-touch-icon-120x120.png                      | 10    |
| /apple-touch-icon-120x120-precomposed.png          | 10    |
| /en/applicant/profile-and-applications/favicon.ico | 6     |

It seems like the first two are requested much more.  Maybe the others are just crawlers/scanners?

## ✅ Acceptance Criteria

- [ ] /images/android-chrome-192x192.png    and /images/android-chrome-512x512.png   are made available

### PR DESCRIPTION
**Pull request by esizer**
🤖 Resolves #9129 

## 👋 Introduction

Fixes incorrect paths and adds new app icons.

## 🕵️ Details

The android paths were just incorrect in the default manifest file so these have been adjusted. as for the others:

- Items prefixed with `/talent` are old paths that are likely just sitting in a long lived cache
- Precompressed apple icon is an [old thing for <= iOS 7](https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html#:~:text=Safari%20on%20iOS%207%20doesn%E2%80%99t%20add%20effects%20to%20icons). Not sure we care about supporting this so left out 🤷‍♀️ 
- Added other sizes for apple touch icons to support older devices
- Couldn't really see where the bottom `favicon.ico` was failing but it had so few requests I didn't worry about it

## 🧪 Testing

> [!NOTE]
> This will be hard to test because you need a specific device to hit the icons.

1. Build `npm run dev`
2. Navigate to the locations listed in the `<head>` and `*.manifest` files and make sure they return the proper image

### CODE REVIEW

**Comment by mnigh** [comment]
> 2. Navigate to the locations listed in the `<head>` and `*.manifest` files and make sure they return the proper image

With this commit, https://github.com/GCTC-NTGC/gc-digital-talent/pull/8901/files#diff-c761322f82e214d2213bf36c17c39a684fb452773f7fa73fea9fed405459a8a7R39, the only webmanifest file that is ever served is `site-en.webmanifest`, basically undoing https://github.com/GCTC-NTGC/gc-digital-talent/pull/8007 and meaning that locale and project specific images are not longer used. Was this intended?

**Comment by esizer** [comment]
> With this commit, https://github.com/GCTC-NTGC/gc-digital-talent/pull/8901/files#diff-c761322f82e214d2213bf36c17c39a684fb452773f7fa73fea9fed405459a8a7R39, the only webmanifest file that is ever served is `site-en.webmanifest`, basically undoing #8007 and meaning that locale and project specific images are not longer used. Was this intended?

Is it not being overwritten by the following?

https://github.com/GCTC-NTGC/gc-digital-talent/blob/8c41f0be936e455f5ee9020b3f5223f5d39fa782/apps/web/src/components/SEO/Favicon.tsx#L39

**Comment by mnigh** [comment]
> > With this commit, https://github.com/GCTC-NTGC/gc-digital-talent/pull/8901/files#diff-c761322f82e214d2213bf36c17c39a684fb452773f7fa73fea9fed405459a8a7R39, the only webmanifest file that is ever served is `site-en.webmanifest`, basically undoing #8007 and meaning that locale and project specific images are not longer used. Was this intended?
> 
> Is it not being overwritten by the following?
> 
> https://github.com/GCTC-NTGC/gc-digital-talent/blob/8c41f0be936e455f5ee9020b3f5223f5d39fa782/apps/web/src/components/SEO/Favicon.tsx#L39

No, not overwritten. It looks like `<link rel="manifest" />` exist in the DOM.

https://github.com/GCTC-NTGC/gc-digital-talent/assets/3046459/742486d6-0c0a-4fa5-a45d-2e0e0ba9d343

**Comment by esizer** [comment]
> No, not overwritten. It looks like `<link rel="manifest" />` exists in the DOM twice.

oof, this may be a larger problem. It seems like `react-helmet-async` is duplicating all tags for different projects (not just index.html) instead of overwriting them. 😬 We may need to stick with a single file in the `index.html` and drop the tags outside of probably `title` since that is the only one not being duplicated. 

Technically these aren't really doing anything anyway since we are an SPA and these should be done through SSR anyway 🤷‍♀️

**Review by petertgiles — APPROVED** [review]
I don't really  understand the the react helmet changes but the android chrome images load up nicely now.  :sweat_smile:

**Comment by esizer** [comment]
> I don't really understand the the react helmet changes but the android chrome images load up nicely now. 😅

Oh, so we added `data-rh="true"` to our `index.html` because `react-helmet-async` only replaces tags with that attribute. It wasn't documented so we missed that 😢 . It still doesn't replace all tags when you change routes in `react-router` but it does replace most.

**Pull request merged**
