### PR TITLE
Restore old labels for old search page

### PR DESCRIPTION
**Pull request by petertgiles**
This branch restores the old Conditions of Employment labels for the old version of the search page.

Testing
- [ ] Refresh your local environment including intl-compile for talentsearch
- [ ] Set the `FEATURE_APPLICANTSEARCH` flag to false and recreate your PHP container
- [x] Confirm the old labels for CoE appear on the search page
image
- [x] Confirm the French labels are loaded, too
image

### CODE REVIEW

**Comment by petertgiles** [comment]
Got verbal approval from Gray.

**Review by tristan-orourke — APPROVED** [review]
Looks good! Tested locally, everything looks right. I'm going to go ahead and merge this into main so that I can push it to UAT right away.

**Comment by tristan-orourke** [comment]
Hmmm, after just fixing a couple merge conflicts, Cypress tests aren't passing :/

**Comment by tristan-orourke** [comment]
Seems okay now

**Comment by patcon** [comment]
I just realized while resolving a merge conflict for #3249 that there are multiple ways we're dealing with selective subsets of enums (_input_ to some options processor), and differing labels for display (_output_ from some options processor).

This is a-ok just as it is, but just wanted to point out the other way it's being handled (from WIP #3249), and then afterwards, a more robust way we might handle it in the future.

### Current Alternative

For label variants:
https://github.com/GCTC-NTGC/gc-digital-talent/blob/951d360357f5618cd4e60de89755172a6d79dde4/frontend/admin/src/js/components/user/useFilterOptions.tsx#L64

https://github.com/GCTC-NTGC/gc-digital-talent/blob/951d360357f5618cd4e60de89755172a6d79dde4/frontend/common/src/constants/localizedConstants.tsx#L756-L771

For variants in the subsets of the enum:
https://github.com/GCTC-NTGC/gc-digital-talent/blob/951d360357f5618cd4e60de89755172a6d79dde4/frontend/common/src/constants/localizedConstants.tsx#L739-L754

https://github.com/GCTC-NTGC/gc-digital-talent/blob/951d360357f5618cd4e60de89755172a6d79dde4/frontend/admin/src/js/components/pool/CreatePool.tsx#L303-L306

### Future?

We can think of this as inputs (subsets of the enum) and outputs (variants of the display text for labels). I think this proposal will help us handle all these cases and variation in the future:
https://github.com/GCTC-NTGC/gc-digital-talent/issues/3314

Please do feel free to weigh in on that issue above :)

**Pull request merged**
