### PR TITLE
Feature/5125 add skills info pool candidates csv

### LINKED ISSUE #5125: Additional skills info in CSV download for Pool Candidates
As an Admin, I want the CSV download for pool candidates data to include all the information needed for screening candidates so I can use it for screening and keep it as a record.

### Description
For each of the "need to have" and "nice to have" skills associated with a pool, add a column to the CSV download. The value in that column should be the "Skill justification" that was provided by the candidate. 

#### Format for skills each row of skills column

Skill name (essential or asset) - Below is for a single person's row

Role 1 @ Org 1: (this will be different for each type of experience though... but use the patterns we already have? Let me know if that's not clear)
Justification 1

Role 2 @ Org 2:
Justification 2

...
### Acceptance criteria
- [ ] Columns for need to have skills : **skill_name (essential)**, then nice to have skills: **skill_name (asset)** are added to the end of the columns
- [ ] The justifications (description) for the skills are added as values for each candidate in the columns. Justifications are associated with an experience and there can be multiple.
- [ ] We don't need checkmarks or anything like that, just 1 column per skill
- [ ] Sanitize the description/justification text before putting it in
- [ ] The current skills column can stay as-is

### PR DESCRIPTION
**Pull request by yonikid15**
🤖 Resolves #5125 

## 👋 Introduction

Admins want more information when screening candidates. 
This adds data to the pool candidates CSV download. There are now new columns for all essential (need to have) and nonessential (nice to have) skills

## 🕵️ Details

Below is the acceptance criteria. Please go through each one and make sure that they are met correctly.

- Columns for need to have skills : **skill_name (essential)**, then nice to have skills: **skill_name (asset)** are added to the end of the columns
- The justifications (description) for the skills are added as values for each candidate in the columns. Justifications are associated with an experience and there can be multiple.
- We don't need checkmarks or anything like that, just 1 column per skill
- Sanitize the description/justification text before putting it in
- The current skills column can stay as-is

## 🧪 Testing

Assist reviewers with steps they can take to test that the PR does what it says it does.

1. Build project: `npm run build`
2. Go to [Pool table](http://localhost:8000/en/admin/pools) and choose a pool and view it's candidates.
3. NOTE: Our seeding is not that great right now atm so it's possible to have candidates that won't have any skills connected to the pool. I suggest either looking at a Pool's skills (eg. `http://localhost:8000/en/admin/pools/{id}/edit#essential-skills`), and manipulating one of the candidates `experience_skills` by adding one or more. You could also apply to a pool on talentsearch side and view that candidate in the CSV.
4. Select one or more candidates and download the CSV.

## 📸 Screenshot

Here's an example of a CSV I created: [pool_candidates_2023-01-05T06_43_54.779Z.csv](https://github.com/GCTC-NTGC/gc-digital-talent/files/10353078/pool_candidates_2023-01-05T06_43_54.779Z.csv)

### CODE REVIEW

**Comment by petertgiles** [comment]
Hi @yonikid15.  Could you take a look at these merge conflicts?

**Comment by yonikid15** [comment]
> Hi @yonikid15. Could you take a look at these merge conflicts?

Okay, merge conflicts are resolved @petertgiles 👍

**Comment by esizer** [comment]
I assume we expect it to not exist if the user manually removes the pool from the filters to export candidates from all pools? Not really sure how else it could work 🤷‍♀️  but that is how it works now and how I would expect it to work.

**Comment by vd1992** [comment]
I think the data is being formatted a bit oddly, I've got this odd chunk floating off to the side
they appear to be of the pattern "experience name: justification"

image

I think they should go here, they've end up in the wrong spot

image

cloud architecture absolutely has justifications

image

**Comment by petertgiles** [comment]
I think the sanitation needs a bit of work.  Or maybe this is the issue with the justification ending up in the wrong spot that Vachan just fixed?  I added three skills to one experience and they all ended up in one column of the file.
image

**Comment by vd1992** [comment]
I did not fix/commit anything

**Comment by yonikid15** [comment]
> I think the data is being formatted a bit oddly, I've got this odd chunk floating off to the side they appear to be of the pattern "experience name: justification"
> 
> 
> I think they should go here, they've end up in the wrong spot
> 
> 
> cloud architecture absolutely has justifications
> 

Thanks Vachan and Peter, I'm looking into this now to see if I can replicate it and make a fix 👍

**Comment by yonikid15** [comment]
Okay @petertgiles and @vd1992, I think I got it! I tested for each below and a combination of one, two, or all:
- Quotes
- Commas
- Newlines 
[pool_candidates_2023-01-13T16_55_54.954Z.csv](https://github.com/GCTC-NTGC/gc-digital-talent/files/10414352/pool_candidates_2023-01-13T16_55_54.954Z.csv)

**Comment by vd1992** [comment]
it seems to have solved things on my end, very nice!
I am not entirely sure what is going on in the CSV functions side of things, so I will defer approval to someone else

**Pull request merged**
