### PR TITLE
Debt/1525 php version 8.1

### LINKED ISSUE #1525: Get app working locally with php 8.1
Get app working locally using PHP 8.1

## Acceptance Criteria
- [ ] create a new docker-compose file which replaces php image with one using PHP 8.1
- [ ] app otherwise works exactly the same. All tests pass.
- [ ] Upgrade the minimum amount of dependencies

### PR DESCRIPTION
**Pull request by vd1992**
closes #1525 
updates php in various odd places, noticeably from the changelog it wasn't consistent to begin with

testing:
tests pass

locally:
check out
`docker-compose build maintenance` 
`docker-compose stop php`
`docker-compose rm php`
`docker-compose build php --no-cache`
`docker-compose up --detach`
`docker-compose run --rm maintenance bash refresh_api.sh`
ensure the site works

### CODE REVIEW

**Comment by petertgiles** [comment]
Seems to work great.  But what's with the two graphql file changes?

**Comment by petertgiles** [comment]
As expected, we're going to have to close this one without merging.  I tried pushing it out to one of our servers just to see and it definitely won't run.  This is a great reference for the eventual "big bang" PR though.  👍 
image

**Comment by vd1992** [comment]
> Seems to work great. But what's with the two graphql file changes?

I dunno, composer did it

**Comment by vd1992** [comment]
> As expected, we're going to have to close this one without merging. I tried pushing it out to one of our servers just to see and it definitely won't run. This is a great reference for the eventual "big bang" PR though. 👍 image

Ah, so what next? Do I close this PR and mark the issue as "completed"?

**Pull request closed without merging**
