### PR TITLE
[Debt] Migrate create account test to Playwright

### LINKED ISSUE #10484: ♻️ Move e2e to Playwright - create-account.cy.ts
## ♻️ Debt/Refactor

Time to move our Cypress tests to Playwright
apps/e2e/cypress/e2e/talentsearch/create-account.cy.ts

## ✅ Acceptance Criteria

- [ ] Test moved to Playwright : create-account.cy.ts

## 🛑 Blockers

```[tasklist]
### Blocked By
```

### PR DESCRIPTION
**Pull request by esizer**
🤖 Resolves #10484 

## 👋 Introduction

Migrates the existing cypress test for new user creation to playwright.

## 🧪 Testing

1. Confirm test has same coverage to previous
2. Confirm it passes

### CODE REVIEW

**Review by yonikid15 — COMMENTED** [review]
I've tried a few times now and can't get the test to pass on webkit :cry: 
It's timing out during the sign in step.

image

image

It's probably just cause my laptop is slow.

**Comment by yonikid15** [comment]
Oh nice you added env variables so we can each increase our time :+1:
Re-running tests now.

**Comment by yonikid15** [comment]
I'm still having trouble with webkit. Seems like it's not able to locate the access token even though it's there :face_with_head_bandage: 

image

I can approve this for Chrome and Firefox. If we want to check webkit as well then someone else will need to review, until I get this sorted out.

**Review by vd1992 — APPROVED** [review]
Ran a few times, works for me 👍 

image

**Pull request merged**
