### PR TITLE
[Feature] Increase tables to full size width

### LINKED ISSUE #12000: ✨ Allow tables to be full screen width
## ✨ Feature

With the removal of the side nav menu for admins and moving all content into a container layout, wide tables have become harder to use for admins. Let's wrap tables in a `full` container so that they can make use of full screen width. 

## 🕵️ Details

The goal is to allow tables to make use of full screen width, while keeping other content on the page in a reasonable centered container.

## 🎨 Design

@JoshBeveridge 

## 📸 Screenshot

Table on a wide monitor before the nav update
Image

Table on a wide monitor after the nav update
Image

## 🙋‍♀️ Proposed Implementation

Wrap the Table component in a `full` container element.

## ✅ Acceptance Criteria

- [ ] Tables take up full screen width
- [ ] Other content remains in the same containers
- [ ] Remove deprecated Hero, and ensure all pages use new Hero component
- [ ] Design review by @JoshBeveridge

### PR DESCRIPTION
**Pull request by yonikid15**
🤖 Resolves #12000 

## 👋 Introduction

- Increase tables to use full screen width hydrogen property
- Pages now use new Hero component
- I'd also like to get a design review before merging @JoshBeveridge 

## 🧪 Testing

1. Buiild app `pnpm run build`
2. Login as `admin@test.com`
3. Ensure all tables are using full screen width hydrogen property

## 📸 Screenshot

localhost_8000_en_admin_pools

### CODE REVIEW

**Review by JoshBeveridge — CHANGES_REQUESTED** [review]
Reviewed with Yoni over a call:
* Couple small margin bugs for random tables
* Yoni offered to swap out the old headers for the new one 🥳

**Review by JoshBeveridge — APPROVED** [review]
From what I can tell, everything looks ace, thanks Yoni!

**Comment by vd1992** [comment]
Uh-oh, new user pages broke

image

**Review by vd1992 — CHANGES_REQUESTED** [review]
This too

image

Not using full width intentionally?

image

**Comment by yonikid15** [comment]
@vd1992 nice catch! Fixed in [cda97fb](https://github.com/GCTC-NTGC/gc-digital-talent/pull/12106/commits/cda97fb57850b0aa415150753a1515290eee8084)

localhost_8000_en_getting-started_from=%2Fen%2Fapplicant

localhost_8000_en_getting-started_from=%2Fen%2Fapplicant (1)

localhost_8000_en_getting-started_from=%2Fen%2Fapplicant (2)

localhost_8000_en_getting-started_from=%2Fen%2Fapplicant (3)

**Review by vd1992 — APPROVED** [review]
Nice!

**Pull request merged**
