### PR TITLE
[Debt] Removes Cypress artisan commands

### LINKED ISSUE #10483: ♻️ Remove artisan-commands.cy.ts
## ♻️ Debt/Refactor

Time to ~move~ delete our Cypress tests 
apps/e2e/cypress/e2e/api/artisan-commands.cy.ts

## ✅ Acceptance Criteria

- [ ] Remove : artisan-commands.cy.ts

## 🛑 Blockers

```[tasklist]
### Blocked By
```

### PR DESCRIPTION
**Pull request by mnigh**
🤖 Resolves #10483.

## 👋 Introduction

This PR removes the `artisan-commands.cy.ts` test file and the `callEloquentFactory` that was only ever used within that test file.

## 🧪 Testing

Assist reviewers with steps they can take to test that the PR does what it says it does.

1. Verify `callEloquentFactory` is not referenced anywhere in codebase
2. Verify Cypress workflow passes all tests

### CODE REVIEW

**Review by esizer — COMMENTED** [review]
Do we want to also remove [the actual artisan command](https://github.com/GCTC-NTGC/gc-digital-talent/blob/main/api/app/Console/Commands/CallFactory.php) for this? :thinking:

**Comment by mnigh** [comment]
> Do we want to also remove [the actual artisan command](https://github.com/GCTC-NTGC/gc-digital-talent/blob/main/api/app/Console/Commands/CallFactory.php) for this? 🤔

@petertgiles, the creator of said command, what say you?

**Comment by petertgiles** [comment]
> what say you?

Yeah, for sure.  It really has no use apart from this Cypress usecase.

**Review by esizer — APPROVED** [review]
Noice :ok_hand:

**Review by esizer — APPROVED** [review]

**Pull request merged**
