### PR TITLE
[Tooling] Reorganize Storybook

### LINKED ISSUE #5071: Reorganize Storybook

### PR DESCRIPTION
**Pull request by mnigh**
🤖 Resolves #5071.

## 👋 Introduction

This PR reorganizes storybook stories and:

- Adds alphabetical [story sorting](https://storybook.js.org/docs/writing-stories/naming-components-and-hierarchy#sorting-stories)
- Removes title prop from story export to let storybook autogenerate titles
- Replaces theme variants (light, dark) both rendered in single stories with Chromatic modes
- Removes stories that are duplicative or serve little utility

## 🎩 Acknowledgment
@esizer for brainstorming on some of the choices regarding conventions and utility of stories

## 🧪 Testing

Assist reviewers with steps they can take to test that the PR does what it says it does.

1. Run storybook
2. Review stories
3. Review snapshots in Chromatic

### CODE REVIEW

**Comment by tristan-orourke** [comment]
The automatic naming based on folder makes sense to me 👍

**Comment by vd1992** [comment]
Just running `pnpm run storybook`
Giving it a go locally. 

Main
Crashed
Built in 3.23 minutes

Branch
Crashed
Crashed
Built in 3.07 minutes

Crashing is not new and appears to be a cointoss. 
Once branch builds successfully, skimming through all the stories and nothing appears broken or errored

**Comment by vd1992** [comment]
298 -> 247 stories by the way it appears
🪓

**Comment by mnigh** [comment]
> should we skip coverage report on stories?

Probably? What do other @GCTC-NTGC/developers think?

This PR actually has some changes to non-story files that are minor, but filtering out story files here wouldn't have mattered for this particularly instance.

**Comment by vd1992** [comment]
> should we skip coverage report on stories?

Absolutely. 
Stories are basically a test onto themselves, or cover a similar niche so the coverage on them is likely rarely and possibly never relevant I'd say

**Comment by tristan-orourke** [comment]
Agreed, codecov can ignore stories.

**Comment by vd1992** [comment]
Digging around, the only story files being reported on appear to be within `/web`
https://app.codecov.io/gh/GCTC-NTGC/gc-digital-talent/pull/10171/tree?search=stories&displayType=list

Likely a settings issue within one of our Jest config files?
Issue https://github.com/GCTC-NTGC/gc-digital-talent/issues/10213

**Comment by mnigh** [comment]
> Digging around, the only story files being reported on appear to be within `/web` https://app.codecov.io/gh/GCTC-NTGC/gc-digital-talent/pull/10171/tree?search=stories&displayType=list
> 
> Likely a settings issue within one of our Jest config files? Issue #10213

Just to be clear, this PR **does** contain changes to non-story files so any change to codecov settings to ignore story files would not apply to this PR.

**Review by esizer — APPROVED** [review]
LGTM! :+1:

**Review by yonikid15 — APPROVED** [review]
Everything works on my end, code looks good. Storybook looks much cleaner as well, now nice work 👍 

image

**Pull request merged**
