### PR TITLE
[Bug] Multiple claim handling in frontend

### LINKED ISSUE #10901: 🐛 Claim verification - one rejection cancels the other claim
## 🐛 Bug

I found "perfect priority" who was unverified priority and veteran. They showed as "priority" in the list. When I rejected the "priority" status they showed up as "Citizen or resident" and got unsorted. I expected them to show as "Veteran" since they still had unverified veteran status.

## ✅ Acceptance Criteria

- [ ] If a user has two claims and one gets rejected then the other claim should still be honoured
- [ ] If a user has two claims and both get rejected then neither claim should be honoured
- [ ] Test suite for this feature, probably phpunit now that it's on the backend

## 🛑 Blockers

```[tasklist]
### Blocked By
- [ ] https://github.com/GCTC-NTGC/gc-digital-talent/pull/10701
```

### PR DESCRIPTION
**Pull request by vd1992**
🤖 Resolves #10901

## 👋 Introduction

Better handle what should be rendered for a person's category. Must account for verification of priority and veterancy as well as citizenship. 

## 🧪 Testing

1. Head to candidates table
2. Verify or reject various candidates and observe category in table updated

## 📸 Screenshot

Priority and Veteran

image

image

Failed Priority but is a Veteran

image

image

Failed both

image

image

Citizen Other

image

image

### CODE REVIEW

**Comment by esizer** [comment]
I thought this was supposed to be done [on the backend](https://github.com/GCTC-NTGC/gc-digital-talent/issues/10901#issuecomment-2211234981)? :thinking:

**Comment by vd1992** [comment]
Okay, this PR didn't affect sorting. Sorting scope acts in two places
That was added in https://github.com/GCTC-NTGC/gc-digital-talent/issues/10419

As well, the function `priorityWeightAfterVerification` was added in PR https://github.com/GCTC-NTGC/gc-digital-talent/pull/10764

**Comment by petertgiles** [comment]
I wrote a manifesto  :grimacing: 
https://github.com/GCTC-NTGC/gc-digital-talent/issues/10901#issuecomment-2225733446

**Review by petertgiles — APPROVED** [review]
Thanks for working on this!  As discussed, there are some bigger structural issues on main but this is a good interim fix.  :clap:

**Pull request merged**
