### PR TITLE
Rollback storybook 6.5

### PR DESCRIPTION
**Pull request by petertgiles**
Storybook 6.5 seems to have some webpack issues in our environment.  I've opened #2875 to take a closer look but in the meantime I've opened this PR to roll back the change.

### CODE REVIEW

**Comment by vd1992** [comment]
seems to be a thing for multiple people
https://github.com/storybookjs/storybook/issues?page=2&q=is%3Aissue+is%3Aopen

**Comment by vd1992** [comment]
counted like 10 issues related to Storybook not working proper after updating
one of them might be similar to ours, webpack one maybe, in any case can rule out it being a problem in your environment or on our half of the turf

**Comment by petertgiles** [comment]
The snapshotting is interesting, too.  It looks like it's picking up all of Vany's font changes and the error messages became more verbose.  :shrug:

**Review by vd1992 — APPROVED** [review]
all appears good, per slack convo

**Pull request merged**
