### PR TITLE
Fix deprecated @faker-js/faker functions

### LINKED ISSUE #2624: faker.random.arrayElement() is deprecated
Warning observed during jest tests:

    [@faker-js/faker]: faker.random.arrayElement() is deprecated since v6.3.0 and will be removed in v7.0.0. Please use faker.helpers.arrayElement() instead.

### PR DESCRIPTION
**Pull request by esizer**
## Summary

This replaces the deprecated `faker.random.arrayElement()` with the new `faker.helpers.arrayElement()`.

Resolves #2624

### CODE REVIEW

**Review by vd1992 — CHANGES_REQUESTED** [review]
still seem to be getting deprecated alerts upon running jests tests
it appears all faker.random.x are deprecated and not just faker.random.arrayElement
example
image

**Comment by vd1992** [comment]
assessing by `npm run test:watch` in directories, then reading the logs

**Comment by esizer** [comment]
> still seem to be getting deprecated alerts upon running jests tests it appears all faker.random.x are deprecated and not just faker.random.arrayElement example image

Thanks @vd1992 ! That is weird, `faker.random.word()` must use the `faker.random.arrayElement()` underneath. I'll do a sweep to see if there are any others that also do.

**Comment by esizer** [comment]
So, I looked into it and it seems that there was a bug in `6.3.0` where the `faker.random.word()` module still used the `faker.random.arrayElement()` module within it. [Seems they fix that with `6.3.1.`](https://github.com/faker-js/faker/pull/903). Faker has been bumped to resolve this issue.

Great catch @vd1992 ! 🎉

**Review by vd1992 — APPROVED** [review]
pulled latest
npm install'd
jest no longer throws deprecated warning

good job!

also, I will share this, my github wants to push this up, just sharing as an FYI
image

**Pull request merged**
