### PR TITLE
Chore - Update all storybook dependencies on /common, /admin, and /talentsearch

### PR DESCRIPTION
**Pull request by yonikid15**
- Updates storybook dependencies from 6.4.0 -> 6.4.8

### CODE REVIEW

**Review by mnigh — COMMENTED** [review]
Not sure if these issues existed before the dependency updates, but I thought I would raise them:

1. Common: Warning in console: _Addon controls: Control of type color only supports string, received "enum" instead_.
2. Common: Border radius seems not to be working on components even though the attribute `data-h2-radius="b(s)"` is present.

### Screenshots
Screen Shot 2021-12-06 at 13 07 34
Screen Shot 2021-12-06 at 13 05 46

**Comment by yonikid15** [comment]
> Not sure if these issues existed before the dependency updates, but I thought I would raise them:
> 
> 1. Common: Warning in console: _Addon controls: Control of type color only supports string, received "enum" instead_ (could be the same [issue raised here](https://github.com/storybookjs/storybook/issues/16322)).
> 2. Common: Border radius seems not to be working on components even though the attribute `data-h2-radius="b(s)"` is present.
> 
> ### Screenshots
> Screen Shot 2021-12-06 at 13 07 34 Screen Shot 2021-12-06 at 13 05 46

I don't think the dependency update is related to these 2 issues. The border radius can be fixed by adding the border settings to the hydrogen config.

**Comment by petertgiles** [comment]
> I don't think the dependency update is related to these 2 issues

I rolled back to the last commit on Friday and confirm that these two problems appeared back then.  I recommend merging this PR and opening new issues on the board to look into these.

**Review by petertgiles — APPROVED** [review]
The two problems @mnigh discovered appear to have existed before this dependency update.  Approving this PR and I will open some issues on the board to track them.

**Pull request merged**
