### PR TITLE
Feature - single search request view

### PR DESCRIPTION
**Pull request by yonikid15**
# Notes
- Creates the view for a individual search request.
- Components should be hooked up to api and fetch data. The forms should be fully functional as well.
- It's possible that the seeded pool candidate search requests return no candidate results in the table. I'll start creating a custom one with weaker filter restraints. 
- All the links should direct the user to the correct page.
- There are stories for each individual piece as well as the page as a whole.

### CODE REVIEW

**Review by petertgiles — COMMENTED** [review]
Very cool.  I'm getting some flags from eslint and prettier on SingleSearchRequestTable, SingleSearchRequest, and UpdateSearchRequest so it might be worth tidying them up a bit.

I'm also getting a React `Each child in a list should have a unique "key" prop` warning on SearchRequestTable in my browser console.

Lastly, I'm getting some awkward wrapping and horizontal scroll bars in the Manager section even when the pages is pretty wide.  I wonder if it might be worth collapsing that section to only two or three columns except on really wide layouts.
image

**Comment by yonikid15** [comment]
> Very cool. I'm getting some flags from eslint and prettier on SingleSearchRequestTable, SingleSearchRequest, and UpdateSearchRequest so it might be worth tidying them up a bit.
> 
> I'm also getting a React `Each child in a list should have a unique "key" prop` warning on SearchRequestTable in my browser console.
> 
> Lastly, I'm getting some awkward wrapping and horizontal scroll bars in the Manager section even when the pages is pretty wide. I wonder if it might be worth collapsing that section to only two or three columns except on really wide layouts. image

Thanks for the review! I was able to get all of the eslint and prettier errors except one. The error seems to be new and happening across all the table components. The accessor key doesn't expect a component inside a component without memoization (or creating outside the Table component, which I tried to do but still not working 😕). `Declare this component outside parent component "SearchRequestTable" or memoize it. If you want to allow component creation in props, set allowAsProps option to true.eslintreact/no-unstable-nested-components`. I think it's best to just create a new issue for it, that way they can all get cleaned up at once. What do you think @petertgiles?

**Comment by petertgiles** [comment]
> I think it's best to just create a new issue for it, that way they can all get cleaned up at once. What do you think @petertgiles?

Yeah, good idea.  We may even decide to turn off that rule it's a new one that's not useful.

**Comment by yonikid15** [comment]
> > I think it's best to just create a new issue for it, that way they can all get cleaned up at once. What do you think @petertgiles?
> 
> Yeah, good idea. We may even decide to turn off that rule it's a new one that's not useful.

Alright I made a issue for it here #1190. The PR is ready for another review whenever you can. Thanks!

**Review by petertgiles — APPROVED** [review]
Love it. 👍

**Pull request merged**
