### PR TITLE
Updates Hydrogen to 2.0.0-beta.33

### PR DESCRIPTION
**Pull request by substrae**
# ✨ Purpose
Fixes a major Windows-specific bug that prevents Hydrogen from compiling thanks to path specifics used in the Glob package. Also includes some Dev-requested QoL.
# 🧪 Changes
- Fixes the Glob bug preventing compiling on Windows @vd1992 
- Adds support for `logging.verbose`, which allows control over system console output @petertgiles 
- Adds support for Hydrogen queries inside of backtick characters @esizer 
# 📑 Related issues
- https://github.com/hydrogen-css/hydrogen/pull/205

### CODE REVIEW

**Review by vd1992 — APPROVED** [review]
Fantastic! 

image

**Review by esizer — APPROVED** [review]
backticks working! 🎉

**Review by mnigh — APPROVED** [review]
:tada:

**Comment by substrae** [comment]
Just going to merge `main` and then if I can get one last set of eyes to make sure nothing has broken 👍 @esizer or @mnigh

**Review by esizer — APPROVED** [review]
LGTM! 👍

**Pull request merged**
