### PR TITLE
[Feature] Adds values for `PoolSeederUat` key_tasks

### LINKED ISSUE #4632: ♻️ PoolSeederUat `key_tasks` missing copy
## 🕵️ Details
https://github.com/GCTC-NTGC/gc-digital-talent/blob/cd1283df758cb44727693772f2ee4131424329ac/api/database/seeders/PoolSeederUat.php#L40-L43

Also referred to as "Your work" in the UI.

## 📸 Screenshots
Screen Shot 2023-04-03 at 10 56 09

Screen Shot 2023-04-03 at 10 55 37

### PR DESCRIPTION
**Pull request by mnigh**
🤖 Resolves #4632.

## 👋 Introduction

This PR adds values for `PoolSeederUat` key_tasks and updates the seeder to work with the current models.

## 🧪 Testing

Assist reviewers with steps they can take to test that the PR does what it says it does.

1. `php artisan migrate:fresh`
2. `php artisan db:seed --class=UatSeeder`
3. Ensure no artisan errors
4. Navigate to `/admin/pools/:pool-id`
5. Observe seeded data under **Your work** heading

## 📸 Screenshot
Screen Shot 2023-07-19 at 12 03 38

### CODE REVIEW

**Comment by vd1992** [comment]
I get this error upon running, I ran `UatSeeder` instead, which I thought would be important to test

image

**Comment by vd1992** [comment]
Okay, it appears to be due to querying for this email

image

When this is seeded

image

**Comment by mnigh** [comment]
> Okay, it appears to be due to querying for this email

Great catch @vd1992! Please see 919029bb080af53aad21c91aa435e5c35e319452.

**Review by vd1992 — APPROVED** [review]
Success!
Though, not sure we'd ever want to run the `UatSeeder` again since it'd wipe what is saved currently

image

**Pull request merged**
