### PR TITLE
[Feature] Add striping to card accordions

### LINKED ISSUE #11497: ✨ Candy striping for accordion groups
## ✨ Feature

Accordions in "card" mode (as opposed to `AccordionMode="simple"`) should include candy stripping (alternating colored rows). 

~Also, accordion groups should include an optional footer section, which appears below the accordion items but is part of the same overall "card".~

## 🎨 Design

@JoshBeveridge  

example from Job Template design: https://www.figma.com/design/kTvZVVsdVziRqxanyUgSKZ/Job-template-library?node-id=355-21116&node-type=FRAME&t=pnKV4IMENftZID59-0

Component library documentation: https://www.figma.com/design/guHeIIh8dqFVCks310Wv0G/Component-library?node-id=3220-162654&node-type=frame&t=1BoTSwoNVIYrFbNq-0

## 📸 Screenshot

Image

## ✅ Acceptance Criteria

- [ ] Add striping to "card" mode accordion groups
- [ ] ~Add footer to accordion on job template page (make it part of the accordion group component)~
- [ ] ~Footer should always display with the same background color (not affected by candy striping)~

- [ ] Design review @JoshBeveridge

### PR DESCRIPTION
**Pull request by petertgiles**
🤖 Resolves #11497 

## 👋 Introduction

This branch adds candy striping to the base card accordion component.

## 🧪 Testing

1. Rebuild and check some pages with card accordions.
2. Check in dark mode as well.
3. Review the Chromatic diffs.

## 📸 Screenshot

image

### CODE REVIEW

**Review by JamesHuf — APPROVED** [review]
Everything looks good to me :+1:

**Comment by petertgiles** [comment]
I've pushed it to DEV as well, to help with review.

**Comment by brindasasi** [comment]
> I've pushed it to DEV as well, to help with review.

Looking great in DEV as well 👍

**Review by JoshBeveridge — DISMISSED** [review]
@petertgiles Looks good to me, the only note I have is that (and please don't hate me) but I keep slightly altering those gray borders between items, so if you can change it to `base(black.darkest.2) base:dark(black.darkest.5)` 🙈

**Comment by petertgiles** [comment]
I updated the border colours as requested.  It seems like "black" in a base:dark selector means fixed black so I guess "black:darkest:5" actually means "white:ightest:5".  It turned out pretty nice, I think.

After-left, before-right.
image
image

**Comment by petertgiles** [comment]
@JamesHuf could you please do a quick check since Josh is gone?

**Comment by JamesHuf** [comment]
I think black borders in dark mode are intentional. It looks like the [component library](https://www.figma.com/design/guHeIIh8dqFVCks310Wv0G/Component-library?node-id=3220-80829&node-type=instance&t=e9G0zrbSZQfGcbRB-0) recently updated in that direction.

**Comment by petertgiles** [comment]
Oh, you're right!  OK, here's that change.
[dark mode colour](https://github.com/GCTC-NTGC/gc-digital-talent/pull/11707/commits/4f0878cc13d94cec4dfeed220bc6c73f62d803a8)
image

**Review by JamesHuf — APPROVED** [review]
LGTM! :+1:

**Pull request merged**
