### PR TITLE
Fix search request submission

### LINKED ISSUE #3031: request creation in Talentsearch broken (local)
Attempting to submit a request errors at /talentsearch/request

error:
image

laravel log snippet
image

### PR DESCRIPTION
**Pull request by petertgiles**
h/t "Eagle Eyed" Vachan for finding the search submission bug.  Hopefully this sort of thing won't slip through once #2988 is in.

I think the problem was that [the EE fields are now in a sub-input](#2966).  Adding the spread directive puts them back where Eloquent expects them.

Suggested Test Steps
- [ ] Use the talent search site to submit a search request
- [ ] Use the admin site to verify search request was successfully saved

Closes #3031

### CODE REVIEW

**Comment by vd1992** [comment]
that enables submission, but still have an issue with the create request form, it does not send the appropriate data
doing some prodding, by adding this button

image

I see that formvalues does not appear to acknowledge anything below the Summary of Filters header

image

**Comment by vd1992** [comment]
Ah! My mistake! The only thing erroneous is the Equity object and that is because it isn't linked to the right variables!

**Comment by vd1992** [comment]
sorry, hope you don't mind me commiting it myself to make it clearer what I meant above
okay...
now it submits almost everything and saves almost everything, what appears to remain non-functional, is that it won't sync pools and won't actually save the equity stuff to database

**Comment by vd1992** [comment]
alright, it successfully saves to the database, so the issue is not there
image

the issue is admin-side, it fails to load the equity stuff, possibly due to it looking for different types
(viewing requests in /admin)

image

**Comment by JamesHuf** [comment]
> This will help: Laravel accessors your mutators: https://laravel.com/docs/9.x/eloquent-mutators#defining-an-accessor https://laravel.com/docs/9.x/eloquent-mutators#defining-a-mutator

We currently have laravel 8.83.15 so we need to use the 8.x version of these: 
https://laravel.com/docs/8.x/eloquent-mutators#defining-an-accessor
https://laravel.com/docs/8.x/eloquent-mutators#defining-a-mutator

**Pull request closed without merging**
