### PR TITLE
Support forms in Dialog components

### PR DESCRIPTION
**Pull request by patcon**
Extracted from #2641 (PR #3249)

We need to export a `<Dialog.Footer>` subcomponent to allow forms to work in `<Dialog>` components.

What this does:
- 82c3adfc12e5a6b600c92e9644a0db12589175d1 straight extraction of `Header` and `Footer` subcomponents within `Dialog` component.
- 1a3e26dceeec6644b6072b6b0741eca5d4579fc6 remove use of deprecated React.FC (needed for dot-notation exports to work)
- 172201d42b0df5b0c8bb67fe6bbf6f64621d1021 fix failing jest test (React.FC was masking something to do with `children`/`content` prop usage, I think?)
- 6ea98277e877c5e7fc7e55663f9a3a9f2df7c5ff added "Dialog with Form" story
- 27cf67541f057f6f8a8e4ab00ca4cfbd5490be50 converted Dialog stories to current storybook format
- 66b3ad0b78ef238c32d4b6aec484fb05db3cafa8 adjusted story names
- 8fabdf1f8faffb93ff0487469747e24fc58501b7 added stories for other 2 color styles (primary+secondary)
- 4d118f2 added decorator so that chromatic snapshots capture dialog window instead of just button
- eric suggestions
  - [x] f7057e98b c65beaac1 Remove Footer prop in favour of composing the component as needed
  - [x] 587d937fa Export additional sub components to be used as needed (Content, Overlay)
  - [x] 2832ee320 Rename `AlertDialog.Actions` -> `AlertDialog.Footer` to match this
- [x] 98e2ba496a95d1d7deb38292decba17934f8254f resolve TS error https://github.com/GCTC-NTGC/gc-digital-talent/pull/3538#issuecomment-1215183427

To review:
- check out "Dialog > WithForm" story, and confirm that forms work in modals now.
https://2641-dialog-footer-for-forms--61e099a1bb1465003a73d3ce.chromatic.com/?path=/story/components-dialog--with-form
- review the chromatic changeset: https://www.chromatic.com/pullrequest?appId=61e099a1bb1465003a73d3ce&number=3538&view=changes (the Dialog stories should now render, and the changes related to skills tabs are related to #3527)

### CODE REVIEW

**Comment by esizer** [comment]
Is this related to #3266 ?

**Comment by patcon** [comment]
> Is this related to https://github.com/GCTC-NTGC/gc-digital-talent/issues/3266 ?

I don't thiiiiiink so. Seems like that has some other proposal I'm not certain of, but this is mainly about exporting `<Dialog.Footer>` so that it can be used enclosed within children of `<Dialog>` tag -- the other stuff mostly just cascaded from resolving the typescript squigly lines, plus organizing related stories / fixing chromatic story snapshots.

**Review by esizer — CHANGES_REQUESTED** [review]
Are we able to attach this to the issue related to refactoring the dialog and incorporate those changes as well? #3266 

- [x] Remove Footer prop in favour of composing the component as needed
- [x] Export additional sub components to be used as needed (Content, Overlay)
- [ ] Rename `AlertDialog.Actions` -> `AlertDialog.Footer` to match this

**Comment by patcon** [comment]
I fully support those suggestions, but wondering if we can keep this separate? This PR was intended to just to ease ability to merge #2641, and I'm a bit remiss to start aligning with another PR to get the sub-PR merged on the way to the actual PR :)

Would it be ok to defer that work to the other [younger] PR?

**Comment by esizer** [comment]
For more context on the requested changes:

> * Remove Footer prop in favour of composing the component as needed

This would simple be removing the `footer: React.ReactNode;`  prop and instead require developers to implement it as a child.

```tsx
  // Old
  <Dialog
     ...
     footer={
      <Button>Button in Footer</Button>
     }
   >
      <p>Body of the dialog.</p>
   </Dialog>
  
  // New
  <Dialog ...>
      <p>Body of the dialog.</p>
      <Dialog.Footer>
        <Button>Button in Footer</Button>
      </Dialog.Footer>
  </Dialog>
 ```

> * Export additional sub components to be used as needed (Content, Overlay)

This is just adding the components to the `Dialog` component so they can be used if needed.

```tsx
Dialog.Overlay = Overlay;
Dialog.Content = Content;
Dialog.Header = Header;
Dialog.Footer = Footer;
export default Dialog;
```

> * Rename `AlertDialog.Actions` -> `AlertDialog.Footer` to match this

This one is just to rename the exiting `Actions` component in `AlertDialog` to match the `Footer` name in `Dialog`. Should just be a copy+paste.

## Notes

This is just a suggestion and if you believe this is out of scope, we can push it off. I just thought it was a little extra work and you are already covering part of that issue here so if we do at least the first two suggestions we can attach and close that issue as well.

**Comment by patcon** [comment]
Question: until a sub-component is actually being used elsewhere, could we consider just keeping them in one file? I'm just seeing all the file renaming that's required for something that is only ever used in one component, and it feels like we're following an exhaustive "one component per file" convention that doesn't feel like it brings benefit.

This PR doesn't need to change this, but just noting that this lingering preference for "less files" is kinda surfacing here again

**Comment by esizer** [comment]
> Question: until a sub-component is actually being used elsewhere, could we consider just keeping them in one file? I'm just seeing all the file renaming that's required for something that is only ever used in one component, and it feels like we're following an exhaustive "one component per file" convention that doesn't feel like it brings benefit.
> 
> This PR doesn't need to change this, but just noting that this lingering preference for "less files" is kinda surfacing here again

I have no real issue with this. The decision was was complete personal preference because of how easily I get overwhelmed  working with and navigating large files and I find the easiest way around that is by containing a single component to it's own file so I can easily see what logic is associated with what component. 😅 

That is why I also like the syntax of either named exports from an `index.ts` or as `Component.SubComponent` to avoid importing all of the sub component individually.

I also frequently work in vue and angular where this is an enforced rule and less of a guideline. Though, I do realize we are working in react where it is more common to see multiple components in a single file so if it is easier for everyone else then go for it! 😄

**Comment by patcon** [comment]
Seeing this error in a few checks, and need to resolve:

```
[tsl] ERROR in /home/runner/work/gc-digital-talent/gc-digital-talent/frontend/talentsearch/src/js/components/roleSalaryForm/dialogs.tsx(205,15)
      TS2339: Property 'Dialog' does not exist on type 'FunctionComponent<{ baseUrl: string; }>'.
ts-loader-default_3e375a5e11b48e2a
 @ ./src/js/components/roleSalaryForm/RoleSalaryForm.tsx 172:0-151 372:14-28 377:13-27 382:13-33 387:13-36 392:13-35 397:13-32
 @ ./src/js/components/Router.tsx
 @ ./src/js/pageContainer.tsx 19:0-45 27:19-25
```

https://github.com/GCTC-NTGC/gc-digital-talent/runs/7697991446?check_suite_focus=true#step:8:57

Thinking that removing use of React.FC should resolve. (The core react team no longer recommends using that base type, and our team previously decided we're good to move in that direction.)

**Comment by patcon** [comment]
Ready for review again @esizer! 🙏

**Review by esizer — CHANGES_REQUESTED** [review]
Looking great! Just two lint warnings. Once those are cleared up it should be good to go! 👍

**Pull request merged**
