### PR TITLE
Bug - 4715 - Fix homepage call to action alignment

### LINKED ISSUE #4715: Homepage calls-to-action size on Safari
# 🌩️ Summary

The calls-to-action on the homepage are currently formatted incorrectly when viewed in Safari. This isn't an issue in other browsers.

# ✅ Required changes

- [ ] Review the call-to-action component's implementation of flexbox to account for Safari-specific bugs

# 📸 Screenshots

## Current state in Safari

image

## What it should look like

image

### PR DESCRIPTION
**Pull request by esizer**
## 👋 Introduction

This accounts for a bug with default `display: flex;` `align-items` in safari 15.1 by setting it to `align-items: flex-start`;  and using `align-self: stretch;` instead of height on the icon container.

## 🧪 Testing

> **Note**
> This can only be completed by someone using macos with Xcode

1. Open Xcode
2. Select "Simulator" from the **Xcode > Open developer tool** menu
3. Select any iPad device from an iOS version <= 15.1
4. Navigate to the homepage in Safari on the simulator
5. Confirm the call to action buttons in the hero are not stretched

### Before

Screenshot 2022-11-15 at 12 21 53 PM

### After

Screenshot 2022-11-15 at 12 35 12 PM

## 🤖 Robot Stuff

Resolves #4715

### CODE REVIEW

**Review by petertgiles — DISMISSED** [review]
Works on my (real) iPad. 😊
2E1A51D1-26B7-4877-BB9D-6280C043CCEB

**Comment by petertgiles** [comment]
> Right now the only info I have is that it exists in `15.1` but not `16.1` sweat

Haha, a little bisection search.  Prod looks fine on my ipad right now

**Comment by esizer** [comment]
> Haha, a little bisection search. Prod looks fine on my ipad right now

Thanks, I guess we can't trust your review after all 😆 I think @mnigh plans on reviewing today 👍

**Review by mnigh — APPROVED** [review]
Nice work! 👍 

## Screenshots
### Simulator - iPad (9th generation), iOS 15.0 - main
Simulator Screen Shot - iPad (9th generation) - 2022-11-16 at 09 41 58_main

### Simulator - iPad (9th generation), iOS 15.0 - bug_4715_fix-homepage-buttons-stretching
Simulator Screen Shot - iPad (9th generation) - 2022-11-16 at 09 46 19_bug_4715_fix-homepage-buttons-stretching

**Pull request merged**
