### PR TITLE
[Debt] Refactor and improve auth for playwright tests

### LINKED ISSUE #9403: ♻️ Improve Playwright grapqhl request auth
## ♻️ Debt/Refactor

The goal is to not need to visit a page to have our access tokens refresh to make specific graphql requests within playwright.

## 🕵️ Details

We use graphql requests to setup specific data for tests. These requests need to be authorized. Currently, we visit the homepage to have our stored tokens refresh to make sure they are not expired and then get them from the browser storage.

Ideally, we just keep these tokens up to date as they refresh during the test run so we can just use [APIRequest](https://playwright.dev/docs/api/class-apirequest) instead.

## 🙋‍♀️ Proposed Solution

> [!NOTE]
> The options are ordered in terms of most ideal to least ideal.

### Option 1

I'm hoping we can intercept calls to the refresh endpoint and update state in the fixture. This would be the easiest and most automated way of completing this.

```tsx
export const test = base.extend<AppFixtures>({
  appPage: async ({ page }, use) => {
    const app = new AppPage(page);
    app.on('response', data => {
      if(response.url() === "/refresh") {
          await app.context().storageState({ path: auth.STATE.APPLICANT });
      }
    });
    await use(app);
  },
});
```

### Option 2

Another solution could be to mimic our `ClientProvider` and check to see if the token is expired before every request and if so, refresh it storing the new one.

```tsx
async graphqlRequest(query: string, variables?: Record<string, unknown>) {
  if(isTokenKnownToBeExpired(accessToken)) {
     await refreshToken();
     await this.page.context().storageState({ path: auth.STATE.APPLICANT });
  }
  // Continue on with API request 
}
```

### Option 3

If the others don't work, we could just extend the life time of our tokens during tests to last much longer. However, this defeats the goal of testing our app in a realistic environment so this should be seen as a last resort.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the debt was addressed and expected functionality has not been affected.

- [ ] `AppPage.graphqRequest()` does not need to visit the app to be run
- [ ] `graphqlRequest` does not need to visit the app to be run
- [ ] Storage state stays up to date as tokens are refreshed
- [ ] Auth is stable in tests

### PR DESCRIPTION
**Pull request by esizer**
🤖 Resolves #9403 

## 👋 Introduction

Updates how we do auth in playwright.

## 🕵️ Details

This does a few important things:

- Allows us to directly get a token from mock auth by using the `e2e` client id
- Adds a graphql context class to run queries with a specific user in setups
- Updates the factories in playwright to be standalone functions that take a context

## :chart_with_upwards_trend: GraphQL Context

This is a new class that contains all the context needed to make graphql requests, most importantly their tokens. In order to make working with it simpler, there is a facrtory for it.

### Usage

```ts
import graphql from "~/utils/graphql";

/**
 * Create a context where every request using this context
 * is sent with the key created in the factory method
 *
 * @param string? sub The sub for the user to create context for (default: admin@test.com)
 * @return GraphQLContext
 */
const ctx = await graphql.newContext(sub);

/**
  * Make a request with this context
  *
  * @param String query The graphql document
  * @param GraphQLRequestOptions opts  Options for the request
  * @param any opts?.variables Variables for the graphql request
  * @param bool opts?.isPrivileged If the request needs to be privileged (/admin/graphql)
  * @return unknown The response as JSON
  */
ctx.post(`
  query GetSkill($id: UUID!) { 
    skill(id: $id) {
      id
    }
  }
`, { variables: { id } };
```

Although, you likely will never need to interact directly with a context while writing tests. We abstract that away with factories. However, that means you will now need to pass the context into our factories.

```ts
const adminCtx = await grapqhl.newContext();
const user = await createUser(adminCtx);
```

## 🧪 Testing

1. Rebuld docker `make down; make up;`
2. Build app `pnpm run dev:fresh`
3. Confirm playwright tests still pass `pnpm run e2e:playwright --ui`

### CODE REVIEW

**Comment by vd1992** [comment]
Set timeout to 30 seconds then ran `pnpm run e2e:playwright:chromium`
All good 

image

**Review by mnigh — COMMENTED** [review]
I ran chromium and webkit individually. 🤷 

## Chromium

```
➜  gc-digital-talent git:(9403-improve-playwright-auth) pnpm run e2e:playwright:chromium

> gc-digital-talent@ e2e:playwright:chromium /Users/matt/gc-digital-talent
> pnpm --filter @gc-digital-talent/playwright run e2e:playwright:chromium


> @gc-digital-talent/playwright@1.0.0 e2e:playwright:chromium /Users/matt/gc-digital-talent/apps/playwright
> pnpm exec playwright test --project=chromium


Running 99 tests using 2 workers
  Slow test file: [chromium] › applicant/application-iap.spec.ts (1.6m)
  Slow test file: [chromium] › applicant/application.spec.ts (1.5m)
  Slow test file: [chromium] › admin/process-actions.spec.ts (1.5m)
  Slow test file: [chromium] › static-pages.spec.ts (50.5s)
  Slow test file: [chromium] › search-workflows.spec.ts (41.5s)
  Consider splitting slow test files to speed up parallel execution
  99 passed (14.1m)

To open last HTML report run:

  pnpm exec playwright show-report
```

## Webkit
```
➜  gc-digital-talent git:(9403-improve-playwright-auth) ✗ pnpm run e2e:playwright:webkit

> gc-digital-talent@ e2e:playwright:webkit /Users/matt/gc-digital-talent
> pnpm --filter @gc-digital-talent/playwright run e2e:playwright:webkit


> @gc-digital-talent/playwright@1.0.0 e2e:playwright:webkit /Users/matt/gc-digital-talent/apps/playwright
> pnpm exec playwright test --project=webkit


Running 99 tests using 2 workers
  1) [webkit] › admin/auth.spec.ts:134:9 › Authenticated › Applicant user › Cannot access restricted paths 

    Error: Timed out 30000ms waiting for expect(locator).toBeVisible()

    Locator: getByRole('heading', { name: 'Sorry, you are not authorized to view this page.' })
    Expected: visible
    Received: <element(s) not found>
    Call log:
      - expect.toBeVisible with timeout 30000ms
      - waiting for getByRole('heading', { name: 'Sorry, you are not authorized to view this page.' })


      143 |               name: "Sorry, you are not authorized to view this page.",
      144 |             }),
    > 145 |           ).toBeVisible();
          |             ^
      146 |         }),
      147 |       );
      148 |     });

        at /Users/matt/gc-digital-talent/apps/playwright/tests/admin/auth.spec.ts:145:13
        at /Users/matt/gc-digital-talent/apps/playwright/tests/admin/auth.spec.ts:135:7

    attachment #1: trace (application/zip) ─────────────────────────────────────────────────────────
    test-results/admin-auth-Authenticated-A-6e44e-not-access-restricted-paths-webkit/trace.zip
    Usage:

        pnpm exec playwright show-trace test-results/admin-auth-Authenticated-A-6e44e-not-access-restricted-paths-webkit/trace.zip

    ────────────────────────────────────────────────────────────────────────────────────────────────

  2) [webkit] › admin/auth.spec.ts:166:9 › Authenticated › Community recruiter › user accesses allowed paths only 

    Error: Timed out 30000ms waiting for expect(locator).toBeVisible()

    Locator: getByRole('heading', { name: 'Sorry, you are not authorized to view this page.' })
    Expected: visible
    Received: <element(s) not found>
    Call log:
      - expect.toBeVisible with timeout 30000ms
      - waiting for getByRole('heading', { name: 'Sorry, you are not authorized to view this page.' })


      177 |               name: "Sorry, you are not authorized to view this page.",
      178 |             }),
    > 179 |           ).toBeVisible();
          |             ^
      180 |         }),
      181 |       );
      182 |       await Promise.all(

        at /Users/matt/gc-digital-talent/apps/playwright/tests/admin/auth.spec.ts:179:13
        at /Users/matt/gc-digital-talent/apps/playwright/tests/admin/auth.spec.ts:169:7

    attachment #1: trace (application/zip) ─────────────────────────────────────────────────────────
    test-results/admin-auth-Authenticated-C-7836a-accesses-allowed-paths-only-webkit/trace.zip
    Usage:

        pnpm exec playwright show-trace test-results/admin-auth-Authenticated-C-7836a-accesses-allowed-paths-only-webkit/trace.zip

    ────────────────────────────────────────────────────────────────────────────────────────────────

  3) [webkit] › applicant/application-iap.spec.ts:74:7 › IAP Application › Can submit application ──

    Test timeout of 100000ms exceeded.

    Error: page.waitForResponse: Test timeout of 100000ms exceeded.

       at ../fixtures/AppPage.ts:29

      27 |    */
      28 |   async waitForGraphqlResponse(operationName: string) {
    > 29 |     await this.page.waitForResponse(async (resp) => {
         |                     ^
      30 |       if (resp.url()?.includes("/graphql")) {
      31 |         const reqJson = await resp.request()?.postDataJSON();
      32 |         return reqJson?.operationName === operationName;

        at ApplicationPage.waitForGraphqlResponse (/Users/matt/gc-digital-talent/apps/playwright/fixtures/AppPage.ts:29:21)
        at /Users/matt/gc-digital-talent/apps/playwright/tests/applicant/application-iap.spec.ts:250:23

    attachment #1: trace (application/zip) ─────────────────────────────────────────────────────────
    test-results/applicant-application-iap--5735e-tion-Can-submit-application-webkit/trace.zip
    Usage:

        pnpm exec playwright show-trace test-results/applicant-application-iap--5735e-tion-Can-submit-application-webkit/trace.zip

    ────────────────────────────────────────────────────────────────────────────────────────────────

  4) [webkit] › applicant/application.spec.ts:74:7 › Application › Can submit application ──────────

    Test timeout of 100000ms exceeded.

    Error: page.waitForResponse: Test timeout of 100000ms exceeded.

       at ../fixtures/AppPage.ts:29

      27 |    */
      28 |   async waitForGraphqlResponse(operationName: string) {
    > 29 |     await this.page.waitForResponse(async (resp) => {
         |                     ^
      30 |       if (resp.url()?.includes("/graphql")) {
      31 |         const reqJson = await resp.request()?.postDataJSON();
      32 |         return reqJson?.operationName === operationName;

        at ApplicationPage.waitForGraphqlResponse (/Users/matt/gc-digital-talent/apps/playwright/fixtures/AppPage.ts:29:21)
        at /Users/matt/gc-digital-talent/apps/playwright/tests/applicant/application.spec.ts:224:23

    attachment #1: trace (application/zip) ─────────────────────────────────────────────────────────
    test-results/applicant-application-Application-Can-submit-application-webkit/trace.zip
    Usage:

        pnpm exec playwright show-trace test-results/applicant-application-Application-Can-submit-application-webkit/trace.zip

    ────────────────────────────────────────────────────────────────────────────────────────────────

[40/99] …kit] › applicant/redirect.spec.ts:10:7 › Applicant redirects › Redirects /applicant/profile-and-applica
[41/99] …applicant/redirect.spec.ts:18:7 › Applicant redirects › Redirects /applicant/profile-and-applications/s
[42/99] …/redirect.spec.ts:28:7 › Applicant redirects › Redirects /applicant/profile-and-applications/skills/sho
[46/99] [webkit] › applicant/registration.spec.ts:6:7 › Registration › New user goes to registration then profil
[47/99] [webkit] › applicant/registration.spec.ts:85:7 › Registration › Skip verification on getting started pag
[65/99] [webkit] › login-logout.spec.ts:60:7 › Login and logout › show a message when logged in as a deleted use
[74/99] [webkit] › profile-page.spec.ts:6:9 › Profile Page › Anonymous visitor › Redirect restricted page to log
[75/99] …2:9 › Profile Page › Signed in user without applicant role › Render not authorized message for /en/appl
[76/99] …Signed in user without applicant role › Render not authorized message for /en/applicant/personal-inform
[77/99] …ge › Signed in user without applicant role › Render not authorized message for /en/applicant/career-tim
[78/99] …ile-page.spec.ts:55:9 › Profile Page › Signed in user with applicant role › Render personal information
[79/99] … profile-page.spec.ts:89:9 › Profile Page › Signed in user with applicant role › Render career timeline
[82/99] [webkit] › static-pages.spec.ts:11:9 › Static pages › Terms & Conditions › has no accessibility violatio
[86/99] …bkit] › static-pages.spec.ts:46:9 › Static pages › Accessibility statement › has no accessibility viola
[88/99] …] › static-pages.spec.ts:65:9 › Static pages › Directive on Digital Talent › has no accessibility viola
[89/99] …ges.spec.ts:73:9 › Static pages › Directive on Digital Talent › download enabling conditions file in En
[90/99] …› Static pages › Directive on Digital Talent › download department-specific recruitment form file in En
[91/99] …pec.ts:96:9 › Static pages › Directive on Digital Talent › download forward talent plan form file in En
[92/99] …ges.spec.ts:109:9 › Static pages › Directive on Digital Talent › download enabling conditions file in F
[93/99] … › Static pages › Directive on Digital Talent › download department-specific recruitment form file in F
[94/99] …pec.ts:139:9 › Static pages › Directive on Digital Talent › download forward talent plan form file in F
[97/99] …bkit] › support-page.spec.ts:21:9 › Support page › Support form › send POST request to existing API end
  Slow test file: [webkit] › applicant/application.spec.ts (1.7m)
  Slow test file: [webkit] › applicant/application-iap.spec.ts (1.7m)
  Slow test file: [webkit] › admin/process-actions.spec.ts (1.4m)
  Slow test file: [webkit] › static-pages.spec.ts (37.5s)
  Slow test file: [webkit] › search-workflows.spec.ts (33.5s)
  Consider splitting slow test files to speed up parallel execution
  4 failed
    [webkit] › admin/auth.spec.ts:134:9 › Authenticated › Applicant user › Cannot access restricted paths 
    [webkit] › admin/auth.spec.ts:166:9 › Authenticated › Community recruiter › user accesses allowed paths only 
    [webkit] › applicant/application-iap.spec.ts:74:7 › IAP Application › Can submit application ───
    [webkit] › applicant/application.spec.ts:74:7 › Application › Can submit application ───────────
  95 passed (14.7m)

  Serving HTML report at http://localhost:9323. Press Ctrl+C to quit.
```

**Comment by vd1992** [comment]
Webkit 😏

**Comment by vd1992** [comment]
Ran webkit locally
`pnpm run e2e:playwright:webkit`

image

**Comment by vd1992** [comment]
Webkit...

Ran failing specs from above one by one, only `auth.spec.ts` failed

<details>

image

</details>

**Comment by esizer** [comment]
> Webkit...
> 
> Ran failing specs from above one by one, only `auth.spec.ts` failed
> 
> image

Yeah, these tests have always sucked. Matt was helping me out a bit with these today. I might put a ticket up to revisit them. My suspicion is the fact they are using `Promise.all` which runs them concurrently. While this will speed the tests up, I think it could be causing some issues. It is probably better to run these synchronously or as separate tests instead of getting fancy :sweat:

**Comment by vd1992** [comment]
> Yeah, these tests have always sucked. Matt was helping me out a bit with these today. I might put a ticket up to revisit them. My suspicion is the fact they are using `Promise.all` which runs them concurrently. While this will speed the tests up, I think it could be causing some issues. It is probably better to run these synchronously or as separate tests instead of getting fancy 😓

Yeah, the more that is run simultaneously the more it probably chokes. Since some specs are getting larger, some of these tests will only get flakier

**Review by vd1992 — APPROVED** [review]
I'll give the approval for Chromium, Webkit has never played nicely for me. I'll leave it up to Matt to give a second approval or hold off

**Comment by mnigh** [comment]
> Yeah, these tests have always sucked. Matt was helping me out a bit with these today. I might put a ticket up to revisit them.

@esizer can you create an issue for this? i'll approve now as webkit locally was flakey before this PR.

**Review by mnigh — APPROVED** [review]
:shipit:

**Pull request merged**
