### PR TITLE
Upgrade php and switch to nginx

### LINKED ISSUE #4583: Upgrade app to use PHP 8.1 and Nginx
Combine the results of #1525 and #4745 to get the app working with PHP 8.1 and Nginx.

This ticket includes testing (and eventually deploying) on Azure infrastructure.

## Acceptance Criteria
- [ ] Devs can run the app locally using the same procedures and .env files as before, but now it will use Nginx and PHP 8.1. (It is understandable that apache_env and live-reloading variables will be different.)
- [ ] All tests continue to pass. Any tests created in for #3560 and #4745 are included.
- [ ] The app works the same. In particular, routing, feature flags, images/resource files served correctly, 404 page, continue to work the same.
- [ ] Tested on the Azure Dev server. 

## Deployment Instructions
- When deploying this to a server, it must be set to use PHP 8.1 instead of 7.4. Do this through the IaC.

### PR DESCRIPTION
**Pull request by petertgiles**
# :wave: Introduction
This branch is a switch to use PHP 8.1 and Nginx both locally and in production. It updates the Docker Compose network to use an Nginx with PHP 8.1 image from Microsoft. The app should continue to work normally with this change under the hood.

> **Note**
> This PR only has a few small modification from the two parent PRs: #4745 and #4591.  You may want to refer back to those for more details

# :test_tube: Testing

This branch should probably be tested in both the local environment and on the dev server.  It's currently available for testing on the dev server but, of course, you need to use your tablet.  Ping me if you need me to promote your user with the ADMIN role there.

1) There are Docker changes. Take down your docker-compose network and re-up it.  You should get a new `webserver` service from the Microsoft image.
1) Rerun the setup.sh script or carefully reset your environment manually.  Note that there are `.env.example` changes that need to be respected.
1) There are API changes.  Make sure you refresh that project.
1) There are frontend Webpack changes.  Make sure you refresh that.
- [ ] Works locally
  - [ ] Can navigate to all the places
    - [ ] Homepage
    - [ ] TC Report
    - [ ] Search, Browser, User, Support, Accessibility Statement
    - [ ] Login
    - [ ] Logout
    - [ ] Login/Logout with SiC
    - [ ] IAP
    - [ ] Admin
    - [ ] Graphql playground
  - [ ] Can download static files: images, PDFs
- [ ] Works on the dev server dev-talentcloud.tbs-sct.gc.ca
  - [ ] test all the same stuff

# :desktop_computer: Deployment Notes
- The vertical must have the IaC pipeline deployed to at least Release 389

# :robot: Robot Stuff
Closes #4583

### CODE REVIEW

**Comment by vd1992** [comment]
My steps so far...

`docker-compose down`
manually remove php from docker
`docker-compose up --detach`
`docker-compose build maintenance --no-cache`
sync env with example in admin, talentsearch, and indigenousapprenticeship 
`docker-compose run --rm maintenance bash refresh_api.sh`
run codegen, intl-compile, dev across workspaces

**Comment by vd1992** [comment]
whoa, bouncing around a bit and some parts actually do feel faster for me!

https://recordit.co/I2exLKasQL

**Comment by vd1992** [comment]
I see that speed boost in Cypress too

image

**Comment by vd1992** [comment]
php commands work but first this error message appears

image

**Comment by petertgiles** [comment]
> php commands work but first this error message appears

Yeah, the variant of the docker image I selected has xdebug in it though I haven't tried to configure it or use it.  We could use the regular image instead if you think the warnings are too much of a nuisance.

**Comment by vd1992** [comment]
> > php commands work but first this error message appears
> 
> Yeah, the variant of the docker image I selected has xdebug in it though I haven't tried to configure it or use it. We could use the regular image instead if you think the warnings are too much of a nuisance.

if the error message doesn't mean anything and can be ignored then I don't think it is that big of a deal

**Comment by vd1992** [comment]
a chunk error still occurred, not relevant to this PR maybe (?) 😕  but thought I would mention it

image

**Comment by petertgiles** [comment]
> a chunk error still occurred, not relevant to this PR maybe (?) confused but thought I would mention it

Bummer, I was hoping #4815 would solve that.  :cry:  When you reloaded did it solve the problem?  Is it happening often?

**Comment by vd1992** [comment]
> > a chunk error still occurred, not relevant to this PR maybe (?) confused but thought I would mention it
> 
> Bummer, I was hoping #4815 would solve that. 😢 When you reloaded did it solve the problem? Is it happening often?

reloading fixed it
but it keeps happening

**Comment by vd1992** [comment]
video

https://recordit.co/RClzXs4W8u

**Review by vd1992 — APPROVED** [review]
- checks green
- navigating successful
- can login/logout locally
- graphQL Playground works
- submitted an application and created a request successfully

things look good from what I can tell, performance seems better
amazing!

**Comment by tristan-orourke** [comment]
Testing
- [ ] Works locally
  - [ ] Can navigate to all the places
    - [ ] Homepage
    - [ ] TC Report
    - [ ] Search, Browser, User, Support, Accessibility Statement
    - [ ] Login
    - [ ] Logout
    - [ ] Login/Logout with SiC
    - [ ] IAP
    - [ ] Admin
    - [ ] Graphql playground
  - [ ] Can download static files: images, PDFs
- [ ] Works on the dev server dev-talentcloud.tbs-sct.gc.ca
  - [ ] test all the same stuff

**Comment by vd1992** [comment]
Oops 😅  I forgot to check the Apprenticeship page
I do see the variable console warning for it... going to poke around a bit

I do not see `Manifest: Line: 1, column: 1, Syntax error.` anywhere in Firefox. I now tried Edge and can confirm it appears there

**Comment by vd1992** [comment]
okay, I think I see the source of the runtime variable issues
the page is rendered in component `<Layout>` found here, `\indigenousapprenticeship\src\js\components\Layout.tsx`
It is nested in `<AuthenticationProvider>` regardless of login/logout appearing on the page

image

and Provider requires the presence of those variables, here
I think it would be best to just add those variables to the .env file?

image

**Comment by petertgiles** [comment]
> Manually entering the /fr version of a url doesn't necessarily bring you to the correct language. Only clicking the link in the header changes the language. (Note: it DOES work for the tc-report.)

This is actually a problem on main right now.  Probably a react router thing. I've opened #4884.

> Console errors on IAP: Missing mandatory runtime variable: OAUTH_LOGOUT_URI and Missing mandatory runtime variable: OAUTH_POST_LOGOUT_REDIRECT though those variables are not used in IAP.

Thanks for the digging, @vd1992 , I think you're right.  It can't hurt so I aligned the config for IAP with the other projects in [align IAP config](https://github.com/GCTC-NTGC/gc-digital-talent/pull/4871/commits/8aa21495403253e6ff6ea8bfa054bbaa593d6623).

> Console error happening everywhere: Manifest: Line: 1, column: 1, Syntax error.

Good catch!  I use Firefox which doesn't do PWAs so I missed this.  I've added webmanifest to the list of static file extensions in [Add webmanifest to static file extensions](https://github.com/GCTC-NTGC/gc-digital-talent/pull/4871/commits/d72764e477b07fe463b6b58fc8480ec5f50e7ba2).

> Going to /en/logged-out causes a warning about react refs in the console. (Probably not related to this PR.)

I'm having trouble replicating this.  I haven't changed any typescript in this PR so I agree that it's probably not related.  Let me know if you want me to try digging into this further.

> Logging out works, but shows some kind of webpack error in console: CombinedError: [Network] Failed to fetch at makeErrorResult (...) at eval (...)

I can't replicate this either.  Is this a chunk error again?

> Also got the CombinedError Failed to fetch when going to support page. EDIT: I can't reproduce this.

I can't replicate. :cry: 

> The login button seems to be a link to /login, but going to /login manually just redirects to home page. EDIT: I reproduced this on production.

Which login button is this?  Do you want me to make an issue?  The one in the header works for me OK.

> I can visit log in via SiC dev server, visit my profile, logout, and then use the browser Back function to get back to my profile, and still be able to edit it!

I can't replicate this.  Did you remember to enable the OAUTH_LOGOUT_URI variable, which got moved to the regular talentsearch .env file in this PR?  That is commented out by default since it doesn't work with mock-auth but is important to notify SiC of the logout.

**Review by tristan-orourke — COMMENTED** [review]
Testing on UAT in Edge...
I still see some console errors:
- Syntax error in set.webmanifest. This happens on every new page.
- Missing mandatory runtime variables on IAP homepage (OAUTH_LOGOUT_URI and OAUTH_POST_LOGOUT_REDIRECT)
- Occasionally I see `CombinedError: [Network] Failed to fetch. I saw this when logging out.

But at the same time... from the perspective of a normal user who doesn't have the console open, everything is working correctly. If any of those issues is tricky to fix, I don't mind bumping them into their own ticket.

**Comment by petertgiles** [comment]
> I still see some console errors:

Shoot, I'm so sorry, the build I put up on UAT was [d36a895](https://github.com/GCTC-NTGC/gc-digital-talent/pull/4871/commits/d36a895be73b56d132dba33256746f05408029bf), before the three commits that fixed the issues you found locally.  :frowning_face:   Thanks for the extra review, though.  I'm glad you didn't find anything new.  :smile:

**Pull request merged**
