### PR TITLE
6163 - implement webpack text compression

### LINKED ISSUE #6163: Perf - Enable text compression
## ♻️ Debt/Refactor

Google lighthouse recommends enabling text compression to reduce file sizes served.

## 🕵️ Details

https://developer.chrome.com/docs/lighthouse/performance/uses-text-compression/?utm_source=lighthouse&utm_medium=devtools

## ✅ Acceptance Criteria

- [ ] JS bundles compressed ahead-of-time for prod builds
- [ ] Nginx config updated to support this
- [ ] Compressed files (images, documents) not affected
- [ ] dev builds not affected
- [ ] API not affected
- [ ] Google Lighthouse audit satisfied

### PR DESCRIPTION
**Pull request by vd1992**
## 👋 Introduction

Closes #6163

Observing the main suggestion of #6071
I attempted implementing compression to test how it works locally. 

Think it is... promising?

## 🕵️ Details

Googled to get a feel for something to try, and implemented things that I found. Like from reading this
https://stackoverflow.com/questions/57504666/enable-text-compression-using-react-webpack-and-apache

Uses
https://github.com/webpack-contrib/compression-webpack-plugin

## 🧪 Testing

1. docker down then up
2. run build
3. observe the site

## 📸 Screenshot

Comparison of results for the homepage

image

Lighthouse run for the homepage (contrast to https://github.com/GCTC-NTGC/gc-digital-talent/issues/6071#issuecomment-1492068357)

image

### CODE REVIEW

**Comment by petertgiles** [comment]
That perf improvement looks yuge!  :laughing: :clap: 

We'd probably only want to gzip it on prod builds to keep dev speedy.  We'd also need to test in Azure to make sure it works well deployed, too.

**Comment by vd1992** [comment]
> Hmm, I wonder how we get our API to gzip our JSON graphql data, too?

pretty easily lol https://github.com/GCTC-NTGC/gc-digital-talent/pull/6151/commits/509424b50c0f21129e1366fceeddea89f88b269b


image

**Comment by esizer** [comment]
Yo, this looks really great 🎉

**Comment by vd1992** [comment]
tweaked it to only compress for `build` and not `dev` in https://github.com/GCTC-NTGC/gc-digital-talent/pull/6151/commits/db973c21e03ba93dbe42baa1f379a294585fa015
realized I was redundantly compressing it on the server, now it only serves a compressed gzip if it exists, it won't make any https://github.com/GCTC-NTGC/gc-digital-talent/pull/6151/commits/445f24a2f7c6d45adb98f2b9c271c50e1371f614

that squeezed a bit more performance out 😀 
think this only needs testing in Azure now 🤔 

image

**Pull request merged**
