### PR TITLE
[Debt] Update assessment step tracker initial state

### LINKED ISSUE #9610: ✨ Change default states for Screening and Assessment tab
## Description

In the "Screening and assessment" tab of a process, change the default state when landing on this page.

### TO-DO

- Default toggle statuses should only have "To assess" On, and other statuses turned off.
- Show distribution should start collapsed 

## Design

[Figma file ](https://www.figma.com/file/em5ArPr044YaIe1Vb1zCZz/Admin---Processes%2FPools%2FRecruitments---Record-of-Decision?type=design&node-id=8543%3A22431&mode=design&t=FOrM1sATMNR7xgJG-1)by @Jerryescandon 

## Screenshots

Image

## Question
Is it easy to always keep the same filters as the user last selected when they come back to the page? If so, we might want to do that. Design is not sure if it's valuable though, so only if it's easy. Otherwise, we can wait until someone complains.

## Acceptance criteria

- [ ] Default filtering has "To assess" selected and all others unselected

### PR DESCRIPTION
**Pull request by esizer**
🤖 Resolves #9610 

## 👋 Introduction

Changes the initial state of the step tracker to only show "to assess" status and hide the distribution summary.

## 🧪 Testing

1. Build `npm run dev`
2. Login as admin `admin@test.com`
3. Navigate to a process screening and assessment page
4. Confirm that only the  "to assess" filter is enabled
5. Confirm the distribution is collapsed

## 📸 Screenshot

Screenshot 2024-03-05 123831

### CODE REVIEW

**Review by vd1992 — APPROVED** [review]
👍

**Comment by vd1992** [comment]
Hang on, Playwright failing 👀

**Comment by esizer** [comment]
> Hang on, Playwright failing 👀

Re-ran but something is odd. We are getting a graphql error 😢 Seems the user is logged in but has no roles? 😕 

Screenshot 2024-03-05 140950

**Comment by vd1992** [comment]
Last run on main failed too 
https://github.com/GCTC-NTGC/gc-digital-talent/actions/workflows/playwright.yml?query=branch%3Amain

**Comment by esizer** [comment]
> Last run on main failed too
> https://github.com/GCTC-NTGC/gc-digital-talent/actions/workflows/playwright.yml?query=branch%3Amain

Yeah, same exact error 😕

**Pull request merged**
