### PR TITLE
[Feature] Update general questions UI

### LINKED ISSUE #8676: ✨ Update General Questions UI
## ✨ Feature

We want to separate the general questions associated with the pool directly with the screening questions associated with an assessment step.  This will allow us to ensure that the general questions are not associated with a skill and cannot be used in the assessment plan.  It will also allow us to make skill associations mandatory for every assessment plan step.

## 🎨 UI Screenshots

**Admin - Advertisement information** [Figma file](https://www.figma.com/file/e2DTvyppj41m6slFWTDZ0U/Admin---Job-advertisement-creation?type=design&node-id=52%3A40341&mode=design&t=po4ttDN8MiQ7QUfn-1) 
(Related ticket #8751 )

We have separated the General questions from the Screening question, "General" questions will appear on the advertisement information page as a repeater that can be used during the poster creation while "Screening" questions will be added during the assessment plan builder and tied to skill (skills would be required).

<details><summary>📸 Empty</summary>
<p>

image

</p>
</details> 

<details><summary>📸 Modal</summary>
<p>

image

</p>
</details> 

<details><summary>📸 Full</summary>
<p>

image

</p>
</details> 

## 🎨 Design File

Rename ScreeningQuestion to GeneralQuestion

```mermaid
classDiagram

class Pool { }

class AssessmentStep {
    Int sortOrder
    AssessmentType type
    LocalizedString title
}

class GeneralQuestion {
    Int sortOrder
}

class GeneralQuestionResponse {
    String answer
}

class PoolCandidate

class ScreeningQuestion {
     Int sortOrder
}

class ScreeningQuestionResponse {
    String answer
}


Pool "1" o-- "0..*" AssessmentStep
Pool "1" o-- "0..*" GeneralQuestion
GeneralQuestion "1" -- "0..*" GeneralQuestionResponse
PoolCandidate "1" o-- "0..*" GeneralQuestionResponse
Pool "1" o-- "0..*" PoolCandidate
AssessmentStep "1" o-- "0..*" ScreeningQuestion
PoolCandidate "1" o-- "0..*" ScreeningQuestionResponse
ScreeningQuestion "1" o-- "0..*" ScreeningQuestionResponse
```

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] Ability to edit general questions added back into the admin pool editor
- [ ] General Questions UI matches new design and uses new Card Repeater
- [ ] Copy checked, no mix-ups between general and screening questions copy, additions as needed such as below

generalQuestions version of 
299756803-73d8ea8e-e681-4799-9246-91e0d5b386e6

### PR DESCRIPTION
**Pull request by esizer**
🤖 Resolves #8676 

## 👋 Introduction

Updates the general questions Ui on the edit pool page to use the new `CardRepeater` component.

## 🧪 Testing

Assist reviewers with steps they can take to test that the PR does what it says it does.

1. Build `npm run dev`
2. Login as admin
3. Navigate to `/admin/pools/create`
4. Create a new pool
5. Scroll down to the "General questions" section
6. Add, update, move, delete questions
7. Confirm each action works as expected

## 📸 Screenshot

Screenshot 2024-02-02 131923

### CODE REVIEW

**Review by petertgiles — COMMENTED** [review]
The edit pool page works very well!  Very clean, no concerns.  :sunglasses: 

I'm not sure what the scope of this issue is - it has been edited many times since I first made it.  :sweat_smile: Probably a question for next standup.

I still see "screening questions" in:
- the application
image
- the view application
image

**Comment by petertgiles** [comment]
Discussion in scrum: covered in #9041

**Review by petertgiles — APPROVED** [review]
:+1:

**Comment by esizer** [comment]
@petertgiles Looks like there was an issue deleting due to the foreign key constraint. Mind taking another look after [fix general question foreign key constraints](https://github.com/GCTC-NTGC/gc-digital-talent/pull/9196/commits/f6e897841007c5c5c04c958fd76b856443d6abea) ?

**Review by petertgiles — APPROVED** [review]
Migration looks good. :+1:

**Pull request merged**
