### PR TITLE
[Fix] Pagination story

### LINKED ISSUE #10193: 🐛 `Pagination` stories render errors
## 🐛 Bug

`Pagination` stories render errors.

## 🦋 Expected Behaviour

No errors.

## 📋 Steps to Reproduce

1. Run storybook
2. Open developer console
3. Navigate to any of the `Pagination` stories
4. Observe errors

## 📸 Screenshot

Screen Shot 2024-04-24 at 08 31 54

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] no errors appear for `Pagination` stories

### PR DESCRIPTION
**Pull request by esizer**
🤖 Resolves #10193 

## 👋 Introduction

Refactors the `Pagination` story to the new format, fixing incorrect args at the same time.

## 🧪 Testing

1. Run storybook `pnpm run storybook`
2. Open the `Pagination` story
3. Confirm no errors in the console

### CODE REVIEW

**Comment by mnigh** [comment]
> Not sure what's causing this 😕 looks like it's outputting all the mouse events

This is not new, this was happening before this PR. The story has 274 controls, I think some from `PaginationProps` though not sure why ones like `onAnimationEndCapture`. 🤷

**Comment by esizer** [comment]
> Not sure what's causing this 😕 looks like it's outputting all the mouse events

@yonikid15 and @mnigh  Looks like the [CSF3 automatically applies actions to every event emitted from the component](https://storybook.js.org/docs/api/csf#default-render-functions:~:text=Not%20only%20are%20these%20versions%20shorter%20and%20more%20accessible%20to%20write%20than%20their%20no%2Dargs%20counterparts%2C%20but%20they%20are%20also%20more%20portable%20since%20the%20code%20doesn%27t%20depend%20on%20the%20actions%20addon%20specifically.). Since we need `DetailedHTMLProps` for hydrogen so we can spreadt `data-attributes` to the compoent, we are actualy also spreading all of those event emitters as well.

We may need to look into a `data-h2-*` specific type since we can't use the bult in `className` for styling :cry: 

For now, fixed by omitting everything except the two actions we care about in [only use actions on specific events](https://github.com/GCTC-NTGC/gc-digital-talent/pull/10353/commits/5421cdc87bfac8b168d82cd0ae72d3c0dc530a0b)

**Comment by mnigh** [comment]
> For now, fixed by omitting everything except the two actions we care about in [only use actions on specific events](https://github.com/GCTC-NTGC/gc-digital-talent/pull/10353/commits/5421cdc87bfac8b168d82cd0ae72d3c0dc530a0b)

@esizer What about [filtering controls](https://storybook.js.org/docs/essentials/controls#filtering-controls) so we don't have a bunch we don't need or removing them all if they are causing trouble?

```ts
export default {
  component: Pagination,
  args: {
    ariaLabel: "Pagination table",
    onCurrentPageChange: action("Change page"),
    onPageSizeChange: action("Change page size"),
    color: "black",
    totalCount: 100,
    totalPages: 10,
    siblings: 1,
    currentPage: 1,
    pageSize: 10,
  },
  parameters: {
    controls: {
      include: [
        "ariaLabel",
        "totalCount",
        "totalPages",
        "siblings",
        "currentPage",
        "pageSize",
      ],
    },
    actions: {
      argTypesRegex: "^(onCurrentPageChange|onPageSizeChange)$",
    },
  },
} satisfies Meta<typeof Pagination>;
```

**Comment by esizer** [comment]
> @esizer What about [filtering controls](https://storybook.js.org/docs/essentials/controls#filtering-controls) so we don't have a bunch we don't need or removing them all if they are causing trouble?

I like that suggestion. Updated in [remove unused controls](https://github.com/GCTC-NTGC/gc-digital-talent/pull/10353/commits/5fb6d4688fa745f8ea31271cacaa4cf22dff7a6f)

**Review by mnigh — APPROVED** [review]
The story still does not highlight the current page on click (does work on when changing the value in the action pane), but that is no different than before (out of scope). LGTM!

**Pull request merged**
