### PR TITLE
[Debt] Ignore stories in code coverage

### LINKED ISSUE #10213: 🛠️ Have Codecov ignore story files for coverage report
## 🛠️ Tooling

Codecov appears to include story files within `/web` for coverage reports. We have decided we don't want that.
Have Codecov ignore all story files for coverage reporting. This may involve digging through settings. 

Example

https://app.codecov.io/gh/GCTC-NTGC/gc-digital-talent/pull/10171/tree?displayType=list&search=stories

## ✅ Acceptance Criteria

- [ ] Codecov ignores all story files

### PR DESCRIPTION
**Pull request by esizer**
🤖 Resolves #10213 

## 👋 Introduction

This ignores storybook files for code coverage reports.

## 🧪 Testing

1. Check code coverage report
2. Confirm stories are not counted

### CODE REVIEW

**Comment by vd1992** [comment]
Could you please push up a junk commit to trigger a Jest run?

**Comment by esizer** [comment]
> Could you please push up a junk commit to trigger a Jest run?

Junky enough? :stuck_out_tongue: [junk: remove commas](https://github.com/GCTC-NTGC/gc-digital-talent/pull/10292/commits/03e5eb3cdc23ccc8d4db8d26a4efe27fd5ce417b)

**Review by vd1992 — APPROVED** [review]
Looks to have done the job!
Ideally revert the commit first then merge 🙃 

image

**Comment by vd1992** [comment]
Large swing from main appears to just have been a failed upload due to connection issues earlier

**Comment by vd1992** [comment]
For reference

image

**Pull request merged**
