### PR TITLE
Fix i18n for getting FR strings

### LINKED ISSUE #3397: List of locations on Profile is showing in English on the French page.
## Description
List of locations on Profile is showing in English on the French page. See screenshot.

## Screenshot: Prototype
image

### PR DESCRIPTION
**Pull request by mnigh**
Resolves #3397, #3398, #3401.

### Bonus
- Fixes a few similar i18n bugs in user profile
- Fixes [FR translation string](https://github.com/GCTC-NTGC/gc-digital-talent/pull/3406/commits/e6578887a9d48e0254b14b0fbfa927085730967b) from [previous change](https://github.com/GCTC-NTGC/gc-digital-talent/commit/7ec2aedd36967fdda53d4b0227c832eb4898a302#diff-9be88dc2973ab04fa23b50f6429fda5ef488c9ddd997982f35bdc12abda31e50R1613)
- [Adds missing defineMessages to languageProficiency to allow for i18n](https://github.com/GCTC-NTGC/gc-digital-talent/pull/3406/commits/e99f795a42f60ef4ec65a91ac4debe8109fe7320)

### CODE REVIEW

**Review by esizer — APPROVED** [review]
Very nice 🥇

**Review by vd1992 — CHANGES_REQUESTED** [review]
hang on

**Comment by vd1992** [comment]
good idea to tackle them in one go, it makes it much smoother 

think this one was missed

**Comment by vd1992** [comment]
shouldn't the equity stuff be localized at this point too?

image

**Comment by mnigh** [comment]
> shouldn't the equity stuff be localized at this point too?
> 
> image

@vd1992 Yes, but because it is not the same kind of fix and part of a larger issue with that content, there are issues to deal specifically with that. See:

- https://github.com/GCTC-NTGC/gc-digital-talent/issues/3410
- https://github.com/GCTC-NTGC/gc-digital-talent/issues/3408

**Comment by mnigh** [comment]
> think this one was missed

@vd1992 Hmm, I don't see what you are seeing. Is your screenshot from production or the locally on the `bug/fr-i18n` branch? This is what I see locally on `bug/fr-i18n`:
Screen Shot 2022-07-19 at 16 24 15

**Comment by mnigh** [comment]
@vd1992 was there a reason this wasn't wrapped in `defineMessages`? https://github.com/GCTC-NTGC/gc-digital-talent/blob/35a46b6bce7b810fba274b8e22fa2f799052d932/frontend/common/src/constants/localizedConstants.tsx#L21

**Comment by vd1992** [comment]
> @vd1992 was there a reason this wasn't wrapped in `defineMessages`?
> 
> https://github.com/GCTC-NTGC/gc-digital-talent/blob/35a46b6bce7b810fba274b8e22fa2f799052d932/frontend/common/src/constants/localizedConstants.tsx#L21

I have no idea lol

**Comment by mnigh** [comment]
@vd1992 please see latest changes related to your previous comments:

- [Add defineMessages to languageProficiency](https://github.com/GCTC-NTGC/gc-digital-talent/pull/3406/commits/e99f795a42f60ef4ec65a91ac4debe8109fe7320)
- [Fix i18n for getting FR string](https://github.com/GCTC-NTGC/gc-digital-talent/pull/3406/commits/9d5acce735f084d1fdf487bc458b8e02870b2d88)

**Comment by vd1992** [comment]
the word "Beginner" appears to still be broken
image

it seems to be broken on the Language Information form too, hm, I wonder what is going on there whether there is a broken translation somewhere
image

**Comment by vd1992** [comment]
putting scrutiny to max here, another little thing I noticed 😈 

image

**Comment by esizer** [comment]
> the word "Beginner" appears to still be broken

Are we sure we have a translation for this? I checked the `lang/fr.json` and there is no matching ID.

**Comment by vd1992** [comment]
> > the word "Beginner" appears to still be broken
> 
> Are we sure we have a translation for this? I checked the `lang/fr.json` and there is no matching ID.

ah, that would explain things!

**Comment by mnigh** [comment]
> putting scrutiny to max here, another little thing I noticed 😈
> 
> image

This is also a missing translation, but another issue here that is sort of related: https://github.com/GCTC-NTGC/gc-digital-talent/issues/3438

**Comment by mnigh** [comment]
@vd1992 any more concerns before your approval?

**Review by vd1992 — APPROVED** [review]
I think I've done enough nitpicking for now

**Pull request merged**
