### PR TITLE
a11y - 3836 - Remove nested labels, checkbox

### LINKED ISSUE #3836: Form field must not have multiple label elements
## Summary

Multiple label elements is not widely supported in assistive technologies. Ensure the first label contains all necessary information.

## Locations

https://github.com/GCTC-NTGC/gc-digital-talent/blob/c8ff1a196d4275a58269f4273774e165366ee676/frontend/common/src/components/form/Checkbox/Checkbox.tsx#L69-L101

### PR DESCRIPTION
**Pull request by esizer**
Resolves #3836 

## Summary

This removes the wrapping `<label>` element which was providing a second label to the checkbox when `boundingBox={true}` .

## Testing

1. Build talentsearch `npm run production --workspace=talentsearch`
2. Navigate to the following experience forms and confirm is only one label for the bonding box checkboxes
    - Community
    - Education
    - Personal
    - Work

### CODE REVIEW

**Review by vd1992 — CHANGES_REQUESTED** [review]
a bit of an issue, it makes the text no longer interactive, you cannot click on the text to toggle the box

**Comment by esizer** [comment]
> a bit of an issue, it makes the text no longer interactive, you cannot click on the text to toggle the box

Right, that is why we had it wrapping the input. This may require a bit more reworking 🤔

**Comment by vd1992** [comment]
that's a lot of Chromatic buzz
from what I can tell, it appears to be a shift in the location of the "required" or "optional" label, but that was shifted inconsistently 

image

**Comment by esizer** [comment]
> that's a lot of Chromatic buzz
> from what I can tell, it appears to be a shift in the location of the "required" or "optional" label, but that was shifted inconsistently

Ahh, yeah. Good catch! Had the logic backwards 😓  Updated in [fix appendLabel logic](https://github.com/GCTC-NTGC/gc-digital-talent/pull/4265/commits/b91a8e57d2b1ab3e76be13f42a38939ac69b8cf6)

**Review by vd1992 — APPROVED** [review]
- checks green
- Chromatic Diff shows mostly noise rather than changes of concern
- manual testing the checkbox works 

whew, that one ended being trickier than expected. amazing job!

**Pull request merged**
