### PR TITLE
[Feature] Expand/Collapse all experience details

### LINKED ISSUE #9959: ✨ Add "Expand All" button to user and snapshot Career Timeline
## ✨ Feature

Add an Expand All button which opens all Experience Details accordions on a user's Career Timeline. This should appear when an admin is viewing a User Profile, or an Applicant Snapshot.

## 🕵️ Details

When admins are using the general search to find a user/candidate, the results don't show _where_ the word was found in the user profile. The workaround for now is to navigate to the user profile and use the browser Find function. However, if the text is in experience details (as it usually is) they have to open every accordion individually before using Find. An "Expand All" button would make this much easier.

## 📸 Screenshot

Image

## 🙋‍♀️ Proposed Implementation

(optional) Do you have a proposed implementation?

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] Expand All button opens all Experience Details accordions on Career Timeline on admin User Profile

### PR DESCRIPTION
**Pull request by esizer**
🤖 Resolves #9959 

## 👋 Introduction

Adds the ability for admins to expand or collapse all of the experience details on a candidates career timeline.

## 🕵️ Details

Since collapsible items are not aware of each other, we needed to add a new hook that is aware of the available items and add the ability to control the cards from a higher level component.

## 🧪 Testing

1. Build `pnpm dev`
2. Login as admin `admin@test.com`
3. Add more than one experience to your career timeline
4. Apply for a process
5. Navigate to the admin view of that application
6. Scroll down to the career timeline
7. Confirm the expand / collapse all button works as expected

## 📸 Screenshot

screenshot_12-Apr-2024_10-50-1712933425
screenshot_12-Apr-2024_10-50-1712933431

### CODE REVIEW

**Review by vd1992 — CHANGES_REQUESTED** [review]
Works great on the view application page, but I think you missed a spot. Should be on the user profile page too. So at
`/en/admin/users/:id/profile#career-timeline-section`

Per

image

**Comment by esizer** [comment]
> Works great on the view application page, but I think you missed a spot. Should be on the user profile page too. So at
> `/en/admin/users/:id/profile#career-timeline-section`

Hmm, idk if that is possible becuase we have tabs and they are split into three different sections that so keeping track of all of them may be tricky :confounded: 

I'll take a look though.

**Comment by vd1992** [comment]
> > Works great on the view application page, but I think you missed a spot. Should be on the user profile page too. So at
> > `/en/admin/users/:id/profile#career-timeline-section`
> 
> Hmm, idk if that is possible becuase we have tabs and they are split into three different sections that so keeping track of all of them may be tricky 😖
> 
> I'll take a look though.

Could you just reset the toggle state upon switching tabs to make it simpler?
Also, I think you can not worry about tab three _By Skills_ as it is pretty unique

**Comment by esizer** [comment]
> Could you just reset the toggle state upon switching tabs to make it simpler?
> Also, I think you can not worry about tab three _By Skills_ as it is pretty unique

The problem I am having is that they are split up even further. Might get it working but I may just need to refactor things a bit to not need to drill down so far.

**Comment by esizer** [comment]
> Works great on the view application page, but I think you missed a spot. Should be on the user profile page too. So at
> `/en/admin/users/:id/profile#career-timeline-section`

@vd1992 Okay, I think I got it working. Maybe not exactly as intended but what do you think?

 - [add expand/collapse all to user profile](https://github.com/GCTC-NTGC/gc-digital-talent/pull/10050/commits/9d2474fdd1cc950821c22e6217f1ef623f45b65f)

screenshot_12-Apr-2024_14-31-1712946718
screenshot_12-Apr-2024_14-32-1712946722

**Comment by vd1992** [comment]
A bit of a nitpick here, should there be less spacing here? It looked kind of funny to me given the minimal spacing elsewhere

image

**Comment by esizer** [comment]
> A bit of a nitpick here, should there be less spacing here? It looked kind of funny to me given the minimal spacing elsewhere

Yeah, good call :+1: I removed as much as I could. The remaining is coming from the heading. Let me know if you think it should be reduced more and I can see what I can do.

[reduce spacing on expand button](https://github.com/GCTC-NTGC/gc-digital-talent/pull/10050/commits/8ab88fea6a9179d829ea669d4c2605a4a65adba5)

**Review by vd1992 — APPROVED** [review]
Looks great to me, nice work getting both places
🏆

**Pull request merged**
