### PR TITLE
[Dependencies] Switch to jwt-library

### LINKED ISSUE #9494: ♻️ Package `web-token/jwt-core` is abandoned
## ♻️ Refactor

> Package web-token/jwt-core is abandoned, you should avoid using it. Use web-token/jwt-library instead.

## 📸 Screenshot

Screen Shot 2024-02-23 at 10 02 28

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the debt was addressed and expected functionality has not been affected.

- [ ] `web-token/jwt-core` no longer referenced in codebase

### PR DESCRIPTION
**Pull request by vd1992**
🤖 Resolves #9494 

## 👋 Introduction

Switch to the recommended package as the other is abandoned. 
Appears to work identically so nothing really changed 🤷 

## 🧪 Testing

1. Can refresh API locally, no warnings appear
2. Tests pass in CI
3. You can log in and out normally

### CODE REVIEW

**Review by esizer — COMMENTED** [review]
Works for me, I just don't understand the library enough to approve 😅 Is there any documentation? I can only find undocumented read only repos :/

**Comment by petertgiles** [comment]
> Is there any documentation?

I think the homepage is https://web-token.spomky-labs.com/ and the GH page is https://github.com/web-token/jwt-framework .  I guess the owner is just refactoring his repo?

**Review by petertgiles — APPROVED** [review]
I set it up with SIC-Test and was able to log in and out.  Nice.  :+1:

**Comment by esizer** [comment]
> I think the homepage is https://web-token.spomky-labs.com/ and the GH page is https://github.com/web-token/jwt-framework . I guess the owner is just refactoring his repo?

Thanks! I wish it didn't still tell you to [install this "abandoned" package](https://web-token.spomky-labs.com/the-components/key-jwk-and-key-set-jwkset) 😓 😛

**Comment by petertgiles** [comment]
> Thanks! I wish it didn't still tell you to [install this "abandoned" package](https://web-token.spomky-labs.com/the-components/key-jwk-and-key-set-jwkset) 😓 😛

Yeah, 100%.  I guess the documentation fell behind.

**Pull request merged**
