### PR TITLE
[Feature] Anonymous application print

### LINKED ISSUE #9201: Add all print options to "Print" button on candidate application page
## Description

Pool operators working on applications would like to be able to access all possible printing options available. They currently only have access to "Print application" but would like to have access to "Print full profile" and "Print profile without contact information" from the same action menu.

## Caveats

Depending on when this gets tackled (before or after RoD flag) there could be two ways to approach this since the application page would look different.

### Fix pre RoD flag

<details><summary>Show steps</summary>
<p>

### To-do

Add the options from the User profile print button to the application print button so we have a total of 3 available print options:

- Print application
- Print full profile
- Print profile without contact information.

<details><summary>📸 Application Print button</summary>
<p>

image

</p>
</details> 

<details><summary>📸 User profile Print options</summary>
<p>

image

</p>
</details> 

</p>
</details> 

### Fix post RoD flag

<details><summary>Show steps</summary>
<p>

### To-do

Add a new in-line action menu in the "More actions" sidebar to include all three print options

<details><summary>📸 Application page with new print options</summary>
<p>

image

</p>
</details> 

</p>
</details> 

## Design

[Figma link](https://www.figma.com/file/em5ArPr044YaIe1Vb1zCZz/Admin---Processes%2FPools%2FRecruitments---Record-of-Decision?type=design&node-id=8165%3A22212&mode=design&t=gnehnBHXJcHwPWEI-1) by @Jerryescandon 

## ☑️ Acceptance Criteria

- [ ] Functional Print user profile button added to pre-RoD candidate page
- [ ] Functional print buttons added to post-RoD candidate page
- [ ] Double check that this works without error for any Role who can see the Application

### PR DESCRIPTION
**Pull request by esizer**
🤖 Resolves #9201 

## 👋 Introduction

Adds a dropdown allowing users to choose either a full or anonymous application print document.

## 🕵️ Details

During developing this, I noticed that the "Print profile" button (where I got the code for this) does not properly print an redacted profile when on the "User profile" page. So, this had to use a different approach of two documents and two handlers. 

I created a ticket (https://github.com/GCTC-NTGC/gc-digital-talent/issues/9209) to look into this in hopes that someone has a better solution. Or at least fix the existing user profile print.

## 🧪 Testing

Assist reviewers with steps they can take to test that the PR does what it says it does.

1. Build `npm run dev`
2. Login as admin
3. Navigate to `/admin/pool-candidates`
4. View an application for a user
5. Active the "Print application" dropdown
6. Select "Print without contact information"
7. Confirm  the user's last name is only the first letter and no contact information section exists
8. Repeat steps 5-6 but selecting "Print with all information"
9. Confirm the full users name is displayed along with a contact information section
10. Update `apps/web/.env` file setting `FEATURE_RECORD_OF_DECISION=false`
11. Repeat steps 1-9

### ROD Enabled

Screenshot 2024-02-05 143855

### ROD Disabled

Screenshot 2024-02-05 145029

### CODE REVIEW

**Review by tristan-orourke — CHANGES_REQUESTED** [review]
This looks good but it doesn't include the third option, to print the _user_ profile

**Comment by esizer** [comment]
> This looks good but it doesn't include the third option, to print the _user_ profile

Hmm, would this mean we actually need 4 options?

- Full application
- Application without contact information
- User profile
- User profile without contact information

**Review by tristan-orourke — CHANGES_REQUESTED** [review]
Nice! 👍

**Comment by esizer** [comment]
> Nice! 👍

Wrong radio button selected perhaps? 😅

**Review by tristan-orourke — APPROVED** [review]
😅

**Pull request merged**
