### PR TITLE
navigate redirect to /profile

### LINKED ISSUE #3488: User should not be navigated to admin page by default after login
## Steps to Reproduce

- goto talent.canada.ca
- Login with gckey & 2fa

## Expected Result 

- User should be taken to profile homepage 

## Actual Result 

- User is taken to admin page by default and shown an error page

### PR DESCRIPTION
**Pull request by vd1992**
resolves #3488 
upon login from `/` path, direct to `/talent/profile` rather than `/admin`

to test
1) copy from .env.example over to your .env
2) navigate to http://localhost:8000/login
3) login and you should be directed to /talent/profile

### DEPLOYMENT
This change will require additional care
On the servers, the environment variable `OAUTH_POST_LOGIN_REDIRECT` will have to be changed from "http://{hostname}/admin" to "http://{hostname}/talent/profile" to resolve this fully. 

Thank you, Peter

### CODE REVIEW

**Comment by petertgiles** [comment]
Could you add deployment instructions?

**Comment by vd1992** [comment]
> Could you add deployment instructions?

I don't know what or how 😅

**Comment by petertgiles** [comment]
> I don't know what or how

The person doing the deployment has to be the expert.  :smile:   Just something simple and clear will do.  How about 
```
"On the servers, the environment variable OAUTH_POST_LOGIN_REDIRECT will have to be changed from "http://{hostname}/admin" to "http://{hostname}/talent/profile"
```

**Comment by vd1992** [comment]
> > I don't know what or how
> 
> The person doing the deployment has to be the expert. 😄 Just something simple and clear will do. How about
> 
> ```
> "On the servers, the environment variable OAUTH_POST_LOGIN_REDIRECT will have to be changed from "http://{hostname}/admin" to "http://{hostname}/talent/profile"
> ```

aye aye

**Review by petertgiles — APPROVED** [review]
:+1:

**Pull request merged**
