### PR TITLE
[Bug] Fix edit pool skill submit button state

### LINKED ISSUE #6369: 🐛 Save Skills button on Edit Pool page not indicated "freshness" correctly
## 🐛 Bug

Sometimes the Save Skills button changes from "Submitted" to "Save asset skills" when the skill selection hasn't changed. Conversely, when the skill selection _has_ changed, it may not indicate that you need to save. 

## 🦋 Expected Behaviour

If any skills have been added to or removed from selection, the button should switch to "Save asset/required skills" to indicate the need to save.
If current skill selections match what is saved, the button should say "Submitted".

## 🕵️ Details

Initially reported by Dasha, who is creating and editing pools in UAT and Production. Reported as: "Sometimes the Save Skills button on Edit Pool page changes from "Submitted" to "Save" when it should still be saved", Dasha was using Edge on Windows.

In my own testing, I found these oddities in behaviour:
- when you add or remove skills, the button does not change
- when you have text in the search bar, the button changes to indicate you should save
- when you remove the text from the search bar, whether or not you added a skill, the button goes back to "Submitted"

## 📋 Steps to Reproduce

1. Go to an Edit Pool page
2. All save buttons start out as dirty (ie indicating the need to save) so click Save Skills. It should switch to saying Submitted
3. Add a skill. Button does not change. Click to save.
4. Remove a skill. Button does not change. Click to save.
5. Enter text in the search skills bar. Now button changes to "Save ___ skills".
6. Add a skill and clear search bar. Submit button changes back to "Submitted".

## 📸 Screenshot

Add a screenshot (if possible).

## 🙋‍♀️ Proposed Solution

(optional) Do you have a proposed solution?

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] On Edit Pool page, when a skill is added or removed, button changes to indicate need to save
- [ ] On Edit Pool page, entering text in the Search Skills bar does not affect the save button

### PR DESCRIPTION
**Pull request by esizer**
🤖 Resolves #6369 

## 👋 Introduction

This moves the `<Submit />` button outside of the `<SkillPicker />` to stabilize it's submitting/submitted/idle state.

## 🕵️ Details

The `<Submit />` button was part of the `<SkillPicker />` form and was not aware of the changing skills. This caused two issues:

1. Changes to the dropdown/search bar were erroneously setting the form state to dirty
2. Skill picker is re-rendered on change so it was reset to clean after every re-render

Moving this out allows us to cleanly track dirty skills and should stabilize the button state.

## 🧪 Testing

Assist reviewers with steps they can take to test that the PR does what it says it does.

1. Build the app `npm run build:fresh`
4. Login as `admin@test.com`
5. Create a pool
6. Add a skill and click the submit button
7. Confirm it changes from default message to "Submitting" then, finally "Submitted"
8. Confirm interacting with the search in the skill picker does not change the state of the submit button
9. Add a skill
10. Confirm the state of the submit button changes back to the default
11. Save the form
12. Confirm it changes from default message to "Submitting" then, finally "Submitted"
13. Remove the added skill
14. Confirm the state of the submit button changes back to the default

### CODE REVIEW

**Comment by vd1992** [comment]
Improved, but still a bit quirky I am finding. Sometimes the "Submitted" text won't appear, other times if you have a bunch of skills already and then remove them, it switches to "Submitted". 

http://recordit.co/8VQ9wVh2W4

**Comment by vd1992** [comment]
Okay, I see part of the reason for the above was that order matters. If you rearrange the skills, then even if it is the same three it comes up as changed. Which isn't a big issue, you have to do it on purpose for it to happen. So that explains at least some of the above and isn't a big deal. 

https://recordit.co/0HkJKHzUYU

**Comment by esizer** [comment]
> Okay, I see part of the reason for the above was that order matters. If you rearrange the skills, then even if it is the same three it comes up as changed. For it to happen, you have to do it on purpose.
> So that explains at least some of the above and isn't a big deal.

Yeah, this is how the other forms work as well. If you submit a form, say "Impact", the button changes to "submitted" if you change the input, it will return to the default and if you return it back to its original state it says "submitted" again.

**Comment by esizer** [comment]
> Improved, but still a bit quirky I am finding. Sometimes the "Submitted" text won't appear, other times if you have a bunch of skills already and then remove them, it switches to "Submitted".

Looks like the submit handler was not resetting the form (other forms on this page have code to work around this). I have went ahead and did the manual reset other forms are doing and it seems to be far more consistent now. 👍 

[reset skill forms after submitting](https://github.com/GCTC-NTGC/gc-digital-talent/pull/6442/commits/2f81b5a30a8108d598895cef57a1e4cbcb188f54)

**Pull request merged**
