### PR TITLE
Debt - 2404 - Upgrade to React 18

### LINKED ISSUE #2404: Upgrade to React v18.0
Upgrade guide: https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html

### PR DESCRIPTION
**Pull request by esizer**
🤖 Resolves #2404 

## 👋 Introduction

This bumps our react dependencies to v18.

## 🕵️ Details

In addtion to bumping `react` and `react-dom` there were some additional changes made that were required:

- Removed `@types/react-select` since it is written fully in typescript and was blocking react 18
- Bumped `@testing-library/*` deps since v12 dropped support for react 17
- Removed `@testting-library/react-hooks` since it has been deprecated and merged into `@testing-library/react`
- Adjusted some components to adhere to stricter typing system
- Fixed some breaking tests after the upgrade
- Adjust the root `react-dom` render pattern

## 🧪 Testing

Assist reviewers with steps they can take to test that the PR does what it says it does.

1. Install dependencies `npm i` and build all projects `npm run production --workspaces`
2. Navigate through the app confirming no errors
3. Confirm all tests (unit, e2e, etc.) pass without issue

### CODE REVIEW

**Review by petertgiles — CHANGES_REQUESTED** [review]
Wow, thanks for taking care of this for me!  :pray: 
It looks great - there's so much tidying up rolled into this too!  I'm having the `admin/pool-candidate.cy.js ` test fail for me locally though, same as the CI.  Also, I noticed a bunch of "not wrapped in act" warnings in the Jest tests, too.
image
All that aside, the app itself seems to work just fine.  I did get a really big diff on the package lock file.  Do you have some changes there to commit or is it just that your system generated a different lock than mine due to npm versions or something?  It's looking so great!

**Comment by esizer** [comment]
> It looks great - there's so much tidying up rolled into this too! I'm having the `admin/pool-candidate.cy.js ` test fail for me locally though, same as the CI.

This has been happening more frequently until last week where it is now consistently failing. Have yet to understand why.

> Also, I noticed a bunch of "not wrapped in act" warnings in the Jest tests, too.

I'm not certain about this either. I actually had to remove some acts to fix tests 🤔 

> I did get a really big diff on the package lock file. Do you have some changes there to commit or is it just that your system generated a different lock than mine due to npm versions or something? It's looking so great!

Hmm, I definitely had to commit the lock file because of all the dependency updates. I'll take a look and see if I can reproduce this.

**Comment by petertgiles** [comment]
> > Also, I noticed a bunch of "not wrapped in act" warnings in the Jest tests, too.
> 
> I'm not certain about this either. I actually had to remove some acts to fix tests thinking
> 
I just pushed up a commit that should take care of it.  I'll watch the CI results.
> > I did get a really big diff on the package lock file. Do you have some changes there to commit or is it just that your system generated a different lock than mine due to npm versions or something? It's looking so great!
> 
> Hmm, I definitely had to commit the lock file because of all the dependency updates. I'll take a look and see if I can reproduce this.

This looks way better.  I'm still getting the `name` property showing up as a diff though.
image

**Comment by esizer** [comment]
> This looks way better. I'm still getting the `name` property showing up as a diff though.

Okay, am I right to assume your folder name is `html`? It seems when a package name is not specified it uses the root folder name. I went ahead and added a root package name and regenerated the lock file so that **_should_** no longer happen.

[add root package name](https://github.com/GCTC-NTGC/gc-digital-talent/pull/5243/commits/9c50348a124f111eae93403f3bdb16e2e028a1e1)

**Comment by petertgiles** [comment]
> > This looks way better. I'm still getting the `name` property showing up as a diff though.
> 
> Okay, am I right to assume your folder name is `html`? It seems when a package name is not specified it uses the root folder name. I went ahead and added a root package name and regenerated the lock file so that **_should_** no longer happen.
> 
> [add root package name](https://github.com/GCTC-NTGC/gc-digital-talent/pull/5243/commits/9c50348a124f111eae93403f3bdb16e2e028a1e1)

That worked!  I think it's that I'm using workspaces so there's no `.git` directory.  `html` is probably a generic fallback.
image

**Comment by petertgiles** [comment]
I'll approve this though you may want to wait for another approval before merging since I contributed a bit of code.  Or maybe not.  It wasn't much.  :shrug: :laughing:

**Review by petertgiles — APPROVED** [review]

**Pull request merged**
