### PR TITLE
Debt - 2697 Move Context Providers to Common

### LINKED ISSUE #2697: Move AuthContainer, ClientProvider, etc, into /common folder
The components that enable logging in and authorization (checking for a specific user or role) are currently in the admin project. Move them to common so that they can be used in talentsearch and indigenousapprenticeship. This will require that some constants, eg the route to redirect to after logging out, be refactored into parameters that can be passed into the components by a parent.

### PR DESCRIPTION
**Pull request by esizer**
Resolves #2697 

## Summary

This PR moves the context providers in the admin project to the common project to be reused by other parts of the application. 

### Items Moved / Renamed

- `admin/AuthContainer` -> `common/components/Auth/AuthenticationContainer`
- `admin/AuthorizationContainer` -> `common/components/Auth/AuthorizationContainer`
- `admin/ClientProvider` -> `common/components/ClientProvider`
- `getMessages` -> `common/hooks/useIntlMessages`

### Items Modified

- `admin` tests `npm` script updated to pass with no tests since the only test was moved to `common`
- `LanaguageRedirectContainer`
  - `getMessages` -> `messages` - We were using this function in each project to merge project specific French strings with common French. Updated to pass specific project strings and handle merging the the `common` project.

### Items Created

Since we need to provide some application specific context to the providers, we have created wrappers that simply pass the context as props to the containers. You can find these in `admin/components/context`

#### AuthenticationProvider

- `homePath` - `string` - Path to redirect to on successful logout
- `tokenRefreshPath` - `string` - Path where the token can be refreshed
- `logoutUri` - `string` - Path to send logout requests to
- `logoutRedirectUri` - `string` - Path to redirect to after logout.

#### AuthorizationProvider

- `userRoles` - `Role[] | undefined` - The current users roles

#### useIntlMessages

This is a simple hook created to replace the project specific merging of French messages. Used in `LanguageRedirectContainer.tsx:42`

```tsx
const compiledMessages = useIntlLanguages(pathLocale, messages);
```

#### IntlContainer

Each project had this component that was no in use except some old tests. It also included a function for merging French messages. 

- Tests updated to use the extended `render` method in `testUtils`
- `getMessages` moved to the `useIntlMessages` hook in common

### CODE REVIEW

**Comment by vd1992** [comment]
when switching to en francais
console.log filled with errors

image

**Comment by esizer** [comment]
> when attempting to log-in, it succeeds but this appears in the console
> does it appear for anyone else? maybe something somewhere is referencing the removed file?

Hmm, I'm unable to reproduce this one. Would love if someone else could test.

**Comment by esizer** [comment]
> I think this one is just missing translations and nothing relevant to the scope of this issue

Confirmed, this also occurs on main branch and is related to missing translations.

**Comment by vd1992** [comment]
> > when attempting to log-in, it succeeds but this appears in the console
> > does it appear for anyone else? maybe something somewhere is referencing the removed file?
> 
> Hmm, I'm unable to reproduce this one. Would love if someone else could test. Pushed up [check is client error has response before accessing](https://github.com/GCTC-NTGC/gc-digital-talent/pull/2761/commits/0497426ac33ba1a72e657bd66e61d8992e9675e1) to see if that would resolve your issue.

hm... it seems to have done the job, no errors now

**Review by vd1992 — APPROVED** [review]
- nothing alarming in checks (no UI updates in Chromatic)
- interacted with the app in various areas, no issues in functionality noticed

I think things are good Eric! Not sure if you want someone else to probe around for any fall-through-cracks issues or not

**Comment by esizer** [comment]
> * nothing alarming in checks (no UI updates in Chromatic)
> * interacted with the app in various areas, no issues in functionality noticed
> 
> I think things are good Eric! Not sure if you want someone else to probe around for any fall-through-cracks issues or not

Perfect! I don't think this is urgent so I'll leave it incase anyone else wants to take a look and maybe merge in the next day or so.

**Comment by petertgiles** [comment]
Dang, this is hugely impressive.  I built it and it works great!  I didn't get the error Vachan logged.  I'd like to spend some more time tomorrow figuring out how you did it. :smile:

**Comment by esizer** [comment]
> Dang, this is hugely impressive. I built it and it works great! I didn't get the error Vachan logged. I'd like to spend some more time tomorrow figuring out how you did it. 😄

Thanks! Since this isn't really a rush I'll leave it up for you to take a look and merge later today.

**Review by petertgiles — APPROVED** [review]
Oh wow, there's some pretty serious tidying and refactoring going on here as well.  :exploding_head:

**Pull request merged**
