### PR TITLE
[Feature] Add notifications to admin dashboard

### LINKED ISSUE #11019: ✨ Add notification bell to Admin UI
## ✨ Feature

Now that the file download feature will make use of notifications, Admins should really be able to see when they have new notifications from their own UI.

## 🕵️ Details

Add the notification icon to the admin sidebar nav, just under the Dashboard link. When the menu is expanded, it should have the text "Notifications". 

In desktop view, clicking the Notifications link should open the notifications dialog from the left, to the right of the nav drawer. 

**NOTE:** The admin nav drawer will very soon be replaced by a unified nav menu. Therefore, I don't want to spend much time on any unique behaviour for the notifications dialog. If it's non-trivial to have it open on the left, it's okay if it opens on the right like on the applicant UI.

## 🎨 Design File

https://www.figma.com/design/fgzxRKjFr4ZUMn5ail1Yc2/Admin---Notification-interface?node-id=111-7725&t=HbsqMGrlmpy9czqm-0

### 🧑‍🎨 Designer

@Jerryescandon 

## 📸 Screenshot

image

## 🙋‍♀️ Proposed Implementation

Something to be careful about - the icon as is won't be visible in light mode in the menu.

## 🌎 Localization

(optional) Provide any new copy along with translations available.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] Notifications appear in the admin side nav, under Dashboard
- [ ] The bell icon is visible in light or dark mode
- [ ] clicking it opens notification pane from the left, to the right of the nav drawer (NOTE: skip this if it takes much effort)
- [ ] When expanded the nav menu says "Notifications" next to the icon

### PR DESCRIPTION
**Pull request by yonikid15**
🤖 Resolves #11019 

## 👋 Introduction

- Adds the notification dialog to the admin dashboard
- The notification panel should work the same way as the main site
- Note: I didn't have time to move the panel next to the side menu. However, it was okay to leave it like this for now.

## 🧪 Testing

Assist reviewers with steps they can take to test that the PR does what it says it does.

1. Build the app `pnpm run dev`
2. Login as `admin@test.com`
3. Go to admin dashboard and ensure the side menu contains the notifications trigger.
4. Ensure the notifications panel works correctly and icon changes when there are unread notifications

## 📸 Screenshot

image
image
image

### CODE REVIEW

**Comment by brindasasi** [comment]
@yonikid15 could you update your branch? ..I get unknown error after deploying this branch into dev env.

**Comment by brindasasi** [comment]
Screenshot 2024-07-26 161946
Screenshot 2024-07-26 161926

**Review by brindasasi — APPROVED** [review]
This is working great in Dev!🙌

- Verified Admin side notification icon shows up and red dot comes up when new notification comes as well as on the applicant side.
- Once read the new notification the red dot goes away in both admin & applicant view 
- notification bar shows up on the right side as per the PR description. Are we getting new issue to fix that? Other than that this should go !🥳👏

**Comment by yonikid15** [comment]
@brindasasi I can make an issue for the Notification pane opening next to the menu :+1:

**Pull request merged**
