### PR TITLE
Move localized messages inline

### LINKED ISSUE #1046: Change instances of react-intl messages to inline
Use [imperative API intl.formatMessage](https://formatjs.io/docs/getting-started/message-declaration/#using-imperative-api-intlformatmessage) inline.

### PR DESCRIPTION
**Pull request by petertgiles**
This branch moves the definition of localized messages in a component from an object near the top of the file to inline locations.  ~Shared localized strings that have been factored out to their own files have not been modified.~  Shared message objects have been broken down to inline strings, too, except the ones in the common project.

Closes #1046

### CODE REVIEW

**Comment by petertgiles** [comment]
Rebased to solve conflict with #1198

**Review by yonikid15 — COMMENTED** [review]
Nice work Peter. I think we decided not to use the FormattedMessage component, and use the [intl](https://formatjs.io/docs/react-intl/api#the-intl-object) object for better performance. Sorry to do this to you, but can you change it to use that instead.

Replace: 
```react

**Review by yonikid15 — COMMENTED** [review]
Looking good so far Peter. There's still a few more files to hit though. We need to move the formatted messages in each `messages.ts` file into there respective files.

**Comment by petertgiles** [comment]
rebased to solve merge conflict from PR #1259

**Review by yonikid15 — CHANGES_REQUESTED** [review]
So.. the errorMessages and commonMessages should stay in the common folder and be pulled in since they are getting used throughout the admin site. Can you put those back. I'm sorry that's not your fault, the instructions should of been more clear 🤦‍♂️.

**Comment by petertgiles** [comment]
commonMessages and errorMessages from the common subproject have been factored back out

**Review by yonikid15 — APPROVED** [review]
This was a big one. Looks good, nice work 👍

**Pull request merged**
