### PR TITLE
Hotfixes to 1.1.4

### PR DESCRIPTION
**Pull request by petertgiles**
This branch is a hotfix for the issue found in production where status overrides were forcing all pool candidates to the "DRAFT" status.

### CODE REVIEW

**Comment by brindasasi** [comment]
I believe the test assertions needs to be changed as well.

**Comment by petertgiles** [comment]
#3946 added to cherry pick these commits to a mergable branch
#3947 added to readd the status overrides
#3949 added to try to migrate the pool_candidates columns again

**Comment by brindasasi** [comment]
trying my luck with UAT atm

**Comment by brindasasi** [comment]
This looks good to me on UAT. 
I was able to view pool dashboard, create new pool , associate existing user with the pool , change his status ..all looks good to me 👍

**Comment by petertgiles** [comment]
Not merging, this branch is just to host v1.1.5.  This version has been deployed to production.

**Pull request closed without merging**
