### PR TITLE
More Prettier Linting

### PR DESCRIPTION
**Pull request by petertgiles**
I found a few more files to pretty lint

Related to #2496

### CODE REVIEW

**Comment by vd1992** [comment]
I don't think some of those should even have linting problems, they were reviewed and merged recently, I think something is up with our Prettiers.

**Comment by vd1992** [comment]
for comparison purposes, I could execute Prettier on a directory and commit it
gives a point of reference

**Comment by vd1992** [comment]
prettier vscode

image

**Comment by petertgiles** [comment]
I'll sit down with Vachan some time and try to figure this out.  For now I'll get rid of this PR.

**Pull request closed without merging**
