### PR TITLE
Edit pool - readonly

### LINKED ISSUE #3162: Edit Pool page - Readonly
<sup>ℹ️ [Figma (root)][figma] | [Sitemap][sitemap]</sup>
<sup>_This initial comment is collaborative and open to modification by all._</sup>

## Description

*This first issue is to create a readonly version of the page - data is populated from the database but all the action buttons do nothing.  Mutations implemented in #3169*

This page contains an editable form for the information in the pool model.
This page also contains buttons that open modals to change the "Status" of this pool. Which in turn changes the behavior of the Pool Advertisement page.

If the pool status is in DRAFT, you can SAVE, PUBLISH, or DELETE.
If the pool status is PUBLISHED (Active before "Closing Date") you can CLOSE or EXTEND THE DATE.
If the pool status is PUBLISHED (Expired after "Closing Date") you can EXTEND THE DATE or ARCHIVE.

NOTE 01: GENERIC CLASSIFICATION: Leave out this dropdown selector from this issue, it will be addressed at a later point.

NOTE 02: DATE PICKER (yyyy/mm/dd): Date will always be set in Pacific Time at 11:59:59 p.m. (probably handled in the backend mutation) 

NOTE 03: We are not gonna implement "ARCHIVE" yet, just leave the button in but it won't do anything yet.

NOTE 04: CLASSIFICATION PICKER (e.g. IT-01): Front-end will be a 1 selection only (dropdown), but back end will allow multiple selections (just in case we need to allow this down the line). 

## Screenshot: Prototype
image

## Acceptance Criteria
- [ ] URL "https://talent.canada.ca/en/admin/pools/[ID]/Edit" (Discuss what happens to old one)
- [ ] Create whole form, query for data, no actions taken on button clicks
- [ ] Put behind feature flag "Direct Intake"
- [ ] All modals need to work 
- [ ] Page needs to behave in different way depending on status (Draft, Published (Active), Closed (Published and Expired)

[Link to Edit Pool Advertisement wireframe](https://www.figma.com/proto/b6lDM86QCJQ6iaAh7qrTYH/Admin-v4-(Direct-Intake)?page-id=0%3A1&node-id=1618%3A6064&viewport=-3442%2C1747%2C0.59&scaling=min-zoom&starting-point-node-id=1618%3A6064)

### PR DESCRIPTION
**Pull request by petertgiles**
This branch implements a read-only version of the new Pool Advertisements - Edit Pool page.

## Testing
- [ ] Old version of the page comes up at `/admin/pools/{id}/edit` with no DIRECTINTAKE flag
- [ ] New version of the page comes up at `/admin/pools/{id}/edit` with DIRECTINTAKE flag
- [ ] Storybook story
- [ ] Unit tests
- [ ] Button presses emit data to the console in the stubs at the top level component but do not fire requests to the API.  That will happen in #3169.
- [ ] Modals appear but also just emit events to the stubs

## Notes
It currently shows the expiry date in the browser local time zone.  Refined time zone handling will be covered in #3315

Closes #3162

### CODE REVIEW

**Comment by vd1992** [comment]
I can see you have still got some workflows to look over, but I took a quick look. Coming along quite fantastically! 
A massive PR, despite being already split. 

Some things I noticed so far: 

Essentials Skills picker a bit off, items splitting off into two spots as well as the "All" one not being clickable
https://recordit.co/sqHlNlDlnt

I cannot interact with Non-Essential skills (I click and the page just shoots up a bit)
https://recordit.co/8R0WmK9Pem 

Language appears to appear twice
image

**Review by vd1992 — CHANGES_REQUESTED** [review]
I guess I should aim to actually click "Review changes" sometimes 🤷

**Comment by vd1992** [comment]
are published/expired advertisements intended to be editable, I thought they weren't supposed to be or am I mixed up somewhere
they appear to be editable in Storybook

**Comment by vd1992** [comment]
switch flag, and some config refresh hack
this works as it should 👍 
don't think anything appears broken below

image

**Comment by petertgiles** [comment]
Thanks for the review, Vachan!  Yeah, there were some issues in the tests and linting that I fixed up in https://github.com/GCTC-NTGC/gc-digital-talent/pull/3383/commits/6fd1d6e5956f0a73eda3e338a7bee550c4becc0b to https://github.com/GCTC-NTGC/gc-digital-talent/pull/3383/commits/5d226293bae2a963d157bc3196ac2a2db810f1df .

Regarding "Essentials Skills picker a bit off", yeah, that's a tricky one.  I think I'm going to have to make a more heavy-handed refactoring of the RadioGroup component to make that work.

Regarding "I cannot interact with Non-Essential skills", good catch!  I bubbled up an `idPrefix` prop in https://github.com/GCTC-NTGC/gc-digital-talent/pull/3383/commits/449f371234fcb460b9dd00117cd1b4edbabfd81f to keep them from interacting with each other.

Regarding "Language appears to appear twice", also a good catch!  I fixed the form IDs in https://github.com/GCTC-NTGC/gc-digital-talent/pull/3383/commits/d6c54638de590934515d6df04e8708f43e492d81.

Regarding "are published/expired advertisements intended to be editable", you're right, they're not.  I'm not sure how to proceed on this one.  The obvious solution is to disable the form but we don't really have a way to do that.  I'm not even sure how a complex form like the skill picker should look if it were disabled.  I could just hide the submit button but that might be confusing since the user could still interact with the form elements.  I could just hide the entire sections but then the user couldn't see the current settings.  @Jerryescandon how should for forms look when the status is published or expired?

Regarding "would it be a good idea for this to warn or something if rather than a further date", good point.  I don't know if I want to lock it down to just making the date bigger but I suppose it should at least check that the date is in the future.  I added that in https://github.com/GCTC-NTGC/gc-digital-talent/pull/3383/commits/2b990f88d976eeea3fdf9df89213dda8e3dfe53f .

**Comment by Jerryescandon** [comment]
> Regarding "are published/expired advertisements intended to be editable", you're right, they're not.

soooo.... barring a conversation about whether you should be able to edit expired. Here's a prototype for the "publ;ished" one where you can't edit anything.

[wireframe](https://www.figma.com/proto/b6lDM86QCJQ6iaAh7qrTYH/Admin-v4-(Direct-Intake)?page-id=0%3A1&node-id=1945%3A3512&viewport=-1015%2C6139%2C0.6&scaling=min-zoom&starting-point-node-id=1618%3A6064)

**Comment by petertgiles** [comment]
OK, I fixed the tests to interact with the dialogs (https://github.com/GCTC-NTGC/gc-digital-talent/pull/3383/commits/272e8fde4001a025987c8b81b7ff51d6f2058b2a), added the logic to disable the forms when not in draft (https://github.com/GCTC-NTGC/gc-digital-talent/pull/3383/commits/e3378880c8a56f39c58978594e969976becb20f1), and fixed the radio groups (https://github.com/GCTC-NTGC/gc-digital-talent/pull/3383/commits/00a8beeadc46f252e34b72d7880644a446141980 https://github.com/GCTC-NTGC/gc-digital-talent/pull/3383/commits/be73d15a5c9de742753183390d654ebb4ca49144 https://github.com/GCTC-NTGC/gc-digital-talent/pull/3383/commits/85f30a725f788d44f4e0ffe1c17c8e9866d3e8a4).  I think it's ready for a re-review.

**Comment by petertgiles** [comment]
> When you select "remote" I think it should emit the locationEN and locationFR fields as NULL

Lol, nothing gets passed you.  https://github.com/GCTC-NTGC/gc-digital-talent/pull/3383/commits/ad26ab1328529481dda2d6fb934dfd965844c162  🦅

**Review by vd1992 — APPROVED** [review]
All right, I think that takes care of everything I noticed. 
Lot going on so I can't really scrutinize the code on a line-by-line basis (can't wrap my head around it all)

Big PR! Great work!

**Pull request merged**
