### PR TITLE
[Feature] Adds translation files for crg, crk, ojw languages

### LINKED ISSUE #4587: Add translation files for indigenous languages
Split off from #4573.

We now have translations into several indigenous languages for the content of the IAP home page. Convert the translation word files into json files which can be used by react-intl, and place them in `frontend/indigenousapprenticeship/src/js/lang`, making sure each string's id lines up with those in en.json and fr.json.

English text: 
[TR20760 - IAP Homepage Text English to Michif - Translation Request_EN.docx](https://github.com/GCTC-NTGC/gc-digital-talent/files/9932099/TR20760.-.IAP.Homepage.Text.English.to.Michif.-.Translation.Request_EN.docx)

Translations:
[014-221021-022_001_TG_TR20760 - IAP Homepage Text English to_Michif.docx](https://github.com/GCTC-NTGC/gc-digital-talent/files/9930331/014-221021-022_001_TG_TR20760.-.IAP.Homepage.Text.English.to_Michif.1.docx)
[014-221021-022_001_TG_TR20760 - IAP Homepage Text English to_Plains Cree.docx](https://github.com/GCTC-NTGC/gc-digital-talent/files/9930333/014-221021-022_001_TG_TR20760.-.IAP.Homepage.Text.English.to_Plains.Cree.docx)
[014-221021-022_001_TG_TR20760 - IAP Homepage Text English to_Western Ojibway.docx](https://github.com/GCTC-NTGC/gc-digital-talent/files/9930335/014-221021-022_001_TG_TR20760.-.IAP.Homepage.Text.English.to_Western.Ojibway.docx)
[014-221021-022_001_TG_TR20760 - IAP Homepage Text English to_Mikmaq.docx](https://github.com/GCTC-NTGC/gc-digital-talent/files/9930337/014-221021-022_001_TG_TR20760.-.IAP.Homepage.Text.English.to_Mikmaq.docx)

### PR DESCRIPTION
**Pull request by mnigh**
🤖 Resolves #4587.

## 👋 Introduction

This PR adds translation files for Michif (crg), Plains Cree (crk), and Western Ojibwe (ojw) languages for the IAP home page.

#### Michif

- [TR40318 - michif_EN.docx](https://github.com/GCTC-NTGC/gc-digital-talent/files/11834526/TR40318.-.michif_EN.docx)
- [TR40318 - 014-230613-011_001_TG_michif_MIC.docx](https://github.com/GCTC-NTGC/gc-digital-talent/files/11834528/TR40318.-.014-230613-011_001_TG_michif_MIC.docx)

#### Plains Cree

- [TR40317 - 014-230612-014_001_TG_plainscree_PC.docx](https://github.com/GCTC-NTGC/gc-digital-talent/files/11834533/TR40317.-.014-230612-014_001_TG_plainscree_PC.docx)
- [TR40317 - plainscree_EN.docx](https://github.com/GCTC-NTGC/gc-digital-talent/files/11834534/TR40317.-.plainscree_EN.docx)

#### Western Ojibwe

- [TR40319 - westernojibway_EN.docx](https://github.com/GCTC-NTGC/gc-digital-talent/files/11834531/TR40319.-.westernojibway_EN.docx)
- [TR40319 - 014-230613-012_001_TG_westernojibway_WO.docx](https://github.com/GCTC-NTGC/gc-digital-talent/files/11834532/TR40319.-.014-230613-012_001_TG_westernojibway_WO.docx)

## 📓 TODO

- [x]  Get [Michif](https://github.com/GCTC-NTGC/gc-digital-talent/files/11201622/michif.pdf) review for long strings with direction on where to add a `softHyphen`
- [x] Get [Plains Cree](https://github.com/GCTC-NTGC/gc-digital-talent/files/11201623/plainscree.pdf) review for long strings with direction on where to add a `softHyphen`
- [x] Get [Western Ojibwe](https://github.com/GCTC-NTGC/gc-digital-talent/files/11201624/westernojibway.pdf) review for long strings with direction on where to add a `softHyphen`

## 🧪 Testing

Assist reviewers with steps they can take to test that the PR does what it says it does.

1. `npm run intl-compile`
2. `npm run build:fresh`
3. Navigate to `/en/indigenous-it-apprentice/`
4. Use language selector to switch between languages
5. Ensure that each of the languages (English (en), French (fr), Michif (crg), Plains Cree (crk), Western Ojibwe (ojw), and Mi'kmaq (mic)) is translated
6. Ensure that each of the languages (English (en), French (fr), Michif (crg), Plains Cree (crk), Western Ojibwe (ojw), and Mi'kmaq (mic)) is legible and is not hidden on different screen sizes

### CODE REVIEW

**Comment by mnigh** [comment]
These strings were also included in the file but are part of the footer which is in common's language files: are we planning to use these strings as well?

- Nashkoumiwaywin
- Ay-itwayhk Tipeyimoowin pi Ay-itwewin
- Tosal lee Lway
- Canada.ca

**Comment by mnigh** [comment]
Related: https://github.com/GCTC-NTGC/gc-digital-talent/issues/4966

**Comment by mnigh** [comment]
Related #6371.

**Review by esizer — APPROVED** [review]
Obviously can't speak to the accuracy of the translations but this works amazing! 🎉 

Can't wait to see it in production!

**Comment by mnigh** [comment]
Approved by IAP team! 🥳

**Pull request merged**
