### PR TITLE
update isVeteran field

### LINKED ISSUE #3747: Update choices on "Member of the Canadian Armed Forces" question
## Description

We need to separate the responses available in the CAF question in the about me section of the profile

New options:

```
I am not a member of the CAF
I am an active member of the CAF
I am a veteran of the CAF
```

### OLD

image

### NEW 

image

## Acceptance Criteria
- [ ] Update the schema to include the new option 
- [ ] Migration for the field 
- [ ]  User should be able to update and edit the options

   [image]: https://user-images.githubusercontent.com/305339/166570935-6425a615-82c7-4b2f-9840-5c7d698fa2ab.png
   [image-link]: https://example.com
   [figma]: https://go.talent.c4nada.ca/figma
   [sitemap]: https://go.talent.c4nada.ca/sitemap

### PR DESCRIPTION
**Pull request by vd1992**
resolves #3747 
updates it from a bool to enum, and changes in a bunch of places to adjust to the new typing

test: make sure you can update in /about-me, and it is reflected correctly in /profile and the /admin side of things
as well, keep an eye on the database and play around with adminer and anything else you think might need checking

### CODE REVIEW

**Review by esizer — CHANGES_REQUESTED** [review]
Looking great!

I noticed we need to update some queries, one I was able to find was the [userOperations](https://github.com/GCTC-NTGC/gc-digital-talent/blob/main/frontend/admin/src/js/components/user/userOperations.graphql) For the admin users table.

**Comment by vd1992** [comment]
> Looking great!
> 
> I noticed we need to update some queries, one I was able to find was the [userOperations](https://github.com/GCTC-NTGC/gc-digital-talent/blob/main/frontend/admin/src/js/components/user/userOperations.graphql) For the admin users table.

ah sorry, but update them with what? I think I got rid of isVeteran everywhere or did you mean something else?
the query you linked doesn't have isVeteran, did you want me to add the new field into it?

**Comment by esizer** [comment]
> ah sorry, but update them with what? I think I got rid of isVeteran everywhere or did you mean something else?
> the query you linked doesn't have isVeteran, did you want me to add the new field into it?

Yeah, it is missing it which is causing that field to always be blank in the CSV and print actions.

**Comment by vd1992** [comment]
okay, appears to be resolved in https://github.com/GCTC-NTGC/gc-digital-talent/pull/3764/commits/9c532164597d1e81146ad1870bee9930f12f812f

print renders it now

image

**Review by esizer — APPROVED** [review]
Cool! 👩‍🎤

**Pull request merged**
