### PR TITLE
[Feature] Skill showcase page

### LINKED ISSUE #7386: ✨ Skill showcase page
image

## ✨ Feature

On this page users can define their "top skills" and "skills you'd like to improve". They can do this separately for Behavioral and Technical skills, for a total of 4 lists (for now). Each list will be orderable by the user.

## 🕵️ Details

You don't actually edit the lists on this page. This page displays all four lists, and has links to other pages where you edit each one specifically (#7388).

QUESTION: what should the url of this page be?
ANSWER: `/applicant/profile-and-applications/skills/showcase`

## 📸 Screenshots

For convenience only - remember to work from figma to stay up-to-date!

<details><summary>Full page (Incomplete)</summary>

</details>

<details><summary>Full page (Complete)</summary>

</details>

## 🌎 Localization

(optional) Provide any new copy along with translations available.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] This is behind SKILL_LIBRARY feature flag
- [ ] Page exists at a new route
- [ ] Page has correct breadcrumbs
- [ ] Table of contents, with two entries and a button-styled link to Skill library
- [ ] Both sections show two lists, one for each skill type
- [ ] Lists show skills in a specific order (determined when lists are edited)
- [ ] Edit buttons on each list go to #7388
- [ ] If a list is empty, null state is a link to #7388
- [ ] Lists show name of each skill as a link to #7378, and the user's skill level if present
- [ ] "Manage all skills" links point back to Skills library page
- [ ] new card component `ShowcaseCard` or variant of `Card` component (research needed to determine if `Card` component can be used on its own)

### PR DESCRIPTION
**Pull request by esizer**
🤖 Resolves #7386

## 👋 Introduction

Adds the skill showcase page to the application.

## 🕵️ Details

This includes some links to paths that do not exist yet. I just added some `TO DO` comments and added it to the AC of the appropriate ticket.

## 🧪 Testing

Assist reviewers with steps they can take to test that the PR does what it says it does.

> **Note**
> You can also run storybook to force certain states instead of manually updating the database.

> **Note**
> Edit links do not work, should be updated in #7388

1. Build `npm run dev`
2. Navigate to `/applicant/profile-and-applications/skills/showcase`
3. Check it matches the mockup
4. Confirm clicking a skill takes you to the edit page
5. Confirm "Manage all skills" links go to the skills library

## 📸 Screenshot

localhost_8000_en_applicant_profile-and-applications_skills_showcase

### CODE REVIEW

**Comment by vd1992** [comment]
@substrae 
If you would like to, please take a look at the Skill Showcase Page story

**Comment by substrae** [comment]
@vd1992 

Sure thing! I'll take a peek and leave comments here.

**Comment by substrae** [comment]
@vd1992

Two things that stand out to me off the bat:

<details>
  <summary>The cards are missing the `foreground` color on their background</summary>
  
</details> 

<details>
  <summary>We might want to add a label such as "Unspecified" to skills that are missing the level declaration</summary>
  <p>I've been in a few discussions about skill levels where we were juggling the idea that anywhere a skill is added, we might be able to check to see if it exists on the user's profile, and if it doesn't prompt them for the level in situ. Not sure how much of a lift this is though.</p>
  
</details>

**Review by brindasasi — APPROVED** [review]
LGTM

**Comment by vd1992** [comment]
@substrae 

Sorry, I don't quite understand this bit. Do you mean the colour of the well with the added red marks over it?

image

**Comment by substrae** [comment]
@vd1992 

Sorry, my bad - the screenshot I included was what it should look like, and I was referring to the white background (`foreground` in Hydrogen) of the whole card. Right now, the cards seem to share the same background color as the page.

**Review by substrae — APPROVED** [review]
Thanks @vd1992 for taking care of all the feedback notes!

**Pull request merged**
