### PR TITLE
[Tooling] Adds `jest-fail-on-console` to jest testing

### LINKED ISSUE #5846: Get notified of jest warnings
Jest warnings, like not using act, should notify us somehow.  Is there a Github Actions warning result?

image

_Originally posted by @vd1992 in https://github.com/GCTC-NTGC/gc-digital-talent/issues/5844#issuecomment-1452495114_

Acceptance Criteria:
- Warnings from Jest notify the PR author in some way

### PR DESCRIPTION
**Pull request by mnigh**
🤖 Resolves #5846.

## 👋 Introduction

This PR adds a library to force jest tests to fail when `console.warn` or `console.error` appear.

## 🕵️ Details

Employs the `jest-fail-on-console` library to force failure when `console.warn` or `console.error` is used. I tried a number of different ways to do it including directly in `apps/web/src/tests/setup.ts` without importing anything heavy but the `jest-fail-on-console` library seemed the most mature and supported option.

## 🏅 Gratitudes
@petertgiles for solving the following issues to unblock this one:

- #6220
- #6223
- #6224

@vd1992 for [proposing a solution](https://github.com/GCTC-NTGC/gc-digital-talent/issues/5846#issuecomment-1490793472)

## 🧪 Testing

Assist reviewers with steps they can take to test that the PR does what it says it does.

1. Run `npm run test`
2. Observe exit code 1 (failure)
3. Comment out `failOnConsole()` in `apps/web/src/tests/setup.ts`
4. Observe exit code 0 (success)

### CODE REVIEW

**Comment by esizer** [comment]
Thanks for shining light on my mess up during the rush job 😅 

https://github.com/GCTC-NTGC/gc-digital-talent/actions/runs/4610351627/jobs/8148719151?pr=6178#step:8:2964

**Comment by vd1992** [comment]
This does take care of it, but creates an immediate need to resolve all those console errors otherwise we have a problem (no idea if something broke or was already broken upon a test run)

We can leverage the expect a console error functionality to push tricky console errors for later

image

**Comment by mnigh** [comment]
> We can leverage the expect a console error functionality to push tricky console errors for later

The problem is we don't actually expect these console errors/warnings and I don't think we want to rewrite our tests to allow for it either.

**Comment by petertgiles** [comment]
Thanks for putting this up, Matt!  I've run it and broken the existing errors into three issues that I've set as blockers.  I'll put the parent issue for this PR back in the product backlog along with this PR.  Once we've got the blockers cleared we can try to merge this again.

**Review by esizer — COMMENTED** [review]
LGTM! 👍

**Comment by mnigh** [comment]
> LGTM! 👍

@esizer Can you approve? 😉

**Review by esizer — APPROVED** [review]

**Pull request merged**
