### PR TITLE
Create profile page

### LINKED ISSUE #1915: Overall Profile page with placeholder sections

### PR DESCRIPTION
**Pull request by JamesHuf**
Will resolve #1915.

Notes/issues:
- ~~I couldn't find the hero icons used for the 'Government information' and 'Work location' sections.~~
- ~~When I tried to increase the size of the header text the background seemed to mess up.~~
- ~~The header background works in the storybook but gets a 404 when navigating to the page.~~
- The graphql query is returning null. I think this is some kind of session issue but I'm not sure what.

I would love any advice or solutions for the above problems.

### CODE REVIEW

**Comment by vd1992** [comment]
for the icons: 
Government Information is "library" from solid
Work Location I don't think I see anywhere... Does it have to be made out of other icons?

resource:
https://heroicons.com/

**Comment by vd1992** [comment]
for the icons: 
Government Information is "library" from solid
Work Location I don't think I see anywhere... Does it have to be made out of other icons?

resource:
https://heroicons.com/

**Comment by vd1992** [comment]
Diversity, equity, and inclusion are not on the sticky menu for the wireframe. Is it desired to be included now?

**Comment by JamesHuf** [comment]
> for the icons:
> Government Information is "library" from solid
> Work Location I don't think I see anywhere... Does it have to be made out of other icons?
> 
> resource:
> https://heroicons.com/

I thought library didn't quite look right to me but that could be it. I have no idea about the Work Location one though.

> Diversity, equity, and inclusion are not on the sticky menu for the wireframe. Is it desired to be included now?

@Jerryescandon - Should the Diversity, Equity and inclusion section be linked to in the 'On this page' section? It's not there on the wireframe. Also if you can provide input on what the icons should be for the 'Government Information' and 'Work Location' sections that be great too.

**Comment by Jerryescandon** [comment]
> Should the Diversity, Equity and inclusion section be linked to in the 'On this page' section?

Yes! sorry about that. Should definitely be in there.

**Comment by Jerryescandon** [comment]
> what the icons should be for the 'Government Information' and 'Work Location'

Brooke custom made those for us. I will export the SVGs and put em here in a sec.

**Comment by Jerryescandon** [comment]
icon_work_location
icon_gov

**Review by petertgiles — CHANGES_REQUESTED** [review]
Wow, this looks great!  A few comments:

- The wireframe has the title _My pools_ but the wireframe has _My hiring pools_.

- I think it's great that you created a `profile` directory since we'll probably have a lot of components here.  However, could you please put these two files in a `ProfilePage` subdirectory?  Convention is that a directory containing a single component should have the same name as the component.  Compare to `AddedSkills` here:
image

- In the component you're building URLs like this: `href={`${paths.home()}/update-status`}`.  I think this logic should be inside one of the routing files.  Vany has created a new routing file for applicant profile in `applicantProfileRoutes.ts`.  Maybe that's the spot?

- Regarding no result in graphql - this is expected I think.  The talentsearch site has no auth yet.

**Comment by JamesHuf** [comment]
@Jerryescandon The wireframe calls the one section 'My hiring pools' but the link to it on the left is just 'My Pools' is this intentional or should they both be referred to as 'My hiring pools'?

**Comment by Jerryescandon** [comment]
> @Jerryescandon The wireframe calls the one section 'My hiring pools' but the link to it on the left is just 'My Pools' is this intentional or should they both be referred to as 'My hiring pools'?

"My hiring pools" is the correct title for both

**Review by petertgiles — APPROVED** [review]
I love it - it looks so good!  I'm a little unsure of the URLs but I think I'm going to request more clarity on that from the designers.  For now, I'm good with it.

**Pull request merged**
