### PR TITLE
[Debt] Store assessment status on submission

### LINKED ISSUE #10939: ♻️ Dispatch assessment status on application submit
## ♻️ Debt/Refactor

We would like to have the assessment status computed on time of submission in addition to the existing computation at assessment creation.

## 🕵️ Details

Some steps can be passed automatically without creating a result so it is odd to see them pop in after doing the first assessment. We can probably avoid this by dispatching the event during application submission.

## 🙋‍♀️ Proposed Solution

Dispatch the `AssessmentResultSaved` event at time of application submission.

## ✅ Acceptance Criteria

- [ ] The assessment status is computed and stored as soon as an application is submitted

### PR DESCRIPTION
**Pull request by esizer**
🤖 Resolves #10939 

## 👋 Introduction

Stores the assessment status when submitting an application.

## 🕵️ Details

Original AC was the dispatch an event but that event could not be dispatched since there is  no assessment result to dispatch the event with. So, it just adds some codes to do a similar thing and meet the goal of having assessment status be accurately initialized.

## 🧪 Testing

1. Sign in as admin `admin@test.com`
2. Publish a pool with an assessment plan that includes auto pass steps (I think non essential behavioural skill assessments work)
3. Apply to that pool
4. Confirm the `computed_assessment_status` is not the default value but the computed value based on the assessment plan

### CODE REVIEW

**Review by mnigh — COMMENTED** [review]
i'm not sure if this is related to this PR, but should the status icon beside **Application screening** be checkmarked and green even if the value is To assess?

## Screenshot
Screen Shot 2024-08-06 at 14 42 23

**Comment by tristan-orourke** [comment]
Yep this looks like a bug. Application Screening step should require Education Requirement to be assessed to be complete.

**Comment by esizer** [comment]
> Yep this looks like a bug. Application Screening step should require Education Requirement to be assessed to be complete.

Thanks, a ticket has been created.

 - https://github.com/GCTC-NTGC/gc-digital-talent/issues/11158

**Review by mnigh — APPROVED** [review]
> The assessment status is computed and stored as soon as an application is submitted

👍 LGTM

**Pull request merged**
