### PR TITLE
[Accessibility] Fix accordion focus overlap with actions

### LINKED ISSUE #11975: ⌨ Overlap of collapse focus background with action links
## ⌨ Accessibility Issue

The links underneath a collapse element overlap with the triggers focus background and looks odd making things difficult to read.

## 🦋 Expected Behaviour

No overlap of background colour and action links for a collapsible item.

## 📋 Steps to Reproduce

1. Login as manager `manager@test.com`
2. Navigate to the manager dashboard
3. Focus the "Your talent requests" trigger
4. Observe the focus background overlap

## 📸 Screenshot

Screenshot 2024-11-14 155715

## 🙋‍♀️ Proposed Solution

1. Add more space between the two items
2. Or, find a way to reduce the background colour coverage

## ✅ Acceptance Criteria

- [ ] No overlap between focus background and action links
- [ ] Little to no visual changes outside of fixing overlap
- [ ] While we're here change focus colour of text to black
- [ ] Design review

### PR DESCRIPTION
**Pull request by vd1992**
🤖 Resolves #11975 

## 👋 Introduction

Resolve the overlap through spacing, also set focus colour to black in all cases

## 🧪 Testing

1. Navigate to manager dashboard
2. Keyboard toggle down

## 📸 Screenshot

image

image

image

### CODE REVIEW

**Review by yonikid15 — APPROVED** [review]
LGTM :+1: 
image

This looks kind of off but it's out of scope. I'll check with a designer and make issue if needed.
image

**Comment by JoshBeveridge** [comment]
Sorry for the delay! Two small things:
* The distance between the title and the action list is `x.75` cumulatively, when it should be `x.5`
* The focus issue @yonikid15 pointed out - the focus background shouldn't extend around the bullet, it should be contained to the actual link's label

From Figma:
image

**Comment by vd1992** [comment]
Okay, I tackled it in https://github.com/GCTC-NTGC/gc-digital-talent/pull/12231/commits/d6b4021ee90a496d7abcda271adeedcf26f0e37a
The bullet character was a little trickier so I tried some refactoring

**Review by JoshBeveridge — APPROVED** [review]
Awesome, thanks for sticking with it @vd1992! Looks great!

**Review by yonikid15 — APPROVED** [review]
Looks good Vachan!

**Pull request merged**
