### PR TITLE
[Debt] Migrate user operations to `client-preset`

### LINKED ISSUE #8716: ♻️ All User Related Items Migrated to `client-preset`
## ♻️ Debt/Refactor

Migrate all `*.operations.graphql` files related to `User`  and associated components to use the new pattern in `@gc-digital-talent/graphql`

## 🕵️ Details

Follow [the documentation](https://github.com/GCTC-NTGC/gc-digital-talent/blob/main/documentation/graphql.md) to complete this issue.

## ✅ Acceptance Criteria

- [ ] `*.graphql` files removed
- [ ] All components used by `User`, `Team`, `Profile` use new pattern
- [ ] All components used by `User`, `Team`, `Profile`  are fragmentized
- [ ] Cypress tests updated to use new queries
- [ ] Refactor usage of `Maybe` to exclude `undefined`

### PR DESCRIPTION
**Pull request by esizer**
🤖 Resolves #8716 

## 👋 Introduction

Migrates all the user based operations to the `@gc-digital-talent/graphql` package.

## 🕵️ Details

I apologize to whoever has to review this. I didn't realize how large it was going to be when I started 😓 . We have a lot of user operations 😛 

## 🧪 Testing

Assist reviewers with steps they can take to test that the PR does what it says it does.

1. Build `npm run dev`
2. Navigate to the many pages that include user operations
3. Confirm no errors from graphql requests

### CODE REVIEW

**Review by yonikid15 — APPROVED** [review]
Nice work Eric! I scanned through all the pages and wasn't able to find anything missing or any bugs. However, I found some non-related bugs that I need to make some issues for 😅.

**Review by yonikid15 — CHANGES_REQUESTED** [review]
Actually the bug is coming from this PR, I wasn't able to reproduce it on main. I'll take a look at whats causing it seems like just an undefined value in the parameter.

image

**Comment by esizer** [comment]
> Actually the bug is coming from this PR, I wasn't able to reproduce it on main. I'll take a look at whats causing it seems like just an undefined value in the parameter.

Oops, I updated to use required params but forgot the `experienceId` is not required. Reverted in https://github.com/GCTC-NTGC/gc-digital-talent/pull/9497/commits/0747e3dc4e461c6a74bec92d02b445e3e0ae27e7

**Review by yonikid15 — APPROVED** [review]
Nice looks good now 👍

**Pull request merged**
