### PR TITLE
fix footer links in TC directory

### LINKED ISSUE #2565: Footer link to canada.ca is broken
### Screencast

[screencast of dead link in footer](https://recordit.co/SxcNbZlnli)

## Notice

1. The footer link for canada.ca:
    1. :x: is broken on all pages
    2. :x: on language picker page, _tries_ to point to english page (should it not be less opinionated?)
    3. ✅ on french and english pages, _tries_ to point to appropriate language page

### PR DESCRIPTION
**Pull request by vd1992**
resolves #2565 

Problem: relative links to what should be an absolute link
What was done: find and replace "/en/https://www.canada.ca/en.html" with "https://www.canada.ca/"

Prettier did stuff automatically

### CODE REVIEW

**Comment by vd1992** [comment]
carried out for "/fr/https://www.canada.ca/fr.html" as well

**Comment by petertgiles** [comment]
> Prettier did stuff automatically

This is really hard to review... :smiling_face_with_tear: Could you either disable Prettier for this or separate the formatting to a different commit?

**Comment by vd1992** [comment]
@petertgiles 
- reverted commits
- ran Prettier through directory first -> commit
- execute find and replace -> commit

**Comment by petertgiles** [comment]
> * ran Prettier through directory first -> commit

Thanks, this is a lot better!  :smile: 

I think your replacements have lost the localization though.  You've replaced `/en/https://www.canada.ca/en.html` with `https://www.canada.ca/` but wouldn't you want to change it to `https://www.canada.ca/en.html`?  Similarly, you would want to change `/fr/https://www.canada.ca/fr.html` to `https://www.canada.ca/fr.html` right?

**Comment by petertgiles** [comment]
@gobyrne Could you confirm that you want all links to just point to canada.ca regardless of the language of the page they're on?

**Comment by tristan-orourke** [comment]
Let's send them to the right language if we can.

**Comment by vd1992** [comment]
@petertgiles 
Alright, take a look now

**Review by petertgiles — APPROVED** [review]
:+1:

**Pull request merged**
