### PR TITLE
Adjust tries and timeout

### LINKED ISSUE #11152: 🐛 New job posted email got sent 3 times to users about the same job
## 🐛 Bug

On Aug. 2 Friday around 1:30 pm we have sent 3 notification emails about the new job posted `IT security Analyst ` .

## 🦋 Expected Behaviour

We should not be sending duplicate emails 

## 🕵️ Details

We have 3 published processes in production. Would that align with why 3 times they have been sent out? 🤔
Here is the process details
https://talent.canada.ca/en/browse/pools/4a8e9f9f-56af-4c21-ad58-864351e088d4

## 📋 Steps to Reproduce
Couldn't reproduce in UAT.
Need more investigation on production why this is happened.  

## 📸 Screenshot

Add a screenshot (if possible).

## 🙋‍♀️ Proposed Solution

(optional) Do you have a proposed solution?

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] New job notification email should be sent only once.

### PR DESCRIPTION
**Pull request by petertgiles**
🤖 Resolves #11152 , #11153 

## 👋 Introduction

I believe the the reason some people got three notifications and some got zero is that the job that queues the notification for each user was timing out and retrying.  This branch sets the timeout to a longer value and disables retries.

## 🕵️ Details

I can see the job that Brinda was referring to in the prod `failed_jobs` table with a TimeoutException.  The default timeout for a job is 60 seconds, the wait to retry is 90 seconds, and our workers are set to 3 retries.  This all lines up with the timeline Brinda logged in the issue.

I seeded 23,000 users locally which is about how many we have who received this notification in prod.  I confirmed that the job fails after 60 seconds, having queued about 7400 jobs.  When I upped the timeout, the full set took a little over 3 minutes.  I picked a timeout of 10 minutes for this job which should be about 3 times as much as we need - assuming that it runs a similar speed in prod.

## 🧪 Testing

1. Start the queue worker
2. Launch Tinker
3. `User::factory()->count(23000)->create(['enabled_email_notifications'=>['JOB_ALERT'], 'enabled_in_app_notifications'=>['JOB_ALERT']])`
4. `$p = Pool::factory()->draft()->create()`
5. `$p->published_at = Carbon/Carbon::now()`
6. `$p->save()`

- [ ] Over 23000 new jobs queued in the `jobs` table
- [ ] The App\Listeners\SendNewJobPostedNotification completes successfully

## 📸 Screenshot

image

### CODE REVIEW

**Review by esizer — APPROVED** [review]
Nice :sunglasses:

**Comment by petertgiles** [comment]
I tested this on dev and it queued about 4600 jobs per minute, so we should have double the needed time right now.

**Comment by tristan-orourke** [comment]
Could we set this up to break the task into multiple jobs, dividing up the list of users if its hits a certain threshold? This pushes back the problem but still won't scale.

**Comment by petertgiles** [comment]
> Could we set this up to break the task into multiple jobs, dividing up the list of users if its hits a certain threshold? This pushes back the problem but still won't scale.

Well, this job is really already that operation - a job that just queues a bunch of other jobs.  :laughing:   Then we would have a job that queues a job that queues more jobs.  

I don't think we can disable the timeout on this job but we could effectively do that by setting the timeout to 12 hours of something.

**Pull request merged**
