### PR TITLE
[Bug] Fix new abbreviations

### LINKED ISSUE #8677: 🐛 No abbreviation found for EX and PM
## 🐛 Bug

We have ATIP and Exec pools now for the EX and PM classifications.  When you hover over them, though, you get an "Abbreviation not found" message.

## ✅ Acceptance Criteria

- [ ] EX abbreviation should show as Executive Group
- [ ] PM abbreviation should show as Programme Administration
- [ ] Double check that there are none missing from prod classifications: IT, AS, CS, EC, EX, PM. (If they are, add them to this ticket according to https://www.canada.ca/en/treasury-board-secretariat/services/collective-agreements/occupational-groups.html)

### PR DESCRIPTION
**Pull request by yonikid15**
🤖 Resolves #8677 

## 👋 Introduction

- Fix abbreviations for EX and PM classifications.
- I think the next step to make this

## 🧪 Testing

1. Login as `admin@test.com`
2. Create EX and PM classification
3. Create a pool with EX and/or PM classification.
4. Hover over abbreviation on admin and front-facing app and ensure abbreviations read correctly.

### CODE REVIEW

**Comment by vd1992** [comment]
Two questions I got

1. The AC says "Program Administration" rather than "Programme Administration", did something change? 

2. The AC also mentions to check some other abbreviations, but not to do anything about it. So I suppose spin off issues to add abbreviations for CS and EC?

**Comment by brindasasi** [comment]
> Two questions I got
> 
> 1. The AC says "Program Administration" rather than "Programme Administration", did something change?
> 2. The AC also mentions to check some other abbreviations, but not to do anything about it. So I suppose spin off issues to add abbreviations for CS and EC?

@tristan-orourke / @gobyrne 
Could you pls look into this?

**Comment by tristan-orourke** [comment]
1. [Looks like](https://www.canada.ca/en/treasury-board-secretariat/services/collective-agreements/occupational-groups.html) it should be Programme Administration (Administration des programmes in French).
2. If we're missing abbreviations for other classifications lets add them to the Acceptance Criteria and handle them in this PR.

**Review by esizer — APPROVED** [review]
LGTM! 👍

**Comment by brindasasi** [comment]
> 1. [Looks like](https://www.canada.ca/en/treasury-board-secretariat/services/collective-agreements/occupational-groups.html) it should be Programme Administration (Administration des programmes in French).
> 2. If we're missing abbreviations for other classifications lets add them to the Acceptance Criteria and handle them in this PR.

I found this in the above link. 
EC - Economics and Social Science Services
But I don't find anything for CS.
Is it because it has been changed to IT ? 🤔

**Review by brindasasi — CHANGES_REQUESTED** [review]
Missing the abbr. for EC & CS.

**Comment by brindasasi** [comment]
@esizer could you review this?

**Review by esizer — APPROVED** [review]
Awesome! ⭐

**Review by brindasasi — APPROVED** [review]

**Pull request merged**
