### PR TITLE
Run chmod on maintenance scripts

### LINKED ISSUE #1188: Maintenance scripts not working on macOS
`setup.sh: /root/scripts/update_auth_env.sh: /bin/bash: bad interpreter: Permission denied
`

Also happens on other shell scripts in `scripts`.

Screen Shot 2021-11-19 at 15 27 31

This could be involved with setting executable rights on the script files.

### PR DESCRIPTION
**Pull request by gggrant**
Resolves #1188.

Note: after running the scripts, all file permissions were modified. I pushed everything.

### CODE REVIEW

**Review by mnigh — COMMENTED** [review]
This changes all of the files (in unix file system parlance) from 644 to 755 meaning all of these files would now be executable by user, group, and other. Would this be considered a security issue if everyone is allowed to execute this files on the server or does this not matter?

**Comment by petertgiles** [comment]
Oh, it's probably the chmod commands in the setup.sh script causing all the file system changes.  I copied it from the [deploy.sh script in the infrastructure folder](https://github.com/GCTC-NTGC/gc-digital-talent/blob/82f572d49ea36f434f885cb931e58cdb831f076d/infrastructure/deploy.sh#L78).  There may be a more nuanced approach to updating the permissions but I'm not sure what the original purpose of the chmod commands are in the deploy script.  I do know that without the chown and chmod updates the logging will sometimes fail in the php container.

**Comment by mnigh** [comment]
> Oh, it's probably the chmod commands in the setup.sh script causing all the file system changes. I copied it from the [deploy.sh script in the infrastructure folder](https://github.com/GCTC-NTGC/gc-digital-talent/blob/82f572d49ea36f434f885cb931e58cdb831f076d/infrastructure/deploy.sh#L78). There may be a more nuanced approach to updating the permissions but I'm not sure what the original purpose of the chmod commands are in the deploy script. I do know that without the chown and chmod updates the logging will sometimes fail in the php container.

I just ran `docker-compose run --rm maintenance bash setup.sh` with all of the `chmod -R 775 ./ ./storage` lines commented out and didn't get any of the `/bin/bash: bad interpreter: Permission denied` messages. Perhaps the fix is removing the chown and chmod instead of changing all of the file permissions (since this would mean that any new files would need this change as well). @gggrant, any thoughts?

**Comment by gggrant** [comment]
Yeah, whatever's clever. I'll close this and open another.

**Pull request closed without merging**
