### PR TITLE
1281 server infrastructure modifications

### LINKED ISSUE #1281: Merge important changes from server-experiments branch
# Description
Many changes have been made to the server-experiments branch in the course of getting it working on the dev server. Determine which changes are important, and merge them into the main branch.

### PR DESCRIPTION
**Pull request by tristan-orourke**
Resolves #1281 

Collects config changes that will enable deployment to production:
- An htacess file which will work equally well when deployed behind a reverse proxy
- Enable using /tmp for all storage, since the usual storage directories may be read-only

### CODE REVIEW

**Comment by yonikid15** [comment]
Should we close this stale draft [PR](https://github.com/GCTC-NTGC/gc-digital-talent/pull/1048)? Since they cover the same issue.

**Comment by petertgiles** [comment]
Wow, looks like some exciting changes happening here! 🚀  Unfortunately, I can't seem to get it to work on my workstation. 😢  I'm getting HTTP 500s on both talentsearch and login.  Browsing the admin site seems to work OK.  I tried updating my .env files to match your new .env.example files but it didn't seem to make a difference.

Sorry about the conflict on the .htaccess file.  If you add my new rewrite rule `RewriteRule ^auth-callback admin/public/ [L]` to your file you should be safe to overwrite main.

**Comment by tristan-orourke** [comment]
> Should we close this stale draft [PR](https://github.com/GCTC-NTGC/gc-digital-talent/pull/1048)? Since they cover the same issue.

Yep, good reminder, I'll close that PR.

**Comment by tristan-orourke** [comment]
@petertgiles After running the refresh_all maintenance script, I'm seeing the same errors you are. I'll take a look into the logs to figure this out.

**Comment by tristan-orourke** [comment]
@petertgiles Give it another try now

**Review by petertgiles — APPROVED** [review]
Very nice, this works for me now. 🙌

Since this change is mostly about running on the server I think this branch should be tested there before merging but it looks good to me on local.

**Comment by tristan-orourke** [comment]
> Since this change is mostly about running on the server I think this branch should be tested there before merging but it looks good to me on local.
 Good point, I'll test this on the dev server before merging it.

**Comment by tristan-orourke** [comment]
This branch has now been deployed successfully to Dev, Uat and Prod servers, so it should be ready to go!

**Review by petertgiles — APPROVED** [review]
To be honest, I don't understand a lot of the lower level PHP setup stuff going on but it does seem to work for me in my local environment.  I'm noticing that there are some issues loading images in the talentsearch app but since this is the way the ENV variables need to be setup for the server I'll merge it and open a new issue for that.  Nice job!  🚀

**Pull request merged**
