### PR TITLE
[Feature] Add education requirements for CR classification

### LINKED ISSUE #11311: 🔤 Add education requirement for CR classification
## 🔤 Copy

New education requirement for CR classification. This is so ATIP can post a CR competition in the fall.

The requirement can follow the same pattern as IT with Applied work experience, but the Education requirement is 2 years of secondary school instead of 2 years post-secondary.

### English
**Applied work experience**
Combination of experience, training or education.

**Two years of secondary school**
Successful completion of two years of secondary school.

### French
**Exigences en matière de travail pratique**
Un agencement d’études, de formation ou d’expérience.

**Deux années d’études secondaires**
La réussite de deux années d’études secondaires.

### 🧑‍🎨 Designer

@NienkeBr 

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the copy has been added or updated appropriately.

- [ ] Job process created with CR classification shows the correct (new) education requirement
- [ ] Add CR-04 classification to seeder, using data from prod
- [ ] Education requirement step of the application shows the correct options for this classification. See comment below (from Nienke)

### PR DESCRIPTION
**Pull request by esizer**
🤖 Resolves #11311 

## 👋 Introduction

Adds education requirements for the CR classification that currently does not exist but will in the future.

## 🧪 Testing

1. Build the app `pnpm run dev:fresh`
2. Login as admin
3. Create a classification with group "CR"
4. Create a pool using the new classification
5. Confirm it has the proper education requirements on:
    - Edit pool page
    - Pool advertisement
    - Application

### CODE REVIEW

**Review by petertgiles — CHANGES_REQUESTED** [review]
Ooops, missing this AC: 
>Add CR-04 classification to seeder, using data from prod

**Comment by esizer** [comment]
> Add CR-04 classification to seeder, using data from prod

Hmm, I did look for that but the data seems incomplete. Do we just add the one item that does exist (CR-04)?

**Comment by petertgiles** [comment]
Yeah, just CR-04.  It's OK if we don't have  1 - 3.

**Comment by esizer** [comment]
> Yeah, just CR-04. It's OK if we don't have 1 - 3.

Okay, thanks. Added in [add seeder for CR group](https://github.com/GCTC-NTGC/gc-digital-talent/pull/11420/commits/c6166ac8e8dad51d85f6f1e004ba6837a43dec6c)

**Review by petertgiles — CHANGES_REQUESTED** [review]
Ooops, missing this AC:
> Education requirement step of the application shows the correct options for this classification. See comment below (from Nienke)

image

**Comment by esizer** [comment]
> Ooops, missing this AC:
> 
> > Education requirement step of the application shows the correct options for this classification. See comment below (from Nienke)

Oof, I forgot those were different :confounded: Should be good after [update application CR education requirements](https://github.com/GCTC-NTGC/gc-digital-talent/pull/11420/commits/246eda8ffa61c96b3b930c5467fdf9d371551c5e)

Would be nice to get these in the database :sweat_smile:

**Review by petertgiles — APPROVED** [review]
Nice.  Good one!

**Pull request merged**
