### PR TITLE
[Feature] Add step tracker to screening page

### LINKED ISSUE #8958: ✨ Add AssessmentStepTracker to "Screening and evalutation" tab
## ✨ Feature

Add the AssessmentStepTracker to the Screening and evaluation tab for a Pool on the admin site.

## 🕵️ Details

We already have the AssessmentStepTracker, with a storybook story.
We already have a placeholder page for "Screening and evaluation", at `/admin/pools/<pool-id>/screening`.
Now we just to put the tracker on the page, and make sure we load the correct data from the api to populate it.

## 🎨 Design File

https://www.figma.com/file/em5ArPr044YaIe1Vb1zCZz/Pools---Record-of-Decision?type=design&node-id=6872-37861&mode=design&t=TeMhyhV3Lb1uklxC-0

### 🧑‍🎨 Designer

@Jerryescandon 

## 📸 Screenshot

<details><summary>Figma screenshot (Jan 04)</summary>
<p>

image

</p>
</details>

<details><summary>Current empty page</summary>
<p>

image

</p>
</details>

## 🙋‍♀️ Proposed Implementation

(optional) Do you have a proposed implementation?

## 🌎 Localization

(optional) Provide any new copy along with translations available.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] The `/admin/pools/<pool-id>/screening` page loads the assessment results for all candidates in the pool and displays them in the assessment step tracker

### PR DESCRIPTION
**Pull request by esizer**
🤖 Resolves #8958 

## 👋 Introduction

This adds the assessment step tracker to the pool's screening and evaluation page.

## 🧪 Testing

> [!NOTE]
> The step tracker contains a known bug where it shows users multiple times which will be fixed as part of another ticket (https://github.com/GCTC-NTGC/gc-digital-talent/issues/8957).

1. Build `npm run dev`
2. Login as an admin
3. Navigate to `/admin/pools`
4. Find and navigate to the "CMO Digital Careers" pool (reliably shows assessments with our seeders)
5. Navigate to the "Screening and evaluation" page
6. Confirm the step tracker is there and populated with the steps
7. Confirm bookmarking users functions as expected

## 📸 Screenshot

localhost_8000_en_admin_pools_ba567ec6-53ef-423a-b23f-f5c9eb3966a0_screening

### CODE REVIEW

**Comment by brindasasi** [comment]
for some reason, book mark doesn't work for me . Am I missing something? 
I logged in as Admin 
```
2024-01-08 21:51:18] local.INFO: GraphQL request from platform admin user [admin@test.com] {"operationName":"ToggleBookmark_Mutation","query":"mutation ToggleBookmark_Mutation($id: ID!) {
  togglePoolCandidateBookmark(id: $id)
}","variables":{"id":"78a12477-cef5-4a8b-af51-0e8161ad3dc4"}} 
[2024-01-08 21:51:29] local.INFO: GraphQL Error: This action is unauthorized.  
```

**Comment by esizer** [comment]
> for some reason, book mark doesn't work for me . Am I missing something?
> I logged in as Admin

I think there may be some odd gap in our auth. I keep seeing this exact error intermittently in unrelated cypress tests 😢

**Comment by brindasasi** [comment]
> > for some reason, book mark doesn't work for me . Am I missing something?
> > I logged in as Admin
> 
> I think there may be some odd gap in our auth. I keep seeing this exact error intermittently in unrelated cypress tests 😢

After the fresh seeding , bookmark worked fine 😌 . I can't seem to find out what went wrong.

**Review by brindasasi — APPROVED** [review]
LGTM!

**Comment by tristan-orourke** [comment]
@brindasasi it was bookmarking which didn't work, right? I think maybe you ran into an issue caused by this: #8977

**Comment by brindasasi** [comment]
> @brindasasi it was bookmarking which didn't work, right? I think maybe you ran into an issue caused by this: #8977

oh yes .. it is .. I noticed that my default column was empty on the initial migration and was wondering about that .. sorry .. I should have thought about that more.

**Pull request merged**
