### PR TITLE
Feature - 2796 - Admin pool placeholder page

### LINKED ISSUE #2796: Pool Summary placeholder Page
[Prototype](https://www.figma.com/proto/XS4Ag6GWcgdq2dBlLzBkay/Admin-v3-(Profile-release)?node-id=752%3A6863&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=410%3A1984&show-proto-sidebar=1)

image

## Acceptance Criteria
- [x] Title
- [x] edit button
- [x] Two tabs
- [x] breadcrumbs
- [x] available at url `/admin/pools/:id`

### PR DESCRIPTION
**Pull request by esizer**
Resolves #2796 

## Summary

This adds the placeholder page for an individual pool.

### No Link

We currently have no link to this page and it will be introduced when we update to the new tables in #2639 I believe.

### Styles (Tabs)

The tabs do not look like they do in the [Prototype](https://www.figma.com/proto/XS4Ag6GWcgdq2dBlLzBkay/Admin-v3-(Profile-release)?node-id=752%3A6863&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=410%3A1984&show-proto-sidebar=1) because they have yet to be updated. This will change when we update the tabs styling.

## Screenshot

Screen Shot 2022-05-20 at 1 07 18 PM

### CODE REVIEW

**Comment by vd1992** [comment]
Pretty solid, some comments: 

The breadcrumbs is a bit different, in its links as well as colour. Is that intentional? 
image

It might look nicer to center the edit button vertically in its container?
image

**Review by vd1992 — CHANGES_REQUESTED** [review]
See comments above; resolve them, or mention the changes aren't required and I will change this review

**Comment by esizer** [comment]
> The breadcrumbs is a bit different, in its links as well as colour. Is that intentional?

I'm actually not sure about this. I used the `<Breadcrumbs>` component in common. We may need to update that component to use the new styles in the prototype (like the tabs).

> It might look nicer to center the edit button vertically in its container?

I agree, this has been updated.

Screen Shot 2022-05-24 at 8 55 31 AM


> There is also a linting thing in one of the files you worked on, won't let me comment on it directly

Hmm, not sure why that is there. I can see the import it is complaining about used on line 67. 😕 

`text={(pool?.name && pool?.name[getLocale(intl)]) ?? ""}`

**Review by vd1992 — APPROVED** [review]
Good job!

**Pull request merged**
