### PR TITLE
Fix bug with candidate ID in requests component directory 

### LINKED ISSUE #2498: Admin - Requests - Wrong candidate ID in link
When reviewing a list of candidates in the admin site in a specific saved request the candidate ID used in the link is wrong.

### PR DESCRIPTION
**Pull request by vd1992**
resolves #2498 

Most of the changes were automatic from formatting. 
The actual changes were a few things, the wrong variables were being passed into the pathing. _UserID_ was used not _poolCandidateID_.  It will be important to be wary of the multiple types of ID in use, in this case UserID =/= PoolCandidateID

See changes of relevance at
https://github.com/GCTC-NTGC/gc-digital-talent/compare/feature/2498-candidate-ID-bug?expand=1#diff-7b5fab6aa374ee8dae4c812f085e7937655958ecdb01fa7b6edaacd5c002c1daR23-R34

https://github.com/GCTC-NTGC/gc-digital-talent/compare/feature/2498-candidate-ID-bug?expand=1#diff-7b5fab6aa374ee8dae4c812f085e7937655958ecdb01fa7b6edaacd5c002c1daL46-R47

https://github.com/GCTC-NTGC/gc-digital-talent/compare/feature/2498-candidate-ID-bug?expand=1#diff-7b5fab6aa374ee8dae4c812f085e7937655958ecdb01fa7b6edaacd5c002c1daR209

### CODE REVIEW

**Review by esizer — COMMENTED** [review]
Thanks for the links 😀 ! This looks good to me, however I do not have any pool candidates showing up, can anyone assist me in how to get some to show up so I can properly test?

Screen Shot 2022-04-22 at 9 07 44 AM

**Review by petertgiles — APPROVED** [review]
Nice one!  If possible, try to isolate the formatting changes in a separate commit to make it easier for the reviewers to isolate the functional changes. :grin:   Hopefully it won't be an issue soon, when the linting is caught up.

**Comment by petertgiles** [comment]
> can anyone assist me in how to get some to show up so I can properly test?

The `php artisan migrate:fresh --seed` command in the setup script should seed a bunch into your database.  Alternatively, you can manually make one if you submit a request on the talentsearch site.

**Review by esizer — APPROVED** [review]
Looks great!

**Comment by vd1992** [comment]
> Nice one! If possible, try to isolate the formatting changes in a separate commit to make it easier for the reviewers to isolate the functional changes. 😁 Hopefully it won't be an issue soon, when the linting is caught up.

D'oh
Yes, that would have been a much better idea 😅

**Pull request merged**
