### PR TITLE
Make skills searchable by keyword

### LINKED ISSUE #3414: Search Skills by Keyword should actually use keywords
<sup>ℹ️ [Figma (root)][figma] | [Sitemap][sitemap]</sup>
<sup>_This initial comment is collaborative and open to modification by all._</sup>

## Description

When you "Search Skills by Keyword", the search function should ACTUALLY match skill keywords (in the proper language), not just the skill name.

I think this functionality is in the handleSearch function in the AddSkillsToExperience.tsx component.

## Screenshot: Prototype
[![a screenshot of ...][image]][image-link]
<sup>[Click screenshot to visit Figma.][image-link]</sup>

## Acceptance Criteria
- [ ] If a skill has a keyword, and you enter a fragment of it in the search bar, the skill should appear in the results, even if the name of the skill does not match.
- [ ] If viewing the page in English, only English keywords should be considered. Same for when viewing the page in French.

   [image]: https://user-images.githubusercontent.com/4313717/179849746-4312ba11-707c-4f60-966d-df90dd174a8d.png
   [image-link]: https://www.figma.com/proto/PrvXEDac0HVp7dF7SLWVFm/Candidate-profile-interfaces---V5.0.0?node-id=2340%3A4352&starting-point-node-id=2340%3A4185
   [figma]: https://go.talent.c4nada.ca/figma
   [sitemap]: https://go.talent.c4nada.ca/sitemap

### PR DESCRIPTION
**Pull request by JamesHuf**
Resolves #3414.

Makes "Search by keyword" for skills actually use keywords.

### CODE REVIEW

**Review by vd1992 — CHANGES_REQUESTED** [review]
this works for adding experiences, but not for skill filter elsewhere, I think that needs the solution replicated elsewhere

**Comment by vd1992** [comment]
successful here

image

but not here

image

and not here

image

**Comment by vd1992** [comment]
frontend\talentsearch\src\js\components\skills\AddSkillsToFilter\AddSkillsToFilter.tsx 
possibly

**Comment by JamesHuf** [comment]
I've moved the logic for this to the common folder and set all three locations to use that function.

**Comment by JamesHuf** [comment]
After looking at things however, I'm curious if it would be a good idea to create a common component for all of the skill selection stuff here. At this point we have 3 files doing the same thing with just minor differences between them:
`frontend\admin\src\js\components\pool\EditPool\AddSkillsToPool.tsx`
`frontend\talentsearch\src\js\components\skills\AddSkillsToExperience\AddSkillsToExperience.tsx`
`frontend\talentsearch\src\js\components\skills\AddSkillsToFilter\AddSkillsToFilter.tsx`

It would probably contain this:
image

**Comment by vd1992** [comment]
edit pool and /search still seem to not search by keyword for me 😕

**Comment by JamesHuf** [comment]
> edit pool and /search still seem to not search by keyword for me 😕

Could you try reloading things? It's working for me.
image

**Comment by vd1992** [comment]
still not working for some reason

@esizer 
if you have a moment, could you please try out this branch, specifically checking if you can search by keywords on the /search page

**Review by vd1992 — APPROVED** [review]
whoops my bad
I kept running `npm run dev`, but didn't realize I needed to refresh codegen

all good now! nice work!

**Pull request merged**
