### PR TITLE
remove usage of fields intended to be migrated

### LINKED ISSUE #3681: Prevent usage of columns Pool Candidate about to be migrated
Before we perform our one-time migration of pool candidate columns we should ensure they don't get repopulated.

## Acceptance Criteria
The following columns in pool_candidates can no longer be populated or changed through the API:
- isWoman
- hasDisability
- isIndigenous
- isVisibleMinority
- hasDiploma
- languageAbility
- locationPreferences
- acceptedOperationalRequirements
- expectedSalary
- expectedClassifications
- cmoAssets

Also delete the pages that use/collect this data:
- create
- update

### PR DESCRIPTION
**Pull request by vd1992**
resolves #3681 
removes fields from the API, deletes components related to it, and then clean up problems that arise from deleting those pages

review: checkout ->codegen -> dev
browse through /admin as well as observe the chromatic diff (will run that after ensuring no tests fail)

### CODE REVIEW

**Comment by vd1992** [comment]
okay, ran storybook

**Review by esizer — CHANGES_REQUESTED** [review]
Awesome, looking great! One suggestion, if we are no longer using the admin paths for create and update, can we remove them from `adminRoutes.ts`?

https://github.com/GCTC-NTGC/gc-digital-talent/blob/9de8e789cf9f76a6de6a86f2487df8d8eae727c9/frontend/admin/src/js/adminRoutes.ts#L27-L37

**Comment by vd1992** [comment]
> Awesome, looking great! One suggestion, if we are no longer using the admin paths for create and update, can we remove them from `adminRoutes.ts`?
> 
> https://github.com/GCTC-NTGC/gc-digital-talent/blob/9de8e789cf9f76a6de6a86f2487df8d8eae727c9/frontend/admin/src/js/adminRoutes.ts#L27-L37

aye aye
https://github.com/GCTC-NTGC/gc-digital-talent/pull/3837/commits/0bb72ea987d387a51dac1b661ae30d197887fd92

**Review by esizer — APPROVED** [review]
LGTM! 👍

**Pull request merged**
