### PR TITLE
[Fix] ESLint configs

### LINKED ISSUE #9611: 🐛 ESLint misconfigured in `apps/e2e` and `apps/playwright`
## 🐛 Bug

Something is misconfigured in the test folders in `apps` leading to the VS Code extension to not highlight errors. Also, we are not actually linting these files 😢 

## 🦋 Expected Behaviour

VS Code ESLint extension can properly parse all files in `apps/*` and `packages/*`. CLI properly lints those folders.

## 🕵️ Details

I'm not exactly sure, but once you install `eslint-config-custom` and extend that, it does work. So there must be something in there. I think maybe it has something to do with typescript since we define some TS stuff in the custom config.

### Error example

```ts
test("should make an assertion", () => {
  console.log("no assertion");
});
```

1. Force an error in `apps/playwright`
2. Confirm VS Code does not highlight the error

## 🙋‍♀️ Proposed Solution

I don't think we want the full `eslint-config-custom` so maybe create a more minimal version so we have like an `eslint-config-custom-app` and `eslint-custom-tests` config to extend from?

As for the plugins, rules etc that should be in the tests one, I'm not certain about that. I guess everything except stuff specific to React?

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] ESLint is run in test directories on CLI
- [ ] ESLint properly configured in test directories
- [ ] VS Code ESLint extension works in test directories

### PR DESCRIPTION
**Pull request by esizer**
🤖 Resolves #9611 

## 👋 Introduction

Fixes an issue where our typescript files were not being processed by ESLint properly.

## 🕵️ Details

This was mostly an issue with playwright files not being processed because we did not have the typescript parser. Though, I split it up into a base file `index.js` and a react file `react.js` so we did not need to apply unnecessary rules to non-react packages.

> [!NOTE]
> I ignored a few Cypress warnings because I wasn't 100% sure how to properly resolve and we are migrating away soon anyway 🤷‍♀️ 

## 🧪 Testing

1. Install to propagate changes `npm install`
2. Restart your eslint server in VS Code
3. Force an error in playwright
4. Confirm it is highlighted by VS code
5. Run `npm run lint`
6. Confirm it fails
7. Repeat steps 2-5 in cypress
8. Repeat steps 2-5 in storybook-helpers

### CODE REVIEW

**Comment by vd1992** [comment]
I'd like someone else to also try this because this isn't working right for me. 
Executing 
`npm run lint -- --force`
And `npm install` plus VSCode relaunch between branch switches.

Main runs normally, this branch seems to not quite freeze my editor but take a really long time to the point where I just cancel the operation. It does highlight style errors for the spec files now though.

**Comment by esizer** [comment]
> Main runs normally, this branch seems to not quite freeze my editor but take a really long time to the point where I just cancel the operation. It does highlight style errors for the spec files now though.

Weird! I'd expect it to take a but longer since we are parsing more files but not to the point of almost crashing 😅

**Review by mnigh — APPROVED** [review]
The cli linting seems to be working for me, though took a hard quit of VS Code to get highlighting to render. @esizer I'm approving, but probably prudent to get someone using WSL to approve this as well before merging to main.

## Screenshots
Screen Shot 2024-03-05 at 15 47 34

Screen Shot 2024-03-05 at 15 44 47

Screen Shot 2024-03-05 at 15 39 31

Screen Shot 2024-03-05 at 15 49 50

**Review by yonikid15 — APPROVED** [review]
I'm getting the same results as Matt using WSL2.
I'm going to Approve it, but maybe @vd1992 Vachan can take another look.

image
image
image

Note: I am forced to run `npm run lint -- --force` due to turbo cache.

**Comment by vd1992** [comment]
It appears it is the Playwright linting that is playwronging for me. I get rid of linting that part and the lint completes in just under 2 minutes for me (no cache)

**Comment by yonikid15** [comment]
@esizer The changes made to the config fixed the turbo cache tester on my end 👍

**Comment by esizer** [comment]
> It appears it is the Playwright linting that is playwronging for me. I get rid of linting that part and the lint completes in just under 2 minutes for me (no cache)

Thanks for the info! Not sure what is going on but I made some changes (we were looking at all TS/JS files in that folder) so I made it a little more specific. Hopefully that helps?

[make playwright lint more specific](https://github.com/GCTC-NTGC/gc-digital-talent/pull/9616/commits/b34b9dbedd89d0b587a38670f3592722f01f5d90)

**Pull request merged**
