### PR TITLE
Release/2.27.2-1

### PR DESCRIPTION
**Pull request by brindasasi**
## 👋 Introduction

The below fix pr missing some imports as it is based off main branch and cherry picked into release branch.
I just checked out release/2.27.1 the current production code and created a new release branch for v2.27.2 by just directly applying the fix and added the missing imports. 
No other code change has been made. 

https://github.com/GCTC-NTGC/gc-digital-talent/pull/11136

## 🧪 Testing

Screening & Evaluation tracker page should load properly and issue the necessary queries

### CODE REVIEW

**Comment by mnigh** [comment]
@petertgiles can with PR be closed? prod is currently on a newer version, [v2.28.1](https://github.com/GCTC-NTGC/gc-digital-talent/compare/v2.28.1) (based on the commit listed https://github.com/GCTC-NTGC/gc-digital-talent/commit/b68d8620, anyway).

## Screenshot

Screen Shot 2024-08-22 at 12 45 30

**Comment by petertgiles** [comment]
@mnigh , sorry, I don't know anything about this.

**Comment by mnigh** [comment]
> @mnigh , sorry, I don't know anything about this.

@tristan-orourke any insight?

**Comment by tristan-orourke** [comment]
This is probably a test branch which we forgot to close. I'll close it now.

**Pull request closed without merging**
