### PR TITLE
Debt/3384 multi select to multi select field

### LINKED ISSUE #3384: Migrate MultiSelect components to MultiSelectFieldV2
<sup>ℹ️ [Figma (root)][figma] | [Sitemap][sitemap]</sup>
<sup>_This initial comment is collaborative and open to modification by all._</sup>

Related: https://github.com/GCTC-NTGC/gc-digital-talent/issues/3128

## Description

MultiSelectFieldV2 is an extension of SelectFieldV2 (both of which are built fully on react-select components). Most of the logic that builds on react-select components exists in SelectFieldV2, and MultiSelectFieldV2 is a minimal extension of it for better developer experience.

Proposed approach:
- write cypress/jest tests that validate that important Select form submissions work
- replace `<MultiSelect>` with `<MultiSelectFieldV2>`
  - wrap v1 around v2, ensuring types play nice together
  - replace all v1 with v2, making any change required if types need massaging
  - rename MultiSelectFieldV2 to SelectField
  - delete MultiSelect
- fix cypress/jest tests as needed

## Acceptance Criteria
- [x] migrate all instance of MultiSelect to MultiSelectFieldV2
- [ ] confirm migrated forms work as expected
- [x] remove MultiSelect component
- [x] remove V2 suffix from MultiSelectFieldV2

   [image]: https://user-images.githubusercontent.com/305339/166570935-6425a615-82c7-4b2f-9840-5c7d698fa2ab.png
   [image-link]: https://example.com
   [figma]: https://go.talent.c4nada.ca/figma
   [sitemap]: https://go.talent.c4nada.ca/sitemap

### PR DESCRIPTION
**Pull request by vd1992**
🤖 Resolves #3384 

## 👋 Introduction

Replace `<MultiSelect>` with `<MultiSelectField>` (renamed from `<MultiSelectFieldV2>`)

## 🕵️ Details

Old Multiselect component removed from the repo. 
Fairly straightforward replacement I think.

## 🧪 Testing

1. ensure tests pass
2. ensure components that used the removed component (/admin pages like user, skill, and skill family etc) continue to work fine

### CODE REVIEW

**Comment by esizer** [comment]
This is just personal preference so feel free to ignore, but what about just `<MultiSelect />` as a name? I'm not sure we need to suffix with `Field`. This would also brig it inline with our other form inputs since this seems to be the only one suffixed with `Field` right now.

**Comment by vd1992** [comment]
> This is just personal preference so feel free to ignore, but what about just `<MultiSelect />` as a name? I'm not sure we need to suffix with `Field`. This would also brig it inline with our other form inputs since this seems to be the only one suffixed with `Field` right now.

I defaulted to just following the acceptance criteria, but I think the naming fits
it isn't the only instance ending in "field" though, it is extending `<SelectFieldV2>`

image

**Comment by vd1992** [comment]
MultiSelectField lacks padding/spacing below it as can be seen here in the diff

image

given this component is used in many different places, such as the Fancy Filter, a blanket spacing style would be a bad idea so I added a spacing wrapper for certain implementations here https://github.com/GCTC-NTGC/gc-digital-talent/pull/5425/commits/443409c62747bb0adca681eca8d5dd5e5a8c9c91

**Comment by esizer** [comment]
> MultiSelectField lacks padding/spacing below it as can be seen here in the diff

Not part of the scope but, maybe we should create a ticket to add baseline margin on this component to bring it inline with our other form inputs?

https://github.com/GCTC-NTGC/gc-digital-talent/blob/fca285a93efbfc7dba2fc47c841c09693af27c24/frontend/common/src/components/form/Input/Input.tsx#L66

**Comment by vd1992** [comment]
> > MultiSelectField lacks padding/spacing below it as can be seen here in the diff
> 
> Not part of the scope but, maybe we should create a ticket to add baseline margin on this component to bring it inline with our other form inputs?
> 
> https://github.com/GCTC-NTGC/gc-digital-talent/blob/fca285a93efbfc7dba2fc47c841c09693af27c24/frontend/common/src/components/form/Input/Input.tsx#L66



I tried adding the spacing to the MultiSelectField itself, and that fixed it for create and update skill/user etc pages
But destroyed the layout of the Fancy Filter
The reason for the commit above adding margins to certain pages using it rather than add spacing onto the component itself, keeps it more neutral that way

**Comment by vd1992** [comment]
UI Review here
https://www.chromatic.com/pullrequest?appId=61e099a1bb1465003a73d3ce&number=5425&view=changes

**Comment by vd1992** [comment]
spun off here #5429

**Comment by brindasasi** [comment]
Looks just great in all the admin pages ! Nice work! 👏

**Review by brindasasi — APPROVED** [review]
good to go!

**Pull request merged**
