### PR TITLE
Fix bug breaking going from search to request

### LINKED ISSUE #2930: Bug - first click from search to Request page results in blank page
# Description
Steps to reproduce
1. Go to https://talent.canada.ca/en/talent/search
2. Click Request (doesn't seem to matter what the filters are)
3. See blank page
4. Click refresh. Correct page loads (and still with the correct filters set!)

### PR DESCRIPTION
**Pull request by vd1992**
resolves #2930 

To test, make sure /search isn't breaking or off in anyway 
Added a basic Cypress test, first try. It is something to build up over time I'd say so it can be barebones for now

### CODE REVIEW

**Review by esizer — APPROVED** [review]
Very nice! 👍 

Working well for me, tests pass and cannot reproduce the original issue anymore!

**Comment by vd1992** [comment]
Thanks!

Gonna page @patcon 
New Cypress test!

**Review by petertgiles — CHANGES_REQUESTED** [review]
This is very cool!  I wonder if we can do better on the test though?
- It has a bunch of built `wait`s that really slow it down.  The tests that Patrick wrote don't have that and can run much faster.
- The last assertion is just that the url has changed.  I think this isn't a great test since the bug does have the url changing, just nothing shows.  Can you make an assertion that the page has some expected content?  (The test does still fail on the bug since there are some exceptions thrown, though.)
- We're trying to keep related files together in a directory.  Is it possible to have this test file live near the search page component?

**Review by petertgiles — APPROVED** [review]
Nice, this test looks much better.  I'll start a slack discussion about test file placement.

**Pull request merged**
