### PR TITLE
Admin - Limit page route authorization

### LINKED ISSUE #2635: Pages and routes are hidden until logged in as admin
## Screenshot: Prototype
[![screenshot][screenshot]][figma]
<sup>[Click screenshot to visit Figma.][figma]</sup>

## Acceptance Criteria
- [ ] When you first arrive at /admin without being logged in, you see this Placeholder Home page, and no other routes are visible in the menu.
- [ ] #2712
- [ ] If you are not logged in, or do not have the Admin role, the side menu should should show only the Home link (regardless of what page you're on).
- [ ] If you you are logged in but do not have the Admin role, and navigate directly to another admin url, you should see 403 Not Authorized instead of normal content.

   [screenshot]: https://user-images.githubusercontent.com/305339/166573611-d5dd4db1-fe9e-477f-82af-441ff8085355.png
   [figma]: https://www.figma.com/proto/XS4Ag6GWcgdq2dBlLzBkay/Admin-v3?node-id=410%3A1984&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=410%3A1984&hide-ui=1

### PR DESCRIPTION
**Pull request by mnigh**
Resolves #2635.

- Adds NotAuthorized component
- Adds getMe graphQL query
- Adds AuthorizationContainer component
- Adds missing key prop to LoginOrLogout button
- Updates PoolDashboard, Dashboard component to limit access based on logged in status and presence of ADMIN role for a logged in user
- Wraps ClientProvider, AuthorizationContainer components around PoolDashboard
- Moves PoolListApi query from Dashboard to PoolDashboard component

### CODE REVIEW

**Comment by vd1992** [comment]
- checked out branch
- refreshed /auth
- refreshed /api
- codegen + run dev in /admin

The side menu is unchanged, did I miss a step?
image

**Comment by vd1992** [comment]
If I run the new admin query on graphQL playground, and the results after it
```
query getMe {
  me {
    roles
  }
}
```
```
{
  "data": {
    "me": {
      "roles": [
        "ADMIN"
      ]
    }
  }
}
```

I think it is messing with this code segment here
https://github.com/GCTC-NTGC/gc-digital-talent/pull/2714/files#diff-d7de5d4cb56b4534bf820fd096dab6c9fad992aa7ef0474785c72ce99fe8ce04R12-R26

**Review by esizer — APPROVED** [review]
Looks to be working well for me. 👍 

Tested the following scenarios:

- See all items when logged in
- Logout and only Home and Login appear
- While logged out navigated to some admin paths and got unauthorized message

**Comment by esizer** [comment]
> If I run the new admin query on graphQL playground, and the results after it
> 
> ```
> query getMe {
>   me {
>     roles
>   }
> }
> ```
> 
> ```
> {
>   "data": {
>     "me": {
>       "roles": [
>         "ADMIN"
>       ]
>     }
>   }
> }
> ```
> 
> I think it is messing with this code segment here https://github.com/GCTC-NTGC/gc-digital-talent/pull/2714/files#diff-d7de5d4cb56b4534bf820fd096dab6c9fad992aa7ef0474785c72ce99fe8ce04R12-R26

I would check to make sure `AUTH_DEFAULT_USER` is not set in the `/api/.env` file. This causes confusion since the api thinks you are logged in but the frontend does not.

**Pull request merged**
