### PR TITLE
[Debt] Upgrade turborepo

### LINKED ISSUE #10607: ♻️ Upgrade turborepo to 2.0
## ♻️ Debt/Refactor

A new version of turborepo has been released with breaking changes.

## 🙋‍♀️ Proposed Solution

Follow the [upgrade guide](https://turbo.build/repo/docs/crafting-your-repository/upgrading#upgrading-to-20).

## ✅ Acceptance Criteria

- [ ] Turborepo is on `^2.0.0`
- [ ] All scripts continue to function as expected

### PR DESCRIPTION
**Pull request by esizer**
🤖 Resolves #10607 

## 👋 Introduction

Upgrades turborepo to v2.

## 🧪 Testing

1. Install deps `pnpm i`
2. Run each script in the root `package.json` that uses `turbo`
3. Confirm they function as expected

### CODE REVIEW

**Comment by petertgiles** [comment]
Any idea what's up with the Playwright workflow?

**Comment by petertgiles** [comment]
Is there any way we can force the other GH workflows to run on this PR?

**Comment by mnigh** [comment]
> Any idea what's up with the Playwright workflow?

Not sure why the cache is suddenly an issue on this PR (this action is used in a bunch of other github workflows we have as well) but maybe the value needs to be quoted?

https://github.com/actions/setup-node#:~:text=version%3A%2020-,cache%3A%20%27npm%27,-%2D%20run%3A

vs.

https://github.com/GCTC-NTGC/gc-digital-talent/blob/0c64cc41ec69093c87d7b40112b1748bbdf27152/.github/workflows/playwright.yml#L63

**Review by petertgiles — CHANGES_REQUESTED** [review]
Works great!  I built it in Azure, too.  I'll approve when I feel a little better about the GH workflows.

**Review by petertgiles — APPROVED** [review]

**Pull request merged**
