### PR TITLE
a11y - 4247 - Remove nested h2

### LINKED ISSUE #4247: Edit Pool Page - h2 cannot be a child of h2
image

### PR DESCRIPTION
**Pull request by esizer**
Resolves #4247 

## Summary

This removes the nested `<h2> elements on the `EditPool` page.

## Testing

1. Build admin `npm run production --workspace=admin`
2. Navigate to a pool `/admin/pools/{poolId}/edit`
3. Confirm there are no nested `<h2>` elements or errors in the console

### CODE REVIEW

**Comment by vd1992** [comment]
are the font changes desired per Storybook?
https://www.chromatic.com/build?appId=61e099a1bb1465003a73d3ce&number=3493

**Review by vd1992 — COMMENTED** [review]
are the font changes desired per Storybook?
https://www.chromatic.com/build?appId=61e099a1bb1465003a73d3ce&number=3493

**Comment by esizer** [comment]
> are the font changes desired per Storybook?

I think so but I'm not certain. It is now using the styles defined in the `Heading` component where before it was using browser defaults.

@JoshBeveridge should these styles be updated or are they the correct ones? I think what is happening is that even though they are supposed to structurally be `<h2>` we want to present them as `<h3>`, am I correct in that assumption?

https://github.com/GCTC-NTGC/gc-digital-talent/blob/8b55555169f629bc9a8001ec5384291d52f448f2/frontend/common/src/components/Heading/styles.ts#L8-L12

**Comment by JoshBeveridge** [comment]
@esizer Yeah, this happens in a handful of places, because the default font size of the pertinent heading might be too visually overwhelming for the context, despite the semantics requiring that level.

**Review by tristan-orourke — APPROVED** [review]
LGTM

**Pull request merged**
