### PR TITLE
[Dependency] Updates Storybook to version 7

### LINKED ISSUE #6185: ✨ Dependency - Storybook 7
## ✨ Feature

Storybook 7 has been released and is now in a stable version.

## 🕵️ Details

- [Migration Guide](https://storybook.js.org/docs/react/migration-guide)
- [Migration Docs](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#from-version-65x-to-700)

## 🙋‍♀️ Proposed Implementation

1. Manually upgrade storybook and its related packages from version 6 to 7.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] ensure storybook stories run without errors
- [ ] ensure Chromatic runs without errors

## 🚫 Blockers
- [x] ~~https://github.com/truffls/storybook-addon-intl/issues/118~~

### PR DESCRIPTION
**Pull request by mnigh**
🤖 Resolves #6185, #1361.

## 👋 Introduction

This PR updates Storybook to version 7, including related addons.

## 🕵️ Details

There are a few additional updates and fixes in this PR including some naming errors that were flagged as part of the upgrade process.

### MERGE_STORYBOOKS
The unused `MERGE_STORYBOOKS` variable was removed (eebaa5a80cbe8855913089731dbd2362e00d0b3a) that actual usage was removed as part of #5528:

https://github.com/GCTC-NTGC/gc-digital-talent/blob/4c86682ba060b37a73dbc1f4f34bc28110bae82e/frontend/admin/.storybook/main.js#L26-L37

### TypeScript
Because Cypress is still [incompatible with TypeScript version 5](https://github.com/cypress-io/cypress/issues/26203), I have pinned it to version 4.

## 🚫 Blockers

- [x] ~~`storybook-addon-intl` package: https://github.com/truffls/storybook-addon-intl/issues/113#issuecomment-1497090688~~

## 🧪 Testing

Assist reviewers with steps they can take to test that the PR does what it says it does.

1. `npm i`
2. `npm run storybook`
3. Ensure storybook stories and documentation still works

### CODE REVIEW

**Comment by petertgiles** [comment]
> Any ideas @GCTC-NTGC/developers?

I guess it goes back in the backlog.  :shrug:

**Comment by mnigh** [comment]
Now being blocked by [webpack](https://github.com/webpack/webpack/issues/17264).

**Comment by vd1992** [comment]
> Now being blocked by [webpack](https://github.com/webpack/webpack/issues/17264).

The hurdles never end! At least that one should probably be resolved by the end of today.

**Comment by vd1992** [comment]
All the failures appear to be

image

huh

**Comment by vd1992** [comment]
locked react-accordion to 1.1.1, it was varying

**Comment by esizer** [comment]
Do not ask me why this error just started appearing on this PR, but it has to do with us implementing empty `Accordion.Root`'s 

https://github.com/radix-ui/primitives/blob/333eaf790a294c3af6092f2dcf870f27092d2a57/packages/react/context/src/createContext.tsx#L72

**Comment by vd1992** [comment]
> Do not ask me why this error just started appearing on this PR, but it has to do with us implementing empty `Accordion.Root`'s
> 
> https://github.com/radix-ui/primitives/blob/333eaf790a294c3af6092f2dcf870f27092d2a57/packages/react/context/src/createContext.tsx#L72

react-accordion 1.1.2 feature maybe 🤷‍♂️

**Comment by vd1992** [comment]
E2E ✅ 
Storybook runs locally ✅ 
Chromatic deployment ✅ 

It seems to... all be good? Reached the 🏁 ?

**Review by brindasasi — APPROVED** [review]
Storybook works fine to me. Well done!

**Comment by mnigh** [comment]
> Storybook works fine to me. Well done!

@brindasasi Can you [approve the UI Review](https://www.chromatic.com/review?appId=61e099a1bb1465003a73d3ce&number=6259&type=linked) as well?

**Comment by brindasasi** [comment]
@mnigh , @vd1992  could you please update this branch with latest? I see some UI discrepancies likely unrelated to this PR

**Comment by brindasasi** [comment]
LGTM! 🥳

**Pull request merged**
