### PR TITLE
Bug - 3824 - Table print warn no selection

### LINKED ISSUE #3824: Print link on users table shows "hand" icon even though link is disabled
CSV link behaves correctly though.

In UAT:

Acceptance Criteria:
- [ ] Remove "disabled" attribute from link (in all scenarios)
- [ ] If no rows are selected and the link is click, put up a toast notification (see text below) and do nothing else.
- [ ] Update the link to say "Download Profiles" "Télécharger les profils" instead of "Print"

English:
"No users selected"
French:
"Aucun utilisateur sélectionné"

### PR DESCRIPTION
**Pull request by esizer**
## 👋 Introduction

This updates the print button on the api table to show a toast when a user attempts to print with no rows selected. Also, it updates the font weight to match the CSV link.

## 📋 TO DO

- [x] Send off new text for translation
- [x] Add translations

## 🧪 Testing

1. Build admin `npm run production --workspace=admin`
2. Navigate to the users table
3. Click "print" in the footer without selecting rows
4. Confirm toast appears with error message
5. Select from rows and attempt to print again
6. Confirm print window appears

## 🤖 Robot Stuff

Resolves #3824

### CODE REVIEW

**Review by JamesHuf — CHANGES_REQUESTED** [review]
It looks like the copy on the link is supposed to be updated to "Download Profiles"/"Télécharger les profils".
Also the copy on the toast is somewhat different from what is provided in the issue.

**Comment by esizer** [comment]
> It looks like the copy on the link is supposed to be updated to "Download Profiles"/"Télécharger les profils".
> Also the copy on the toast is somewhat different from what is provided in the issue.

Good catch! Updated in [update copy](https://github.com/GCTC-NTGC/gc-digital-talent/pull/4907/commits/080e149e6670b0e1a6366bcfe99476b89cf07b39)

In regards to the toast copy, I spoke with @Jerryescandon this morning about the change so we could add a bit more context to the actual error.

**Review by JamesHuf — APPROVED** [review]
Works for me! 🚀

**Comment by vd1992** [comment]
Saw the Cypress failed for the same reason as one of my runs earlier
Seems like my merge #4900 earlier introduced an edge case bug 😭 

where if there is only one pool present, the stream selection changes nothing and doesn't send a graphQL request 
so it is the marked bit below, should that line just get deleted or what?

image

**Pull request merged**
