### PR TITLE
[Debt] Bump mock auth for rotating refresh tokens

### LINKED ISSUE #9538: ♻️ Bump Mock Auth to set refresh token rotation
## ♻️ Debt/Refactor

The Mock Auth team has added an option to rotate refresh tokens.  When it is added to a release let's get it and set the option.

## 🕵️ Details

https://github.com/navikt/mock-oauth2-server/pull/645

## ✅ Acceptance Criteria

- [ ] Mock Auth is bumped to the version including the token rotation option
- [ ] Our container config sets the option

Blocked until Mock Auth creates a release with the PR included and the docker container is available.

### PR DESCRIPTION
**Pull request by esizer**
🤖 Resolves #9538 

## 👋 Introduction

Bumps the mock auth container to set the rotating refresh tokens.

## 🧪 Testing

1. Rebuild docker container `make down` then `make up`
2. Confirm mock auth functions
3. Confirm refresh tokens work still

### CODE REVIEW

**Review by yonikid15 — APPROVED** [review]
LGTM :+1: 
The playwright test :cry:

**Review by yonikid15 — APPROVED** [review]
Looks good Eric :+1:  tokens are working as expected
(Sorry missed this yesterday)

**Review by petertgiles — APPROVED** [review]
Seems good.  I can't get "Can submit application" in applicant/application.spec.ts to pass locally but it does in CI, so :shrug: .

**Comment by esizer** [comment]
> I can't get "Can submit application" in applicant/application.spec.ts to pass locally but it does in CI, so 🤷 .

The age old problem 😛

**Pull request merged**
