### PR TITLE
My Status section #1910

### LINKED ISSUE #1910: My Status section
# Description
The My Status section contains a form with a single radio input. Changing the selection should immediately submit the form.

If the applicant profile doesn't have all required fields filled out, disable the input and show the "Why can't I change my status?" block.

QUESTION: where should we determine whether the profile is "complete"? - lets do this overall complete check on the backend

[Wireframe](https://www.figma.com/proto/PrvXEDac0HVp7dF7SLWVFm/Candidate-profile-interfaces---V5.0.0?node-id=2340%3A4185&starting-point-node-id=1%3A2)

# Acceptance Criteria
- [x] Storybook
- [x] Graphql operations
- [x] Wrapper component that gets and submits data to API
- [x] Jest test for:
   - [x] inputs disabled if application not complete, enabled otherwise
   - [x] Why can I change my status appears if application not complete, hidden otherwise
   - [x] submit handler called whenever radio selection changes

### PR DESCRIPTION
**Pull request by RVany**
Resolves #1910 
# Description
The My Status section contains a form with a single radio input. Changing the selection should immediately submit the form.

If the applicant profile doesn't have all required fields filled out, disable the input and show the "Why can't I change my status?" block.

QUESTION: where should we determine whether the profile is "complete"? - lets do this overall complete check on the backend

[Wireframe](https://www.figma.com/proto/PrvXEDac0HVp7dF7SLWVFm/Candidate-profile-interfaces---V5.0.0?node-id=2340%3A4185&starting-point-node-id=1%3A2)

# Acceptance Criteria
- [x] Storybook
- [x] Graphql operations
- [x] Wrapper component that gets and submits data to API
- [x] Jest test for:
   - [x] inputs disabled if application not complete, enabled otherwise
   - [x] Why can I change my status appears if application not complete, hidden otherwise
   - [x] submit handler called whenever radio selection changes

### CODE REVIEW

**Comment by vd1992** [comment]
Did you write the component file in lower case and then try and change it later? Cause if so, that might be the cause of the problems, case changes sometimes aren't picked up well. Especially on Windows. 
The imports are looking for `MyStatusForm`
The GraphQL file capitalization doesn't matter much though. 

image

**Comment by RVany** [comment]
> 



> Did you write the component file in lower case and then try and change it later? Cause if so, that might be the cause of the problems, case changes sometimes aren't picked up well. Especially on Windows. The imports are looking for `MyStatusForm` The GraphQL file capitalization doesn't matter much though.
> 
> image

Really? I will try that. Thank you! @vd1992

**Comment by RVany** [comment]
@vd1992 So, what is the naming convention we are using for folders and filenames? Most of the files are PascalCase but folders are mixed with PascalCase and camelCase. I am just talking inside the src folders of all the sub projects.

**Comment by petertgiles** [comment]
You've got 50 changed files in the PR but I think most are unrelated to this change.  It looks like you accidentally deleted and modified a bunch of unrelated files in commit 35956939df0c912ee9ae790b37a6428cc21c53f3.  If your actual change involves just a few files might it be easier to copy to those files into a fresh branch and make a new PR with that?

**Comment by RVany** [comment]
> You've got 50 changed files in the PR but I think most are unrelated to this change. It looks like you accidentally deleted and modified a bunch of unrelated files in commit [3595693](https://github.com/GCTC-NTGC/gc-digital-talent/commit/35956939df0c912ee9ae790b37a6428cc21c53f3). If your actual change involves just a few files might it be easier to copy to those files into a fresh branch and make a new PR with that?

I think it because I completely remove the git and add again to solve file name change problem.  I will create a new branch and PR then.

**Comment by RVany** [comment]
New PR created!

**Pull request closed without merging**
