### PR TITLE
Bug - 2828 -  IAP mobile homepage

### LINKED ISSUE #2828: Mobile view bugs on IAP
Mobile view bugs: 

Section 1, Block 1
- [x] increase size of feather (green)
- [x] ensure that copy is not overlapping any elements (orange)
- [ ] remove the border/drop shadow on the image (pink)

Screen Shot 2022-05-20 at 9 40 44 AM

Section 1, Block 2 
- [x] shift background rings to the right so there is no text overlap 
- [x] increase the size of the gloves (orange)
- [x] ensure that the copy is not overlapping any elements (pink)
- [x] ensure that the buttons are using the correct font (green)

Screen Shot 2022-05-20 at 9 44 16 AM

Section 1, Block 3
- [x] shift ulu down and to the right (pink arrow) 
- [x] ensure that the button is using the correct font (desktop/moblie body copy) 

Screen Shot 2022-05-20 at 9 46 25 AM

Final section call out box 
- [x] decrease size of the logo to fit the green circle 

Screen Shot 2022-05-20 at 9 48 06 AM

_Originally posted by @BrookeCameron in https://github.com/GCTC-NTGC/gc-digital-talent/issues/2807#issuecomment-1133024002_

### PR DESCRIPTION
**Pull request by esizer**
Resolves #2828  and #2860

## Summary

This fixes some notable bugs on the mobile view for the IAP homepage.

## Note

This is being sent to @BrookeCameron for initial review before we are ready for a code review.

## Links

The following are the links to the updated storybooks.

- [English](https://61e099a1bb1465003a73d3ce-tskrizrnui.chromatic.com/iframe.html?id=indigenous-apprenticeship-home-page--english-home-story&viewMode=story)
- [French](https://61e099a1bb1465003a73d3ce-tskrizrnui.chromatic.com/iframe.html?id=indigenous-apprenticeship-home-page--french-home-story&viewMode=story)

## To Do

- [x]  increase size of feather - [adjust feather size, placement](https://github.com/GCTC-NTGC/gc-digital-talent/commit/cebfeae420db70bf141811d130c413d5e919e790)
- [x] remove the border/drop shadow on the image
- [x] ensure that copy is not overlapping any elements - [adjust gloves + circles placement](https://github.com/GCTC-NTGC/gc-digital-talent/commit/dd18dcef4561f5f089b4580b87d9107be09bbd67)
- [x] increase the size of the gloves - [adjust gloves + circles placement](https://github.com/GCTC-NTGC/gc-digital-talent/commit/dd18dcef4561f5f089b4580b87d9107be09bbd67)
- [x] ensure that the buttons are using the correct font - [fix button font family](https://github.com/GCTC-NTGC/gc-digital-talent/commit/50b68609ba1d5dd5df513460bab458abbb4420a9)
- [x] shift ulu down and to the right - [adjust ulu position](https://github.com/GCTC-NTGC/gc-digital-talent/commit/e4780e800c0979ccb1230004640be5c9ce1548fa)
- [x] decrease size of the logo - [adjust icon size on talent portal section](https://github.com/GCTC-NTGC/gc-digital-talent/commit/f19c3af4c1daecd801296edcca1a8c60c003a442)
- [x] Add tagline to FR logo - [add tagline to FR logo](https://github.com/GCTC-NTGC/gc-digital-talent/pull/2897/commits/8f1c769c07819d5459604d9de3c6d5fb5339c43c)

## Screenshot

 - [French Screenshot](https://user-images.githubusercontent.com/4127998/171456602-e4b6fc25-fef3-47d9-9678-f165282d4a39.jpg)
 - [English Screenshot](https://user-images.githubusercontent.com/4127998/171456604-1eca3c0e-39b5-4f8d-8eab-70098eae3e12.jpg)

### CODE REVIEW

**Comment by esizer** [comment]
> did you roll #2860 into this?

Yeah, looks like it did not connect properly. Should be fixed now!

**Comment by patcon** [comment]
Oops, @esizer I accidentally hit the "Update branch" button on your PR, when I meant to ask whether you could do it...! You'll need to pull the merge commit locally before adding more. (`git pull origin --rebase` if you already have local commits)

**Comment by esizer** [comment]
> Oops, @esizer I accidentally hit the "Update branch" button on your PR, when I meant to ask whether you could do it...! You'll need to pull the merge commit locally before adding more. (`git pull origin --rebase` if you already have local commits)

Thanks for the heads up! Luckily I do not have anything locally right now :)

**Review by petertgiles — APPROVED** [review]
From a dev perspective, it looks lovely. :grinning:

**Pull request merged**
