### PR TITLE
Regenerate package-lock.json

### LINKED ISSUE #2695: dependabot stopped working (frontend package-lock.json malformed)
@esizer was working on this pre-ticket

we're not seeing any updates to dependabot, even though it monday. something is wrong. DEPENDABOT NEEDS OUR HELP

- dependabot.yml is working fine
- encountering issue parsing frontend/package-lock.json
  - logs here: https://github.com/GCTC-NTGC/gc-digital-talent/network/updates

<details>
<summary>Click to view log...</summary>

```
  proxy | time="2022-05-09T02:10:34Z" level=info msg="proxy starting" commit=d0e8fc9c52e08bf359a8a4cff6deb91b01c23136
  proxy | 2022/05/09 02:10:34 Listening (:1080)
updater | 2022-05-09T02:10:34.981124974 [anonymous-instance:main:WARN:src/firecracker/src/main.rs:370] You are using a deprecated parameter: --seccomp-level 2, that will be removed in a future version.
updater | 2022-05-09T02:10:35.054594528 [361998685:main:WARN:src/devices/src/legacy/serial.rs:432] Detached the serial input due to peer close/error.
updater | time="2022-05-09T02:10:38Z" level=info msg="guest starting" commit=d54c1f07420d2f98b700854f969f92bffb6a9ded
updater | time="2022-05-09T02:10:38Z" level=info msg="starting job..." fetcher_timeout=5m0s job_id=361998685 updater_timeout=45m0s updater_version=0.184.0-90a199ddb668cf5d41b3b630375b1d042908b04b
updater | I, [2022-05-09T02:10:42.171435 #7]  INFO -- sentry: ** [Raven] Raven 3.1.2 ready to catch errors
updater | warning: parser/current is loading parser/ruby27, which recognizes2.7.6-compliant syntax, but you are running 2.7.5.
updater | Please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
updater | INFO <job_361998685> Starting job processing
  proxy | 2022/05/09 02:10:48 [002] GET https://api.github.com:443/repos/GCTC-NTGC/gc-digital-talent
  proxy | 2022/05/09 02:10:48 [002] * authenticating github api request
  proxy | 2022/05/09 02:10:48 [002] 200 https://api.github.com:443/repos/GCTC-NTGC/gc-digital-talent
  proxy | 2022/05/09 02:10:48 [004] GET https://api.github.com:443/repos/GCTC-NTGC/gc-digital-talent/git/refs/heads/main
  proxy | 2022/05/09 02:10:48 [004] * authenticating github api request
  proxy | 2022/05/09 02:10:48 [004] 200 https://api.github.com:443/repos/GCTC-NTGC/gc-digital-talent/git/refs/heads/main
  proxy | 2022/05/09 02:10:48 [006] GET https://api.github.com:443/repos/GCTC-NTGC/gc-digital-talent/contents/frontend/package.json?ref=c40bfaf8d9a397ed9f2e68fe1e1ab55093ee51db
  proxy | 2022/05/09 02:10:48 [006] * authenticating github api request
  proxy | 2022/05/09 02:10:48 [006] 200 https://api.github.com:443/repos/GCTC-NTGC/gc-digital-talent/contents/frontend/package.json?ref=c40bfaf8d9a397ed9f2e68fe1e1ab55093ee51db
  proxy | 2022/05/09 02:10:48 [008] GET https://api.github.com:443/repos/GCTC-NTGC/gc-digital-talent/contents/frontend?ref=c40bfaf8d9a397ed9f2e68fe1e1ab55093ee51db
  proxy | 2022/05/09 02:10:48 [008] * authenticating github api request
  proxy | 2022/05/09 02:10:48 [008] 200 https://api.github.com:443/repos/GCTC-NTGC/gc-digital-talent/contents/frontend?ref=c40bfaf8d9a397ed9f2e68fe1e1ab55093ee51db
  proxy | 2022/05/09 02:10:48 [010] GET https://api.github.com:443/repos/GCTC-NTGC/gc-digital-talent/contents/frontend/package-lock.json?ref=c40bfaf8d9a397ed9f2e68fe1e1ab55093ee51db
  proxy | 2022/05/09 02:10:48 [010] * authenticating github api request
  proxy | 2022/05/09 02:10:48 [010] 200 https://api.github.com:443/repos/GCTC-NTGC/gc-digital-talent/contents/frontend/package-lock.json?ref=c40bfaf8d9a397ed9f2e68fe1e1ab55093ee51db
  proxy | 2022/05/09 02:10:48 [012] GET https://api.github.com:443/repos/GCTC-NTGC/gc-digital-talent/contents/.npmrc?ref=c40bfaf8d9a397ed9f2e68fe1e1ab55093ee51db
  proxy | 2022/05/09 02:10:48 [012] * authenticating github api request
  proxy | 2022/05/09 02:10:49 [012] 404 https://api.github.com:443/repos/GCTC-NTGC/gc-digital-talent/contents/.npmrc?ref=c40bfaf8d9a397ed9f2e68fe1e1ab55093ee51db
  proxy | 2022/05/09 02:10:49 [014] GET https://api.github.com:443/repos/GCTC-NTGC/gc-digital-talent/contents/.npmrc?ref=c40bfaf8d9a397ed9f2e68fe1e1ab55093ee51db
  proxy | 2022/05/09 02:10:49 [014] * authenticating github api request
  proxy | 2022/05/09 02:10:49 [014] 404 https://api.github.com:443/repos/GCTC-NTGC/gc-digital-talent/contents/.npmrc?ref=c40bfaf8d9a397ed9f2e68fe1e1ab55093ee51db
  proxy | 2022/05/09 02:10:49 [016] GET https://api.github.com:443/repos/GCTC-NTGC/gc-digital-talent/contents/.npmrc?ref=c40bfaf8d9a397ed9f2e68fe1e1ab55093ee51db
  proxy | 2022/05/09 02:10:49 [016] * authenticating github api request
  proxy | 2022/05/09 02:10:49 [016] 404 https://api.github.com:443/repos/GCTC-NTGC/gc-digital-talent/contents/.npmrc?ref=c40bfaf8d9a397ed9f2e68fe1e1ab55093ee51db
  proxy | 2022/05/09 02:10:49 [018] GET https://api.github.com:443/repos/GCTC-NTGC/gc-digital-talent/contents/.npmrc?ref=c40bfaf8d9a397ed9f2e68fe1e1ab55093ee51db
  proxy | 2022/05/09 02:10:49 [018] * authenticating github api request
  proxy | 2022/05/09 02:10:49 [018] 404 https://api.github.com:443/repos/GCTC-NTGC/gc-digital-talent/contents/.npmrc?ref=c40bfaf8d9a397ed9f2e68fe1e1ab55093ee51db
  proxy | 2022/05/09 02:10:49 [020] GET https://api.github.com:443/repos/GCTC-NTGC/gc-digital-talent/contents/.yarnrc?ref=c40bfaf8d9a397ed9f2e68fe1e1ab55093ee51db
  proxy | 2022/05/09 02:10:49 [020] * authenticating github api request
  proxy | 2022/05/09 02:10:49 [020] 404 https://api.github.com:443/repos/GCTC-NTGC/gc-digital-talent/contents/.yarnrc?ref=c40bfaf8d9a397ed9f2e68fe1e1ab55093ee51db
  proxy | 2022/05/09 02:10:49 [022] GET https://api.github.com:443/repos/GCTC-NTGC/gc-digital-talent/contents/.yarnrc?ref=c40bfaf8d9a397ed9f2e68fe1e1ab55093ee51db
  proxy | 2022/05/09 02:10:49 [022] * authenticating github api request
  proxy | 2022/05/09 02:10:49 [022] 404 https://api.github.com:443/repos/GCTC-NTGC/gc-digital-talent/contents/.yarnrc?ref=c40bfaf8d9a397ed9f2e68fe1e1ab55093ee51db
  proxy | 2022/05/09 02:10:49 [024] GET https://api.github.com:443/repos/GCTC-NTGC/gc-digital-talent/contents/frontend/admin/package.json?ref=c40bfaf8d9a397ed9f2e68fe1e1ab55093ee51db
  proxy | 2022/05/09 02:10:49 [024] * authenticating github api request
  proxy | 2022/05/09 02:10:49 [024] 200 https://api.github.com:443/repos/GCTC-NTGC/gc-digital-talent/contents/frontend/admin/package.json?ref=c40bfaf8d9a397ed9f2e68fe1e1ab55093ee51db
  proxy | 2022/05/09 02:10:49 [026] GET https://api.github.com:443/repos/GCTC-NTGC/gc-digital-talent/contents/frontend/common/package.json?ref=c40bfaf8d9a397ed9f2e68fe1e1ab55093ee51db
  proxy | 2022/05/09 02:10:49 [026] * authenticating github api request
  proxy | 2022/05/09 02:10:49 [026] 200 https://api.github.com:443/repos/GCTC-NTGC/gc-digital-talent/contents/frontend/common/package.json?ref=c40bfaf8d9a397ed9f2e68fe1e1ab55093ee51db
  proxy | 2022/05/09 02:10:49 [028] GET https://api.github.com:443/repos/GCTC-NTGC/gc-digital-talent/contents/frontend/talentsearch/package.json?ref=c40bfaf8d9a397ed9f2e68fe1e1ab55093ee51db
  proxy | 2022/05/09 02:10:49 [028] * authenticating github api request
  proxy | 2022/05/09 02:10:50 [028] 200 https://api.github.com:443/repos/GCTC-NTGC/gc-digital-talent/contents/frontend/talentsearch/package.json?ref=c40bfaf8d9a397ed9f2e68fe1e1ab55093ee51db
  proxy | 2022/05/09 02:10:50 [030] GET https://api.github.com:443/repos/GCTC-NTGC/gc-digital-talent/contents/frontend/indigenousapprenticeship/package.json?ref=c40bfaf8d9a397ed9f2e68fe1e1ab55093ee51db
  proxy | 2022/05/09 02:10:50 [030] * authenticating github api request
  proxy | 2022/05/09 02:10:50 [030] 200 https://api.github.com:443/repos/GCTC-NTGC/gc-digital-talent/contents/frontend/indigenousapprenticeship/package.json?ref=c40bfaf8d9a397ed9f2e68fe1e1ab55093ee51db
updater | INFO <job_361998685> Finished job processing
updater | time="2022-05-09T02:10:50Z" level=info msg="task complete" container_id=job-361998685-file-fetcher exit_code=0 job_id=361998685 step=fetcher
updater | I, [2022-05-09T02:10:51.520148 #7]  INFO -- sentry: ** [Raven] Raven 3.1.2 ready to catch errors
updater | warning: parser/current is loading parser/ruby27, which recognizes2.7.6-compliant syntax, but you are running 2.7.5.
updater | Please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
updater | INFO <job_361998685> Starting job processing
updater | INFO <job_361998685> Starting update job for GCTC-NTGC/gc-digital-talent
updater | INFO <job_361998685> Finished job processing
updater | INFO Results:
updater | Dependabot encountered '1' error(s) during execution, please check the logs for more details.
updater | time="2022-05-09T02:10:53Z" level=info msg="task complete" container_id=job-361998685-updater exit_code=0 job_id=361998685 step=updater
```

</details>

### PR DESCRIPTION
**Pull request by esizer**
## Summary

It seems there was something wrong in our `package-lock.json` file that lead to dependabot not being able to parse it. This PR simply deleted and recreated the `package-lock.json` file and tested on a fork successfully.

Screen Shot 2022-05-09 at 1 25 42 PM

Resolves #2695

### CODE REVIEW

**Comment by vd1992** [comment]
if they are not guaranteed to exist, are we left with no choice but to ignore it then?

**Comment by esizer** [comment]
> I am a bit concerned that the subsequent commits may have re-broken the dependabot, is there anyway to check? Like stealing this branch for your fork?

I did check against my fork. You can check to confirm by:

1. Forking the repo
2. Merge this branch into your forked `main` branch
3. Navigating to **Insights > Dependancy Graph > Dependabot**
4. Run the `/frontend/package.json` check

**Review by vd1992 — APPROVED** [review]
Forked this repo, pulled this branch

image

Enabled and waited on Dependabot, executes successfully 

image

all good i think!

**Comment by esizer** [comment]
> Forked this repo, pulled this branch
> 
> image
> 
> Enabled and waited on Dependabot, executes successfully
> 
> image
> 
> all good i think!

Perfect! Merged and check is running now!

**Pull request merged**
