### PR TITLE
Remove `npm rebuild node-sass`

### LINKED ISSUE #2452: Remove sass workaround
In [our build readme](https://github.com/GCTC-NTGC/gc-digital-talent/tree/main/frontend/talentsearch#getting-started) we have this text:

After the node packages are installed, run npm rebuild node-sass incase vendor folder isn't created. (Error: sass/node-sass#1579).

Do we still need this workaround?  The linked issue appears to have been closed years ago?  Can we remove it from the setup scripts?

### PR DESCRIPTION
**Pull request by mnigh**
Resolves #2452.

### Note
The node-sass package is not referenced anywhere in our files nor does it appear anywhere in our dependency tree.

### Steps to Test
1. Refresh [all of the projects](https://github.com/GCTC-NTGC/gc-digital-talent/blob/main/maintenance/README.md#environment-maintenance) by running `docker-compose run --rm maintenance bash refresh_all.sh`
2. Search for **node-sass** in all files

### CODE REVIEW

**Review by petertgiles — APPROVED** [review]
Very nice!  Works for me on linux.

**Review by patcon — APPROVED** [review]
you're right, not used anymore! good catch

**Review by vd1992 — APPROVED** [review]
Ran and no node-sass issues
Only matter was how docker refresh messes up my node modules but that is unrelated

**Comment by mnigh** [comment]
> Only matter was how docker refresh messes up my node modules but that is unrelated

@vd1992 Are you sure that is unrelated? Did it mess up your node modules before this PR?

**Comment by vd1992** [comment]
> > Only matter was how docker refresh messes up my node modules but that is unrelated
> 
> @vd1992 Are you sure that is unrelated? Did it mess up your node modules before this PR?

yep, not a new thing

**Pull request merged**
