### PR TITLE
Create azure-pipelines.noop.yml

### PR DESCRIPTION
**Pull request by patcon**
Related to https://github.com/GCTC-NTGC/gc-digital-talent/issues/1843

As per conversation with @tristan-orourke, this file is a first step to getting our deploy process into version control.

This file is just a placeholder, and the comments and filename will be update if/when the file becomes the actual source of truth (rather than just a copy of the UI settings).

## Candidate To Dos
- [x] copy step YML from Azure UI
- [x] copy boilerplate yaml from https://github.com/sign-in-canada/Acceptance-Platform/blob/main/azure-pipelines.yml
- [x] extract [macro syntax variables](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#runtime-expression-syntax) into one envvar
- [x] extract scripts into bash scripts (passing in macro vars)
- optional
    - [x] answer questions below
    - [x] ~~ensure azure is set to read yml from repo -- @tristan-orourke~~ `reticket`
        - https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#access-to-github-repositories
    - [x] test scripts -- @tristan-orourke `reticket`
- [x] ensure binaries executable
- [x] ~~consolidate htaccess files?~~ `wontdo`
- [x] ~~consolidate setup scripts~~ `wontdo`
- final touch-ups from https://github.com/GCTC-NTGC/gc-digital-talent/pull/2683#issuecomment-1120318626 and responding comments
  - [x] added security `Header` directives to _development_ `.htaccess` 7e1a13de9
  - [x] added line to _development_ `.htaccess`, to ignore serving of dist (aligning with prod `.htaccess`) 7d4c32dde
  - [x] re-arranged and merged `a2enmod` commands in dockerfile for better layer caching d5839873d
  - [x] removed remnant (already commented out) of staging server directive from _development_ `.htaccess` 9ab08f185
  - didn't touch `auth/` endpoint stuff in production `.htaccess`, as going away soon

We can always just merge it as no-op, and get it working later, in the interest of getting it in repo

### CODE REVIEW

**Comment by patcon** [comment]
Can these align any closer @tristan-orourke? Wondering if we can just add the logic into apache, and have a single config file)

```diff
--- infrastructure/php-container/src/.htaccess	2022-05-07 19:48:11.000000000 -0400
+++ infrastructure/conf/deploy.htaccess	2022-05-07 19:43:12.000000000 -0400
@@ -1,3 +1,4 @@
+# Don't automatically add slash (with 301 redirect) if path matches a directory
 DirectorySlash off
 
 <IfModule mod_rewrite.c>
@@ -6,14 +7,9 @@
     # Strip trailing slash from all urls and redirect back to public url, unless already pointing to a public folder
     RewriteCond %{REQUEST_URI} ^/(.+)/$
     RewriteCond %{REQUEST_URI} !/public/$
+    RewriteCond %{REQUEST_URI} !/dist/$
     RewriteRule ^ %{ENV:APP_URL}/%1 [L,R=301]
 
-    # Send auth requests to auth folder (only for local environments)
-    RewriteCond %{REQUEST_URI} !^auth/public/
-    RewriteRule ^auth(/(.*))?$ auth/public/$2 [L]
-
-    RewriteRule ^oauth(/(.*))?$ auth/public/$2 [L]
-
     # Rewrite api requests
     RewriteRule ^graphql-playground$ api/public/graphql-playground [L]
     RewriteRule ^graphql$ api/public/graphql [L]
@@ -37,10 +33,6 @@
     # Send localized talent requests also to talentsearch dist folder;
     RewriteRule ^(en|fr)/talent(/(.*))?$ frontend/talentsearch/dist/$3 [L]
 
-    # Indigenous Apprenticeship routes
-    RewriteRule ^indigenous-it-apprentice(/(.*))?$ frontend/indigenousapprenticeship/dist/$2 [L]
-    RewriteRule ^(en|fr)/indigenous-it-apprentice(/(.*))?$ frontend/indigenousapprenticeship/dist/$3 [L]
-
     # PHP Info page for debugging
     RewriteRule ^phpinfo.php$ phpinfo.php [L]
 
@@ -48,18 +40,14 @@
     RewriteRule ^(.*)/?$ tc-report/$1 [L]
 </IfModule>
 
-#<IfModule mod_headers.c>
-#    RequestHeader set X-Forwarded-Host "dev-talentcloud.tbs-sct.gc.ca"
-#    RequestHeader set Forwarded "host=dev-talentcloud.tbs-sct.gc.ca;proto=https"
-#</IfModule>
-
 # Security headers
-#Header add X-Content-Type-Options nosniff
-#Header add X-XSS-Protection "1; mode=block"
-#Header add  Strict-Transport-Security "max-age=31536000; includeSubdomains;"
-#Header add Cache-Control "max-age=31536000"
-#Header add Pragma no-cache
+Header add X-Content-Type-Options nosniff
+Header add X-XSS-Protection "1; mode=block"
+Header add  Strict-Transport-Security "max-age=31536000; includeSubdomains;"
+Header add Cache-Control "max-age=31536000"
+Header add Pragma no-cache
+
 # Policy headers
-#Header add Referrer-Policy "no-referrer-when-downgrade"
+Header add Referrer-Policy "no-referrer-when-downgrade"
 #Header add Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.google-analytics.com https://www.googletagmanager.com https://tagmanager.google.com https://code.jquery.com https://cdn.datatables.net https://cdnjs.cloudflare.com https://cdn.jsdelivr.net https://html2canvas.hertzen.com https://stackpath.bootstrapcdn.com; img-src 'self' data: https://www.google-analytics.com https://ssl.gstatic.com https://www.gstatic.com https://www.gravatar.com https://images.unsplash.com; style-src 'self' 'unsafe-inline' https://tagmanager.google.com https://fonts.googleapis.com https://code.ionicframework.com https://cdn.datatables.net https://stackpath.bootstrapcdn.com https://cdnjs.cloudflare.com; font-src 'self' data: https://fonts.gstatic.com https://tagmanager.google.com https://code.ionicframework.com https://stackpath.bootstrapcdn.com; frame-src 'self'; object-src 'self'; connect-src 'self' https://api.github.com https://www.google-analytics.com;"
-#Header add Feature-Policy "geolocation 'none'; midi 'none'; sync-xhr 'none'; microphone 'none'; camera 'none'; magnetometer 'none'; gyroscope 'none'; fullscreen 'self'; payment 'none';"
+Header add Feature-Policy "geolocation 'none'; midi 'none'; sync-xhr 'none'; microphone 'none'; camera 'none'; magnetometer 'none'; gyroscope 'none'; fullscreen 'self'; payment 'none';"
```

**Review by tristan-orourke — APPROVED** [review]
Let's just merge this in for now. We can connect it to azure infrastructure later.

**Comment by patcon** [comment]
> - final touch-ups from https://github.com/GCTC-NTGC/gc-digital-talent/pull/2683#issuecomment-1120318626 and responding comments
>  - [x] added security `Header` directives to _development_ `.htaccess` 7e1a13de9
>  - [x] added line to _development_ `.htaccess`, to ignore serving of dist (aligning with prod `.htaccess`) 7d4c32dde
>  - [x] re-arranged and merged `a2enmod` commands in dockerfile for better layer caching d5839873d
>  - [x] removed remnant (already commented out) of staging server directive from _development_ `.htaccess` 9ab08f185
>  - didn't touch `auth/` endpoint stuff in production `.htaccess`, as going away soon

This is now the only diff going from prod to dev `.htaccess`:

```diff
--- infrastructure/conf/deploy.htaccess	2022-05-20 16:04:01.000000000 -0400
+++ infrastructure/php-container/src/.htaccess	2022-05-20 19:05:47.000000000 -0400
@@ -1,4 +1,3 @@
-# Don't automatically add slash (with 301 redirect) if path matches a directory
 DirectorySlash off
 
 <IfModule mod_rewrite.c>
@@ -10,6 +9,12 @@
     RewriteCond %{REQUEST_URI} !/dist/$
     RewriteRule ^ %{ENV:APP_URL}/%1 [L,R=301]
 
+    # Send auth requests to auth folder (only for local environments)
+    RewriteCond %{REQUEST_URI} !^auth/public/
+    RewriteRule ^auth(/(.*))?$ auth/public/$2 [L]
+
+    RewriteRule ^oauth(/(.*))?$ auth/public/$2 [L]
+
     # Rewrite api requests
     RewriteRule ^graphql-playground$ api/public/graphql-playground [L]
     RewriteRule ^graphql$ api/public/graphql [L]
@@ -33,6 +38,10 @@
     # Send localized talent requests also to talentsearch dist folder;
     RewriteRule ^(en|fr)/talent(/(.*))?$ frontend/talentsearch/dist/$3 [L]
 
+    # Indigenous Apprenticeship routes
+    RewriteRule ^indigenous-it-apprentice(/(.*))?$ frontend/indigenousapprenticeship/dist/$2 [L]
+    RewriteRule ^(en|fr)/indigenous-it-apprentice(/(.*))?$ frontend/indigenousapprenticeship/dist/$3 [L]
+
     # PHP Info page for debugging
     RewriteRule ^phpinfo.php$ phpinfo.php [L]
 ```

**Comment by patcon** [comment]
Passing, so gonna merge as suggested!

**Pull request merged**
