### PR TITLE
Bug - Add missing translations

### PR DESCRIPTION
**Pull request by esizer**
## 👋 Introduction

This adds missing translations that were lost at some point and accidentally merged in #4761

### CODE REVIEW

**Review by mnigh — COMMENTED** [review]
i can't find `/78DsY` or `pg1S01` anywhere in the code nor their descriptions. is this PR necessary?

**Comment by esizer** [comment]
> i can't find `/78DsY` or `pg1S01` anywhere in the code nor their descriptions. is this PR necessary?

I actually don't know now 😢 . I submitted it because of this failure: https://github.com/GCTC-NTGC/gc-digital-talent/actions/runs/3593432775

**Comment by mnigh** [comment]
> > i can't find `/78DsY` or `pg1S01` anywhere in the code nor their descriptions. is this PR necessary?
> 
> I actually don't know now 😢 . I submitted it because of this failure: https://github.com/GCTC-NTGC/gc-digital-talent/actions/runs/3593432775

What happens if you remove the strings from fr.json, will it fail the **Translations / Check translations** in this PR?

**Comment by esizer** [comment]
> What happens if you remove the strings from fr.json, will it fail the **Translations / Check translations** in this PR?

So, base was somehow behind the commit that had the missing translations 😆 Updated branch with main and found them:

https://github.com/GCTC-NTGC/gc-digital-talent/blob/9ae4d1f30b185baa285de5397c284b19434b5350/frontend/common/src/components/SkillPicker/SkillPicker.tsx#L175-L187

https://github.com/GCTC-NTGC/gc-digital-talent/blob/9ae4d1f30b185baa285de5397c284b19434b5350/frontend/common/src/components/SkillPicker/SkillPicker.tsx#L270-L277

**Review by mnigh — APPROVED** [review]
French copy that was [removed](https://github.com/GCTC-NTGC/gc-digital-talent/pull/4803/commits/8822fd8efa632c1ea554bfb5d024efae94635aff) is back. 👍

**Pull request merged**
