### PR TITLE
Tooling/cypress v10 attempt

### LINKED ISSUE #4264: Upgrade cypress from v9 to v10
Re-ticketed from https://github.com/GCTC-NTGC/gc-digital-talent/pull/4209#issuecomment-1271839207

**Priority:** low (?)

v10 Migration Guide: https://docs.cypress.io/guides/references/migration-guide#Migrating-to-Cypress-version-10-0

cc @tristan-orourke confirming priority as low?

## To Do
- [ ] follow migration guide
- [ ] add ability to read env vars for feature flags  in cypress.config.js (where was set manually in cypress.json before)

### PR DESCRIPTION
**Pull request by vd1992**
closes #4264 
Upgrades Cypress to v10.11.0

things to note:
made a tsconfig file in the `/cypress` folder, still says no tsconfig file exists but things run fine
exception added due to Cypress failing tests with a `Cannot read properties of null (reading 'contentWindow')` message

testing:
???
poke around and see if anything looks off? 

command to run changed a bit (spec -> cy)
example command `npx cypress run --headed --spec "cypress/e2e/talentsearch/profile-page.cy.js"`

### CODE REVIEW

**Comment by petertgiles** [comment]
> made a tsconfig file in the `/cypress` folder, still says no tsconfig file exists but things run fine

All our Cypress code is in plain Javascript so it's probably a matter of _excluding_ this directory somehow rather than adding typescript configs for it.

**Comment by petertgiles** [comment]
For some reason the new version of Cypress didn't install for me automatically.  Probably has to do with me running `npm` in Docker.  I had to run `./node_modules/.bin/cypress install` locally to get it set up.

**Comment by vd1992** [comment]
> > made a tsconfig file in the `/cypress` folder, still says no tsconfig file exists but things run fine
> 
> All our Cypress code is in plain Javascript so it's probably a matter of _excluding_ this directory somehow rather than adding typescript configs for it.

seems to be a known annoyance reading through this issue and replies, but doesn't break things so 🤷 
https://github.com/cypress-io/cypress/issues/22273

**Comment by vd1992** [comment]
not a 100% sure where the gpu-disable would go, don't think it works in the CLI as it isn't a Cypress option
will wait a bit more to merge to see if anyone else is taking a peek

**Pull request merged**
