### PR TITLE
[Fix] Prevent attempting to verify null emails

### LINKED ISSUE #11573: 🐛 Prod logs - Null email address
## 🐛 Bug

In the prod logs I'm seeing some errors like this:
```
App\Notifications\Messages\GcNotifyEmailMessage::__construct(): Argument #2 ($emailAddress) must be of type string, null given, called in /home/site/wwwroot/api/app/Notifications/VerifyEmail.php on line 52 {"userId":"d4b21821-2a02-4acd-9934-36c2b8d32f74","exception":"[object] (TypeError(code: 0): App\\Notifications\\Messages\\GcNotifyEmailMessage::__construct(): Argument #2 ($emailAddress) must be of type string, null given, called in /home/site/wwwroot/api/app/Notifications/VerifyEmail.php on line 52 at /home/site/wwwroot/api/app/Notifications/Messages/GcNotifyEmailMessage.php:12)
```

@gobyrne here, I found this on UAT today:
Image

## 🦋 Expected Behaviour

If the email address is null then there's no point in trying to build a GcNotify message to verify the email.  The app should prevent this, at least at the mutation to request verification.

## 🕵️ Details

Reach out to Marc for additional details and to answer questions 

## 📸 Screenshot

image

## 🙋‍♀️ Proposed Solution

How is the user even trying to verify a null email address?  Is this log indicating a bug or a gap in the application?

## ✅ Acceptance Criteria

- [ ] It is not possible for a user to attempt to verify a null email address

### PR DESCRIPTION
**Pull request by esizer**
🤖 Resolves #11573 

## 👋 Introduction

Prevents users from attempting to verify null emails.

## 🕵️ Details

This is accomplished with two things:

- We hide the link to verify when the email is null on the front end
- If the user somehow gets there with a null email, we verify it exists and return an error when it does not

## 🧪 Testing

1. Login as any user
2. Confirm you have a work email set but not verified
3. Load both the profile and verify email pages
4. Manually set both work email and verified at columns in the DB to null
5. Reload both pages in step 3
6. Confirm no verify link appears on profile
7. Confirm you get error on the verify page

### CODE REVIEW

**Comment by vd1992** [comment]
I am a little confused for reviewing this, is this part of the issue? https://github.com/GCTC-NTGC/gc-digital-talent/issues/11573#issuecomment-2368965839

**Comment by esizer** [comment]
> I am a little confused to be able to review this, is this part of the issue? [#11573 (comment)](https://github.com/GCTC-NTGC/gc-digital-talent/issues/11573#issuecomment-2368965839)

We can confirm in stand-up but I believe that specific item was excluded from this until we get more information. It is not exactly the same issue so I believe we planned on splitting it off into its own issue.

**Review by petertgiles — APPROVED** [review]
Works great!  Thanks.

**Comment by petertgiles** [comment]
> I am a little confused to be able to review this, is this part of the issue? [#11573 (comment)](https://github.com/GCTC-NTGC/gc-digital-talent/issues/11573#issuecomment-2368965839)

I'd give it 50/50 that this PR solves that issue.  I'm wondering if people are expecting that clicking "verify email" on a null work email will verify their gov email address that they have set as a contact email.  If the issue does persist, hopefully it will be clearer with this fix in.

**Pull request merged**
