### PR TITLE
[Debt] Migrate pools tests to Playwright

### LINKED ISSUE #10482: ♻️ Move e2e to Playwright - pools.cy.ts
## ♻️ Debt/Refactor

Time to move our Cypress tests to Playwright
apps/e2e/cypress/e2e/admin/pools.cy.ts

## ✅ Acceptance Criteria

- [ ] Test moved to Playwright : pools.cy.ts

## 🛑 Blockers

```[tasklist]
### Blocked By
```

### PR DESCRIPTION
**Pull request by esizer**
🤖 Resolves #10482 

## 👋 Introduction

Migrates the pools test from Cypress to Playwright.

## 🕵️ Details

There were some tests that were redundant so they were removed.

- Testing certain role access was already done in `auth.spec.ts`
- Testing platform admins could access which were covered in the other tests

## 🧪 Testing

1. Confirm new test covers cases in Cypress test (minus redundant ones)
2. Confirm new tests pass

### CODE REVIEW

**Comment by mnigh** [comment]
@esizer is there any duplication between this PR and #10439? is there a need for both `process.spec.ts` and `pools.spec.ts` or could they be combined or renamed?

**Comment by esizer** [comment]
> @esizer is there any duplication between this PR and #10439? is there a need for both `process.spec.ts` and `pools.spec.ts` or could they be combined or renamed?

Oh yeah.. goo catch. I'm guessing we combine them :+1: Maybe this one should wait until that one is merged?

**Comment by esizer** [comment]
> > @esizer is there any duplication between this PR and #10439? is there a need for both `process.spec.ts` and `pools.spec.ts` or could they be combined or renamed?
> 
> Oh yeah.. goo catch. I'm guessing we combine them 👍 Maybe this one should wait until that one is merged?

@mnigh okay, it seems as though we cannot merge them because this one has to be run in serial mode since we re-use the pool created in previous steps. Since you cannot mix parallel and serial tests, they needed to be different files.

I have tried to differentiate them with a note to hopefully make it clear as to why they are separate :woman_shrugging: 

[differentiate process tests](https://github.com/GCTC-NTGC/gc-digital-talent/pull/10521/commits/12cf233a71eea8af093322ab7028b1db8423eac6)

**Comment by mnigh** [comment]
> > > @esizer is there any duplication between this PR and #10439? is there a need for both `process.spec.ts` and `pools.spec.ts` or could they be combined or renamed?
> > 
> > 
> > Oh yeah.. goo catch. I'm guessing we combine them 👍 Maybe this one should wait until that one is merged?
> 
> @mnigh okay, it seems as though we cannot merge them because this one has to be run in serial mode since we re-use the pool created in previous steps. Since you cannot mix parallel and serial tests, they needed to be different files.
> 
> I have tried to differentiate them with a note to hopefully make it clear as to why they are separate 🤷‍♀️
> 
> [differentiate process tests](https://github.com/GCTC-NTGC/gc-digital-talent/pull/10521/commits/12cf233a71eea8af093322ab7028b1db8423eac6)

Ok, but shouldn't they use the same noun if the are referring to the same model?

**Comment by esizer** [comment]
> Ok, but shouldn't they use the same noun if the are referring to the same model?

They should be now, unless I missed it somewhere?

> Ok, but shouldn't they use the same noun if the are referring to the same model?

Okay, updated the remaining uses of Pool to Process where possible in [prefer term process over pool](https://github.com/GCTC-NTGC/gc-digital-talent/pull/10521/commits/6c01bdce35c46b858684fd726e133b48a8aada77)

**Review by mnigh — APPROVED** [review]
👍 Meets the acceptance criteria. Is splitting slow test files to speed up parallel execution something that can easily be done?

## Screenshot
Screen Shot 2024-05-29 at 12 41 34

**Comment by esizer** [comment]
> 👍 Meets the acceptance criteria. Is splitting slow test files to speed up parallel execution something that can easily be done?

Uhh, yeah. The reason this one is being run in serial mode due to how it was originally written. In favour of speeding up the migration I just copied it over exactly how it was and just set it to run in serial mode. 

I created [a ticket](
https://github.com/GCTC-NTGC/gc-digital-talent/issues/10528) to update it so it can run in the default parallel mode.

**Pull request merged**
