### PR TITLE
Feature - Update support page style

### LINKED ISSUE #4456: Support page styling and cleanup
# 📖 Details
Just an issue to capture a few cleanup design items for the support page. FAQs are being omitted for now due to timelines and missing content, but will be added at a later date.

# ✅ Requirements
- Ensure the header is importing properly with the correct image
- Include the breadcrumbs
- Apply the gray background color
- Apply the background texture (@BrookeCameron has these on the way)
- Add a container to the support form
- Ensure the footer is importing properly

# 📸 Screenshot
image

### PR DESCRIPTION
**Pull request by mnigh**
Resolves #4456.

## Steps to test

1. Compile talentsearch `npm run intl-compile --workspace=talentsearch`
2. Build talentsearch `npm run production --workspace=talentsearch`
3. Navigate to **/support**
4. Verify page looks good and text makes sense
5. Verify page title, subtitle, and breadcrumbs are different in English and French (other parts of this page will be translated as part of #4115)

### CODE REVIEW

**Comment by mnigh** [comment]
Waiting on French translations for:

```
{
    defaultMessage: "Contact and support",
    id: "MZJYQd",
    description: "Page title for the Support page",
},
{
    defaultMessage: "Get in touch with us to provide feedback or report a problem.",
    id: "axQDlj",
    description: "Subtitle for the Support page",
}
```

**Comment by mnigh** [comment]
French translations:
```
{
   defaultMessage: "Contact et soutien",
   id: "MZJYQd",
   description: "Page title for the Support page",
},
{
   defaultMessage: "Contactez-nous pour nous faire part de votre rétroaction ou d'un problème.",
   id: "axQDlj",
   description: "Subtitle for the Support page",
}
```

**Review by esizer — CHANGES_REQUESTED** [review]
Very nice! 😁 

Only small nitpick would be the form submit button looks out of place with the new brand. Could be update the `<Submit />` component to use the `Color` type and change it to `"blue"`?

https://github.com/GCTC-NTGC/gc-digital-talent/blob/b0a640cf4782bc276dcb6e5d22e876ff410e9e5e/frontend/common/src/components/Button/Button.tsx#L19-L20

**Review by esizer — APPROVED** [review]
LGTM! 👍

**Pull request merged**
