### PR TITLE
Bug - 6327 - application flash of error

### LINKED ISSUE #6327: Application Revamp: Uh oh message during navigation
Not a huge thing, nor relevant to just this PR.
But, it is a little jarring, especially on slower connections, for the Uh-oh to immediately appear and then the page is updated with the steps information. (waits for the graphQL operation to complete I believe)
Worth spinning off an issue to wrap things in `<Pending/>` ?

gif

_Originally posted by @vd1992 in https://github.com/GCTC-NTGC/gc-digital-talent/issues/6296#issuecomment-1512004794_
            

## Acceptance Criteria
- [ ] Uh oh component not rendered at all during normal page navigation in the application revamp outlet

### PR DESCRIPTION
**Pull request by yonikid15**
🤖 Resolves #6327 and #6146

## 👋 Introduction

- Adds another check to `fetching` prop in the the `<Pending />` component. 
- Checks if the results from the application query is `stale`. If so, it continues loading icon until its finished fetching fresh data.

## 🧪 Testing

Assist reviewers with steps they can take to test that the PR does what it says it does.

1. Create an application.
2. Go to `/en/applications/{applicationId}/welcome`
3. Ensure you don't see the "Uh Oh" message flash before moving to the next step.

## Additional Notes

- I also tested this fix on #6296. Since it doesn't use `<ApplicationApi />` like the other steps, it's going to need to follow the same pattern.
```js
  ...

  const [
    {
      data: applicationData,
      fetching: applicationFetching,
      error: applicationError,
      stale: applicationStale, // Get stale param
    },
  ] = useGetApplicationQuery({
    requestPolicy: "cache-first", // use cache value first otherwise fallback to sending api request.
    variables: {
      id: applicationId || "",
    },
  });
 
  ...

  return (
    <Pending
      fetching={applicationFetching || applicationStale || userFetching} // add stale check
      error={applicationError || userError}
    >
      {application?.poolAdvertisement && userData?.me ? (
        <ApplicationProfile application={application} user={userData.me} />
      ) : (
        <ThrowNotFound />
      )}
    </Pending>
  );
};
```

### CODE REVIEW

**Comment by esizer** [comment]
Does this also solve https://github.com/gctc-ntgc/gc-digital-talent/issues/6146 ? I am not seeing it anymore after running `npm run dev` 🤔

**Review by esizer — APPROVED** [review]
This looks great! I'd like to see if someone else can reproduce  https://github.com/GCTC-NTGC/gc-digital-talent/issues/6146 in this branch because as far as I can tell, this also solves that issue.

**Comment by yonikid15** [comment]
> Does this also solve #6146 ? I am not seeing it anymore after running `npm run dev` 🤔

Yea it does! It took me a while to get there, but the problem was the duplicate getApplicant query running in `<ApplicationApi />` and `<ApplicationLayout />` causing the API request to go into an infinite loop since our default request policy is `cache-and-network`.

**Comment by vd1992** [comment]
running dev off of:
main -> console error appears at `/en/applications/:id/welcome`
branch -> console error did not appear at `/en/applications/:id/welcome`

seems good to me 👍

**Pull request merged**
