### PR TITLE
Update Candidate status chips

### LINKED ISSUE #9316: ✨ Update chip appearance of Candidate Status
## ✨ Feature

Update the way some Candidate Statuses are represented in the chip whip appears on the Candidates table and the Candidates page

## Details

This updates the work of #8675.

| Pool Candidate Status       | Final Decision | Colour |
|-----------------------------|----------------|---------|
| DRAFT                       | To assess* | *
| DRAFT_EXPIRED               | To assess* | *
| NEW_APPLICATION             | To assess* | *
| APPLICATION_REVIEW          | To assess* | *
| SCREENED_IN                 | To assess* | *
| UNDER_ASSESSMENT            | To assess* | *
| SCREENED_OUT_APPLICATION    | Disqualified   |  red
| SCREENED_OUT_NOT_INTERESTED | Removed: To assess      |  grey
| SCREENED_OUT_NOT_RESPONSIVE | Removed: To assess        | grey
| SCREENED_OUT_ASSESSMENT     | Disqualified   |  red
| QUALIFIED_AVAILABLE         | Qualified      | green
| QUALIFIED_UNAVAILABLE       | Removed: Qualified        |  grey
| QUALIFIED_WITHDREW          | Removed: Qualified        | grey
| PLACED_CASUAL               | Qualified      | green
| PLACED_TERM                 | Qualified      | green
| PLACED_INDETERMINATE        | Qualified      | green
| EXPIRED                     | Expired: Qualified        | gray
| REMOVED                     | Removed: To assess        | gray

### To Assess status requires additional logic!
This logic is related to how we display candidates on the Assessment Tracker page.
1. If the candidate has been disqualified in any _required_ assessments, then the status should show a red "Disqualified: Pending decision"
2. If the candidate shows as Successful or On Hold for every step of the Assessment Tracker, and is successful in the final step, then status pill should show a green "Qualified: Pending decision"
3. If the candidate shows as Successful or On Hold for every step of the Assessment Tracker, but "On Hold" for the final step of the tracker, then show a yellow "To assess: Step n" where n is the number of assessment steps
4. Otherwise, show a yellow "To assess: Step n" where n is the number of the first step which would show as "To assess" on the Assessment Tracker

Here are some examples showing how a candidate appears for each assessment step in the tracker, and how the overall status should appear:

S1: Demonstrated
S2: Hold
S3: To Assess
==> To Assess: Step 3

S1: Demonstrated
S2: Hold
S3: Demonstrated
==> Demonstrated: pending decision

S1: Demonstrated
S2: Hold
S3: Hold
==> To Assess: Step 3

S1: Demonstrated 
S2: Demonstrated
S3: Hold
==> To Assess: Step 3

S1: Demonstrated
S2: Hold
S3: Demonstrated
S4: Hold
==> To Assess: Step 4

## 🎨 Design File

https://www.figma.com/file/em5ArPr044YaIe1Vb1zCZz/Admin---Processes%2FPools%2FRecruitments---Record-of-Decision?type=design&node-id=8165-22301&mode=design&t=BYBLA4BX6IkFELVi-0

### 🧑‍🎨 Designer

@Jerryescandon 

### Status on Candidate page header
image

### Statuses in Candidate table
image

## 🙋‍♀️ Proposed Implementation

Use the functions from #9022 to determine "To assess" status

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] Status chips in Candidates table and in header of Candidate page follow the table
- [ ] Status of candidates in assessment follows the extra logic
- [ ] Jest tests for complicated statuses (may be useful to reference tests for Assessment Step Tracker)

### PR DESCRIPTION
**Pull request by tristan-orourke**
🤖 Resolves #9316

## 👋 Introduction

Updates the Pool Candidate status chips so that Removed statuses include extra details and so that To Assess statuses may show "Qualified: Pending decision" and "Disqualified: Pending decision" depending on assessment results.

## 🕵️ Details

If #8961 gets merged in soon, that will make part of this much easier to test manually.
I considered a few different ways to organize the utility functions, so let me know if you find the code very confusing.

## 🧪 Testing

Assist reviewers with steps they can take to test that the PR does what it says it does.

1. Log in as admin
2. Go to the Search Candidates table
3. Ensure you can see a variety of Status chips, with colors that make sense
4. Go to an individual candidate page
5. Manually change the status (click the link below the sidebar tools) and ensure the status in the header changes appropriately.
6. The "To Assess" statuses will be hard to test until #8961 is merged in. For now, review the tests and try to consider any missing cases.

### CODE REVIEW

**Review by esizer — APPROVED** [review]
Awesome! 🌟 Love the addition of the tests 👍

**Comment by brindasasi** [comment]
Question: Are we ok showing To assess: step 1 when ROD flag is off
Screenshot 2024-02-21 at 12 51 01 PM

**Comment by brindasasi** [comment]
Another thing noticed:` Final decision` column and all of these status changes are not reflected in CSV download yet.
Is it planned in diff story? 
Screenshot 2024-02-21 at 1 16 45 PM

**Comment by tristan-orourke** [comment]
@brindasasi, its a bit of ugly code, but I've simplified To Assess status while RoD flag is off, in https://github.com/GCTC-NTGC/gc-digital-talent/pull/9394/commits/01ac32397c745136fb2bf1d29c4054485ff4ea86

**Comment by tristan-orourke** [comment]
> Final decision column and all of these status changes are not reflected in CSV download yet.

Good catch! I'll make sure there's another story for that

**Review by brindasasi — APPROVED** [review]
Looking great to me !👏

**Pull request merged**
