### PR TITLE
Debt - 3899 - Remove Pool Placeholders

### LINKED ISSUE #3899: direct intake placeholder pages need completion or removal
<sup>ℹ️ [Figma (root)][figma] | [Sitemap][sitemap]</sup>
<sup>_This initial comment is collaborative and open to modification by all._</sup>

## Description
they seem kind of forgotten and could do with updating or removal 

the index page that lists them could use with a little pretty-ing
the second page does not seem to do anything now that `pool/:id/view` exists and probably should be removed

## Screenshot: Prototype
browse pools index page
image

page when you click on a pool from the list
image

## Acceptance Criteria
- [ ] resolve /view placeholder problem
- [ ] resolve /apply placeholder problem

   [image]: https://user-images.githubusercontent.com/305339/166570935-6425a615-82c7-4b2f-9840-5c7d698fa2ab.png
   [image-link]: https://example.com
   [figma]: https://go.talent.c4nada.ca/figma
   [sitemap]: https://go.talent.c4nada.ca/sitemap

### PR DESCRIPTION
**Pull request by esizer**
Resolves #3899 

## Summary

This removes some unused placeholder pages and routes we had for direct intake that were never used.

## Testing

1. Build talent search `npm run production --workspace=talentsearch`
2. Login and navigate to "Brows Opportunities" in the nav bar
3. Click on one of the pool and ensure you land on the advertisement page (not the placeholder)
4. Apply for a pool
5. Click the "Edit X" links in the profile section (step one)
6. Ensure the breadcrumbs work for the pool advertisement and steps

### CODE REVIEW

**Review by petertgiles — APPROVED** [review]
Looks like you might need to update a cypress test before merging but this looks nice to me!

**Review by yonikid15 — COMMENTED** [review]
Looking great Eric. Looks like the cypress test isn't working cause it can't click on the apply button, probably because the pool isn't published. We might have to update the seeder to ensure that we have a pool that is open to accept applications.

**Comment by vd1992** [comment]
definitely looks to be the case to me

image

**Comment by esizer** [comment]
@petertgiles @yonikid15 @vd1992 I watched three of the test snapshot videos and this test **should** be passing. The latest one just links to a 404, even though all I did was remove a single line from the test 🤔 .

Is there some sort of weird caching going on with our e2e tests?

**Pull request merged**
