### PR TITLE
[Feature] Application Welcome Page

### LINKED ISSUE #5961: ✨ Build Welcome page
## ✨ Feature

Welcome page to start the new application process 

## 🕵️ Details

Add any additional details that could assist with the development of the new feature.

## 🎨 Design File

https://www.figma.com/file/BXYVsu1fo9LS2IySJDUINY/Applicants---Job-application?node-id=636-59839&t=uYeh8QDrmOQsNpJQ-0

## 📸 Screenshot

Image

## 🙋‍♀️ Proposed Implementation

(optional) Do you have a proposed implementation?

## 🌎 Localization

(optional) Provide any new copy along with translations available

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] Page exists under the given url  applications/:id/welcome 
- [ ] Page is accessible only when the feature flag "Application Revamp" is ON 
- [ ] Hero subtitle and breadcrumbs are correct
- [ ] Return to the advertisement link takes the user to the job poster page 
- [ ] Let's go button saves the application state ( https://github.com/GCTC-NTGC/gc-digital-talent/issues/5985) 

## :stop_sign: Blockers
Blocked by #5985, #6027

### PR DESCRIPTION
**Pull request by esizer**
🤖 Resolves #5961 

## 👋 Introduction

Adds the application welcome page content + navigation to next step.

## 🕵️ Details

I made the next step a link since it is technically navigating. Though, it is also posting to the API so could be a form with a single submit 🤔 Does anyone feel strongly about making it more of a submission than a navigation link? 

## 🧪 Testing

Assist reviewers with steps they can take to test that the PR does what it says it does.

1. Start an application
2. Update the URL to the new application process `/applications/{applicationId}/welcome`
3. Confirm the page matches the mock up
4. Confirm the "Return to the advertisement" link brings you back to the correct advetisment
5. Confirm the "Let's go" link takes you to the next step and marks this step as "submitted"

## 📸 Screenshot
Screenshot 2023-04-06 130849

### CODE REVIEW

**Review by petertgiles — APPROVED** [review]
This looks great!  Personally, I think form submit makes more sense.  It will line it up with the other pages and the prevent default on the link smells not-quite-right.

**Comment by esizer** [comment]
> This looks great! Personally, I think form submit makes more sense. It will line it up with the other pages and the prevent default on the link smells not-quite-right.

Yeah, makes sense. I'll convert this to a form while I wait on translations if you are okay doing another review 😅

**Review by petertgiles — APPROVED** [review]
Heh, you're trying to avoid using react hook form for this?  I'm not used to seeing the prevenDefault on form submission.  :smiling:  It works, nice job!

**Comment by esizer** [comment]
> Heh, you're trying to avoid using react hook form for this? I'm not used to seeing the preventDefault on form submission. 😄 It works, nice job!

lol yeah, I didn't see the need to pull it in for a single submit button 😜

**Pull request merged**
