### PR TITLE
[Fix] Add codegen to watch command

### LINKED ISSUE #8401: 🐛 Gap between npm watch and codegen actions
## 🐛 Bug

I've noticed that sometimes changes to a graphql file while running a top-level watch command don't end up in the packages/graphql/index.ts file but appear as expected in the apps/web/src/api/generated.ts.  If I manually run codegen in the packages/graphql directory the changes appear but then they (maybe?) get overwritten again on the next watch cycle.  I haven't pinned down exactly what's going on yet, though.   I'm not sure if this has always been the case but I first started noticing it about 1-2 months ago. I've just stared running npm run codegen -- --force before watching and it seems to work fine.

## 🙋‍♀️ Proposed Solution

There is probably a missing dependency in the turbo.json file

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] When running top-level watch, changes to a graphql file should end up in both packages/graphql/index.ts and  apps/web/src/api/generated.ts files.

### PR DESCRIPTION
**Pull request by esizer**
🤖 Resolves #8401 

## 👋 Introduction

This allows codegen to re-run on changes to our operations. It also prevents codegen from being cached since this seemed to be causing more problems than it was solving.

## 🕵️ Details

We were only running `codegen` on the start of the watch command but it never actually watched any files. This [uses concurrently](https://the-guild.dev/graphql/codegen/docs/getting-started/development-workflow#watch-mode) to have it run in watch mode alongside the `tsup` watch.

> [!NOTE]
> Something that is a tad annoying is that when you kill the process, you need to do it twice. This is [a known bug](https://github.com/open-cli-tools/concurrently/issues/452) and hopefully gets fixed.

## 🧪 Testing

Assist reviewers with steps they can take to test that the PR does what it says it does.

1. Run watch `npm run watch`
2. Go add or delete a query in `apps/web`
3. Confirm the command is re-run and it affects the build

### CODE REVIEW

**Comment by vd1992** [comment]
Cannot run on WSL

Running in a Linux environment
Running watch
-> off main, deleting a graphql operation causes no change 
-> off branch, deleting a graphql operation triggers codegen action and webpack compile but no errors are emitted

**Comment by esizer** [comment]
> Cannot run on WSL

Hmm, odd. I am also on WSL and it seemed to work for me 🤔 

> -> off branch, deleting a graphql operation triggers codegen action and webpack compile but no errors are emitted

Which query did you delete? Do you remember? I'd like to see if I can reproduce.

**Comment by petertgiles** [comment]
I'm not sure what to think here.  :laughing:  Codegen doesn't seem to be watching for changes to the .graphql files.  :-1:    But I can manually run codegen with having to do the force flag.  :+1: 

On the other hand, the new stuff with the client-preset is working great in watch mode, so maybe we don't care that much about the deprecated codegen stuff?

**Comment by esizer** [comment]
> I'm not sure what to think here. :laughing: Codegen doesn't seem to be watching for changes to the .graphql files. :-1: But I can manually run codegen with having to do the force flag. :+1:

Ohh, that is a good point. Ever since we merged the `client-preset` (after I started this branch) the `.graphql` files are watched in a different place. I think I can resolve this, I had it working but merged main this morning which probably broke that 😅 .

**Review by petertgiles — APPROVED** [review]
Yay!  This is working great for me now.

**Comment by esizer** [comment]
> Yay! This is working great for me now.

Awesome! This is going to make the `client-preset` migrations far more enjoyable. You have no idea how many times I have ran `npm run codegen -- --force` in the past 24 hours 💀

**Pull request merged**
