### PR TITLE
Task/pool candidates table view

### LINKED ISSUE #51: Pool Dashboard - Create a table view for PoolCandidates using react-table
This task includes connecting the table to the API. That means writing the client-side graphql operation that queries all PoolCandidates, and creating a component that wraps the table component and includes a urql query hook.

TODO: Decide which columns should be displayed on the table? For reference here are all the possible fields:
```
type Pool {
    id: ID!
    pool: Pool @belongsTo
    user: User @belongsTo

    # cmoIdentifier can be an arbitrary string used to relate this candidate to an external database.
    cmoIdentifier: ID
    # Expiry date for this candidate being in the pool.
    expiryDate: Date

    isWoman: Boolean
    hasDisability: Boolean
    isIndigenous: Boolean
    isVisibleMinority: Boolean

    hasDiploma: Boolean
    languageAbility: LanguageAbility
    locationPreferences: [WorkRegion]
    acceptedOperationalRequirements: [OperationalRequirement]
    expectedSalary: [SalaryRange]
    expectedClassifications: [Classification]
    cmoAssets: [CmoAsset] 

    status: PoolCandidateStatus
}
```
Any type surrounded by [square brackets] represents a list, which we'd have to decide how to represent in a table cell.

### PR DESCRIPTION
**Pull request by jaysonmc**
Resolves #51

Remaining questions: Do we have solutions for localization atm? Presently the function for Y/N for boolean fields is unilingual (and same for table headers). I imagine this is acceptable until localization gets added in? If so, should be good to go.

As for which fields to choose. I think I chose a relevant subset, but should validate with users. As for a next task, we'll need a way to transition between tables, as this table has lots of data that won't fit into a single table view. Clicking on a given pool, for example, should transfer the user to the pool view filtered on the selected field.

### CODE REVIEW

**Comment by tristan-orourke** [comment]
Yep, the unilingual is fine for now, we'll do another pass over these components when we've figured out our bilingual solution.

I agree with the column choices, but I've started a conversation with Jerbo to be sure.

For the columns which should link to other entities, we can embed a <Link /> component from helpers/router.tsx, something like:
```
accessor: (user) => (
  <Link href={`${dashboardUrl}/users/${user.id}/edit`>{user.email}</Link>
)
```
I'm not sure what the base way to handle the hrefs is though. Pass a root url into the component? Put all the url constants in a file somewhere and just reference those?

**Comment by jaysonmc** [comment]
I wasn't even thinking about editing, but just displaying. In the model proposed, we would click to edit information we cannot see in a tabular fashion.

I'd envision a way to click a given colum and be redirected to a table with more details about a given row. Otherwise I'm being redirected to edit a peice of information I don't even know the information of before clicking it (and, as above, have no way of seeing in tabular format). 

I was thinking have a column row that re directs to another table to see the details. On the 'leaf tables' (that is, the tables showing all of the details for a given object and don't reference any further), then have some edit functionality. For the table here, for example, linking to edit the row doesn't make a sense given the missing information.

And in this case, store the clicked string in local storage, then redirect to a table (depending on the item clicked), and then filter the table based on the record in the local storage; then clear local storage.

Then editing would be some other workflow. As for the UI of it, yeah. I'd consult the designers on that.

**Comment by tristan-orourke** [comment]
That's a good point. I've been thinking that the only page that represents a single entity in a CRUD dashboard is the Edit view, but that doesn't need to be the case. Maybe a linked item should bring you to the table view, with filters included to select only the one item? A query string in the url might be a good representation of that: `dashboard/users?id=${user.id}`.

**Comment by tristan-orourke** [comment]
On the other hand, if you wanted to follow up on a linked PoolCandidate on another table and were redirected to this one, you still wouldn't be seeing _all_ the fields. Do you think each resource should have page for viewing all the details of an entity, separate from the Edit view?

**Comment by jaysonmc** [comment]
Perhaps that would be a discussion with the users to see what the use case is.

My thinking is, how do I know I want to edit a given field if I cant see all the information about it?
Or, if Im checking to validate a particular field for all candidates, would I have to click on every single field in order to validate the data/reponse?

But as always, we should validate these assumptions with the users.

**Review by tristan-orourke — APPROVED** [review]

**Pull request merged**
