### PR TITLE
[Fix] Add postgresql client to app service

### LINKED ISSUE #10777: 🐛 Can't run fresh setup in Azure app service
## 🐛 Bug

We've squashed our migrations but this means that the postgresql client needs to be present for a fresh start.

## 🙋‍♀️ Proposed Solution

Add the postgresql client to the post-deploy script that runs in the app service.

## ✅ Acceptance Criteria

- [ ] Can run a fresh setup in Azure
- [ ] Local webserver image can also run a fresh setup

### PR DESCRIPTION
**Pull request by petertgiles**
🤖 Resolves #10777 

## 👋 Introduction

This branch adds the postgresql to the app service setup to ensure that a fresh setup is possible.  It also adds it to the local webserver docker container to mirror the setup.

## 🕵️ Details

I created a custom Dockerfile for the webserver image.  Before, we were pretty strict about using a pristine image but this is a convenient way to mimic some of the customization we perform on the image during post-deploy.

### :house: Locally

1. Rebuild the webserver image `docker-compose build webserver`
2. Composer install by whatever method you normally use

- [ ] Can perform a database reset in the webserver container  `docker-compose exec webserver sh -c "php /home/site/wwwroot/api/artisan migrate:fresh"`

### :cloud: Azure

1. Deploy this branch to the dev vertical
2. SSH in

- [ ] Can perform a database reset `php /home/site/wwwroot/api/artisan migrate:fresh`

## 📸 Screenshot

image

### CODE REVIEW

**Comment by tristan-orourke** [comment]
I believe I've followed all the steps, but I'm getting an error locally 😕 . I'm using docker + WSL.

image

**Comment by petertgiles** [comment]
> I believe I've followed all the steps, but I'm getting an error locally 😕 . I'm using docker + WSL.

Perhaps you missed the step to rebuild the webserver container?
`docker-compose build webserver`

Or if you did, maybe it didn't do it and you can try the `--force-recreate` flag?

**Comment by tristan-orourke** [comment]
Okay, I ran through the steps again and it worked. 😅 
`php artisan migrate:fresh` now works both in the `webserver` and `maintenance` containers. This kind of makes https://github.com/GCTC-NTGC/gc-digital-talent/pull/10773 redundant, but I don't think there's a downside either.

**Review by tristan-orourke — APPROVED** [review]
Tested, looks good

**Comment by petertgiles** [comment]
> This kind of makes #10773 redundant, but I don't think there's a downside either.

Yeah, true. I asked Eric if he wanted me to roll back those changes in this PR but he said the way it is now is fine.

**Pull request merged**
