### PR TITLE
Updates Hydrogen to beta.31 in preparation for theming

### PR DESCRIPTION
**Pull request by substrae**
# ✨ Purpose

Updates the Hydrogen dependency so that we can begin working with themes. This update also includes support for automatic dark mode once we define sibling values.

# 🧪 Changes
- [x] Update the Hydrogen dependency
- [x] Migrate the configuration file
- [ ] If possible, leverage the new promise response in the Webpack compiler hooks
  - Turns out this isn't possible right now, due to the same reasons we struggled with Webpack's hooks in the past 
- [x] Fix breaking opacity changes

# 📑 Related issues
- https://github.com/hydrogen-css/hydrogen/pull/199
- https://github.com/hydrogen-css/hydrogen/pull/202
- https://github.com/hydrogen-css/hydrogen/pull/203

### CODE REVIEW

**Review by petertgiles — COMMENTED** [review]
I'm seeing some sus changes in Chromatic.  Are these intentional?
image

image

image

image

**Comment by substrae** [comment]
Thanks @petertgiles! Taking a peek.

**Comment by substrae** [comment]
Oops, noticed one last thing to fix that was breaking that I forgot about - color variable exports.

**Comment by petertgiles** [comment]
Nice!  Chromatic is down to just a few diffs now.

The first one I probably wouldn't have noticed and I don't know if it's worth worrying about.  It seems like it noticed some green jaggies on the edges of the diagonal gradients:
image
I can't even replicate it in my browser on the actual page.

The second is that our Hero lost the placeholder image.
image
It doesn't seem to be a problem on the actual Browse Opportunities page.
image

Just a small personal preference, is there a way to make the Hydrogen output less noisy?  Unless we're trying to debug a problem with the tool this seems like a lot.  :laughing: Single-spaced start and stop messages would be enough.
image

**Comment by substrae** [comment]
@petertgiles
- The green jaggies are likely differences in subpixel rendering, because nothing would have changed there
- I can't seem to replicate the hero issue... opening Storybook from the build above shows me the 500x500 image placeholder like your first screenshot
  - image 
- And yes! The system messages can't be silenced at the moment, but the timers can, so I'll pop a commit up for that

**Review by esizer — APPROVED** [review]
LGTM! 👍 

Can't wait to go in and attempt to replace all the custom css in https://github.com/GCTC-NTGC/gc-digital-talent/pull/4136 once it is finally merged 😀

**Pull request merged**
