### PR TITLE
Feature  -2923 - Register Page

### LINKED ISSUE #2923: Register Page
There will be a page to give a user context before registering for GCKey.

[image](https://www.figma.com/file/UDWAkiGXMt9YGbrfsuSzmr/Interface---Registration-and-login?node-id=133%3A1144)

## User Acceptance Critera
- [ ] Can navigate to /[lang]/register to view page
- [ ] Post login redirect should be the welcome page
- [ ] Files created in talentsearch directory
- [ ] The three links on the page operate

### PR DESCRIPTION
**Pull request by esizer**
Resolves #2923 

## Summary

This adds a page where users can register to use the application.

## Issue

While it is fine to have multiple links with different text that go to the same location, the issue is that the links on this page each have a different function.

- Register for a GC Key
- Login to the application
- Register for application with GC Key

Ref: https://www.w3.org/TR/WCAG20-TECHS/H30.html

### CODE REVIEW

**Comment by petertgiles** [comment]
Yeah, I'm seeing that weird behavior I was worried about.  The *Register for one* link correctly hits the `/login` endpoint of the API while the two buttons at the bottom try to navigate within React to `/en/login` which doesn't exist.  I think all three should go to the API endpoint, right?

**Comment by esizer** [comment]
> Yeah, I'm seeing that weird behavior I was worried about. The _Register for one_ link correctly hits the `/login` endpoint of the API while the two buttons at the bottom try to navigate within React to `/en/login` which doesn't exist. I think all three should go to the API endpoint, right?

I forgot that `navigate` only works on internal links. Fixed with [allow override of navigate on Link](https://github.com/GCTC-NTGC/gc-digital-talent/pull/2960/commits/5c5540e976ea3d147c2b4247953a22f19c124fea)

**Comment by vd1992** [comment]
- small thing, but in interface `LinkProps`, could you add a comment referring to the purpose of `external`, for ease of understanding when someone is looking through Link at a later time
- wireframe appears to want bolding around the "Dont have a gc account?" line

**Comment by esizer** [comment]
> * small thing, but in interface `LinkProps`, could you add a comment referring to the purpose of `external`, for ease of understanding when someone is looking through Link at a later time

Added comment with [add external link comment](https://github.com/GCTC-NTGC/gc-digital-talent/pull/2960/commits/0130e587c98282471b35d83ce6e84b1db71732a3)

> * wireframe appears to want bolding around the "Dont have a gc account?" line

Thanks for catching that, I have bolded it with [bold dont have a key?](https://github.com/GCTC-NTGC/gc-digital-talent/pull/2960/commits/f50cd8a39c2473bc4c26455678d29975ce7b11d0)

**Review by petertgiles — APPROVED** [review]
Love it!

**Pull request merged**
