### PR TITLE
delete experience function

### LINKED ISSUE #1932: Delete Button on Experience form (with Alert confirmation)
# Description
Add a "Delete experience from My Profile" button to bottom of Edit Experience form. 

It doesn't need to be part of the form, its just its own button with its own submit handler. It should throw up an alert/confirmation modal with confirm and cancel buttons. If you confirm, it should send you back to the Skills and Experience page, delete the experience via api, and display a Toast with the result of the operation.

This story requires writing the graphql operation as well.

Use the browser alert for confirmation.

[Wireframe](https://www.figma.com/proto/PrvXEDac0HVp7dF7SLWVFm/Candidate-profile-interfaces---V5.0.0?node-id=2340%3A4352&starting-point-node-id=1%3A2)

### PR DESCRIPTION
**Pull request by vd1992**
resolves #1932 

I think it is functional and ready to be looked at now, Eric making the dialogs sure was real handy!
eslint is being weird unfortunately, I tried but failed with the ignore eslint prettier at the top

tbh, I'm a little surprised the delete works 😮

### CODE REVIEW

**Review by esizer — CHANGES_REQUESTED** [review]
Looking good! 👀 

Only thing would be to write a test for this. I would look at the [About Me for test for saving](https://github.com/GCTC-NTGC/gc-digital-talent/blob/82166f142c9d8799ecdfb9d617eb502329324956/frontend/talentsearch/src/js/components/aboutMeForm/AboutMeForm.test.tsx#L107-L118).

```tsx
it("Should submit successfully with required fields", async () => {
    const mockSave = jest.fn(() => Promise.resolve(mockUser));
    renderAboutMeForm({
      initialUser: mockUser,
      onUpdateAboutMe: mockSave,
    });

    fireEvent.submit(screen.getByRole("button", { name: /save/i }));
    await waitFor(() => {
      expect(mockSave).toHaveBeenCalled();
    });
  });
```

**Review by esizer — APPROVED** [review]
Nice work! 😄 Looks good and tests passing!

**Comment by vd1992** [comment]
Thanks!
Mostly thanks to @petertgiles with the environment help that writing tests isn't impossible anymore

**Comment by vd1992** [comment]
a linting tweak or two I missed that I wanted to cover before merging

**Pull request merged**
