### PR TITLE
Add run-script for building the merged storybook

### PR DESCRIPTION
**Pull request by patcon**
Just a little helper for running in `frontend/` dir.

### CODE REVIEW

**Review by petertgiles — APPROVED** [review]
Very cool!

**Review by esizer — APPROVED** [review]
Ohh, this is pretty cool :)

**Comment by mnigh** [comment]
neato!

**Comment by patcon** [comment]
Ah jeez, i didn't realize this was so niche...! Sorry for hiding seeeeecret helpful commands

**Pull request merged**
