### PR TITLE
[Debt] Stepper updates

### LINKED ISSUE #8032: ♻️ Update the progress stepper component
image

## ✨ Summary

[Visit the Figma file](https://www.figma.com/file/guHeIIh8dqFVCks310Wv0G/Style-library?type=design&node-id=5-26&mode=design) • Chat with @substrae for design questions

The primary goal of this ticket is bring the progress stepper's styles more in line with the table of contents component so that they visually echo each other. Icons have been changed for visual clarity, and an optional button has been added.

```[tasklist]
### ✅ Requirements
- [x] Update whitespace and general styles to match the design
- [x] Update the "edit", "complete", and "error" icons to match the design
- [ ] ~~Ensure that an optional button is available~~ (edit: this button gets [added externally](https://github.com/GCTC-NTGC/gc-digital-talent/issues/8032#issuecomment-1775576667))
- [x] Storybook story is updated
```

### PR DESCRIPTION
**Pull request by yonikid15**
🤖 Resolves #8032 

## 👋 Introduction

- Updates Stepper styling
- Updates "edit", "completed", and "error" icons
- Changes setup so an icon prop is not required for "default" and "disabled" steps.

## 🕵️ Details

The styling values are now provided in figma (dev mode): [Stepper](https://www.figma.com/file/guHeIIh8dqFVCks310Wv0G/Style-library?node-id=34%3A4128&mode=dev)

## 🧪 Testing

Assist reviewers with steps they can take to test that the PR does what it says it does.

1. Open storybook and ensure Stepper component matches styling in figma designs.
2. Ensure icon updates are all correct for each step type.
3. Ensure Stepper still appears correctly throughout site (I believe it's only used in the Application process at the moment)

### CODE REVIEW

**Comment by substrae** [comment]
@yonikid15 

Heyo! Eric and I were taking a peek at the Chromatic link, and a few things stood out that we should collab on changing:
* Icon size vs. circle size is real wonky; this isn't on you - it displays one way in Figma, another in Chromatic, and I think it has to do with pixel rounding and the monitor resolution you look at it on; I think we'll likely have to shrink the icon slightly (`x.7` or `x.65`) and potentially increase the circle size (`x1.15`)?
* The text elements seem a bit far from their sibling circles (should be `x.25` in this case)
* There are a lot of weird hover effects going on here - any chance we can just import the `Link` component and use the `text` mode? If not, we should be at least pulling the styles to ensure consistency with other links; I've noticed the focus doesn't target the text either (it should focus the circle and the text)
* Only the success state should have the colored tail

I've updated the Figma file here: https://www.figma.com/file/guHeIIh8dqFVCks310Wv0G/Style-library?type=design&node-id=5-26&mode=design

**Comment by yonikid15** [comment]
@substrae 

Hello there,

First off, thanks for the review! I think I got all of the things you were looking for. If the circle size and icon size are still not proportional, let me know. We can even pair up to make it easier.

- [x] Changed the icon size to `x.65` and circle size to `x1.15`
- [x] Changed the StepLink component to use our Link component instead of directly using `react-router-dom`
- [x] Only success state should have the colored tail

**Review by esizer — CHANGES_REQUESTED** [review]
This is looking great! While you are here, do you mind overriding the colour for disabled links so there is no hover effect? I've noticed it for a while and it has been bugging me 😆 

https://github.com/GCTC-NTGC/gc-digital-talent/blob/e8aa4133fe239002dded4e7a608c51b0a699e343/packages/ui/src/components/Stepper/Step.tsx#L30

**Comment by yonikid15** [comment]
> This is looking great! While you are here, do you mind overriding the colour for disabled links so there is no hover effect? I've noticed it for a while and it has been bugging me 😆

For sure.. Fixed by [e787afc](https://github.com/GCTC-NTGC/gc-digital-talent/pull/8315/commits/e787afcb80f4f55214b688edd3c490de9820e5cc)! Should I remove the hover effect for active step as well?

**Review by esizer — APPROVED** [review]
Sweet! 🍭

**Comment by substrae** [comment]
@yonikid15 

Sorry it took so long! Looks to me like you got everything from my comment, awesome work :)

**Pull request merged**
