### PR TITLE
Refactor docker: the PR

### LINKED ISSUE #2217: Refactor Docker
Some loose thoughts as I think on this:

- inspiration of style will be https://github.com/compdemocracy/polis/blob/dev/docker-compose.yml
- we want to do e2e testing. this would be simpler with a more "conventional" docker setup, that we could run in GitHub Actions environment
- docker conventions of note
  - one process per container (php, apache, etc)
  - one dockerfile per section? (admin/talent/common)
    - potentially multistage build for static builds, ie single dockerfile (for react build)
- stretch goals (prob not in this PR)
  - deploy container image artifacts to github container repo
    - this would allow the containers to be built once, and then pulled into other jobs (no rebuild) for parallelized testing or other stuff
    - demo: https://github.com/g0v-network/polis/blob/dev/.github/workflows/release-docker-images.yml
      - https://github.com/orgs/g0v-network/packages?repo_name=polis
- great feature on smaller docker images: https://symflower.com/en/company/blog/2022/complete-guide-on-shrinking-container-images/

## Prior Art
(Potentially useful when this is revived)

- https://github.com/GCTC-NTGC/gc-digital-talent/pull/2451
- https://github.com/GCTC-NTGC/gc-digital-talent/pull/2945

### To Do
- [x] https://github.com/GCTC-NTGC/gc-digital-talent/issues/2324
  - [x] read peter's [docker manifesto](https://talent-cloud.slack.com/files/U02J583KLGP/F038HCD796E/docker_manifesto.md)
    - [x] @petertgiles  🙃 
    - [x] @patcon 
    - [x] @brindasasi 
    - [x] @JamesHuf 
    - [x] @gggrant 
    - [x] @RVany
    - [ ] others? [add yourself]
  - [x] schedule time -- @petertgiles [FRI MAR 25 @ 2-3pm]
  - [x] invite all interesteds [from thread](https://talent-cloud.slack.com/archives/CB424V61J/p1648129419092389) -- @petertgiles 
  - [x] do the call! -- all
- [x] optional: summarize goals as decided?
- [ ] optional: split out tasks/tickets/accept-criteria (nearterm, longterm, etc)
- [ ] https://github.com/GCTC-NTGC/gc-digital-talent/issues/2327

### PR DESCRIPTION
**Pull request by patcon**
Resolves #2217 

## CAPTAINS LOG 🚀 

 - [x] did stuff together (last week) 👬 
 - TUE APR 12 cowork
   - [x] ensured htaccess being read
   - [x] removed LogMessage debug stuff
   - [x] moved htaccess to `frontend/conf/` dir
   - [ ] fix issue with `npm ci` from lockfile version change
   - [ ] ...

## Open Questions
1. in-container watch (node) vs manual vs on-host watch (docker)?
2. webserver routing structure / container arch?
    - frontend containers vs php container

### CODE REVIEW

**Comment by patcon** [comment]
halpful? https://stackoverflow.com/a/54725355

**Comment by patcon** [comment]
just did a debrief with tristan and he's taking this for a stretch

**Comment by mnigh** [comment]
@patcon is this PR still relevant now that we are moving to [nginx](https://github.com/GCTC-NTGC/gc-digital-talent/pull/4871) or can it be closed?

**Comment by patcon** [comment]
I feel like the extent of the changes will mean it's easier to restart. I'd suggest we
1. close both mine and Tristan's,
2. link them clearly from #2217 and
3. extract the good bits when we find time to prioritize this

**Comment by patcon** [comment]
Decided in retro to close this in favour of the parent issue

**Pull request closed without merging**
