### PR TITLE
fix action links on the track application card

### PR DESCRIPTION
**Pull request by brindasasi**
🤖 Resolves {issue #7309 }

## 🕵️ Details

Add any additional details that could assist with reviewing or testing this PR.

## 🧪 Testing

Assist reviewers with steps they can take to test that the PR does what it says it does.
1. Navigate to en/applicant/profile-and-applications
2. Make sure you have a application with "Qualified" status
3. Verify the below A/C 

- [ ] Change "Visit Résumé" to "Manage Recruitment"  
- [ ] Change aria-label to "Manage the {title} recruitment"
- [ ] Remove "Manage availability" link

## 📸 Screenshot
Screenshot 2023-07-19 at 9 40 45 AM

Add a screenshot (if possible).

### CODE REVIEW

**Review by vd1992 — CHANGES_REQUESTED** [review]
Aria-label appears to not include a value for `{title}`

image

I think it might have to do with this bit

image

image

**Comment by vd1992** [comment]
Oh, it appears present in multiple places
I don't understand what the `&& ""` is for

image

**Comment by brindasasi** [comment]
> Aria-label appears to not include a value for `{title}`
> 
> image
> 
> I think it might have to do with this bit
> 
> image
> 
> image

Changing the aria-label slightly after Gray mentioned french translation is not quite right. 
It should be now 
Manage the {title} recruitment and Gérer le recrutement {title} for french

**Comment by brindasasi** [comment]
> > Aria-label appears to not include a value for `{title}`
> > image
> > I think it might have to do with this bit
> > image
> > image
> 
> Changing the aria-label slightly after Gray mentioned french translation is not quite right. It should be now Manage the {title} recruitment and Gérer le recrutement {title} for french



> Oh, it appears present in multiple places I don't understand what the `&& ""` is for
> 
> image

This probably due to an auto correct setting in VSCode. Removing it

**Comment by brindasasi** [comment]
> > > Aria-label appears to not include a value for `{title}`
> > > image
> > > I think it might have to do with this bit
> > > image
> > > image
> > 
> > 
> > Changing the aria-label slightly after Gray mentioned french translation is not quite right. It should be now Manage the {title} recruitment and Gérer le recrutement {title} for french
> 
> > Oh, it appears present in multiple places I don't understand what the `&& ""` is for
> > image
> 
> This probably due to an auto correct setting in VSCode. Removing it

ohh .. this is due to a string was expected here .. where as the return type of this function is a ReactNode

**Comment by vd1992** [comment]
I think the second function in the picture should do the job

image

**Comment by brindasasi** [comment]
> I think the second function in the picture should do the job
> 
> image

That worked. Thanks! 😊 
Screenshot 2023-07-24 at 5 16 06 PM
Screenshot 2023-07-24 at 5 15 16 PM

**Review by vd1992 — APPROVED** [review]
Great 🥳 
All the aria-labels seem fixed now too!

image

**Pull request merged**
