### PR TITLE
11762 improve screening candidates query

### LINKED ISSUE #11762: 🐛 Slow Page - Screening
## 🐛 Bug

Our logs are full of warnings about how slow the screening page is.  This is causing poor UX, PHP worker shortage, and even worker timeout.

## 📸 Screenshot

image
image
image

## ✅ Acceptance Criteria

- [ ] Performance of screening page is generally improved

### PR DESCRIPTION
**Pull request by brindasasi**
🤖 Resolves  #11762 

## 👋 Introduction
I've made some simple improvements like eager loading , adding indexes and reducing computing time on the query by reusing var.s

There wasn't lot of diff when running in normal scenario.
I introduced throttling and 4 hardware concurrency by the browser extension and results are visible in those conditions. 

We do have over fetching on the screening tracker as we are not showing Expired:qualified statuses. 
But when I talked to Jerbo this is something we have to show on the page ..and the enhancement is coming up. So I didn't trim it.

## 🕵️ Details

Browser: Edge
Env.
Screenshot 2024-11-13 100317
Test Data 
https://dev-talentcloud.tbs-sct.gc.ca/en/admin/pools/df7b540b-4076-47ac-8223-5c669dbf9a64
1009 candidates including expired/rejected 
image

Current Main performance in the above scenario
Screenshot 2024-11-13 093726

This PR 
Screenshot 2024-11-13 100351

## 🧪 Testing
Verify query timing under some throttling

### CODE REVIEW

**Review by esizer — COMMENTED** [review]
I can't seem to reproduce the performance gains but, it is not slower :sweat_smile: 

## Candidates table



## Screening and Eval

**Review by esizer — APPROVED** [review]
Going to approve since you saw real good gains on performance and it at least stayed the same for me.

If you want to wait on someone else to attempt to reproduce your perf gains you can but I think this is good to go :+1:

**Comment by vd1992** [comment]
Took it for a whirl to try out. With about 1000 candidates seeded. 

### Screening and evaluation page
Reduction in time by maybe ~3%

### Talent placement page - 500 candidates
Reduction in time by ~2.5%

A small reduction but nothing appears worsened, possibly more impactful in production. 
But an actual issue, I could not reverse the migration. Please check that. 

Changing the `dropIndex('status_weight')` to the below fixed it for some reason 🤷 

`            $table->dropIndex(['status_weight']);`

**Comment by brindasasi** [comment]
> Took it for a whirl to try out. With about 1000 candidates seeded.
> ### Screening and evaluation page
> 
> Reduction in time by maybe ~3%
> ### Talent placement page - 500 candidates
> 
> Reduction in time by ~2.5%
> 
> A small reduction but nothing appears worsened, possibly more impactful in production. But an actual issue, I could not reverse the migration. Please check that.
> 
> Changing the `dropIndex('status_weight')` to the below fixed it for some reason 🤷
> 
> ` $table->dropIndex(['status_weight']);`

sorry for the delay. Changed to names indexes so that it can delete properly. Thanks for verifying that!

**Pull request merged**
