### PR TITLE
[Bug] Handle multiple spaces in text search

### LINKED ISSUE #10384: 🐛 Multiple spaces between search terms breaks User general search
## 🐛 Bug

If you include multiple spaces between search terms in the search bar of the User of PoolCandidate table, filtering stops working and all rows are returned.

## 🦋 Expected Behaviour

Two search terms separated by a space should work the same as two terms separated by multiple spaces.

## 📋 Steps to Reproduce

1. Go to Pools table
2. find two search terms which match one or two candidates
3. try searching `term1 or term2`. You should get the union of results
4. now put an extra space between `or` and one of terms. You will see all candidates!

## 📸 Screenshot

Add a screenshot (if possible).

## 🙋‍♀️ Proposed Solution

I'm guessing we're doing a split on empty space somewhere, and ending up with an empty string search term which matches everything. But that seems unrelated to this work, and can get its own ticket.

## ✅ Acceptance Criteria

- [ ] multiple spaces between search terms are treated like one
- [ ] add a test case to KeywordSearchTest.php for this

### PR DESCRIPTION
**Pull request by vd1992**
🤖 Resolves #10384 

## 👋 Introduction

Handle multiple spaces being present in search string like `"a  or   b"`
Added a test function to the search test file. 

## 🧪 Testing

1. Navigate to `/en/admin/pool-candidates`
2. Exercise searching with multiple spaces

## 📸 Screenshot

image

### CODE REVIEW

**Comment by brindasasi** [comment]
I get time out when I combine 2 terms. Single words work fine :( 
Screenshot 2024-05-23 at 2 43 09 PM
Screenshot 2024-05-23 at 2 48 04 PM
Screenshot 2024-05-23 at 2 38 32 PM

**Comment by brindasasi** [comment]
Screenshot 2024-05-23 at 2 54 20 PM
If its not reproducible for you , we can verify it in dev. If its working there , then it could be my local being slow. 
But single search term brings out the results very swiftly makes me suspicious.
Let me know if you need help deploying in dev

**Comment by vd1992** [comment]
> If its not reproducible for you , we can verify it in dev. If its working there , then it could be my local being slow. But single search term brings out the results very swiftly makes me suspicious. Let me know if you need help deploying in dev

No, I can't seem to replicate that issue/error 😕 
Do you want to deploy it or wait for someone else to try it out?

**Comment by brindasasi** [comment]
> > If its not reproducible for you , we can verify it in dev. If its working there , then it could be my local being slow. But single search term brings out the results very swiftly makes me suspicious. Let me know if you need help deploying in dev
> 
> No, I can't seem to replicate that issue/error 😕 Do you want to deploy it or wait for someone else to try it out?

yeah I can deploy it in dev

**Review by brindasasi — APPROVED** [review]
works just fine in dev 😌
I hate my local 😭

**Comment by vd1992** [comment]
> works just fine in dev 😌 I hate my local 😭

Crowdfund a new PC for you and @yonikid15 💸

**Pull request merged**
