### PR TITLE
[Bug] Fix a11y tests

### LINKED ISSUE #6224: Jest - a11y tests call console.error
## 🐛 Bug

The _web_ app has three a11y tests that begin to fail when Jest is set to fail on console.error.

The _web_ package tests should not be calling console.error or it should be handled if expected

## 🕵️ Details

```
Default Client: No client has been specified using urql's Provider.
Warning: Encountered two children with the same key, `test-file-stub`.
```

## 📋 Steps to Reproduce

1. (optional) Check out branch `tooling_5846_jest-notify` from #6178
2. Run `npx jest --testNamePattern=accessibility` from the `apps/web` directory
3. Observe three tests failing

## 📸 Screenshot
image

## ✅ Acceptance Criteria

- [ ] Running the a11y tests results in no errors
- [ ] Tests continue to function as intended

### PR DESCRIPTION
**Pull request by petertgiles**
🤖 Resolves #6224

## 👋 Introduction

This bug fixes the console.error messages in the a11y Jest tests.

## 🕵️ Details

- The first set of errors was happening because the mock Urql provider wasn't set up.  I added the existing one.
- The second set of errors was happening because our file mock doesn't not unique hrefs.  I added an optional natural key to the link component to use.

## 🧪 Testing

1. Rebuild the app
2. cd to the `apps/web` directory
3. Run `npx jest --testNamePattern=accessibility`
4. Confirm that the tests pass and there are no errors or warnings logged to the console.

## 📸 Screenshot

image

### CODE REVIEW

**Review by vd1992 — APPROVED** [review]
👍 

image


Not quite done with the console errors however, still see some left in the CI run.

**Comment by petertgiles** [comment]
Thanks Vachan!  I think I might merge this as is and clean up the rest in the #6178.  I've requested a review from Eric since I know he was looking at the file key issue and am interested in his opinion on the solution.

**Comment by esizer** [comment]
I like the addition of `naturalKey`, though I'm not sure we need to add it to the the props of `<Link />` and `<ExternalLink />`. Would it work to just add it to the  `getGenericLinks` array?

https://github.com/GCTC-NTGC/gc-digital-talent/blob/e7bf729cdf489c89cd12db22c1476c8052500f93/apps/web/src/pages/DirectivePage/utils.ts#L84

To:

```tsx
type LinkType = ExternalLinkProps & { naturalKey?: string };

const links: Array<LinkType> = [ ... ];
```

**Comment by petertgiles** [comment]
> I'm not sure we need to add it to the the props of `<Link />` and `<ExternalLink />`

@esizer Oh, you're right!  I just had to omit it from the props going down to avoid the "React does not recognize the prop" warning.
[don't push natural key to link components](https://github.com/GCTC-NTGC/gc-digital-talent/pull/6536/commits/0a534e22ca9c20e3d3734eda891347af64cf2f85)

**Review by esizer — APPROVED** [review]
LGTM! 😁

**Pull request merged**
