### PR TITLE
dependencies/4540-laravel-9 

### LINKED ISSUE #4540: Upgrade to Laravel 9
Once we get to PHP 8 we should upgrade to Laravel 9.

https://laravel.com/docs/9.x/upgrade

### PR DESCRIPTION
**Pull request by vd1992**
closes #4540 
upgrades Laravel to 9.X
somehow error messages in some tests got more useful 🤷 

testing
not entirely sure, at the minimum
refresh API -> navigate site to make sure it all works

### IMPORTANT
you must clear cache to account for dependency changes or else you'll run into errors
go to `api/bootstrap/cache` and delete `packages.php` and `services.php`
then run refresh commands or whatever

### CODE REVIEW

**Comment by esizer** [comment]
It doesn't seem to impact anything but I noticed this change was not made 🤔 

> The `schema` configuration option used to configure Postgres connection search paths in your application's `config/database.php` configuration file should be renamed to `search_path`.

https://laravel.com/docs/9.x/upgrade#postgres-schema-configuration

**Comment by vd1992** [comment]
I think it effects nothing because the file doesn't seem to do anything
https://github.com/GCTC-NTGC/gc-digital-talent/blob/main/api/config/database.php
postgres is not configured in that file

**Comment by esizer** [comment]
> I think it effects nothing because the file doesn't seem to do anything https://github.com/GCTC-NTGC/gc-digital-talent/blob/main/api/config/database.php postgres is not configured in that file

This is the line the guide refers to:

https://github.com/GCTC-NTGC/gc-digital-talent/blob/847e44a6680384ecf089122fdd2dbe7aa61edf26/api/config/database.php#L77

**Comment by vd1992** [comment]
> > I think it effects nothing because the file doesn't seem to do anything https://github.com/GCTC-NTGC/gc-digital-talent/blob/main/api/config/database.php postgres is not configured in that file
> 
> This is the line the guide refers to:
> 
> https://github.com/GCTC-NTGC/gc-digital-talent/blob/847e44a6680384ecf089122fdd2dbe7aa61edf26/api/config/database.php#L77

yep, I tried it out in the commit above

php unit seems to be acting strange now, I reran it on main to see if it was something in this branch but it is also taking real long to load on main
https://github.com/GCTC-NTGC/gc-digital-talent/actions/runs/3593432771/jobs/6054451344

**Comment by vd1992** [comment]
okay, php tests passed successfully. took a long while but it mirrors the rerun on main
so rules out a branch issue

**Comment by esizer** [comment]
> I meant that file is not what controls how our database is set up, docker and env do, so that would explain no impact

This file is the actual config file, it derives its info from the environment variables. The `env()` function just reads the environment variables then it gets cached in `bootstrap/cache/config.php` 😸 

https://github.com/GCTC-NTGC/gc-digital-talent/blob/847e44a6680384ecf089122fdd2dbe7aa61edf26/api/config/database.php#L69-L73

**Comment by vd1992** [comment]
ah thanks, nevermind then 🙃

**Comment by petertgiles** [comment]
Not sure what's going on with the CI.  It ran in about 30 seconds for me, both in the the maint container and locally.
image

**Comment by petertgiles** [comment]
Oh, nevermind, 20 seconds on the last CI run.
image

**Comment by vd1992** [comment]
issue up at #4987

**Pull request merged**
