### PR TITLE
Debt - 3952 - Replace primitives

### LINKED ISSUE #3952: Replace Reach UI with new primitives
## Summary

It seems that `@reach/ui` is lagging on updating to `react@18`. While the project is still being maintained, updates in general have slowed. It could be useful to migrate to a different primitive library. 

## Research

From some research with @patcon , it seems a good candidate would be radix. It provides all of the the same primitives we are currently using and some more. It also seems to be more regularly updated (1-6 months).

## To Do

- [x] Replace `AlertDialog`
- [x] Replace `Dialog`
- [x] Replace `MenuButton`
- [x] Replace `Tabs`
- [x] Implement `Accordion`
- [x] Investigate `Checkbox`
- [x] Investigate `RadioGroup`

### PR DESCRIPTION
**Pull request by esizer**
Resolves #3952 

## 📋 Summary

This replaces our underlying custom/reach `common` primitives with `radix-ui`

## ❓Rationale

> **Warning**
> [Reach is not currently maintained.](https://github.com/reach/reach-ui/issues/972)

Currently, we are stuck on `react@17` and the only real blocker is `reach-ui`. After some research and looking at a number of primitive libraries, it seems as though radix is the best option because:

- It has full keyboard navigation
- Managed focus
- Has proper semantics for assistive technology
- WAI-ARIA compliant
- Screen reader tested
- Allows us to worry about styling rather than API
- Exposes all sub-components for more control
- Has a fairly large library to use

## ✅ TO DO

- [ ] Fix linting
- [ ] Translation run

## 🧪 Testing

> Good luck! 🍀 

1. Build all projects `npm run production --workspaces`
2. Bounce around the place where the components were replaced and confirm they all still work and look fine
3. Check storybook for components and docs! `npm run storybook`

### Places to Check

- Admin
  - Logout
  - Edit Pool
  - Table column dialog
  - User/Pool Candidate filter dialogs
  - API Table search dropdown
  - User tabs
- IAP
  - Dialogs on homepage
- Talent Search
  - Employment equity form dialogs
  - Experience form delete confirmation
  - Logout
  - Role Salary form dialogs

## ⚛️ Components

| Component     | Created | Stories | Tests | Replaced |
| ------------- | ------- | --------- | ----- | -------- |
| `Accordion`     |     ✅     |      ✅     |    ✅   |     ✅     |
| `AlertDialog`  |    ✅     |     ✅      |   ✅    |      ✅    |
| `Collapsible`        |    ✅     |      ✅     |    ✅   |      ✅      |
| `Dialog`        |    ✅     |      ✅     |    ✅   |      ✅      |
| `DropdownMenu` |     ✅    |      ✅     |    ✅     |    ✅      |
| `ScrollArea` |     ✅    |      ✅     |    ✅     |    ✅      |
| `Separator` |     ✅    |      ✅     |    ✅     |    ✅      |
| `Switch` |     ✅    |      ✅     |    ✅     |    ✅      |
| `Tabs`          |   ✅       |     ✅       |     ✅   |    ✅      |
| `ToggleGroup` |     ✅    |      ✅     |    ✅     |    ✅      |

### Accordion

```tsx
import Accordion from "@common/components/Accordion";

/**
 * Allows multiple accordions items to be open at once
 */
const ExampleAccordionMultipleOpen = () => (
  <Accordion.Root type="multiple">
    <Accordion.Item value="one">
        <Accordion.Trigger Icon={HeroIcon} subtitle="Subtitle">
          Example Accordion One Heading
        </Accordion.Trigger>
        <Accordion.Content>
          <p>Example accordion one content.
        </Accordion.Content>
      </Accordion.Item>
    <Accordion.Item value="two">
        <Accordion.Trigger Icon={HeroIcon} subtitle="Subtitle">
          Example Accordion Two Heading
        </Accordion.Trigger>
        <Accordion.Content>
          <p>Example accordion two content.
        </Accordion.Content>
      </Accordion.Item>
  </Accordion.Root>
);

/**
 * Allows only one accordions item to be open at once
 */
const ExampleAccordionSingleOpen = () => (
  <Accordion.Root type="single">
    <Accordion.Item value="one">
        <Accordion.Trigger Icon={HeroIcon} subtitle="Subtitle">
          Example Accordion One Heading
        </Accordion.Trigger>
        <Accordion.Content>
          <p>Example accordion one content.
        </Accordion.Content>
      </Accordion.Item>
  </Accordion.Root>
);
```

### Alert Dialog

```tsx
import AlertDialog from "@common/components/AlertDialog";
import Button from "@common/components/Button";

const ExampleAlertDialog = () => (
  <AlertDialog.Root>
    <AlertDialog.Trigger>
      <Button>Open Alert Dialog</Button>
    </AlertDialog.Trigger>
    <AlertDialog.Content>
      <AlertDialog.Title>Example Alert Dialog</AlertDialog.Title>
      <AlertDialog.Description>Example Alert Dialog Description</AlertDialog.Description>
      <AlertDialog.Footer>
        <AlertDialog.Cancel>
          <Button color="white">Cancel</Button>
        </AlertDialog.Cancel>
        <AlertDialog.Action>
          <Button color="cta">Action</Button>
        </AlertDialog.Action>
      </AlertDialog.Footer>
    </AlertDialog.Content>
  </AlertDialog.Root>
);
```

### Dialog

```tsx
import Dialog from "@common/components/Dialog";
import Button from "@common/components/Button";

const ExampleDialog = () => (
  <Dialog.Root>
    <Dialog.Trigger>
      <Button>Open Dialog</Button>
    </Dialog.Trigger>
    <Dialog.Content>
      <Dialog.Header subtitle="short description">
        Dialog Title
      </Dialog>
      <p>Dialog body</p>
      <Dialog.Footer>
        <Dialog.Close>
          <Button>Close</Button>
        </Dialog.Close>
      </Dialog.Footer>
    </Dialog.Content>
  </Dialog.Root>
);
```

### Collapsible

```tsx
import Collapsible from "@common/components/Collapsible";
import Button from "@common/components/Button";

const ExampleCollapsible = () => (
 <Collapsible.Root>
	 <Collapsible.Trigger asChild>
		 <Button>Open Collapsible</Button>
	 </Collapsible.Trigger>
	 <Collapsible.Content>
		 <p>Content for a Collapsible element</p>
	 </Collapsible.Content>
 </Collapsible.Root>
```

### Dropdown Menu

```tsx
import DropdownMenu from "@common/components/DropdownMenu";

const DropdownMenuExample = () => {
  const [value, setValue] = React.useState<string>("");
  return (
    <DropdownMenu.Root>
      <DropdownMenu.Trigger>
        <Button>Open Dropdown</Button>
      </DropdownMenu.Trigger>
      <DropdownMenu.Content>
        <DropdownMenu.Label>Basic Items</DropdownMenu.Label>
        <DropdownMenu.Item>Item One</DropdownMenu.Item>
        <DropdownMenu.Item>Item Two</DropdownMenu.Item>
        <DropdownMenu.Separator />
        <DropdownMenu.Label>Form Items</DropdownMenu.Label>
        <DropdownMenu.CheckboxItem>
          Basic CheckboxItem
        </DropdownMenu.CheckboxItem>
        <DropdownMenu.RadioGroup value={value} onValueChange={setValue}>
          <DropdownMenu.RadioItem value="one">
            <Check />
            RadioItem One
          </DropdownMenu.RadioItem>
          <DropdownMenu.RadioItem value="two">
            <Check />
            RadioItem Two
          </DropdownMenu.RadioItem>
          <DropdownMenu.RadioItem value="three">
            <Check />
            RadioItem Three
          </DropdownMenu.RadioItem>
        </DropdownMenu.RadioGroup>
      </DropdownMenu.Content>
    </DropdownMenu.Root>
  );
}
```

### Scroll Area

```tsx
import ScrollArea from "@common/components/ScrollArea";

const ExampleScrollArea = () => (
	<ScrollArea.Root style={{ height: 500, width: 320, }}>
		<ScrollArea.Viewport>
			<p>Content for the Scroll Area</p>
		<ScrollArea.ViewPort>
		<ScrollArea.Scrollbar orientation="vertical">
			<ScrollArea.Thumb />
		</ScrollArea.Scrollbar>
	</ScrollArea.Root>
);
```

### Separator

```tsx
import Separator from "@common/components/Separator";

const ExampleSeparator = () => (
	<Separator
		decorative
		orientation="vertical"
		color="secondary"
	/>
);
```

### Switch

```tsx
import Switch from "@common/components/Switch";

const SwitchExample = () => (
	<Switch.Root id="example-switch">
		<Switch.Thumb />
	</Switch.Root>
);
```

### Tabs

```tsx
import DropdownMenu from "@common/components/DropdownMenu";

const ExampleTabs = () => (
	<Tabs.Root defaultValue="one">
	    <Tabs.List aria-label="Tabs Nav">
			<Tabs.Trigger value="one">One</Tabs.Trigger>
			<Tabs.Trigger value="two">Two</Tabs.Trigger>
			<Tabs.Trigger value="three">Three</Tabs.Trigger>
		</Tabs.List>
		<Tabs.Content value="one">
			<p>One</p>
		</Tabs.Content>
		<Tabs.Content value="two">
			<p>Two</p>
		</Tabs.Content>
		<Tabs.Content value="three">
			<p>Three</p>
		</Tabs.Content>
	</Tabs.Root>
);
```

### Toggle Group

```tsx
import Toggle Group from "@common/components/ToggleGroup";

const ToggleGroupExample = () => (
	<ToggleGroup.Root>
		<ToggleGroup.Item value="one">One</ToggleGroup.Item>
		<ToggleGroup.Item value="two">Two</ToggleGroup.Item>
		<ToggleGroup.Item value="three">Three</ToggleGroup.Item>
	</ToggleGroup.Root>
);

```

### CODE REVIEW

**Comment by patcon** [comment]
Actually @esizer, going to focus on https://github.com/GCTC-NTGC/gc-digital-talent/issues/3648, so don't count me as a reviewer on this just yet

**Review by yonikid15 — COMMENTED** [review]
Hey, I'm still in the middle of reviewing, but I found a bug when trying to open up the Columns dialog on the admin side. Can you let me know if this happening for you as well.

Error on the console: `Cannot read properties of null (reading 'control')`

**Comment by esizer** [comment]
> Hey, I'm still in the middle of reviewing, but I found a bug when trying to open up the Columns dialog on the admin side. Can you let me know if this happening for you as well.
> 
> Error on the console: `Cannot read properties of null (reading 'control')`

Are you seeing this in storybook, localhost or both?

**Comment by vd1992** [comment]
is this change intentional? I thought the ones on the left were supposed to be worded differently intentionally 

image

**Comment by vd1992** [comment]
bolding appears to have been lost

image

**Comment by vd1992** [comment]
change to that dropdown makes it no longer recognizable as a dropdown, lost its little pointer

image

**Comment by esizer** [comment]
> is this change intentional? I thought the ones on the left were supposed to be worded differently intentionally

I'll have to look into this. As far as I know, I did not touch that string 😓

**Comment by esizer** [comment]
> bolding appears to have been lost

Hmm, very odd. Something else that I do not remember touching in this PR. I just merged in main to see if I'm just a few commits behind or something 🤔

**Comment by esizer** [comment]
> is this change intentional? I thought the ones on the left were supposed to be worded differently intentionally

Looks like it was some bad merge conflict resolutions on my part. Should be good now in [fix equity option titles](https://github.com/GCTC-NTGC/gc-digital-talent/pull/4136/commits/b1404e395850aa312d1fec4056ce8d8eb868e365)

> bolding appears to have been lost

I'm not sure what one is correct but main is bold so I updated it to be bold in [fix regular font weight delete action](https://github.com/GCTC-NTGC/gc-digital-talent/pull/4136/commits/34bd7334fcb1f78b2ad322c86a04b31bc48da17a)

> change to that dropdown makes it no longer recognizable as a dropdown, lost its little pointer

Good eye! Added chevron in [fix dropdown menu styles](https://github.com/GCTC-NTGC/gc-digital-talent/pull/4136/commits/807beb5fe2c3722ff0c88c45ab94abbd93bff927)

**Comment by vd1992** [comment]
> > is this change intentional? I thought the ones on the left were supposed to be worded differently intentionally
> 
> Looks like it was some bad merge conflict resolutions on my part. Should be good now in [fix equity option titles](https://github.com/GCTC-NTGC/gc-digital-talent/pull/4136/commits/b1404e395850aa312d1fec4056ce8d8eb868e365)
> 
> > bolding appears to have been lost
> 
> I'm not sure what one is correct but main is bold so I updated it to be bold in [fix regular font weight delete action](https://github.com/GCTC-NTGC/gc-digital-talent/pull/4136/commits/34bd7334fcb1f78b2ad322c86a04b31bc48da17a)
> 
> > change to that dropdown makes it no longer recognizable as a dropdown, lost its little pointer
> 
> Good eye! Added chevron in [fix dropdown menu styles](https://github.com/GCTC-NTGC/gc-digital-talent/pull/4136/commits/807beb5fe2c3722ff0c88c45ab94abbd93bff927)

Nice! Overall it looks like things function just the same as before! 
All right, I'll hand things back to Yoni, who I entirely have faith in to review this

**Review by yonikid15 — CHANGES_REQUESTED** [review]
This was a big one, but as always great work Eric 🎉 Thanks for taking this one on, and again apologies for the long wait on the review.

Manual tests:
- [x] Editing all touched sections of the Profile. Ensure all forms work behave and look correct.
- [x] Login/Logout.
- [x] Editing a pool.
- [x] Table column and filter dialogs, and search dropdowns.
- [x] User tabs
- [x] Dialogs on IAP homepage.

Bugs:
- [x] On the IAP homepage,  the "See Eligibility Criteria" and "Learn more" dialog close buttons are not working.
- [ ] On the IAP homepage, when closing a dialog the tab index jumps back to the first element on the page, in this case the Home link in the nav menu. This can get annoying for users with screen readers. It seems to be working correctly on the Admin and TalentSearch side though.
- [ ] User cannot scroll when the dialog is open. This could prevent the user from seeing the entire Dialog, especially on smaller screens. For example, on the EE dialog I cannot click the Save button. Also, the "Learn more" dialog on IAP homepage is very long so most of the content is unviewable. Would adding a `<ScrollArea />` within the Dialog fix this?
- [ ] The search form dropdown is missing on Pool Candidates table (Def out of scope. I'll make an issue for that)
- [ ] Clicking add user to pool breaks the page. It looks like it has something to do with the Input components (out of scope(?)). To recreate: go to Users table->View User->Click "add user to pool" 


Cool stuff:
- Thanks for adding the docs for each of the new Primitives. It will come in handy down the line when ppl are using them for the first time.
- I like the subtle transition of color and the rotating chevron on the Accordion when opening and closing.

**Comment by esizer** [comment]
> * On the IAP homepage,  the "See Eligibility Criteria" and "Learn more" dialog close buttons are not working.
> * On the IAP homepage, when closing a dialog the tab index jumps back to the first element on the page, in this case the Home link in the nav menu. This can get annoying for users with screen readers. It seems to be working correctly on the Admin and TalentSearch side though.

Good catch, fixed with [fix iap dialog close + focus](https://github.com/GCTC-NTGC/gc-digital-talent/pull/4136/commits/0bb65bccf0b4ab83c30d00a51108b14f3dfa3854)

> * User cannot scroll when the dialog is open. This could prevent the user from seeing the entire Dialog, especially on smaller screens. For example, on the EE dialog I cannot click the Save button. Also, the "Learn more" dialog on IAP homepage is very long so most of the content is unviewable. Would adding a `<ScrollArea />` within the Dialog fix this?

Oops, this was a problem with the composition of the dialog. Thanks for catching that! Fixed in [fix long content dialogs not scrolling](https://github.com/GCTC-NTGC/gc-digital-talent/pull/4136/commits/324a4ebb2fc4e28343d70913e2cf70884f9a444b)

> * Clicking add user to pool breaks the page. It looks like it has something to do with the Input components (out of scope(?)). To recreate: go to Users table->View User->Click "add user to pool"

Looks like this was missed in the unsaved changes PR 😢 Fixed in [fix add user to pool dialog](https://github.com/GCTC-NTGC/gc-digital-talent/pull/4136/commits/6af1284836d567416b6a9f7240609c0b7ce5cf19)

**Comment by esizer** [comment]
> Almost there! The close button seems to have jumped into the top right of the screen. Was that intentional?

oohhh, good eye 🦅  Fixed with [fix dialog close button position](https://github.com/GCTC-NTGC/gc-digital-talent/pull/4136/commits/1b6b43d3c55997e9de91cc828e75f3ddf1a203ed)

**Review by yonikid15 — APPROVED** [review]
Alright looks good to me! ✅

**Pull request merged**
