### PR TITLE
Localize messages in Form components

### LINKED ISSUE #2181: Form helpers need to be localized
Some of our form helpers, like "required", "optional", and "submit", need to be localized.

### PR DESCRIPTION
**Pull request by yonikid15**
Closes #2181 

# Notes
- I'm changed the estimate to a 1 since it didn't take long
- I haven't done translations in a while and the directions in the README helped perfectly 🎉 
- I found the translations to the messages in the TalentCloud repo, so no need to send to translations.

### CODE REVIEW

**Comment by vd1992** [comment]
The loading message I guess could be updated too?
image

**Review by petertgiles — CHANGES_REQUESTED** [review]
I'm not sure why but this worked in Storybook for me but not in the actual Admin site.  Does it work for you?
image
image

**Comment by petertgiles** [comment]
> And "Skills" and "Skill Families"

These were part of the third translation round that just went in.  Next time you pull main you should have them.

**Comment by yonikid15** [comment]
> I'm not sure why but this worked in Storybook for me but not in the actual Admin site. Does it work for you? image image

No it's not working on admin on my end either. I think it's cause we aren't including the common folders french translations in the admin or talentSearch 😅

**Comment by petertgiles** [comment]
> I think it's cause we aren't including the common folders french translations

Oof, sticky.  Probably why this hasn't been done until now. 😁 I wonder what the solution is?  Update the intl-compile script for admin and talentsearch to pull in all common strings, too?

**Review by petertgiles — APPROVED** [review]
Whoah, that fixed the footers, too!  Nice one!
image

**Pull request merged**
