### PR TITLE
[Feature] Pool completeness accessor 

### LINKED ISSUE #7917: ✨ Pool completeness variable
## ✨ Feature

The ability to check whether a pool is "complete", all required fields are complete and should be allowed to be published. 
Essential to start pool rework so high priority 

## 🕵️ Details

Backend check that emits a boolean through API enabling checking if it is complete on the frontend

## 🙋‍♀️ Proposed Implementation

Accessor on the pool model that works akin to profile completeness on the user model (validator in the accessor)
`isComplete`

## ✅ Acceptance Criteria

- [ ] Completeness field added to pool schema type, can be queried for a pool
- [ ] Basic test asserting incomplete pools emit the correct boolean

### PR DESCRIPTION
**Pull request by vd1992**
🤖 Resolves #7917 

## 👋 Introduction

Introduces an accessor that allows checking from API/frontend whether a pool is "complete", allowing checking without publishing. 

## 🕵️ Details

Adds an accessor, that is acting with a validator per issue body and leverages a reusable rule. 
Tests it too. 

## 🧪 Testing

1. Open up a draft pool in edit mode in one tab, graphiQL in another
2. Query with the below, while changing the pool around, checking validation logic

```
query pool {
  pool(id: :id) {
    isComplete
  }
}

```

### CODE REVIEW

**Review by petertgiles — CHANGES_REQUESTED** [review]
Nice, this is very clean!  I love you've included a test, too.  The one thing I'm not fond of is that you've added a validation routine that is very similar to the one already there.  Is it possible to either reuse or replace the existing validation logic?
image

**Comment by vd1992** [comment]
> Nice, this is very clean! I love you've included a test, too. The one thing I'm not fond of is that you've added a validation routine that is very similar to the one already there. Is it possible to either reuse or replace the existing validation logic?

Yeah, it is very similar because I used it as a guide for what a complete pool should look like 🤣 

But yeah, my intent with introducing a `PoolIsComplete` rule was to make it so an issue like #7920 or a debt issue could recycle the rule. Updating the pool publish validator to refactor to use the new rule seemed to really push the scope on this issue so I did not do it now.

**Comment by vd1992** [comment]
@tristan-orourke 
Can I please request your opinion on the PR, and the conversation?

**Comment by tristan-orourke** [comment]
@vd1992 I'd ask you reuse the PublishPoolValidator for this, for now. Not only does that avoid duplicated code, but by using a set of rules, instead of creating one new rule, the validation error will say which fields are missing.

**Comment by tristan-orourke** [comment]
I can see your point about #7920 suggesting that we might need two different validators. This might be a use case for class extension or composition? Like maybe, 
```
class PublishPoolValidator {
  rules() {
    $completenessRules = (new PoolIsCompleteValidator)->rules();
    $extraRules = ...;
    return array_merge($completenessRules, extraRules);
  }
}
```

**Comment by vd1992** [comment]
> @vd1992 I'd ask you reuse the PublishPoolValidator for this, for now. Not only does that avoid duplicated code, but by using a set of rules, instead of creating one new rule, the validation error will say which fields are missing.

Okay sure I can do that, my concern about all this was how there will be a gap between what is considered "complete" and what can be published, which will arise from issues #7918 and #7920 
Those issues are not set in stone, but I am a bit concerned as there will be a gap between a pool being "complete" and "ready to publish" so I feel hesitant about using the validator attached to "publish" for the purpose of "completeness" ☹️

**Comment by vd1992** [comment]
Okay, I factored out a completeness validator and used it instead

**Review by petertgiles — APPROVED** [review]
Very nice!  I like this much better.  :+1: Works well for me.

**Review by tristan-orourke — APPROVED** [review]
Nice

**Comment by petertgiles** [comment]
You're in a race with James' enum PR.  Whichever one is in second place will have some fixup to do.

**Pull request merged**
