### PR TITLE
debt/5129-remove-from-pool-column

### LINKED ISSUE #5129: Remove column from User Profile page (Admin)
## Description

When looking at a user profile through admin side, the remove from pool no longer applies since we wanna keep historical data. Please remove this column

## Screenshot: Prototype

image

## Acceptance Criteria
- [ ] Column no longer appears on user page

   [image]: https://user-images.githubusercontent.com/305339/166570935-6425a615-82c7-4b2f-9840-5c7d698fa2ab.png
   [image-link]: https://example.com
   [figma]: https://go.talent.c4nada.ca/figma
   [sitemap]: https://go.talent.c4nada.ca/sitemap

### PR DESCRIPTION
**Pull request by vd1992**
closes #5129 
removes the header as well as the cell with placeholder text

test:
head to `/en/admin/users/:id`
scroll to Pool Status
confirm the table is updated and functionality intact (can do other operations properly)

### CODE REVIEW

**Comment by vd1992** [comment]
while working on this I noticed a bug with the status selection
spun it out here #5163

**Review by petertgiles — APPROVED** [review]
:broom: :+1:

**Review by mnigh — CHANGES_REQUESTED** [review]
Don't forget to remove the associated French strings if they are not being used elsewhere! 🇫🇷 

https://github.com/GCTC-NTGC/gc-digital-talent/blob/7a7d9628e42384a887a81b74581aa13c7685f96e/frontend/admin/src/js/lang/fr.json#L1180-L1183

https://github.com/GCTC-NTGC/gc-digital-talent/blob/7a7d9628e42384a887a81b74581aa13c7685f96e/frontend/admin/src/js/lang/fr.json#L949-L952

**Review by mnigh — APPROVED** [review]
👍

**Pull request merged**
