### PR TITLE
Add label to "direct" deps in dependabot PRs, to determine easiest merge order

### PR DESCRIPTION
**Pull request by patcon**
Resolves https://github.com/GCTC-NTGC/gc-digital-talent/issues/2175

## To Do
- [x] decide label to add to "top-level": `dependencies-priority`
- [x] split frontend npm packages into two types
- [x] split composer packages into two types
- docs??

### CODE REVIEW

**Comment by patcon** [comment]
Look ok? Does it need any more docs, or does this suffice?

**Review by petertgiles — CHANGES_REQUESTED** [review]
Looking great!  Though I think maybe the composer /api block is duplicated on lines 62 - 72?

**Comment by petertgiles** [comment]
> Does it need any more docs, or does this suffice?

I think the file is pretty self-explanatory.  Though we can add more detail in [the markdown documentation](https://github.com/GCTC-NTGC/gc-digital-talent/pull/2177) if we want.

**Comment by petertgiles** [comment]
> there's another blessed way

This would allow you to not break each project into two?  That would certainly be an improvement.

**Comment by patcon** [comment]
Removing myself for now, as I shouldn't have 2 when it's been outstanding for so long

**Comment by patcon** [comment]
Closing in favour of https://github.com/GCTC-NTGC/gc-digital-talent/pull/3562

**Pull request closed without merging**
