### PR TITLE
Copy change for Create/Update Pool Candidate page #2482

### LINKED ISSUE #2482: Copy change for Create/Update Pool Candidate page
Please change the copy for the "CMO identifier" label to "Process Number".

French: 
"Identifiant du BGC"  -> "Numéro de processus"

### PR DESCRIPTION
**Pull request by RVany**
Resolves #2482 
Please change the copy for the "CMO identifier" label to "Process Number".

French: 
"Identifiant du BGC"  -> "Numéro de processus"

### CODE REVIEW

**Comment by petertgiles** [comment]
This is a localized string.  Don't forget to update the French copy in the fr.json file to the value that Gray provided.

**Comment by petertgiles** [comment]
Sorry, the change didn't work if you check in storybook  The IDs are auto generated based on the string so new string means new ID.  You'll need to do the extract-change-merge cycle.  You can refer to the README in the common project or the video I posted in learningfam.

**Comment by RVany** [comment]
Screenshot 2022-04-19 174226
I am just wondering the _**User Assignment**_ is the correct french translation?

**Comment by vd1992** [comment]
> Screenshot 2022-04-19 174226 I am just wondering the _**User Assignment**_ is the correct French translation?

No, I don't think so 

image

**Review by petertgiles — APPROVED** [review]
Nice, looks like you got it!

Out of curiosity, do you remember what string "hlcd+5" in the whitelist represents?

**Comment by RVany** [comment]
> Nice, looks like you got it!
> 
> Out of curiosity, do you remember what string "hlcd+5" in the whitelist represents?

{
  "hlcd+5": {
    "defaultMessage": "Table results"
  }
}

This is still in my admin's untranslated.json

**Comment by RVany** [comment]
> > Screenshot 2022-04-19 174226 I am just wondering the _**User Assignment**_ is the correct French translation?
> 
> No, I don't think so
> 
> image

Create a new issue then, I will do it.😀

**Pull request merged**
