### PR TITLE
[Feature] Support nesting table of contents

### LINKED ISSUE #6990: ⚙️ Update the table of contents component
image

# ✨ Details ([Figma file](https://www.figma.com/file/T1R64oNWog10OXiBnuiMkz/2.-Components?type=design&node-id=758-5887))

We've never formally established design standards for the table of contents, so this ticket aims to do so, alongside establishing common variants and use cases.

# 📐 Standards and layout

## Accessibility

We'll want to ensure that the table of contents is using proper landmark elements to identify itself as a navigation. Generally, we should build it using a `nav` element, with nested `ul` and `li` elements.

## Color and typography

- The table of contents label/header should use the `h6` font size, bolded
- Standard text links should use the `copy` font size and be `black`
- Incomplete states should use the `x-circle` Heroicon and both the icon and text should use `error.darker`
- Complete states should use the `check-circle` Heroicon and both the icon and text should use `success.darker`
- If included, buttons should be `secondary` and `solid`

## Layout and size

<details><summary>📸 Hydrogen layout diagram</summary>

</details> 

# 🎨 Variants

## With a button

Some pages require a fixed primary action that will follow the user down the page as they complete tasks. In these cases, a `secondary`, `solid` style button with a custom label should be used.

<details><summary>📸 ToC with a button</summary>

</details> 

## Tracking completion

In some cases it is beneficial to show the user their status when completing multiple sections in a long form. The table of contents should be able to adapt to show the user which sections on the page have been successfully completed. The criteria for what constitutes "complete" will be determined on section-by-section basis for each individual page.

<details><summary>📸 ToC with tracking - Incomplete</summary>

</details>

<details><summary>📸 ToC with tracking - Complete</summary>

</details>

## Acceptance Criteria
- [ ] Table of contents uses a nav, ul and li elements
- [ ] Items can be nested
- [ ] Typograph and Layout matches specs
- [ ] Status icons (optional) match specs
- [ ] Can include a button at bottom which matches specs
- [ ] Table of Contents follows user down the side

### PR DESCRIPTION
**Pull request by esizer**
🤖 Resolves #6990 

## 👋 Introduction

Updates the table of contents to support nesting. As well, adjusts the spacing to match the mock up.

## 🕵️ Details

In order to support nesting, we must now the new sub components `List` and `ListItem`. This allows us to nest lists as deep as is reasonable.

```tsx
<TableOfContents.Wrapper>
  <TableOfContents.Navigation>
    <TableOfContents.List>
      <TableOfContents.ListItem>
        <TableOfContents.AnchorLink id="main-section">
          Main Section
        </TableOfContents.AnchorLink>
        <TableOfContents.List>
          <TableOfContents.ListItem>
            <TableOfContents.AnchorLink id="sub-section">
              Sub-Section
            </TableOfContents.AnchorLink>
          </TableOfContents.ListItem>
        </TableOfContents.List>
      </TableOfContents.ListItem>
    </TableOfContents.List>
  </TableOfContents.Navigation>
  <TableOfContents.Content>
    <TableOfContents.Section id="main-section">
      <TableOfContents.Heading as="h3">
        Main Section
      </TableOfContents.Heading>
    </TableOfContents.Section>
    <TableOfContents.Section id="sub-section">
      <TableOfContents.Heading as="h4">
        Sub-Section
      </TableOfContents.Heading>
    </TableOfContents.Section>
  </TableOfContents.Content>
</TableOfContents.Wrapper>
```

## 🧪 Testing

Assist reviewers with steps they can take to test that the PR does what it says it does.

> **Note**
> Some alignment depends on the applicant dashboard feature flag. You may need to comment it out to see the proper story if  #7097 is not complete.

1. Run storybook `npm run storybook`
2. Navigate to the "Table of Contents" story
3. Confirm it matches [the mockup](https://www.figma.com/file/T1R64oNWog10OXiBnuiMkz/2.-Components?type=design&node-id=758-5887&mode=design&t=kTwby59afgATch1G-0) and nests properly

## 📸 Screenshot

Screenshot 2023-07-05 114808

### CODE REVIEW

**Review by vd1992 — DISMISSED** [review]
Looking at the Chromatic Build https://www.chromatic.com/review?appId=61e099a1bb1465003a73d3ce&number=7171&type=linked

Something appears to be going wrong with spacing of bullets
It also appears to align things to the right instead

image

image

image

**Comment by vd1992** [comment]
Oh hang on, I just noticed the note, am I seeing what I should be seeing then?

**Comment by esizer** [comment]
> Oh hang on, I just noticed the note, am I seeing what I should be seeing then?

Yeah, until we can get feature flags working in storybook or remove the applicant dashboard flag, this one is going to look a little weird.

**Comment by vd1992** [comment]
I think I am missing something, running locally regardless of `FEATURE_APPLICANT_DASHBOARD` status the alignment is off

FALSE

**Comment by esizer** [comment]
> I think I am missing something, running locally regardless of `FEATURE_APPLICANT_DASHBOARD` status the alignment is off
> Or are the profile parts intended to be sub-listed (the second one)?

Hmm, I was able to reproduce and fix part of this. Are the screenshots from storybook or from the actual application? 
Screenshot 2023-07-06 141326

**Comment by vd1992** [comment]
> > I think I am missing something, running locally regardless of `FEATURE_APPLICANT_DASHBOARD` status the alignment is off
> > Or are the profile parts intended to be sub-listed (the second one)?
> 
> Hmm, I was able to reproduce and fix part of this. Are the screenshots from storybook or from the actual application? Screenshot 2023-07-06 141326

Actual application

**Review by vd1992 — APPROVED** [review]
I ended up taking another look anyway 🤣 
Looking good!

image

**Pull request merged**
