### PR TITLE
Feature - 4029 - Theme Switcher

### LINKED ISSUE #4029: New Component - dark mode switcher
Build a component (based on Josh's designs) to switch the site between auto, light, and dark mode.

Acceptance criteria:
- [ ] Component built
- [ ] Emits events when toggled
- [ ] Storybook story
- [ ] Jest test

Questions:
- Is this based on a generic toggle component or fully independent?
- Does this component have any of its own state or is the current setting injected as a prop?

Out of scope:
- This component will be added to the home page in #4033

### PR DESCRIPTION
**Pull request by esizer**
Resolves #4029 

> **Note**
> ~~If someone approves https://github.com/GCTC-NTGC/gc-digital-talent/pull/4131 first, I can see about using that component in this~~

## Summary

Introduces a new context and component to control the current colour theme (dark/light mode).

## TO DO

- [x] Merge `main` once #4049 is complete
- [x] Create story
- [x] Write tests
- [x] Add dark mode styles
- [x] Fix background colour

## Testing

> **Note**
> This is only in storybook right now so all testing must take place there. Jest is testing that `localStorage.theme` is modified when buttons are clicked along with the `className` update which is derived from the `ThemeContext`.

1. Run the common storybook `npm run storybook --workspace=common`
2. Navigate to the Theme Switcher story
3. Click on the buttons and ensure the switcher updates
4. Bonus: Check to see if "theme" key exists in local storage with the appropriate value

### Context: `<ThemeProvider>`

This is added within our existing `<ContextContainer>` just below the language container. This controls the current theme including manipulating the DOM.

### Hook: `useTheme`

This is a simple hook that allows us to interact with the context, retrieving the current theme mode along with a method to set it.

### Component: `<ThemeSwitcher>`

A new component (created by @JoshBeveridge ) has been created that uses the `useTheme` hook to update the current mode.

## Example

```tsx
const ExampleSwitcher = () => {
  const { mode, setMode } = useTheme();
  
  return (
     <div>
       Current Mode: {mode}
       <button onClick={() => setMode("pref"}>
         Toggle Preference
       </button>
       <button onClick={() => setMode("light"}>
         Toggle Light Mode
       </button>
       <button onClick={() => setMode("dark"}>
         Toggle Dark Mode
       </button>
    </div>
  ); 
}
```

### CODE REVIEW

**Comment by tristan-orourke** [comment]
> will it be possible to hook our themes in [storybook](https://storybook.js.org/docs/react/configure/theming)?

We already have a [Add Dark Mode to Storybook](https://github.com/GCTC-NTGC/gc-digital-talent/issues/4027) issue, so I wouldn't worry about it here.

Also, it looks to me like the [Storybook Theming](https://storybook.js.org/docs/react/configure/theming) is about theming the storybook UI itself, not the stories _in_ Storybook, so I'm not sure if that's the tool we want to use for #4027.

**Review by petertgiles — APPROVED** [review]
It looks good to me!  I can see the local storage value changing with the toggle and it looks like the mockup as far as I can tell.  I'm hoping we can get a review from @JoshBeveridge before you merge though.

**Comment by JoshBeveridge** [comment]
Wait, which mockup is this based on? Also, is there a way for me to see the dark styles of the switcher itself?

**Review by JoshBeveridge — APPROVED** [review]
Looks gouda! 🧀

**Comment by JoshBeveridge** [comment]
Oh wait - does this component have dedicated focus styles?

**Comment by esizer** [comment]
> Oh wait - does this component have dedicated focus styles?

Okay, it has focus styles now after [add focus styles](https://github.com/GCTC-NTGC/gc-digital-talent/pull/4099/commits/06cb5bca22877d5016c7dc4b0156c32eefe80117)

**Review by JoshBeveridge — APPROVED** [review]
Thanks @esizer !

**Pull request merged**
