### PR TITLE
Fix import extension linting

### LINKED ISSUE #2490: Linting - import/extensions
Fix all instances of the linting error with rule [import/extensions](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/extensions.md).  If necessary, add a rule disable comment for instances where appropriate and add a justification comment.  

Tips:
- Run `npm run lint --workspaces` from the frontend folder to manually run linting on all subprojects
- The [eslint-formatter-summary](https://github.com/mhipszki/eslint-formatter-summary) package can be handy for generating a linting summary by rule

### PR DESCRIPTION
**Pull request by petertgiles**
Fixes a single instance of import/extension linting

Closes #2490

### CODE REVIEW

**Review by esizer — COMMENTED** [review]
Outside of the tests failing, this seems good to go!

Running `npm i @formatjs/ts-transformer --workspace=admin`, not sure if we want to include here or create a separate issue to look into it.

**Comment by petertgiles** [comment]
> Not sure if we want to include here

Thanks for the tip!  I'll to fix it here.

**Comment by esizer** [comment]
> > Not sure if we want to include here
> 
> Thanks for the tip! I'll try to fix it here.

Sweet, thanks! 🍭  I have an open PR that is blocked by tests failing so ill merge in main once that gets merged.

**Comment by vd1992** [comment]
I made issue #2618 for the tests

**Comment by esizer** [comment]
> I made issue #2618 for the tests

@petertgiles If you haven't already started working on it I can pick that issue up and work on it. Seems like a priority since all PRs going forward will be affected by it.

**Review by esizer — APPROVED** [review]
Not sure where we are on the tests breaking, but this looks good to me now.

**Pull request merged**
