### PR TITLE
Debt - 2862 - Loading/Error Component

### LINKED ISSUE #2862: Common component which includes Loading and Error messages
We have a common pattern on many pages, where we show a loading message until initial data is loaded, and an error message if something went wrong, and then the real component otherwise. It would be good to have a common component for this, to simplify our page components and ensure we're using consistent messages. It will also make it easier to improve our loading display in the future.

# Acceptance Criteria
- [ ] Every component following this pattern (loading, error, component) should use this common component instead.

### PR DESCRIPTION
**Pull request by esizer**
Resolves #2862 

## Summary

This will introduce a new component that does two things:

1. Normalize our pending query UI
2. Make the loading state a little less ugly

## Pending - New Component!

This component takes two props, fetching and error. These can be passed in directly from the `urql` result. It will then display a loading spinner if `fetching` is `true` or a normalized error message if `fetching` is `false` and an error exists.

If `fetching` is `false` and no error exists, it will display the children.

Note: I could not think of  nice way of showing a "not found" message if the query is resolved, no error exists and no data exists. Mainly because we need to have the ability to inspect the data and decide what message to display if that is true. We could just export a `<NotFound>` component to normalize the look of this message however.

### Example

```tsx
import NotFound from "@common/components/NotFound";
import Pending  from "@common/components/Pending";

const Page: () => {
  const intl = useIntl();
  const [{fetching, error, data }] = useQuery();
  
  return (
    <Pending fetching={fetching} error={error}>
      {data ? (
        <InnerPage data={data} />
      ) : (
        <NotFound headingMessage="Not found">
          {intl.formatMessage({
            defaultMessage: "No data found.",
            description: "Message to display when no data was returned from query.",
          })}
        </NotFound>
      )}
    </Pending>
  );
}
```

### CODE REVIEW

**Comment by vd1992** [comment]
I feel this merits a Story, to judge it

**Comment by esizer** [comment]
> I feel this merits a Story, to judge it

It doesn't necessarily change anything, just moves some boilerplate code to `@common`. 

Though, if you'd like to see it you can pull it down, build it and view it at `/talent/profile`.

**Comment by petertgiles** [comment]
Nice, I like what I'm seeing!  I like how you've added the aria tags in there, too.  No concerns about the approach from me.  I agree with Vachan that I'd like to see some storybook stories eventually.

**Comment by esizer** [comment]
> I'll work on some stories this morning :) @vd1992 @petertgiles

Stories added with [add pending component stories](https://github.com/GCTC-NTGC/gc-digital-talent/pull/2957/commits/f02209001d2f06d61e3236fbb77565353450452e) @vd1992 @petertgiles

**Comment by petertgiles** [comment]
> Stories added

Nice looks good.  Maybe take a peek at "not found" though.
image

**Comment by esizer** [comment]
> Nice looks good. Maybe take a peek at "not found" though.

Oops, had an uppercase "N" 😅 , thanks!

**Comment by petertgiles** [comment]
I love it!  So much cleaner.  Time to apply it to `admin` as well?
image

**Comment by esizer** [comment]
> I love it! So much cleaner. Time to apply it to `admin` as well?

Cool! Added it to the admin with [update admin with loading component](https://github.com/GCTC-NTGC/gc-digital-talent/pull/2957/commits/4b50e9fd23b74c7a782021d51b88139f00e06539).

**Comment by petertgiles** [comment]
There are some linting warnings leftover on the last change.  It seems like you've removed `DashboardContentContainer` on some pages but left it on others.  Was that intentional?

**Comment by esizer** [comment]
> There are some linting warnings leftover on the last change.

Resolved with [remove unused imports](https://github.com/GCTC-NTGC/gc-digital-talent/pull/2957/commits/e4b31d401083f4aba8903f2876c1a1affc53051e)

> It seems like you've removed `DashboardContentContainer` on some pages but left it on others. Was that intentional?

We are inconsistent on how/when we use this. In the ones where it was removed, it was only being used to wrap the loading/error messages. Some, however, it was also wrapping the content and that is when I left it in.

I'm assuming each one will become more consistent as we update each component to the new 2.0 designs.

**Pull request merged**
